[[install-decide]]
=== Concept: Methods for Downloading and Installing the Core Software

[role="summary"]
Overview of methods you can use to download the core software.

(((Downloading,core software)))
(((Installing,core software)))
(((Core software,downloading)))
(((Core software,installing)))

==== Prerequisite knowledge

* <<install-tools>>
* <<install-requirements>>
* <<understanding-distributions>>

==== What methods are available for downloading the core software?

Before you can build a site, you will need to first download the core software.
Depending on your plans, there are several ways that you can download the core
software:

Use Composer::
  If you plan to build a site, and continue to develop it over time you should
  use Composer to download the core software, because Composer will manage the
  dependencies properly. If you plan to use the Drush tool (see
  <<install-tools>>), using Composer is required. See <<install-composer>> for
  instructions.

Try a free online demo::
  If you are evaluating whether or not to use Drupal to build a site, you
  can use an online provider to get a demo installation of the core software in
  20 minutes or less. See the
  https://www.drupal.org/try-drupal[_Drupal.org_ page "Try Drupal"].

Use a one-click installer from your hosting provider::
  If you choose to install the core software at your hosting provider, your
  hosting provider may have specific documentation and/or a one-click install
  that you can use. See
  https://www.drupal.org/association/supporters/hosting[_Drupal.org's_ list of hosting providers that support Drupal].

Use a pre-configured environment::
  Use a pre-configured environment or virtual machine that contains Drupal and
  all the required supporting software to install Drupal locally. See the
  section for your operating system under
  https://www.drupal.org/docs/develop/local-server-setup[_Drupal.org_ community documentation page "Local server setup guide"]
  for possible options.

==== What happens when I install the core software?

_Installing_ the core software means setting up some database tables,
configuration, and an administrative user account, so that you can build and use
your site.

==== What methods are available for installing the core software?

There are several ways to install the core software:

Behind-the-scenes installer::
  If you choose to use an online demo or one-click installer from a hosting
  provider, the core software may be installed for you automatically.

Interactive installer::
  The core software has an interactive installer that presents you with several
  on-line forms, and then completes the installation using the information you
  provide in the forms. See <<install-prepare>> and <<install-run>>.

Command-line tool::
  Command-line tools (see <<install-tools>>) can also be used to perform the
  installation steps.

Demo site installer::
  Quickly create a temporary demo site that uses the built-in web server and
  SQLite database that are part of PHP by running the command below from the
  root directory of your project. In this case, you will not run the interactive
  installer. See the https://www.drupal.org/docs/official_docs/evaluator-guide[Evaluator Guide]
  to learn more.

  ----
  php -d memory_limit=256M core/scripts/drupal quick-start demo_umami
  ----

// ==== Related topics

// ==== Additional resources

*Attributions*

Written and edited by https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] at
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
and https://www.drupal.org/u/jojyja[Jojy Alphonso] at
http://redcrackle.com[Red Crackle].
