[[preface-audience]]

=== Audiencia y objetivo

[role="summary"]
Entendiendo la audiencia objetivo de esta guía, y lo que aprenderán de ella.

Esta guía fue escrita principalmente para personas con un conocimiento mínimo del sistema de gestión de contenido de Drupal. 
Los temas los ayudarán a ser expertos en la instalación, administración, construcción de sitios y/o mantenimiento del contenido 
de un sitio web basado en Drupal. La guía también está dirigida a personas que ya tienen alguna experiencia con una versión actual 
o pasada de Drupal, y desean ampliar el rango de sus habilidades y conocimientos o actualizarlos a la versión actual.

Esta guía asume que ya ha dedicido que quiere aprender y usar Drupal. Si necesita 
leer más antes de decidirse, vea <<understanding-drupal>>.

Dependiendo de qué aspectos de Drupal le gustaría aprender, va a necesitar algunos
conocimientos preeliminares para entender esta guía: habilidades de uso de internet básicas son asumidas, 
y la guía se concentra en cómo usar el software en si mismo. Por ejemplo, las secciones sobre instalar Drupal 
en un servidor web asumen que puede obtener un alojamiento web y aprender por si mismo cómo transferir archivos
a su servidor. De manera similar, las secciones sobre gestión de contenido asumen que puede iniciar sesión en 
una página web y rellenar un formulario.

Después de leer esta guía, usted debería ser capaz de:

* Planificar las arquitecturas de contenido de una página basada en Drupal.

* Construir el sitio web que ha planificado

* Gestionar y administrar su sitio web

* Entender la documentación y las entradas de webs sobre los temas no cubiertos aqui, para 
expandir sus habilidades y conocimientos.

* Conectar con la comunidad de Drupal a nivel mundial


*Atribuciones*

Escrito por https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traducido por https://www.drupal.org/u/guiurocafortferrer[Guiu Rocafort Ferrer].
