[[preface-reporting]]
=== Reportando problemas
[role="summary"]
Cómo reportar un problema en esta guía ( con pasos detallados ).

==== Objetivo

Reportar un problema en esta guía, tales como:

* Información incorrecta o que no sigue las buenas prácticas
* Pasos que no funcionan
* Capturas de pantalla o texto que no encaja exactamente con lo que ve en la pantalla
* Pasos que no funcionan
* Redacción poco clara
* Lugares donde una tabla o una captura de pantalla no aclara el texto
* Terminología poco clara
* Conocimientos previos o requisitos del sitio web no especificados
* Errores tipográficos, gramáticos, de formato, o erratas
* Enlaces rotos

// ==== Prerequisite knowledge

// ==== Site prerequisites

==== Advertencia

Los pasos detallados a continuación explican el procedimiento de reportar un 
error en la página de incidencias del proyecto. Esta página solamente está disponible
en inglés, por lo que se indicarán los lugares en los que hay que hacer click o rellenar
con el texto que aparece en Inglés.

==== Pasos
. Tome nota del tema o temas que contienen el problema que ha encontrado.

. Inicie sesión en https://www.drupal.org[_Drupal.org_] ( va a necesitar 
crear una cuenta si no está registrado ).

. Visite la https://www.drupal.org/project/issues/user_guide[Página de 
incidencias en _Drupal.org_]

. Verifique que el problema que ha encontrado no ha sido informado ya en 
otro reporte.
  * Si solo hay unos pocos reportes abiertos, escanee la columna de 
  _Title_ (Título ) para ver si alguna de las descripciones encaja con el problema
  que encontró. Quizás deba leer algunos de los reportes para asegurarse, lo
  cual puede hacer haciendo click en la columna de _Title_ (Título).
  * Si la lista de reportes abiertos es larga, puede introducir una palabra
  clave relacionada con el problema que encontró o el título del tema donde
  el problema ocurre en la casilla _Search for_ ( Buscar por ), y hacer click en  _Search_ ( Buscar )
  para reducir la lista de reportes. Entonces, puede leer los títulos o 
  leer los reportes para ver si alguno encaja con su problema.

. Si determina que su problema no ha sido reportado todavía, haga click en
_Create a new issue_ ( Crear un nuevo reporte ), y rellene el formulario como sigue:
+
[width="100%",frame="topbot",options="header"]
|================================
| Nombre del campo | Explicación | Valor de ejemplo
| Title ( Título) | Resumen corto del problema que encontró | Las instrucciones
 en "Crear un tipo de contenido" no funcionan
| Category ( Categoría ) | Tipo de problema reportado | Bug report
| Version ( Versión ) | Versión de la guiía donde encontró el problema | 8.x-0.x-dev
| Issue summary ( Resumen del incidente ) | Detalles de los problemas que encontró | En el 
apartado de "Añadir un tipo de contenido, en el paso 3, cuando hago click
en _Save_, me aparece el siguiente mensaje de error: ...
|================================

. Relea el _Title_ ( Título ) y el _Issue summary_ ( Resumen de la incidencia ) que introdujo, 
y verifique que la siguiente información se encuentra incluida en su informe:
  * Una descripción completa del problema
  * El nombre del tema o temas donde encontró el problema
  * El idioma en el que estuvo leyendo la guía
  * Si leyó la guía en una página web, un enlace a la página o páginas
    donde se encuentra el problema

. Haga click en _Save_ ( Guardar ) ara crear la incidencia.

. Revise la incidencia en unos dias. Si uno de los mantenedores del proyecto ha
pedido alguna clarificación, responda añadiendo un comentario en la misma.

// ==== Expand your understanding

// ==== Related concepts

// ==== Additional resources


*Atribuciones*

Escrito por https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traducido por https://www.drupal.org/u/guiurocafortferrer[Guiu Rocafort Ferrer].
