[[attributions]]
=== Attributions pour l'ensemble du guide

[role="summary"]
Liste de contributeurs impliqués dans la gestion de projet et des tâches
d'écriture et de modication.

(((Attributions pour le contenu de ce document)))
(((Attributions pour ce document)))
(((Copyright pour ce document)))

Ce guide a été écrit par les contributeurs du projet à code ouvert Drupal, et
est sous licence https://creativecommons.org/licenses/by-sa/2.0/deed.fr[CC BY-SA
2.0]. Consulter <<copyright>> pour plus d'informations. On trouvera ci-dessous
des détails sur les contributeurs à des tâches sur l'ensemble du guide. Pour
chaque sujet individuel, les attributions pour l'écriture, l'édition et/ou la
traduction se trouvent à la fin de chaque sujet.

==== Coordination du projet de document original (en anglais, pour Drupal 8)

L'écriture de la version initiale de ce guide a été coordonnée par les personnes
suivantes :

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] - Coordination des
volontaires et gestion de projet

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] - Supervision du contenu

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] - Supervision du contenu

* https://www.drupal.org/u/ifrik[Antje Lorch] - Supervision du contenu


==== Écriture, édition et test du document original

Les personnes suivantes ont contribué à l'écriture de l'ensemble du guide :

* Le glossaire a été écrit et adapté par
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon], en reprenant des parties
des pages https://www.drupal.org/docs/7/understanding-drupal/glossary["Glossary"],
https://www.drupal.org/docs/drupal-apis/configuration-api/overview-of-configuration-vs-other-types-of-information["Overview of Configuration (vs. other types of information)"], et
https://www.drupal.org/docs/theming-drupal/working-with-breakpoints-in-drupal["Working
with breakpoints in Drupal"], chacune copyright 2000-copyright_upper_year
contributeurs individuels à la
https://www.drupal.org/documentation[documentation de la communauté de Drupal].

* L'index a été amélioré et supervisé par
https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst].

* Les résumés des sujets ont été écrits par
https://www.drupal.org/u/jojyja[Jojy Alphonso] et
http://redcrackle.com[Red Crackle].


L'ensemble du guide a été modifié par les personnes suivantes :

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] de
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst]

* https://www.drupal.org/u/ifrik[Antje Lorch]

* https://www.drupal.org/u/balu-ertl[Balu Ertl]

* https://www.drupal.org/u/batigolix[Boris Doesborg]

* https://www.drupal.org/u/cleverington[Charles Leverington]

* https://www.drupal.org/u/chishah92[chirag shah]

* https://www.drupal.org/u/gdunham[Grant Dunham]

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] de
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle] -- qui a corrigé la plus grande partie du guide
utilisateur

* https://www.drupal.org/u/kamalkantpansari[Kamal Kant Pansari] de
http://www.intelliswift.com/[Intelliswift]

* https://www.drupal.org/u/michaellenahan[Michael Lenahan]
d'https://erdfisch.de[erdfisch]

* https://www.drupal.org/u/swarad07[Swarad Mokal] de
http://www.blisstering.com[Blisstering Solutions]

Le contenu a été testé par :

* https://www.drupal.org/u/zachcarter[Zach Carter]

* Un atelier a été organisé par le
https://groups.drupal.org/spokane-wa["Groupe d'utilisateurs de Drupal de Spokane" sur groups.drupal.org], avec des étudiants du programme de certification en développement web du
http://scc.spokane.edu[Spokane Community College]

==== Images

La plupart des images dans ce guide sont des captures d'écran du logiciel
Drupal, générées grâce à un programme écrit par
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Le mot Drupal, le logo Druplicon (qui apparaît dans plusieurs images à travers
ce guide), et le logo de la marque Drupal (qui fait partie de l'image de
couverture) sont des
https://www.drupal.org/about/media-kit/logos[marques déposées par Dries Buytaert]).

L'image de couverture est une illustration sous licence CC BY-SA 2.0
d'https://www.drupal.org/u/mndonx[Amanda Luker] de
https://www.advomatic.com/[Advomatic].

Le logo du marché fermier d'Anytown, qui apparaît dans plusieurs images à
travers ce guide, est une illustration sous licence CC BY-SA 2.0 
de Justin Harrell de https://drupalize.me/[Drupalize.Me].

L'image d'abeille, qui apparaît dans plusieurs images à travers ce guide, est
une image dans le domaine public de
https://en.wikipedia.org/wiki/User:Severnjc[John Severns] du
https://en.wikipedia.org/wiki/Main_Page[projet Wikipédia en anglais] via
https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg[Wikimedia Commons].

L'image de ferme, qui apparaît dans plusieurs images au cours de ce guide, est
une image dans le domaine public de Xianmin Chang via
https://commons.wikimedia.org/wiki/File:Bere%26ModernBarley.jpg[Wikimedia Commons].

L'image de laitue, qui apparaît dans plusieurs images au cours de ce guide, est
une image dans le domaine public de https://www.goodfreephotos.com/[Yinan Chen]
via https://commons.wikimedia.org/wiki/File:Gfp-salad.jpg[Wikimedia Commons].

L'image de carotte, qui apparaît dans plusieurs images au cours de ce guide, est
une image dans le domaine public
https://www.ars.usda.gov/oc/images/photos/nov04/k11611-1/[K11611-1] de Stephen
Ausmus de
l'https://en.wikipedia.org/wiki/Agricultural_Research_Service[Agricultural
Research Service du département d'agriculture des États-Unis] via
https://commons.wikimedia.org/wiki/File:Carrots_of_many_colors.jpg[Wikimedia Commons].

==== Traduction en français

La traduction en français de ce guide a été coordonnée par :

* https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky]

* https://www.drupal.org/u/fmb[Felip Manyer i Ballester]
