[[copyright]]
=== Droits d'auteur

[role="summary"]
Informations relatives au droit d'auteur de ce guide.

(((Droits d'auteur pour ce document)))

Ce guide a été écrit par des contributeurs du projet à code source ouvert
Drupal, copyright 2015-copyright_upper_year contributeurs individuels, et peut
être utilisé en accord avec la
https://creativecommons.org/licenses/by-sa/2.0/deed.fr[Licence Creative Commons,
Attribution - Partage dans les Mêmes Conditions 2.0] (CC BY-SA 2.0). Chaque page
de ce document (y compris celle-ci) comporte à la fin une section d'attributions
énumérant les personnes ayant contribué à l'écriture, la modification ou la
traduction de cette page. Consulter également <<attributions>> pour la
modification de l'ensemble du guide, la traduction, et des informations
relatives à la gestion du projet.

La licence CC BY-SA (très similaire à la GPL) permet à quiconque de copier,
modifier, et redistribuer des modifications de tout ou partie de cette œuvre, du
moment que les conditions suivantes sont remplies :

* Vous créditez correctement l'œuvre (consulter la licence pour de plus amples
informations).
* Vous fournissez un lien vers la licence.
* Vous indiquez si des modifications ont été apportées.
* Vous distribuez l'œuvre sous les mêmes conditions que cet original.

*Attributions*

Cette page a été adaptée et modifiée par
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
et https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle], à partir de
https://www.drupal.org/terms["Documentation copyright and licensing"],
copyright 2000-copyright_upper_year contributeurs individuels à la
https://www.drupal.org/documentation[documentation de la communauté Drupal].
Traduit par https://www.drupal.org/u/fmb[Felip Manyer i Ballester].


// The following is the copyright statement to appear at the bottom of
// each page in the HTML display of this guide.

[role="copyright"]
Droit d'auteur : copyright 2015-copyright_upper_year contributeurs individuels;
consulter <<copyright>> pour plus d'informations. Sous licence
https://creativecommons.org/licenses/by-sa/2.0/deed.fr[CC BY-SA 2.0].
