[[install-composer]]
=== Utiliser Composer pour télécharger et mettre à jour les fichiers

[role="summary"]
Comment utiliser l'outil Composer pour gérer les fichiers du cœur (core) et les
modules et thèmes contribués.

(((Outil Composer,utiliser pour télécharger le cœur)))
(((Outil Composer,utiliser pour télécharger des modules)))
(((Outil Composer,utiliser pour télécharger des thèmes)))
(((Cœur,télécharger)))
(((Cœur,mettre à jour)))
(((Télécharger,cœur)))
(((Télécharger,thème)))
(((Télécharger,module)))
(((Dépendances logicielles,gérer)))
(((Module,télécharger)))
(((Module,mettre à jour)))
(((Thème,télécharger)))
(((Thème,mettre à jour)))
(((Thème contribué,télécharger)))
(((Thème contribué,mettre à jour)))
(((Module contribué,télécharger)))
(((Module contribué,mettre à jour)))
(((Mise à jour de sécurité,appliquer)))

==== Objectif

Utiliser Composer pour télécharger et mettre à jour les fichiers et les
dépendances du cœur (core) ou des modules et thèmes contribués. Passer ce sujet
si vous n'utilisez pas Composer.

==== Prérequis

<<install-tools>>

==== Prérequis du site

Si vous voulez utiliser Composer, il doit être installé, soit sur votre serveur
de développement local, soit sur votre site en production. Consulter
<<install-tools>>.

==== Étapes

Si vous n'êtes pas en mesure d'installer l'outil Composer sur votre serveur de
production, vous pouvez suivre les étapes dans n'importe laquelle des sections
ci-dessous sur votre serveur local, et ensuite transférer tout fichier ajouté ou
mis à jour sur votre serveur de production. La procédure recommandée est de
faire une archive ou un fichier zip des nouveaux répertoires ou des répertoires
modifiés que vous tranférerez sur votre serveur de production, d'y supprimer les
répertoires qui ont été modifiés, et d'extraire l'archive. Inspecter les
modifications et ajouts aux fichiers suivants, à la racine de votre
installation :

* répertoire _vendor_
* _autoload.php_
* _composer.json_
* _composer.lock_

===== Utiliser Composer pour télécharger le cœur (core)

Suivre ces étapes si vous n'avez pas encore téléchargé ou installé le cœur, et
que vous voulez utiliser Composer pour télécharger à la fois le cœur et ses
dépendances externes :

. Dans la ligne de commande, se placer un niveau au-dessus du répertoire où vous
souhaitez que se trouve le logiciel.

. Saisir cette commande, où _monrépertoire_ est le répertoire que vous souhaitez
créer :
+
----
composer create-project drupal/recommended-project monrépertoire
----

. La dernière version du cœur sera téléchargée dans le sous-répertoire
_monrépertoire/web_.

===== Convertir un site précédemment téléchargé à l'utilisation de Composer

Si vous avez précédemment téléchargé le cœur sans utiliser Composer, vous
pourriez vous rendre compte plus tard que vous voulez ou devez utiliser Composer
pour gérer et mettre à jour les dépendances. Pour les sites créés en utilisant
la version 8.8.0 ou postérieure du cœur, les fichiers contiennent déjà la
configuration nécessaire pour Composer et vous pouvez commencer à utiliser
Composer à n'importe quel moment.

Si votre site comprend des modules, thèmes, ou profils qui ne font pas partie du
cœur, c'est une bonne idée de les ajouter au fichier _composer.json_ dans le
répertoire racine de votre site.

Lancer la commande suivante une fois pour chaque module, thème ou profil
téléchargé depuis Drupal.org en remplaçant +nom_du_module+ par le nom du projet
que vous voulez ajouter :

----
composer require drupal/nom_du_module
----

Voir ci-dessous pour plus d'informations sur la gestion des dépendances du site
avec Composer.

Pour convertir un site qui a été créé en utilisant une version du cœur
antérieure à 8.8.0, ou qui a été installée depuis un fichier zip ou tar.gz
téléchargé depuis Drupal.org, consulter les instructions sur la page
https://www.drupal.org/docs/installing-drupal/add-composer-to-an-existing-site[Add Composer to an existing site]
(en anglais).

===== Utiliser Composer pour télécharger un module ou un thème

Suivre ces étapes si vous utilisez déjà Composer pour gérer le cœur, et que vous
voulez utiliser Composer pour ajouter un module ou thème contribué avec ses
dépendances.

. Chaque fois que vous voulez ajouter un module ou thème contribué, déterminer
le nom court du projet. Il s'agit de la dernière partie de l'URL de la page du
projet ; par exemple le module Geofield, à l'adresse
https://www.drupal.org/project/geofield, a pour nom court +geofield+.

. Pour télécharger le module ou thème contribué avec ses dépendances externes,
saisir la commande suivante à la racine de votre site (en remplaçant +geofield+
par le nom court du module ou du thème) :
+
----
composer require drupal/geofield
----

===== Utiliser Composer pour mettre à jour des fichiers précédemment téléchargés

Suivre ces étapes pour mettre à jour les fichiers du cœur ou d'un thème ou
module contribué, après avoir commencé à gérer les dépendances avec Composer :

. Déterminer le nom court du projet que vous voulez mettre à jour. Pour le cœur,
il s'agit de _core_. Pour des modules ou thèmes contribués, il s'agit de la
dernière partie de l'URL de la page du projet ; par exemple le module Geofield,
à l'adresse https://www.drupal.org/project/geofield, a pour nom court +geofield+.

. Si vous voulez mettre à jour vers la dernière version stable, utiliser la
commande suivante, en remplaçant +geofield+ par le nom court du projet à mettre
à jour :
+
----
composer update drupal/geofield --with-dependencies
----

. S'il vous faut une version spécifique, déterminer comment saisir le numéro de
version vers lequel vous voulez mettre à jour. Par exemple, pour la version
8.x-1.16 d'un module contribué, vous saisiriez juste 1.16, tandis que pour la
version 9.0.7 du cœur, vous saisiriez 9.0.7. Saisir ensuite la commande suivante
à la racine de votre site (en remplaçant +geofield+ par le nom court du projet
et en indiquant le bon numéro de version) :
+
----
composer require drupal/geofield:1.16
----

==== Améliorer votre compréhension

Vous pouvez en apprendre plus sur les commandes de Composer en utilisant son
sytème d'aide intégré. Par exemple, pour en savoir plus sur la commande
`create-project`, saisir `composer help create-project` dans votre invite de
commande.

// ==== Related concepts

==== Vidéos

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/v-WeFthdmD4[title="Using Composer and Git to Download Files"]

==== Pour aller plus loin (en anglais)

* https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies[Page de documentation  de la communauté sur _Drupal.org_ "Using Composer to manage Drupal site dependencies"]
* https://www.drupal.org/docs/updating-drupal/update-drupal-core-via-composer[Page de documentation de la communauté sur _Drupal.org_ "Update Drupal core via Composer"]
* https://www.drupal.org/docs/installing-drupal/add-composer-to-an-existing-site[Page de documentation de la communauté sur _Drupal.org_ "Add Composer to an existing site"]

*Attributions*

Adapté par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
https://www.drupal.org/u/hansfn[Hans Fredrik Nordhaug], et
https://www.drupal.org/u/eojthebrave[Joe Shindelar] de
https://drupalize.me[Drupalize.Me] à partir de
https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies["Using Composer to manage Drupal site dependencies"],
copyright 2000-copyright_upper_year contributeurs individuels à la
https://www.drupal.org/documentation[documentation de la communauté de Drupal].
Traduit par https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
