[[install-requirements]]

=== Concept: Server Requirements

[role="summary"]
Vue d'ensemble des pré-requis pour le serveur pour l'installation et le
fonctionnement du cœur (core) du logiciel.

(((Pré-requis à l'installation,vue d'ensemble)))
(((Pré-requis à l'installation,espace disque)))
(((Pré-requis à l'installation,serveur web)))
(((Pré-requis à l'installation,base de données)))
(((Pré-requis à l'installation,langage de programmation PHP)))
(((Installer,cœur du logiciel)))
(((Cœur du logiciel,pré-requis à l'installation)))
(((Espace disque,pré-requis à l'installation)))
(((Serveur web,pré-requis à l'installation)))
(((Serveur web Apache,version exigée)))
(((Serveur web Hiawatha,version exigée)))
(((Serveur web Nginx,version exigée)))
(((Serveur web IIS,version exigée)))
(((Base de données,installation requirements)))
(((Base de données MySQL,version exigée)))
(((Base de données PostgreSQL,version exigée)))
(((Base de données SQLite,version exigée)))
(((Langage de programmation PHP,version exigée)))

// ==== Prerequisite knowledge

==== Quels sont les pré-requis pour faire fonctionner le cœur du logiciel ?

===== Espace disque

Une installation minimum nécessite 15 Mo. 60 Mo sont nécessaires pour un site
avec de nombreux modules communautaires et thèmes installés. Gardez en tête que
vous aurez besoin de plus d'espace pour la base de données, les fichiers déposés
par les utilisateurs, les médias, les sauvegardes, et les autres fichiers.

===== PHP

PHP 7.2 ou supérieur. PHP doit être configuré avec un espace mémoire minimal de
64 Mo ; si vous utilisez plusieurs modules sur votre site ou des outils en ligne
de commande basés sur PHP qui consomment beaucoup de mémoire (comme Composer),
une quantité de mémoire considérablement plus importante pourrait être
nécessaire.

Certaines extensions PHP sont également requises ; la liste exacte des
extensions PHP dépend de la manière dont vous installez le cœur du logiciel et
des modules que vous utilisez sur le site. En général, les fournisseurs de
services d'hébergement ont déjà installé les extensions PHP dont vous aurez
besoin. Si vous hébergez vous même votre site ou s'il tourne en local sur votre
ordinateur, vous verrez des messages d'erreur pendant l'installation si des
extensions PHP nécessaires sont manquantes, et devriez être en mesure de les
installer avant de continuer.

===== Serveur web

Apache (recommandé)::
  Apache est le serveur web le plus fréquemment utilisé. Le cœur du logiciel
  fonctionnera avec Apache 2.x hébergé sur UNIX/Linux, OS X, ou Windows avec
  module mod_rewrite d'Apache installé et activé. La configuration du
  VirtualHost d'Apache doit contenir la directive _AllowOverride All_ pour
  autoriser l'utilisation des fichiers _.htaccess_.
Nginx::
  Nginx est un serveur web qui se concentre sur les accès concurrents, la
  performance et une faible utilisation de la mémoire. Le cœur du logiciel
  fonctionnera avec Nginx 1.1 ou supérieur herbergé sur UNIX/Linux, OS X, ou
  Windows. ngx_http_rewrite_module doit être installé et activé.
Hiawatha::
  Hiawatha est un serveur web qui se concentre sur la sécurité. Il se veut aussi
  facile à utiliser et léger. Des recherches effectuées par des chercheurs
  indépendants prouve que Hiawatha offre une performance comparable aux autres
  serveurs web dans les mêmes conditions d'utilisation, mais meilleure en cas
  d'attaques. URL Toolkit doit être installé et configuré pour la réécriture
  d'URL.
Microsoft IIS::
  Microsoft IIS est un serveur web et un ensemble de modules et de
  fonctionnalités tournant sous Microsoft Windows. Le cœur du logiciel
  fonctionnera avec IIS 5, IIS 6, ou IIS 7 si PHP est configuré correctement. En
  raison de la nécessité de la réécriture d'URL, vous pourriez avoir besoin d'un
  logiciel supplémentaire. Pour IIS 7, vous pouvez utiliser le module Microsoft
  URL Rewrite ou une autre solution externe.

===== Database

Utiliser une des bases de données suivantes :

* MySQL - 5.5.3 (MariaDB 5.5.20, Percona 5.5.8) ou supérieur avec un moteur
de stockage compatible InnoDB

* PostgreSQL - 9.1.2 ou supérieur

* SQLite - 3.4.2 ou supérieur

//==== Sujets liés

==== Pour aller plus loin (en anglais)

https://www.drupal.org/docs/8/system-requirements[_Drupal.org_ community documentation page "System requirements"]


*Attributions*

Adapté par https://www.drupal.org/u/KarlKedrovsky[Karl Kedrovsky] et
https://www.drupal.org/u/bemery987[Brian Emery] depuis
https://www.drupal.org/docs/8/system-requirements["System requirements"],
copyright 2000-2019 contributeurs individuels à la
https://www.drupal.org/documentation[documentation de la communauté Drupal].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
