[[install-decide]]
=== Concept : méthodes pour télécharger et installer le cœur (core)

[role="summary"]
Vue d'ensemble des méthodes que vous pouvez utiliser pour télécharger le cœur
(core).

(((Télécharger,cœur)))
(((Installer,cœur)))
(((Cœur,télécharger)))
(((Cœur,installer)))

==== Prérequis

* <<install-tools>>
* <<install-requirements>>
* <<understanding-distributions>>

==== Quelles sont les méthodes disponibles pour télécharger le cœur ?

Pour construire un site, vous devrez d'abord télécharger le cœur (core). En
fonction de vos plans, il y a plusieurs manières de télécharger le cœur :

Essayer une démo en ligne gratuite::
  Si vous êtes en train d'évaluer Drupal en vue de l'utiliser pour construire un
  site, vous pouvez recourir à un fournisseur en ligne pour obtenir une
  installation de démonstration du cœur, cela ne prend pas plus de 20 minutes. Consulter la 
  https://www.drupal.org/try-drupal[page "Try Drupal" sur _Drupal.org_].

Utiliser un installeur en un clic chez votre hébergeur::
  Si vous décidez d'installer le cœur chez votre hébergeur, ce dernier pourrait
  offrir une documentation spécifique et/ou une installation en un clic.
  Consulter
  https://www.drupal.org/association/supporters/hosting[la liste d'hébergeurs qui supportent Drupal sur _Drupal.org's_].

Utiliser un environnement pré-configuré::
  Utiliser un environnement pré-configuré ou une machine virtuelle qui contient
  Drupal et tous les composants logiciels requis pour installer Drupal en local.
  Consulter la section concernant votre système d'exploitation sur la
  https://www.drupal.org/docs/develop/local-server-setup[page de documentation de la communauté sur _Drupal.org_ "Local server setup guide"]
  avec les options envisageables.

Téléchargement manuel depuis le site web::
  Si vous prévoyez de construire un site sans modules complémentaires avec des
  dépendances complexes, vous pouvez télécharger le cœur, ou une distribution
  qui contient le cœur et des modules et thèmes additionnels, depuis le site
  web. Consulter <<install-manual>> pour des instructions.

Utiliser Composer::
  Si vous prévoyez d'utiliser l'outil Drush (consulter <<install-tools>>), ou si
  vous êtes en train de construire un site qui pourrait utiliser des modules
  avec des dépendances complexes, vous devriez utiliser Composer pour
  télécharger le cœur, car Composer gèrera correctement les dépendances.
  Si vous commencez votre site en le téléchargeant manuellement, vous pourrez
  plus tard le convertir en une installation utilisant Composer. Consulter
  <<install-composer>> pour des instructions pour le téléchargement et la
  conversion.

==== Que se passe-t-il quand j'installe le cœur ?

_Installer_ le cœur signifie mettre en place les tables dans la base de données,
la configuration, et un compte d'utilisateur d'administration, de manière à ce
que vous puissiez construire et utiliser votre site.

==== Quelles sont le méthodes disponibles pour installer le cœur ?

Il y a plusieurs manières d'installer le cœur (core) :

Installeur en arrière-plan::
  Si vous décidez d'utiliser une démo en ligne ou un installeur chez votre
  hébergeur, le cœur pourrait être installé automatiquement pour vous.

Installeur interactif::
  Le cœur comporte un installeur interactif qui vous présente plusieurs
  formulaires en ligne, et achève l'installation en  utilisant les informations
  que vous saisissez dans les formulaires. Consulter <<install-prepare>> et
  <<install-run>>.

Installeur d'un site de démo::
  Si vous téléchargez le cœur sur votre ordinateur local, vous pouvez rapidement
  créer un site de démo temporaire qui utilise le serveur web intégré et la base
  de données SQLite qui sont pris en charge par PHP. La commande pour mettre en
  place un site de démo est donnée à la fin d'<<install-manual>>. Dans ce cas,
  vous n'aurez pas à lancer l'installer interactif.

Outil en ligne de commande::
  Des outils en ligne de commande (consulter <<install-tools>>) peuvent
  également être utilisés pour mener à bien les étapes de l'installation.

// ==== Related topics

// ==== Additional resources

*Attributions*

Écrit et modifié par https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan]
d'https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
et https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
