[[install-requirements]]

=== Concept: Server Requirements

[role="summary"]
Vue d'ensemble des pré-requis pour le serveur pour l'installation et le
fonctionnement du cœur (core) du logiciel.

(((Pré-requis à l'installation,vue d'ensemble)))
(((Pré-requis à l'installation,espace disque)))
(((Pré-requis à l'installation,serveur web)))
(((Pré-requis à l'installation,base de données)))
(((Pré-requis à l'installation,langage de programmation PHP)))
(((Installer,cœur du logiciel)))
(((Cœur du logiciel,pré-requis à l'installation)))
(((Espace disque,pré-requis à l'installation)))
(((Serveur web,pré-requis à l'installation)))
(((Serveur web Apache,version exigée)))
(((Serveur web Nginx,version exigée)))
(((Serveur web IIS,version exigée)))
(((Base de données,pré-requis à l'installation)))
(((Base de données MySQL,version exigée)))
(((Base de données PostgreSQL,version exigée)))
(((Base de données SQLite,version exigée)))
(((Langage de programmation PHP,version exigée)))

// ==== Prerequisite knowledge

==== Quels sont les pré-requis pour faire fonctionner le cœur du logiciel ?

===== Espace disque

L'espace disque requis pour votre site n'est pas une quantité fixée, dans la
mesure où il dépend de votre site. Les fichiers de base pour le cœur du logiciel
occupent jusqu'à 100 Mo sur le serveur web. Vous aurez besoin de plus d'espace
si vous installez des modules additionnels ou des thèmes, et vous aurez
également besoin d'espace pour les médias, les sauvegardes, et autres fichiers
générés par votre site ou téléversés. La base de données occupe également de
l'espace disque, bien que souvent elle ne se trouve pas au même endroit (et
dans certains cas, sur le même serveur) que celui utilisé pour les fichiers du
site.

===== PHP

PHP 7.2 ou supérieur. PHP doit être configuré avec un espace mémoire minimal de
64 Mo ; si vous utilisez plusieurs modules sur votre site ou des outils en ligne
de commande basés sur PHP qui consomment beaucoup de mémoire (comme Composer),
une quantité de mémoire considérablement plus importante pourrait être
nécessaire.

Certaines extensions PHP sont également requises ; la liste exacte des
extensions PHP dépend de la manière dont vous installez le cœur du logiciel et
des modules que vous utilisez sur le site. En général, les fournisseurs de
services d'hébergement ont déjà installé les extensions PHP dont vous aurez
besoin. Si vous hébergez vous même votre site ou s'il tourne en local sur votre
ordinateur, vous verrez des messages d'erreur pendant l'installation si des
extensions PHP nécessaires sont manquantes, et devriez être en mesure de les
installer avant de continuer.

===== Serveur web

Apache (recommandé)::
  Apache est le serveur web le plus fréquemment utilisé. Le cœur du logiciel
  fonctionnera avec Apache 2.x hébergé sur UNIX/Linux, OS X, ou Windows avec
  module mod_rewrite d'Apache installé et activé. La configuration du
  VirtualHost d'Apache doit contenir la directive _AllowOverride All_ pour
  autoriser l'utilisation des fichiers _.htaccess_.
Serveur local de PHP::
  Vous pouvez temporairement faire tourner un site de démonstration en local sur
  votre ordinateur en utilisant juste PHP, sans installer de serveur web.
Nginx::
  Nginx est un serveur web qui se concentre sur les accès concurrents, la
  performance et une faible utilisation de la mémoire. Le cœur du logiciel
  fonctionnera avec Nginx 1.1 ou supérieur herbergé sur UNIX/Linux, OS X, ou
  Windows. ngx_http_rewrite_module doit être installé et activé.
Microsoft IIS::
  Microsoft IIS est un serveur web et un ensemble de modules et de
  fonctionnalités tournant sous Microsoft Windows. Le cœur du logiciel
  fonctionnera avec IIS 5, IIS 6, ou IIS 7 si PHP est configuré correctement. En
  raison de la nécessité de la réécriture d'URL, vous pourriez avoir besoin d'un
  logiciel supplémentaire. Pour IIS 7, vous pouvez utiliser le module Microsoft
  URL Rewrite ou une autre solution externe.

===== Database

Utiliser une des bases de données suivantes :

* MySQL - 5.5.3 (MariaDB 5.5.20, Percona 5.5.8) ou supérieur avec un moteur
de stockage compatible InnoDB

* PostgreSQL - 9.1.2 ou supérieur

* SQLite - 3.4.2 ou supérieur

//==== Sujets liés

==== Pour aller plus loin (en anglais)

https://www.drupal.org/docs/system-requirements[Page de documentation de la communauté sur _Drupal.org_ "System requirements"]
* https://secure.php.net/manual/en/configuration.php[PHP Runtime Configuration (PHP memory limit and other settings)]
* https://www.drupal.org/docs/official_docs/en/_local_development_guide.html[Installing a new Drupal application on your local machine]
* https://www.drupal.org/docs/official_docs/en/_evaluator_guide.html[Creating a Drupal demo application for evaluation purposes]

*Attributions*

Adapté par https://www.drupal.org/u/KarlKedrovsky[Karl Kedrovsky],
https://www.drupal.org/u/bemery987[Brian Emery], et
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] depuis
https://www.drupal.org/docs/system-requirements["System requirements"],
copyright 2000-copyright_upper_year contributeurs individuels à la
https://www.drupal.org/documentation[documentation de la communauté Drupal].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
