[[install-prepare]]
=== Se préparer à l'installation

[role="summary"]
Comment télécharger le cœur du logiciel et satisfaire aux prérequis à
l'installation.

(((Télécharger,cœur du logiciel)))
(((Cœur (core) de Drupal,préparer l'installation)))

==== Objectif

Télécharger le cœur du logiciel, et prendre en compte les prérequis à
l'installation.

==== Prérequis

* <<install-requirements>>

* <<install-tools>>

* <<install-decide>>

* Comment installer et configurer des logiciels sur un serveur (si
l'installation se fait sur votre propre ordinateur)

* Comment configurer l'hébergement pour un site web générique

* Comment créer une base de données

==== Prérequis du site

Les logiciels serveurs doivent être installés sur le serveur où vous avez
l'intention d'héberger votre site. Consulter <<install-requirements>>.

Selon la méthode de téléchargement du cœur du logiciel que vous envisagez, vous
pourriez avoir besoin d'installer auparavant des logiciels additionnels.
Consulter <<install-decide>> et <<install-tools>>.

==== Étapes

. Choisir une méthode pour télécharger ou installer le cœur du logiciel, à
partir de celles listés dans <<install-decide>>. Le reste de ces instructions
s'applique aux options utilisant Composer, au téléchargement manuel et à
l'installeur interactif ; si vous avez choisi d'autres options, le logiciel
devrait être installé pour vous.

. Configurer une URL et un hébergement pour votre site sur le serveur. Vérifier
que l'hébergement fonctionne en plaçant un simple fichier HTML dans le
répertoire racine de votre hébergement, et en visitant l'URL de votre site.

. Créer une base de données, ainsi qu'un utilisateur de la base de données
jouissant d'un accès complet.

. Transférer les fichiers du cœur du logiciel dans le répertoire racine du site
web, en utilisant la méthode que vous avez choisie. Consulter <<install-decide>>
pour des liens vers les instructions.

==== Améliorer votre compréhension

Consulter <<install-run>> pour lancer l'installeur interactif.

Alternativement, vous pouvez utiliser la commande Drush suivante, depuis le
répertoire où vous avez transféré le logiciel, où _DB_NAME_, _DB_USER_ et
_DB_PASS_ sont les identifiants de votre base de données :

----
drush site:install standard --db-url='mysql://DB_USER:DB_PASS@localhost/DB_NAME' --site-name=example
----

// ==== Concepts liés

==== Vidéos (en anglais)

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/7Aib3y9DM80[title="Preparing to Install"]

==== Pour aller plus loin (en anglais)

http://www.drush.org[Drush]


*Attributions*

Écrit et modifié par https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] de
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
and https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
