[[planning-modular]]
=== Concept : contenu modulaire

[role="summary"]
Vue d'ensemble de la modularité du contenu et comment le contenu d'une page peut
provenir de différents éléments de contenus.

(((Contenu,modulaire)))
(((Contenu module,vue d'ensemble)))
(((Page,composite)))
(((Page composite,créer à partir de contenu modulaire)))
(((Vue,et contenu modulaire)))
(((module Views,vue d'ensemble)))

==== Prérequis

* <<planning-data-types>>
* <<planning-layout>>

==== Qu'est ce qu'un contenu modulaire ?

Étant donné que le contenu de votre site est stocké dans une base de données, il
est préférable de rendre le contenu _modulaire_, ce qui signifie que certaines
pages de votre site, plutôt que d'être modifiées comme une seule page, sont à la
place générées automatiquement depuis d'autres éléments de contenus. Par
exemple, dans le scénario du site du marché fermier, vous pourriez créer des
éléments de contenu individuels pour les recettes. Si les éléments de contenu de
type recette ont un champ qui garde une trace des ingrédients, alors votre site
pourrait inclure une page composite qui listerait les recettes et autoriserait
les visiteurs à rechercher une recette qui contiendrait un ingrédient
particulier qu'ils ont acheté au marché.

Des morceaux de pages plus petits peuvent aussi être générés. Par exemple, une
recette peut contenir un champ qui fait le lien avec le vendeur qui l'a proposée
(consulter <<structure-reference-fields>>), avec le détail du vendeur modifié
dans un contenu vendeur séparé. Cela permet de faire les choses suivantes sur
votre site :

* Sur chaque page Recette, il pourrait y avoir une zone qui affiche certaines
informations à propos du vendeur qui a proposé la recette, comme son nom, et le
numéro de son étal au marché.

* Chaque vendeur pourrait avoir une section qui liste les recettes qu'il a
proposées.

L'idée directrice est que chaque morceau d'information est modifié une seule
fois, à un seul endroit. Quand l'information sur un vendeur est mise à jour,
toutes les pages de recette qui affichent ces informations sur le vendeur sont
automatiquement mises à jour ; quand une recette est soumise par un vendeur,
elle est automatiquement affichée sur la page du vendeur. Le module du cœur
Views est le moyen standard pour utiliser le contenu modulaire et créer des
pages composées et des sections de pages ; consulter <<views-concept>> pour plus
d'informations. De plus, les _modes d'affichages_ sont utiles pour définir
différentes façons d'afficher chaque élément de contenu, voir
<<structure-view-modes>> pour plus d'informations.


==== Sujets liés

* <<planning-structure>>
* <<structure-content-type>>
* <<structure-fields>>
* <<structure-reference-fields>>
* <<structure-view-modes>>
* <<views-concept>>

// ==== Pour aller plus loin


*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
