[[preface-scenario]]
=== Scénario guide

[role="summary"]
Comprendre le scénario du projet utilisé dans ce guide pour mieux suivre les
sujets abordés.

(((Scénario pour ce document (marché fermier),vue d'ensemble)))
(((Scénario guide pour ce document (marché fermier))))
(((Scénario d'usage (marché fermier))))
(((Marché fermier,scénario d'usage pour ce document)))

À l'heure de lire ce guide, il est utile d'avoir à l'esprit un projet de site à
construire. Le scénario de projet suivant fournit un contexte et lie ensemble
les exemples de ce guide :

Vous êtes en train de réaliser un site web pour un marché fermier. Le site doit
afficher des informations sur la localisation et les heures de marché, et une
page _À propos_ expliquant l'histoire du marché. Il doit aussi lister les
vendeurs. Ces derniers devraient être capables de modifier leur éléments (dont
un logo ou une photo), et poster des recettes. Les visiteurs du site devraient
pouvoir naviguer dans les recettes, ou trouver des recettes utilisant les
ingrédient achetés au marché. Certains visiteurs parlent une autre langue, de
sorte que les pincipales pages et les pages des vendeurs doivent être traduites.

Au fur et à mesure que vous lisez ce guide et mettez en pratiques les tâches
qu'il décrit, vous pouvez choisir de suivre exactement le scénario ; vous pouvez
aussi adapter les tâches à votre but. Si vous voulez effectivement suivre le
scénario à la lettre, vous verrez que vous aurez besoin des fichiers des
images, qui se trouvent dans le répertoire _assets_ de l'archive _.zip_ ou
_.tgz_ à télécharger depuis la page
https://www.drupal.org/project/user_guide[User Guide project page].

*Attributions*

Écrit et modifié par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traduit par https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
