[[preface-organization]]
=== Organisation

[role="summary"]
Comprendre l'organisation et la structure de ce guide pour une navigation
améliorée à travers les sujets.

Ce guide utilisateur comporte une série de sujets, dont chacun couvre une
_tâche_ (comment faire quelque chose) ou un _concept_ (connaissances générales,
terminologie, etc.). Les sujets relatifs à des concepts ont des noms qui
commencent par _Concept :_, tandis que ceux relatifs à des tâches ont des noms
contenant des verbes, comme _Modifier les paramètres de base de votre site_.

Les sujets sont groupés en chapitres dans un ordre logique, les concepts et les
tâches intercalés de manière à ce que les concepts soient présentés avant les
tâches liées, et que les tâches s'appuient les unes sur les autres. Pour en
tirer profit, la lecture du guide entier dans l'ordre de sa présentation est
encouragée, éventuellement en passant les sujets qui ne nous intéressent pas ou
qui présentent des informations que vous connaissez déjà. Penser à essayer les
tâches sur votre propre site au fur et à mesure que vous lisez ce guide ; la
plupart des gens apprennent mieux en faisant qu'en lisant.

Si vous préférez, vous pouvez utiliser l'index ou la table des matières pour
consulter directement un sujet à propos duquel vous souhaitez en savoir plus,
plutôt que de lire l'ensemble du guide. Afin de faciliter cette approche, chaque
sujet énumère, le cas échéant, les pré-requis nécessaires à sa compréhension
(avec des liens vers les sujets concernés) ; les sujets relatifs à des tâches
sont désignés comme des _pré-requis du site_ (éléments qui nécessitent d'être
configurés ou créés sur votre site afin de réaliser la tâche). En outre, la
plupart des sujets comportent à la fin des sections où vous pouvez trouver des
informations liées et/oû des tâches pour approfondir vos connaissances, ou
continuer votre apprentissage.

Vous pourriez également vous référer au à la section <<glossary>> au cours de
votre lecture -- elle fournit des définitions brèves de la plupart de la
terminologie utilisée dans ce guide, avec des liens vers les sujets comportant
de plus amples explications.


*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
