[[preface-audience]]

=== Public et objectif

[role="summary"]
Comprendre le public visé par ce guide, et ce qu'ils en apprendront.

Ce guide a été écrit principalement à destination de personnes ayant un niveau
de connaissances minimal du système de gestion de contenus Drupal. Les sujets
choisis les aideront à gagner en compétences sur l'installation,
l'administration, la construction de sites et/ou la maintenance de contenus d'un
site web basé sur Drupal. Ce guide vise également les personnes qui ont déjà une
expérience de la version courante ou d'une version antérieure de Drupal, et qui
veulent élargir la gamme de leurs compétences et connaissances, ou les mettre
à jour avec la nouvelle version.

Ce guide part du principe que vous avez déjà décidé d'apprendre et d'utiliser
Drupal. Si vous voulez en savoir plus avant de prendre cette décision, consulter
<<understanding-drupal>>.

En fonction des aspects de Drupal que vous souhaitez apprendre, you aurez besoin
de connaissances préalables pour comprendre ce guide : certaines compétences et
connaissances générales liées à Internet sont présupposées, et ce guide se
concentre sur l'utilisation du logiciel en lui-même. Par exemple, les sections
sur l'installation de Drupal sur un serveur web présupposent que vous pouvez
acquérir un hébergement web et comprendre comment transférer des fichiers vers
l'hébergement web choisi. De même, les sections traitant de la gestion  de
contenus présupposent que vous savez vous connecter à un site web et remplir un
formulaire web.

Après avoir lu ce guide, vous devriez être capable de :

* Planifier l'architecture du contenu d'un site basé sur Drupal.

* Construire le site planifié.

* Gérer et administrer votre site.

* Comprendre la documentation et les articles de blogs sur des sujets qui ne
sont pas abordés ici, pour étendre votre connaissance et vos compétences.

* Entrer en contact avec la communauté Drupal mondiale.

*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
