[[prevent-backups]]

=== Concept : sauvegarde de données

[role="summary"]
Vue d'ensemble des sauvegardes de données et de ce qui devrait être sauvegardé
sur un site.

(((Sauvegarde,vue d'ensemble)))
(((Contenu,sauvgarder)))
(((Fichier,sauvgarder)))
(((Base de données,sauvegarder)))

==== Prérequis

* <<understanding-drupal>>
* <<install-prepare>>

==== En quoi consiste la sauvegarde d'un site ?

Si quelque chose arrive à l'ordinateur (ou aux ordinateurs) sur lequel votre
site et sa base de données tournent, ou si vous ne pouvez plus accéder à cet
ordinateur, vous pourriez perdre tout ou partie des données de votre site. Vous
pourriez aussi perdre des données si votre site est attaqué, ou si quelqu'un
jouissant des droits d'administration sur votre site supprime ou modifie des
données par erreur depuis l'interface d'administration. Afin d'empêcher de tels
scénarios de pertes de données irréversibles et coûteuses, il est important de
réaliser régulièrement des sauvegardes des données de votre site, et de les
stocker dans un lieu éloigné de l'endroit où se trouve l'ordinateur sur lequel
tourne votre site.

La fréquence à laquelle vous devriez sauvegarder vos données, et la quantité de
sauvegardes que vous devriez conserver, dépendent de la fréquence à laquelle votre
site change. Si vous avez sur votre site un très large volume de contenus qui
sont ajoutés ou mis à jour de nombreuses fois chaque jour, vous voudrez
probablement réaliser des sauvegardes plus fréquemment que s'il s'agit d'un site qui change
rarement. Il faut également prendre en compte qu'il pourrait s'écouler quelque temps
entre le moment où un problème affecte les données et celui où vous vous en
rendez compte, de sorte que stocker une série de sauvegardes (pour pouvoir
revenir au dernier état correct connu de vos données et les extraire), plutôt
que d'écraser de manière répétée une seule sauvegarde, est une bonne pratique.

Quel que soit le format utilisé pour stocker vos sauvegardes, il ne faut pas perdre de vue qu'il est bon de vérifier que vous pouvez effectivement récupérer
depuis ces sauvegardes des données perdues. Vous pourriez vouloir tester
plusieurs scénarios possibles de perte de données, et vous assurer que vos
données peuvent être restaurées dans tous les cas.

Afin de réaliser une sauvegarde complète de votre site, vous aurez besoin de
faire des copies des éléments suivants :

* Les données dans le répertoire _sites_, y compris le fichier
_sites/default/settings.php_.

* Les données stockées dans la base de données de votre site. Quelques tables
peuvent être tronquées, comme celles stockées dans le cache contenant des
données temporaires et des informations liées aux sessions des utilisateurs,
mais il est toujours prudent de sauvegarder l'ensemble de la base de données.

* Les fichiers téléversés, comme les images et autres pièces jointes. La
localisation de ces fichiers est configurable ; la localisation standard est le
répertoire _sites/default/files_ sous la racine de votre site. Dans le menu
d'administration _Gérer_, naviguer vers _Configuration_ > _Média_ > _Système de
fichiers_ (_admin/config/media/file-system_) et vérifier les localisations des
répertoires contenant les fichiers téléversés ; pour les changer, vous devrez
modifier votre fichier _settings.php_.

* Les modules, les thèmes et tout fichier du logiciel que vous avez
personnalisé. Vous pouvez trouver les modules et thèmes personnalisés
respectivement dans les répertoires _modules_ et _themes_. Certains préfèrent
sauvegarder l'ensemble des fichiers du logiciel, y compris les fichiers du cœur
et les modules et thèmes contribués (que vous pourriez récupérer en les
téléchargeant à nouveau depuis la source), plutôt que de cibler les fichiers
spécifiques qui nécessitent d'être sauvegardés.

Vous pouvez effectuer un test pour confirmer que votre sauvegarde a été réalisée
correctement en faisant une copie de développement de votre site (consulter
<<install-dev-making>>).

==== Sujets liés

* <<security-update-core>>
* <<install-dev-making>>
* <<prevent-cache>>

==== Pour aller plus loin

* https://www.drupal.org/docs/7/backing-up-and-migrating-a-site/backing-up-a-site[Page de documentation de la communauté sur _Drupal.org_ "Backing up a site"]

* Le https://www.drupal.org/project/backup_migrate[module contribué Backup and
Migrate], qui peut être utilisé pour mettre en place des sauvegardes
automatiques de la base de données et des fichiers téléversés.

*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
