[[prevent-cache]]

=== Concept : cache

[role="summary"]
Vue d'ensemble du cache et des données du site qui peuvent être mises en cache.

(((Cache,vue d'ensemble)))
(((Cache des pages,vue d'ensemble)))
(((Module,Internal Page Cache)))
(((Module,Dynamic Page Cache)))
(((Module Internal Page Cache,vue d'ensemble)))
(((Module Dynamic Page Cache,vue d'ensemble)))

==== Prérequis

<<understanding-drupal>>

==== Qu'est-ce que le cache des pages ?

Le logiciel qui fait tourner votre site, à chaque requête de page, doit réaliser
un certain nombre de calculs et récupérer des données depuis la base de données,
afin de composer la page qui est envoyée au navigateur web ou à une autre
application qui accède au site. Ces calculs prennent du temps, ce qui peut
entraîner un temps de chargement plus long qu'il n'est souhaitable pour votre
page.

Il existe plusieurs moyens d'accélerer le temps de chargement de la page, y
compris l'installation de logiciels sur votre serveur. Le système inclut les
modules du cœur Internal Page Cache et Dynamic Page Cache, qui ne nécessitent
aucun logiciel supplémentaire : ils utilisent un mécanisme de cache en base de
données. Ces modules fonctionnent en stockant, durant l'exécution des calculs,
les résultats intermédiaires et le rendu final dans une zone spéciale de la base
de données (connue comme le _cache_). Ensuite, la prochaine fois qu'une requête
compatible est effectuée, les résultats intermédiaires ou les résultats finaux,
selon la situation, peuvent être récupérés et utilisés plutôt que de refaire
l'ensemble des calculs. De plus, lorsque du contenu ou des données qui affectent
un calcul particulier sont mis à jour, les données en cache affectées sont
retirées du cache, forçant cette partie du calcul à être refaite la prochaine
fois qu'on en aura besoin.

Ces modules de cache fonctionnent normalement assez bien, et apportent au moins
un surcroît de vitesse à la plupart des sites. Cependant, le cache des pages
peut parfois rencontrer des problèmes, tels que :

* Des données corrompues en cache, menant à un rendu de la page incorrect.

* De vieilles données restant trop longtemps en cache, menant à des rendus
périmés.

* Un manque de cache, entraînant des chargements de page lents.

==== Quelles autres données sont mises en cache ?

Indépendamment de si les deux modules de cache sont installés sur votre site, le
logiciel sous lequel tourne votre site mettra toujours en cache le résultat de
nombreux calculs internes. Les systèmes du cœur qui mettent des données en cache
incluent :

* La couche de thème met en cache dans la base de données des informations
indiquant quels fichiers de gabarits (_templates_) sont utilisés pour le rendu
de divers types de données. Si vous développez un nouveau thème et ajoutez un
nouveau fichier de gabarit, vous devrez vider le cache pour que le fichier de
votre thème soit reconnu.

* Les fichiers CSS et JavaScript peuvent optionnellement être optimisés et
compressés (en fonction des paramètres de votre site). Si tel est les cas, les
versions compressées sont stockées dans le système de fichiers de manières à ce
qu'elles n'aient pas à être ré-optimisées trop souvent. Si vous développez un
module ou un thème, il pourrait être nécessaire de désactiver ou vider ce cache
de fichiers pour que les modifications de fichiers JavaScript ou CSS soient
reconnues.

* Le système localise certaines fonctions et classes PHP bas niveau, tels que
les mises en œuvres de _hooks_ et les classes d'extension (_plugin classes_),
depuis vos modules installés, et stocke des informations pour savoir quel module
a quelle fonctionnalité. Si vous développez un nouveau module ou ajoutez des
fonctionnalités à un module existant, il pourrait être nécessaire de vider ce
cache de sorte que vos nouvelles fonctionnalités soient reconnues.

==== Sujets liés

Si vous avez des problèmes avec  votre site, la première chose à essayer pour
les résoudre est en général de vider le cache. Consulter <<prevent-cache-clear>>
pour de plus amples informations.

==== Pour aller plus loin (en anglais)

S'informer de méthodes supplémentaires de mise en cache et d'optimisation des
performances sur la
https://www.drupal.org/docs/7/managing-site-performance-and-scalability/caching-to-improve-performance/caching-overview[page de documentation de la communauté sur _Drupal.org_ "Caching overview"].


*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
