[[security-cron-concept]]

=== Concept : cron

[role="summary"]
Vue d'ensemble du cron et différences avec le cron d'Unix.

(((Tâche cron,vue d'ensemble)))
(((Automated Cron module,vue d'ensemble)))

//==== Prerequisite knowledge

==== Que sont les tâches cron ?

Pour s'assurer que votre site et ses modules continuent à fonctionner
correctement, un groupe d'opérations d'administration devraient être lancées
périodiquement. Ces opérations sont appelées des _tâches cron_. Exemples de
tâches cron : vérification des mises à jour des modules et des thèmes,
indexation du contenu pour la recherche, ou nettoyage des fichiers temporaires.

==== Quelle relation existe-t-il entre les tâches cron du site et le cron d'Unix ?

Les systèmes d'exploitation basés sur GNU/Linux ou Unix ont un planificateur qui
peut être utilisé pour exécuter des tâches périodiques. Vous pouvez utiliser le
cron du serveur pour planifier l'exécution des tâches cron de votre site. Vous
pouvez vérifier l'état des tâches cron de votre site dans le tableau de bord
d'administration.

==== Sujets liés

* <<security-cron>>
* <<prevent-status>>

==== Pour aller plus loin

https://www.drupal.org/docs/7/setting-up-cron/overview[Page de documentation de
la communauté sur _Drupal.org_ "Setting up cron"]


*Attributions*

Écrit et modifié par
https://www.drupal.org/u/dianalakatos[Diána Lakatos] de
https://pronovix.com/[Pronovix],
https://www.drupal.org/u/dalin[Dave Hansen-Lange]
d'https://www.advomatic.com/[Advomatic],
et https://www.drupal.org/u/batigolix[Boris Doesborg]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
