[[security-announce]]

=== Rester informé des mises à jour

[role="summary"]
Comment protéger votre site en restant informé des dernières mises à jour de
sécurité.

(((Mettre à jour,rester informé)))
(((Mise à jour de sécurité,rester informé)))
(((Module Update Manager,vue d'ensemble)))
(((Annonce de sécurité,s'inscrire par courriel)))
(((Annonce de sécurité,s'inscrire sur Twitter)))

==== Objectif

Garder votre site sûr et à jour en restant informé des dernières mises à jour de
sécurité.

==== Prérequis

<<security-concept>>

//==== Site prerequisites

==== Étapes

Il y a plusieurs manières différentes de recevoir des notifications de
publications de mises à jour de sécurité :

* Dans le menu d'administration _Gérer_, naviguer vers _Rapports_ > _Mises à
jour disponibles_ > _Paramètres_. Saisir l'adresse électronique à laquelle vous
notifier lorsque de nouvelles mises à jour sont disponibles. Vous pouvez aussi
spécifier si vous voulez être notifié·e de manière quotidienne ou hebdomadaire.
Cliquer sur _Enregistrer la configuration_.

* S'inscrire à la liste de diffusion des annonces de sécurité. Pour vous
enregistrer, se connecter à _Drupal.org_, aller sur la page de votre profil
d'utilisateur et s'inscrire à la liste de diffusion sur l'onglet _Edit_ > _My
newsletters_.

* Suivre @drupalsecurity sur Twitter.

* S'inscrire aux flux RSS pour
https://www.drupal.org/security/rss.xml[core security updates] (mises à jour de
sécurité du cœur), https://www.drupal.org/security/contrib/rss.xml[contributed
project updates] (mises à jour des projets contribués) and
https://www.drupal.org/security/psa/rss.xml[public service announcements]
(annonces de sécurité publiques).

//==== Expand your understanding

==== Concepts liés

* <<security-concept>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>

==== Vidéos (en anglais)

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/GcamYLNeGAs[title="Keeping Track of Updates"]

==== Pour aller plus loin (en anglais)

* https://www.drupal.org/security["Security advisories" sur _Drupal.org_]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team]
* https://twitter.com/drupalsecurity[@drupalsecurity sur Twitter]


*Attributions*

Écrit par https://www.drupal.org/u/hey_germano[Sarah German]
d'https://www.advomatic.com[Advomatic]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
