[[structure-image-styles]]

=== Concept : styles d'images

[role="summary"]
Vue d'ensemble des styles d'images et de la manière dont ils sont utilisés pour
afficher une image donnée sous plusieurs formes.

(((Style d'image,vue d'ensemble)))
(((Style,image)))
(((Effet appliqué à une image,vue d'ensemble)))
(((Effet,image)))



==== Pré-requis

<<structure-fields>>


==== Qu'est ce qu'un style d'image ?

Les styles d'images vous permettent de transférer une seule image, mais de
l'afficher de différentes façons ; chaque variante d'affichage, ou _style
d'image_, est le résultat de l'application d'un ou plusieurs _effets_ sur
l'image originale.

Par exemple, vous pourriez vouloir transférer une image en haute résolution avec
un ratio 4:3, et l'afficher à une échelle plus petite, avec les coins arrondis,
ou en noir et blanc (ou toute combinaison de ces effets). Le cœur du logiciel
fournit un moyen efficace de le faire :

. Configurer un style d'image avec les effets souhaités dans la page _Style
d'image_ (_admin/config/media/image-styles_).

. Les effets seront appliqués la première fois qu'une image particulière doit
s'afficher avec ce style.

. L'image résultante est enregistrée.

. La prochaine fois que le même style est requis, l'image enregistrée est
retrouvée sans qu'il soit nécessaire de recalculer les effets.

Le cœur du logiciel fournit plusieurs effets que vous pouvez utiliser pour
définir les styles ; d'autres peuvent être fournis par les modules
contribués.

Visiter la page des _Styles d'image_ via le menu d'administration _Gérer_, aller 
à _Configuration_ > _Média_ > _Styles d'images_ (_admin/config/media/image-styles_)
pour voir les styles d'images qui sont définis par défaut.

==== Concepts liés

* <<structure-image-style-create>>
* <<structure-image-responsive>>
* <<structure-fields>>


==== Pour aller plus loin (en anglais)

https://www.drupal.org/docs/8/core/modules/image/working-with-images[_Drupal.org_ community documentation page "Working with images in Drupal 7 and 8"]


*Attributions*

Adapté et modifié par https://www.drupal.org/u/batigolix[Boris Doesborg],
et https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle], depuis
https://www.drupal.org/docs/8/core/modules/image/working-with-images["Working with images in Drupal 7 and 8"],
copyright 2000-copyright_upper_year contributeurs individuels de
https://www.drupal.org/documentation[la documentation de la communauté Drupal]
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
