[[structure-text-formats]]

=== Concept : formats de texte et éditeurs

[role="summary"]
Vue d'ensemble des formats de texte, des filtres, des éditeurs et du cross-site
scripting.

(((Format de texte,vue d'ensemble)))
(((Contenu saisi par l'utilisateur,filtrer)))
(((Sécurité,format de texte)))
(((Sécurité,cross-site scripting)))
(((Cross-site scripting (XSS),éviter)))
(((XSS (Cross-site scripting),éviter)))

// ==== Connaissances requises 

==== Que sont les formats de texte et les filtres ?

Les _formats de texte_ modifient la manière dont les balises HTML et autres
éléments textuels sont traités et affichés sur votre site. Les formats de textes
sont composés d'une série de _filtres_, chacun effectuant des transformations
sur le texte. Lorsque les utilisateurs créent du contenu, un format de texte est
associé avec le contenu, et le texte complet et original est stocké dans la base
de données. Le contenu est alors passé au travers des filtres du format de texte
avant d'être affiché sur le site.

Le module du cœur Filter fournit cette fonctionnalité, et le profil
d'installation Standard du coeur définit les formats de texte _Basic HTML_,
_Restricted HTML_, et _Full HTML_. Chaque format de texte est associé à un
droit, de sorte que vous puissiez autoriser uniquement les utilisateurs de
confiance à utiliser des formats de texte permissifs. Cela restreint les
utilisateurs non vérifiés à l'utilisation de format de texte comme _Basic
HTML_, qui filtre les balises HTML dangereuses. 

==== Que sont les éditeurs associés aux formats de texte ?

Chaque format de texte peut être associé à un éditeur, comme un éditeur WYSIWYG
(What You See Is What You Get). Le module du coeur Text Editor fournit la
possibilité d'associer les éditeurs à des formats de texte, et de configurer les
éditeurs (comme ajouter ou supprimer des boutons de leurs barres d'outils). Le
module du cœur CKEditor fournit un éditeur respectant les standards de
l'industrie nommé CKEditor, qui peut être utilisé pour modifier le contenu HTML
de votre site.

==== Qu'est ce que le cross-site scripting?

Le Cross-site scripting (XSS) est une faille de sécurité communément trouvée sur
les sites web. Dans un site qui n'est pas bien protégé, les utilisateurs
malicieux peuvent saisir des scripts dans les pages web qui sont vues par les
autres utilisateurs (par exemple, dans un commentaire ou dans le corps de la
page). Une faille de cross-site scripting peut être utilisée par les attaquants
pour s'identifier en tant qu'un autre utilisateur. Il est important de
configurer les formats de textes du site pour éviter de tels abus.

==== Sujets liés

<<security-concept>>

==== Pour aller plus loin

* https://www.drupal.org/docs/core-modules-and-themes/core-modules/filter-module/filter-module-overview[Page de documentation de la communauté sur _Drupal.org_ "Filter module overview"] (en anglais)

* https://fr.wikipedia.org/wiki/Cross-site_scripting[Page Wikipédia sur le cross-site
scripting]


*Attributions*

Ecrit et modifié par https://www.drupal.org/u/batigolix[Boris Doesborg] et
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
