[[structure-reference-fields]]

=== Concept : champs de type référence

[role="summary"]
Vue d'ensemble des champs de type référence et de leurs types fréquemment
utilisés.

(((Champ de type référence,vue d'ensemble)))
(((Champ de type référence,contenu)))
(((Champ de type référence,terme de taxonomie)))
(((Champ de type référence,utilisateur)))
(((Champ,référence)))
(((Champ,référence à un contenu)))
(((Champ,référence à un terme de taxonomie)))
(((Champ,référence à un utilisateur)))
(((Champ de type référence à un terme de taxonomie,vue d'ensemble)))
(((Champ de type référence à un utilisateur,vue d'ensemble)))
(((Champ de type référence à un contenu,vue d'ensemble)))

==== Prérequis

<<planning-data-types>>

==== Qu'est ce qu'un champ de type référence ?

Un _champ de type référence_ est un champ qui représente une relation entre une
entité et une ou plusieurs autres entités, qui peuvent être du même type ou d'un
type différent. Les trois cas les plus fréquents de champs de type référence
sont :

Référence à un contenu ::
  Une référence vers un élément de contenu. Par exemple, vous pourriez vouloir
  relier les recettes et les vendeurs qui les ont proposées. Vous définiriez un
  champ de type référence à un contenu appelé _Soumis par_ référençant les
  éléments de contenu de type Vendeur sur le type de contenu Recette.

Référence à un terme de taxonomie ::
  Une référence vers un terme de taxonomie. Par exemple, vous pourriez vouloir
  relier les recettes à leurs ingrédients. Vous définiriez un champ de type
  référence à un terme de taxonomie appelé Ingrédient sur le type de contenu
  Recette. Ce champ de type référence pointera vers le vocabulaire Ingrédients.

Référence à un utilisateur ::
  Référence vers un compte utilisateur. Par exemple, vous pourriez vouloir
  relier les recettes à leurs chefs. Vous définiriez un champ référence à un
  utilisateur appelé Chefs sur le type de contenu Recette.

==== Sujets liés

<<structure-taxonomy>>

//==== Pour aller plus loin


*Attributions*

Ecrit et modifié par https://www.drupal.org/u/surendramohan[Surendra Mohan],
et https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
