[[structure-widgets]]

=== Concept : formulaires et widgets

[role="summary"]
Vue d'ensemble des formulaires et des widgets.

(((Formulaire de modification de contenu,vue d'ensemble)))
(((Widget,vue d'ensemble)))
(((Champ,vue d'ensemble)))
(((Formulaire,vue d'ensemble)))

==== Prérequis

<<planning-data-types>>

==== Que sont les formulaires et les widgets ?

Le logiciel de gestion de contenu que votre site utilise permet aux
administrateurs de modifier le contenu et configurer des paramètres en ligne,
en utilisant de nombreux _formulaires_ web. En particulier, les _formulaires de
modification de contenu_ sont utilisés pour modifier les entités de contenu de
votre site, et ils sont configurables par les administrateurs ; les formulaires
de configuration sont fournis par les modules et ne peuvent pas eux-même être
configurés.

Les données des entités de contenu de votre site sont stockées dans un ou
plusieurs champs qui sont attachés au type d'entité et/ou au sous-type.
Lorsque vous configurez le formulaire de modification du contenu pour chaque
sous-type d'entité, vous pouvez :

* Sélectionner un _widget_ pour chaque champ. Un widget définit la méthode de
saisie des données d'un champ. Par exemple, un terme de taxonomie peut être
choisi en utilisant un champ auto-complétion, une liste de sélection ou un champ
de style mots clés qui permet aux éditeurs d'ajouter directement de nouveaux
mots clés.

* Configurer les paramètres des widgets. Par exemple, vous pouvez choisir
la taille d'un champ de saisie de texte brut.

* Masquer un ou plusieurs champs du formulaire d'édition.

* Réordonner les champs.

En principe, vous pouvez aussi avoir plusieurs formulaires d'édition
disponibles pour chaque sous-type d'entité. Cette fonctionnalité est rarement
utilisée, cependant ; la seule exception est l'usage courant pour les champs du
profil utilisateur : vous pouvez utiliser différents formulaires pour
l'enregistrement d'un utilisateur et la modification d'un compte utilisateur.
Par exemple, vous pourriez avoir un ensemble de champs limité de champs
affichés lorsque les utilisateurs s'inscrivent sur le site, et plus de champs
affichés plus tard lorsqu'ils modifient leurs profils.

==== Sujets liés

* <<structure-form-editing>>
* <<structure-view-modes>>

//==== Pour aller plus loin


*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Traduit par
https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
