[[thoughts-connecting]]
=== Comment entrer en contact avec la communauté

[role="summary"]
Comment entrer en contact avec la communauté open source et s'impliquer.

(((Communauté,entrer en contact avec)))
(((Projet Drupal,entrer en contact avec)))
(((Évènement,Drupal)))
(((Groupe d'intérêt,trouver)))
(((Groupe d'utilisateurs,trouver)))
(((Groupe,trouver)))
(((Groupe d'utilisateurs de Drupal,trouver)))
(((Slack,utiliser pour discuter en ligne)))
(((DrupalChat,utiliser pour discuter en ligne)))
(((Discuter en ligne)))
(((Contribuer au projet)))
(((Bogue,signaler)))

==== Prérequis

<<understanding-project>>

==== Comment entrer en contact avec la communauté ?

Le projet Drupal a une communauté mondiale de développeurs et d'utilisateurs.
Un des meilleurs moyens d'améliorer vos connaissances sur la plate-forme est
d'entrer en contact avec d'autres utilisateurs, et de s'impliquer dans la
communauté _open source_. Il y a plusieurs manières de se lancer :

Assister à un évènement::
  Il y a dans le monde entier des évènements autour de Drupal tant régionaux
  qu'internationaux. Consulter la
  https://events.drupal.org[page "DrupalCon" sur _Drupal.org_] pour trouver des
  évènements internationaux, et le
  https://groups.drupal.org/events["calendrier des évènements" sur _groups.drupal.org_]
  ou https://www.drupical.com/[_drupical.com_] pour trouver des évènements
  régionaux.
Devenir membre d'un groupe local::
  Il y a des groupes d'utilisateurs de Drupal dans le monde entier. Beaucoup
  organisent des rencontres régulières, auxquelles vous pouvez assister pour en
  apprendre plus sur Drupal et entrer en relation avec d'autres utilisateurs.
  Trouver des groupes d'utilisateurs locaux sur
  https://groups.drupal.org/[_groups.drupal.org_].
Participer à un groupe thématique ou linguistique::
  Il y a également des groupes d'intérêt pour toute une gamme de sujets, qui
  disposent de forums de discussion. Trouver des groupes thématiques sur
  https://groups.drupal.org/[_groups.drupal.org_]. Beaucoup de langues ont aussi
  leurs propres sites web ; vous pouvez les trouver sur la
  https://www.drupal.org/language-specific-communities[page "Language-specific communities" sur _Drupal.org_].
Discuter en ligne::
  Le projet Drupal utilise Slack et DrupalChat pour les conversations en ligne.
  Des groupes régionaux, thématiques et généraux sont disponibles. En apprendre
  plus sur les pages https://www.drupal.org/slack["Slack"] et
  https://www.drupal.org/drupalchat["DrupalChat"] sur _Drupal.org_.
Signaler un problème::
  Voir ci-dessous.
Contribuer::
  Vous pouvez contribuer en donnant à la communauté de votre temps et de votre
  expertise de diverses manières, telles que :
  * Développer des modules et des thèmes (consulter la
    https://www.drupal.org/contribute/development[Page "Contribute to
    Development" sur _Drupal.org_]),
    ou les améliorer (en utilisant le système de tickets existant pour chaque
    projet).
  * Traduire l'interface utilisateur. Consulter
    https://localize.drupal.org[_localize.drupal.org_].
  * Écrire la documentation. Consulter la page
    https://www.drupal.org/contribute/documentation["Contribute to
    Documentation" sur _Drupal.org_].
  * Répondre aux demandes d'aide. Consulter <<thoughts-support>>.

==== Comment signaler un problème ou suggérer une fonctionnalité ?

Chaque projet au sein de la communauté (tel que le cœur de Drupal pour le
logiciel de base, et les projets pour chaque module ou thème contribués)
utilisent des _tickets_ (_issues_) pour suivre les erreurs logicielles et
planifier de nouvelles fonctionnalités. Vous pouvez participer en créant un
rapport de bogue quand vous trouvez un problème, en créant une demande de
fonctionnalité (_feature request_), ou en commentant des tickets existants.
Rechercher avant de créer un ticket, afin de vous assurer que le problème ou la
fonctionnalité n'a pas déjà été signalée ou demandée. Consulter la
https://www.drupal.org/issue-queue[page sur _Drupal.org_ "Use the issue queue"]
et la https://www.drupal.org/node/314185[page sur _Drupal.org_ "Reporting a
problem"] pour plus d'informations.

Si vous trouvez un problème et que vous pensez qu'il est lié à la sécurité,
telle qu'une vulnérabilité de type _cross-site scripting_, ne pas le signaler
dans le système de tickets standard. à la place, mais le signaler à l'équipe de
sécurité. Consulter la https://www.drupal.org/node/101494[page sur _Drupal.org_
"How to report a security issue"] pour plus de détails.

==== Sujets liés

<<thoughts-support>>

==== Pour aller plus loin

* https://www.drupal.org/dcoc["Code of Conduct" sur _Drupal.org_]

* https://groups.drupal.org/events["Event Calendar" sur _groups.drupal.org_] ou
https://www.drupical.com/[_drupical.com_]

* https://www.drupal.org/community[Page "community" sur _Drupal.org_]

* https://groups.drupal.org/[_groups.drupal.org_]

* https://www.drupal.org/slack[Page "Slack" sur _Drupal.org_]

* https://www.drupal.org/drupalchat[Page "DrupalChat" sur _Drupal.org_]

* https://www.drupal.org/contribute[Page "Ways to get involved" sur _Drupal.org_]

* https://www.drupal.org/node/2486391[Page "Why get involved?" sur _Drupal.org_]

* https://www.drupal.org/contributor-tasks[Page "Contributor tasks" sur _Drupal.org_]

* https://www.drupal.org/issue-queue[Page "Use the issue queue" sur Drupal.org]

* https://www.drupal.org/node/314185[Page "Reporting a problem" sur Drupal.org]

* https://www.drupal.org/node/101494[Page "How to report a security issue" sur Drupal.org]


*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]
et https://www.drupal.org/u/eojthebrave[Joe Shindelar] de
https://drupalize.me[Drupalize.Me]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
