[[thoughts-learn-more]]
=== Approfondir vos connaissances

[role="summary"]
Comment trouver des informations supplémentaires pour obtenir des compétences
avancées en construction de sites.

(((Ressource d'apprentissage,lien vers)))
(((Formation,ressource de)))
(((Formation à Drupal,ressources de)))
(((Documentation,à propos de Drupal)))
(((Ressource,documentation et formation)))
(((Documentation,disponible sur drupal.org)))
(((Documentation,contribuée par la communauté de Drupal)))
(((Documentation,à propos de l'API de Drupal)))
(((Documentation,pour les programmeurs)))
(((Documentation,billets de blog sur le Drupal Planet)))
(((Formation,Training Marketplace)))
(((Formation,Global Training Days)))

==== Prérequis

* <<understanding-project>>
* <<thoughts-connecting>>

==== Où pouvez-vous aller pour approfondir vos connaissances ?

Les ressources suivantes pourraient s'avérer utiles pour vous, au fur et à
mesure que vos compétences progressent :

https://www.drupal.org/documentation[Documentation de la communauté de Drupal]::
  Documentation (en anglais) organisée de manière semblable à un wiki contribuée
  par la communauté de Drupal, touchant tous les aspects de Drupal (construction
  de sites et administration, thèmes, développement et modules contribués).
https://api.drupal.org[_api.drupal.org_]::
  Documentation de référence (en anglais) sur l'API (_application programming
  interface_ ou interface de programmation d'application) destinée aux
  programmeurs.
https://www.drupal.org/planet[Page "Drupal Planet" sur _Drupal.org_]::
  Une agrégation d'articles de blogs sur Drupal sur l'ensemble du web, postés
  par des membres de la communauté Drupal qui ont demandé à y être inclus. Les
  sujets vont de la programmation à la construction de sites, en passant par les
  actualités de Drupal.
Groupes, évènements et rencontres::
  Consulter <<thoughts-connecting>> pour en savoir plus sur les groupes
  thématiques, regionaux et linguistiques, comme sur les évènements locaux,
  régionaux et internationaux.
https://www.drupal.org/training[Page "Training Marketplace" sur _Drupal.org_]::
  La place de marché (_Marketplace_) référence des prestataires de formations
  payantes. Pour des formations gratuites, vérifier s'il y a des évènements
  comprenant des sessions de formation ; il y a aussi des évènements de
  formation gratuits ou à bas prix référencés sur la
  https://groups.drupal.org/global-training-days[Page "Global Training Days" sur _Drupal.org_].
Sites d'aide::
  Consulter <<thoughts-support>> pour localiser des forums d'aide ; les
  rechercher peut être utile pour apprendre sur des sujets spécifiques.

// ==== Related topics

// ==== Additional resources

*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
et https://www.drupal.org/u/eojthebrave[Joe Shindelar] de
https://drupalize.me[Drupalize.Me]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
