[[thoughts-support]]
=== Obtenir de l'aide

[role="summary"]
Comment obtenir de l'aide lorsqu'on rencontre des problèmes au cours du
développement d'un site.

(((Aide,trouver)))
(((Forum,aide utilisateur)))
(((IRC (Internet Relay Chat),utiliser pour discuter en ligne)))
(((Internet Relay Chat (IRC),utiliser pour discuter en ligne)))
(((Discuter en ligne)))

==== Pré-requis

* <<understanding-project>>
* <<thoughts-connecting>>

==== Où puis-je trouver de l'aide ?

Le projet Drupal est à code ouvert (_open-source_). En conséquence, si vous avez
des questions à propos du logiciel ou rencontrez des problèmes, les possibilités
pour trouver des réponses et des solutions sont quelque peu différentes de
celles que l'on peut rencontrer pour un logiciel commercial.

Il y a plusieurs possibilités d'aide fournie gratuitement par les volontaires de
la communauté. D'abord, quelques canaux IRC, groupes locaux, et communautés
linguistiques encouragent les demandes d'aide, à travers des conversations
en ligne, des rencontres en personne, ou des sites web (apprenez-en plus dans
<<thoughts-connecting>>).

Ensuite, quelques (mais pas tous) projets contribués de modules, distributions
et thèmes vous encouragent à poster des demandes d'aide (_support requests_)
dans les tickets. En général, les projets qui ont un très grand nombre
d'utilisateurs n'autorisent pas les demandes d'aide dans leurs tickets (le cœur
de Drupal en fait partie), tandis que les projets ayant moins d'utilisateurs
font bon accueil aux demandes d'aide occasionnelles. Il convient d'être
respectueux du temps des développeurs et de lire la documentation du projet
avant de poser une question dans un ticket. D'un autre côté, tous les projets
vous encouragent à signaler des problèmes et des bogues ; consulter
<<thoughts-connecting>> pour en savoir plus à ce sujet.

En plus de ces ressources, les sites suivants fournissent des forums gratuits où
des volontaires répondent aux demandes d'aide à propos de Drupal :

* Les  https://www.drupal.org/forum[forums sur _Drupal.org_]
* https://drupal.stackexchange.com/["Drupal Answers" sur StackExchange]

Si vous préférez un support payant (vraisemblablement pour un service plus
important ou une meilleure disponibilité), vous pouvez trouver des prestataires
de service dans la
https://www.drupal.org/drupal-services["Drupal Marketplace" sur _Drupal.org_].

==== Sujets liés

* <<thoughts-learn-more>>
* <<thoughts-connecting>>

==== Pour aller plus loin

* https://www.drupal.org/support[Page "Support" sur _Drupal.org_]
* https://www.drupal.org/drupal-services["Drupal Marketplace" sur _Drupal.org_]
* Les https://www.drupal.org/forum[forums sur _Drupal.org_]
* https://drupal.stackexchange.com/["Drupal Answers" sur StackExchange]


*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
