[[understanding-gpl]]

=== Concept: licence de Drupal

[role="summary"]
Vue d'ensemble de la licence de Drupal et directives à suivre par les
utilisateurs et contributeurs.

(((Licence,vue d'ensemble)))
(((Licence de Drupal,vue d'ensemble)))
(((GPL (General Public License or GNU General Public License),vue d'ensemble)))
(((GNU General Public License,vue d'ensemble)))
(((Aspect juridique,vue d'ensemble)))

==== Prérequis

<<understanding-drupal>>

==== Qu'est ce que la licence de Drupal ?

Drupal et tous les fichiers contribués herbergés sur _Drupal.org_ sont sous la
licence GNU General Public License (GPL), version 2 ou supérieure. Cela signifie
que vous êtes libre de télécharger, réutiliser, modifier et distribuer tous les
fichiers qui sont dans un projet sur _Drupal.org_ sous les termes de la GPL
version 2 ou 3. Vous pouvez aussi utiliser le cœur du logiciel en combinaison
avec n'importe quel code dont la licence est compatible avec la version 2 ou 3.

Les contributeurs à Drupal devraient suivre ces directives :

* Tous les fichiers (PHP, JavaScript, images, Flash, etc) qui font partie d'un projet
de _Drupal.org_ doivent être sous licence GPL version 2 ou ultérieure. 

* Tous les contributeurs à Drupal conservent le copyright sur leur code, mais
autorisent sa publication sous la même licence que Drupal.

* Les modules Drupal et les thèmes sont un travail dérivé de Drupal. Si vous 
les distribuez, vous devez le faire selon les termes de la GPL version 2 ou
ultérieure.

* Tout le contenu sur _Drupal.org_ est la propriété de ses auteurs originaux,
et est sous licence Creative Commons Atrribution-ShareAlike version 2.0.

* Les exemples de code sur _Drupal.org_ est aussi disponible sous licence GPL
version 2 ou ultérieure.

==== Sujets liés

<<thoughts-connecting>>

==== Pour aller plus loin (en anglais)

* https://www.drupal.org/about/licensing[_Drupal.org_ page on "Licensing"]

* https://api.drupal.org/api/drupal/core!LICENSE.txt/8.2.x["Drupal 8 LICENSE.txt" page on _api.drupal.org_]

* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU General Public License, version 2]

* http://www.gnu.org/licenses/gpl-3.0.en.html[GNU General Public License, version 3]

* https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons Attribution-ShareAlike license 2.0.]

* https://groups.drupal.org/legal["Legal Group" on _groups.drupal.org_]


*Attributions*

Adapté par https://www.drupal.org/u/dianalakatos[Diána Lakatos] chez
https://pronovix.com/[Pronovix] depuis
https://www.drupal.org/about/licensing["Licensing"]
copyright 2000-copyright_upper_year par les contributeurs individuels à
https://www.drupal.org/documentation[la documentation de la communauté Drupal].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
