[[understanding-themes]]

=== Concept : thèmes

[role="summary"]
Vue d'ensemble des thèmes et obtention

(((Thème,vue d'ensemble)))
(((Thème,cœur (core))))
(((Thème du cœur (core),vue d'ensemble)))
(((Thème,tiers)))
(((Thème tiers,vue d'ensemble)))
(((Thème,personnalisé)))
(((Thème personnalisé,vue d'ensemble)))

==== Pré-requis

<<understanding-drupal>>

==== Qu'est ce qu'un thème ?

Un thème est un ensemble de fichiers qui définissent la présentation de votre
site. Le cœur et les modules de votre site déterminent quels _contenus_ (y
compris le texte HTML et les autres données stockées dans la base de données,
les images téléchargées et toutes les autres ressources) apparaissent sur les
pages de votre site. Le thème détermine les balises HTML et les styles CSS qui
encapsulent le contenu.

Le cœur fournit plusieurs thèmes basiques avec sa distribution. Ces thèmes ont
globalement été essentiellement conçus et construits par la communauté ces
dernières années et seront tous de bons choix pour construire vos premiers sites
et vous familiariser avec le fonctionnement du cœur.

Drupal est un SGC de référence, de sorte que le marché des thèmes tiers —
gratuits comme payants — est solide.

Si aucun des thèmes communautaires ne convient à vos besoin, il vous faudra
créer un thème personnalisé. Un thème personnalisé peut être aussi simple qu'un
seul fichier CSS qui ajoute des styles aux balises fournies par le cœur. Des
conseils pour la creation des thèmes personnalisés est disponible ici :
https://www.drupal.org/docs/theming-drupal[page de documentation de la communauté sur _Drupal.org_ "Theming Drupal"].

==== Sujets liés

* <<extend-theme-find>>
* <<extend-theme-install>>
* <<understanding-modules>>

==== Pour aller plus loin

https://www.drupal.org/docs/theming-drupal[Page de documentation de la communauté sur _Drupal.org_ "Theming Drupal"]


*Attributions*

Écrit et modifié par https://www.drupal.org/u/jgrubb[John Grubb] et
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky],
https://www.drupal.org/u/duaelfr[Edouard Cunibil] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
