[[understanding-distributions]]

=== Concept : distributions

[role="summary"]
Vue d'ensemble des distributions, qui peuvent être utilisées pour mettre en
place de sites à objectifs spécifiques.

(((Distribution,vue d'ensemble)))
(((Distribution,complète)))
(((Distribution,démarrage rapide)))
(((Distribution complète,vue d'ensemble)))
(((Distribution à démarrage rapide,vue d'ensemble)))

==== Pré-requis

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>

==== Que sont les distributions ?

Les _distributions_ fournissent des fonctionnalités pour un type spécifique de
site en un téléchargement unique contenant le cœur, les modules contribués, les
thèmes et une configuration pré-définie. Une distribution rend possible la mise
en place d'un site complexe, avec des besoins spécifiques, en moins d'étapes
qu'en installant et configurant individuellement les éléments.

Il existe deux principaux types de distributions :

Les distributions complètes::
  Une distribution complète est un projet qui fournit une solution complète pour
  mettre en place un site ayant un objectif spécifique, comme un site
  universitaire, pour le commerce, un gouvernement, une association à but non
  lucratif, de la publication, ayant un objectif social, etc. Par exemple, vous
  pourriez utiliser une distribution existante pour les marchés fermiers pour
  construire votre propre site, ou vous pourriez partager la configuration de
  votre site pour les marchés fermiers comme une distribution pour que les
  autres l'utilisent.

Les autres distributions::
  Les distributions peuvent aussi avoir un rôle de kit de démarrage rapide pour les
  développeurs et les webmasters qui l'utilisent comme point de départ.

==== Sujets liés

<<thoughts-connecting>>

==== Pour aller plus loin

https://www.drupal.org/project/project_distribution[_Drupal.org_ Drupal Distribution Downloads]

*Attributions*

Adapté et edité par https://www.drupal.org/u/dianalakatos[Diána Lakatos]
et https://www.drupal.org/u/ifrik[Antje Lorch],
depuis https://www.drupal.org/docs/7/distributions["Distributions"]
et https://www.drupal.org/project/project_distribution["Download & Extend -- Distributions"]
copyright 2000-copyright_upper_year par les contibuteurs individuels de
 https://www.drupal.org/documentation[Drupal Community Documentation].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky],
https://www.drupal.org/u/duaelfr[Edouard Cunibil] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
