[[understanding-modules]]
=== Concept : modules

[role="summary"]
Vue d'ensemble des modules et des fonctionnalités pour lesquelles ils peuvent
être utilisés.

(((Module,vue d'ensemble)))
(((Module contribué,vue d'ensemble)))
(((Module du cœur (core),vue d'ensemble)))
(((Module Field,vue d'ensemble)))
(((Module Field UI,vue d'ensemble)))
(((Module Menu UI,vue d'ensemble)))
(((Module Node,vue d'ensemble)))
(((Module User,vue d'ensemble)))
(((Module Views,vue d'ensemble)))
(((Module Views UI,vue d'ensemble)))
(((Module,cœur (core))))
(((Module,contribué)))
(((Module,Field)))
(((Module,Field UI)))
(((Module,Menu UI)))
(((Module,Node)))
(((Module,User)))
(((Module,Views)))
(((Module,Views UI)))

==== Connaissance requises

<<understanding-drupal>>

==== Qu'est ce qu'un module ?

Un module est un ensemble de fichiers PHP, Javascript et/ou CSS qui étendent les
fonctionnalités du site et ajoutent des fonctionnalités. Vous pouvez activer les
fonctionnalités en _installant_ le module, et vous pouvez les désactiver en
_désinstallant_ le module ; cependant, avant de le désinstaller, vous pourriez
avoir besoin de supprimer les données et la configuration en lien avec le
module. Chaque module qui est installé ajoute du temps nécessaire pour générer
les pages de votre site, donc une bonne idée est de désinstaller les modules qui
ne sont pas nécessaires.

Le téléchargement du cœur fournit des modules avec des fonctionnalités comme :

* Gestion des comptes utilisateur (le module du cœur User)

* Gestion basique du contenu (le module du cœur Node) et les champs (les modules
du cœur Field et Field UI ; il y a aussi des modules du cœur qui fournissent des
types de champs)

* Gestion des menus de navigation (le module du cœur Menu UI)

* Faire des listes, des grilles et des blocs pour les contenus existants (les
modules du cœur Views et Views UI)

Vous pouvez télécharger des _modules contribués_ supplémentaires depuis
https://www.drupal.org/project/project_module[_Drupal.org_ Module Downloads], ou créer vos propres _modules personnalisés_.

==== Sujets liés

* <<understanding-themes>>
* <<understanding-distributions>>
* <<config-uninstall>>
* <<extend-module-find>>
* <<extend-module-install>>
* <<security-concept>>
* <<security-update-module>>

==== Pour aller plus loin

https://www.drupal.org/developing/modules[_Drupal.org_ page de la documentation communautaire "Module developer's guide"]

*Attributions*

Écrit par https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Traduit par https://www.drupal.org/u/vanessakovalsky[Vanessa Kovalsky],
https://www.drupal.org/u/duaelfr[Edouard Cunibil] et
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
