[[views-concept]]
=== Concept: usages des vues

[role="summary"]
Vue d'ensemble des vues et des données qu'elles peuvent afficher ou générer.

(((Vue,vue d'ensemble)))
(((Module Views,vue d'ensemble)))

==== Prérequis

* <<planning-modular>>
* <<planning-data-types>>

==== Qu'est-ce qu'une vue ?

Une vue est une liste de contenus sur votre site web. Le module du cœur Views
gère l'affichage des vues, et le module du cœur View UI permet de les créer et
de les modifier dans une interface d'administration. Quand vous définissez des
vues, votre but est de récupérer les données de votre site web pour les afficher
aux utilisateurs.

==== Quels types de données peuvent être affichés avec des vues ?

Vous pouvez créer des vues pour afficher pratiquement n'importe quelle entité de
contenu stockée dans le système. Par exemple, vous pouvez créer les listes
suivantes pour le site du marché fermier :

* listes de marchands,
* listes de recettes,
* listes de contenus les plus récents sur votre site,
* listes d'utilisateurs de votre site.

==== De quelles manières les données peuvent-elles être générées en utilisant les vues ?

Une liste créée par une vue peut prendre n'importe laquelle des formes
suivantes :

* tableau avec champs triables,
* mises en page sous forme de grilles,
* accroches ou images liées à des articles,
* blocs,
* données en JSON,
* flux RSS,
* calendriers,
* diaporamas.

==== Sujets liés

* <<views-parts>>
* <<views-create>>

// ==== Additional resources


*Attributions*

Écrit et modifié par
https://www.drupal.org/u/michaellenahan[Michael Lenahan]
d'https://erdfisch.de[erdfisch], et
https://www.drupal.org/u/jojyja[Jojy Alphonso] de
http://redcrackle.com[Red Crackle]. Traduit par
https://www.drupal.org/u/fmb[Felip Manyer i Ballester].
