[[attributions]]
=== Handbuchweite Namensnennung
[role="summary"]
Liste der Mitwirkenden, die am Projektmanagement und am Benutzerhandbuch beteiligt sind.

(((Content attributions for this document)))
(((Attributions for this document)))
(((Copyright for this document)))

Dieses Handbuch wurde von Mitwirkenden des Open-Source-Projekts Drupal erstellt
und ist unter der Lizenz
https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0] lizenziert.
Siehe <<copyright>> für weitere Informationen. Details zu den Mitwirkenden die einzelne
Aufgaben übernommen haben, die in Zusammenhang mit dem gesamte Handbuch durchgeführt
 wurden, sind unten aufgeführt. Die Autoren und Übersetzer der einzelnen Themen im
Handbuch sind direkt im jeweiligen Abschnitt zu finden.


==== Projektkoordination des Originaltextes (Englisch, Drupal 8)

Die ersten Version dieses Handbuch wurde von den im Folgenden aufgeführten
Personen erstellt.

Mitgewirkt haben:

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] - Koordination der Freiwilligen
sowie des Projektmanagements

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] - Inhaltliche Verantwortung

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] - Inhaltliche Verantwortung

* https://www.drupal.org/u/ifrik[Antje Lorch] - Inhaltliche Verantwortung


==== Verfassen, Bearbeiten und Testen der Originaltexte

Folgende Personen haben zum Erstellen des Handbuchs beigetragen:

* Das Glossar wurde geschrieben und angepasst von
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
Es wurden Teilweise Inhalte aus dem https://www.drupal.org/docs/7/understanding-drupal/glossary["Glossar"], dem
https://www.drupal.org/node/2120523["Überblick über die Konfiguration (vs. andere
Arten von Informationen)"], und von der Seite
https://www.drupal.org/docs/8/theming-drupal-8/working-with-breakpoints-in-drupal-8["Arbeiten mit
Breakpoints in Drupal 8" (egnlissch)] übernommmen.
Alle Rechte liegen seit 2000 - copyright_upper_year bei den einzelnen
Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].

* Der Index wurde verbessert und kuratiert von
https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst].

* Die Themenzusammenfassungen wurden geschrieben von
https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle].

Die redaktionelle Bearbeitung des Handbuchs wurde von den folgenden Personen
durchgeführt:

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] bei
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst]

* https://www.drupal.org/u/ifrik[Antje Lorch]

* https://www.drupal.org/u/balu-ertl[Balu Ertl]

* https://www.drupal.org/u/batigolix[Boris Doesborg]

* https://www.drupal.org/u/cleverington[Charles Leverington]

* https://www.drupal.org/u/chishah92[chirag shah]

* https://www.drupal.org/u/gdunham[Grant Dunham]

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] bei
https://drupalize.me[Drupalize.Me].

* https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle] -- der den größten Teil des Benutzerhandbuchs korrekturgelesen hat.

* https://www.drupal.org/u/kamalkantpansari[Kamal Kant Pansari] bei
http://www.intelliswift.com/[Intelliswift].

* https://www.drupal.org/u/michaellenahan[Michael Lenahan] bei
 https://erdfisch.de[erdfisch].

* https://www.drupal.org/u/swarad07[Swarad Mokal] bei
http://www.blisstering.com[Blisstering Solutions].


Der Inhalt wurde getestet von:

* https://www.drupal.org/u/zachcarter[Zach Carter].

* Ein Workshop organisiert von der https://groups.drupal.org/spokane-wa["Spokane
Drupal User Group" auf groups.drupal.org], mit Studentendes
Zertifizierungsprogramms für Webentwickler am
http://scc.spokane.edu[Spokane Community College].

==== Bilder

Die meisten Bilder im Handbuch sind Screenshots aus der Software Drupal,
erzeugt mit Software, die von
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] erstellt wurde.

Das Wort Drupal, das Druplicon-Logo (das im gesamten Handbuch als Teil
mehrerer Bilder erscheint)
und das Wortmarkenlogo Drupal (das Teil des Covers ist)
sind
https://www.drupal.org/about/media-kit/logos[eingetragene Warenzeichen von Dries Buytaert].

Das Titelbild ist eine unter der CC BY-SA 2.0 lizenzierte Illustration von
https://www.drupal.org/u/mndonx[Amanda Luker] auf
https://www.advomatic.com/[Advomatic].

Das Logo des Anytown Farmers Market, das als Teil mehrerer Bilder im
gesamten Handbuch erscheint ist eine CC BY-SA 2.0 lizenzierte Abbildung
von Justin Harrell bei https://drupalize.me/[Drupalize.Me].

Das Honigbienenbild, das als Teil mehrerer Bilder im Handbuch erscheint,
ist ein Bild dass unter Public Domain von
https://en.wikipedia.org/wiki/User:Severnjc[John Severns] bei der
https://en.wikipedia.org/wiki/Main_Page[English Wikipedia project] über
https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg[Wikimedia Commons] veröffentlicht wurde.

Das Bauernhofbild, das als Teil mehrerer Bilder im gesamten Handbuch erscheint,
ist ein gemeinfreies Bild von Xianmin Chang auf
https://commons.wikimedia.org/wiki/File:Bere%26ModernBarley.jpg[Wikimedia Commons].

Das Salatbild, das als Teil mehrerer Bilder im Handbuch erscheint,
ist ein Bild, unter Public Domain von
https://www.goodfreephotos.com/[Yinan Chen] über
https://commons.wikimedia.org/wiki/File:Gfp-salad.jpg[Wikimedia Commons]
veröffentlicht wurde.

Das Karottenbild, das als Teil mehrerer Bilder im gesamten Handbuch erscheint,
ist ein Bild, dass unter Public Domain, das unter
https://www.ars.usda.gov/oc/images/photos/nov04/k11611-1/[K11611-1] von
Stephen Ausmus beim
https://en.wikipedia.org/wiki/Agricultural_Research_Service[Agricultural Research Service of the United States Department of Agriculture] über
https://commons.wikimedia.org/wiki/File:Carrots_of_many_colors.jpg[Wikimedia Commons] veröffentlicht wurde.
