[[block-concept]]

=== Konzept: Blöcke

[role="summary"]
Überblick über Blöcke.

(((Block,overview)))

//==== Erforderliche Vorkenntnisse

==== Was ist ein Block?

_Blöcke_ sind einzelne Teile des Layouts Ihrer Website. Sie werden
innerhalb der Abschnitte (siehe <<block-regions>>) Ihres Themes platziert und
können erstellt, entfernt und auf der Seite
_Blocklayout_  (_admin/structure/blocks_) neu angeordnet werden. Beispiele für
Blöcke sind der Block _„Wer ist online?“_, das Hauptnavigationsmenü und die
Pfadnavigation. Der Inhaltsbereich der Hauptseite ist ebenfalls ein Block.

Einige Module stellen neue Blöcke zur Verfügung, die Sie auf Ihrer Website
platzieren können. Das Modul Search, das mit dem Kernsystem ausgeliefert wird,
stellt zum Beispiel einen Block bereit, der ein Suchformular enthält,
wenn das Search-Modul installiert und konfiguriert ist.
Sie können auch Ihr eigenes benutzerdefiniertes Suchformular erstellen
und platzieren.

Jeder Block hat seine eigenen Konfigurationseinstellungen, die es
ermöglichen, folgendes festzulegen:

* Auf welche Seiten Ihrer Website der Block angezeigt werden soll.

* Es ist sogar möglich, mehrere Kopien eines Blocks zu platzieren. Jede Kopie
eines Blocks kann dabei mit einer separaten Konfiguration und gesonderten
Sichtbarkeitsregeln versehen werden.

==== Verwandte Themen

* <<block-regions>>
* <<block-create-custom>>
* <<block-place>>

//==== Weiterführende Quellen


*Mitwirkende*

Adaptiert von https://www.drupal.org/u/les-lim[Les Lim] aus
https://www.drupal.org/docs/8/core/modules/block/overview["Arbeiten mit Blöcken
(Inhalt in Regionen)"]]
copyright 2000 - copyright_upper_year von den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Gemeinschaft].
