[[content-paths]]

=== Konzept: Pfade, Aliase, und URLs

[role="summary"]
Überblick über Pfade, Aliase, und URLs (mit Beispielen).

(((Path,overview)))
(((Alias,overview)))
(((URL (Uniform Resource Locator),overview)))
(((Uniform Resource Locator (URL),overview)))
(((URL alias,overview)))

//==== Erforderliche Vorkenntnisse


==== Was ist eine URL?

URL ist die Abkürzung für „Uniform Ressource Locator", d.h. für
„die einzigartige Adresse" der Seite Ihrer Website im Internet.
Es ist der „Name", über den ein Browser eine Seite identifiziert, um diese
anzeigen zu können. Im Beispiel „Besuchen Sie uns unter _example.com_."
ist _example.com_ die URL für die Startseite Ihrer Website.
Benutzer verwenden URLs, um Inhalte im Web zu finden.

==== Was ist ein Pfad?

Ein Pfad ist der eindeutige, hintere  Teil der URL für eine bestimmte
Funktion oder einen bestimmten Inhalt. Für eine Seite, deren vollständige URL
_http://example.com/node/7_ lautet, lautet der Pfad beispielsweise _node/7_.

Hier sind einige Beispiele für Pfade, die Sie auf Ihrer Website finden könnten:

* _node/7_
* _taxonomy/term/6_
* _admin/content/comment_
* _user/login_
* _user/3_

==== Was ist ein Alias?

Das Kernsystem verfügt über eine Funktion namens „URL-Alias",
die es Ihnen ermöglicht, eine verständlichere Bezeichnung für einen Inhalt
festzulegen. Wenn Sie beispielsweise eine Seite mit dem Titel _„Über uns"_
angelegt  haben, die den Pfad _node/7_ besitzt, können Sie einen Alias
einrichten, so dass Ihre Besucher die Seite über
_http://www.example.com/Über-Uns_ aufrufen können. Das Modul Path,
das mit dem Kernsystem ausgeliefert wird, stellt diese Funktionalität
zur Verfügung.

==== Verwandte Themen

* <<content-create>>
* <<content-edit>>

// The following topic has been deferred, so remove the link for now.
// @todo Put this link back in when/if the topic gets added back.
// * <<structure-pathauto>>


//===== Zusätzliche Ressourcen


*Mitwirkende*

Adaptiert von https://www.drupal.org/u/dianalakatos[Diána Lakatos] bei
https://pronovix.com/[Pronovix] von
https://www.drupal.org/node/120631[„URL-Aliase (englisch)"], und
https://www.drupal.org/node/31644[„Drupal-Pfade verstehen (englisch)"]
copyright 2000 - copyright_upper_year liegt bei den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community]
Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
