[[copyright]]
=== Rechtliche Angaben

[role="summary"]
Rechtliche Informationen zu diesem Handbuch

(((Rechtliche Angaben zum Benutzterhandbuch)))

Dieses Handbuch wurde von Mitwirkenden am Open-Source-Projekt Drupal erstellt.
Alle Rechte sind von 2015 - copyright_upper_year den einzelnen Mitwirkenden,
vorbehalten und werden unter der
https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons License,
Attribution-ShareAlike 2.0] (CC BY-SA 2.0) zur Verfügung gestellt.
Jede Seite in diesem Dokument (einschließlich dieser) nennt am Ende
die Personen, die an der jeweilige Seite mitgewirkt haben.
Siehe auch: <<attributions>> um Informationen zur,
Übersetzung und zum Projektmanagement für das gesamte Handbuch zu erhalten.

Die CC BY-SA-Lizenz (die der GPL sehr ähnlich ist) erlaubt es jedem, die Inhalte
in diesem Handbuchs zu kopieren, zu modifizieren, und eine geänderte Version
dieser Arbeit komplett oder in Teilen weiterzugeben, solange dabei
folgendes eingehalten wird:

* Es findet eine entsprechende Namensnennung statt (weitere Informationen finden Sie in der Lizenz).
* Das Werk enthält einen Link zur Lizenz (weitere Informationen finden Sie in der Lizenz).
* Es wird angegeben, ob und wo Änderungen vorgenommen wurden.
* Das Werk wird unter der gleichen Lizenz veröffentlicht, unter der auch dieses Dokument veröffentlicht wird.

*Mitwirkende*

Diese Seite wurde von
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
und https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle] von der Seite
https://www.drupal.org/terms[„Urheberrecht und Lizenzierung der Dokumentation" (englisch)] adaptiert und angepasst.

Die Übersetzung des Benutzerhandbuchs ins Deutsche wurde von
https://www.drupal.org/u/joachim-namyslo[Joachim Namyslo] übernommen.


Alle Rechte von 2000 - copyright_upper_year sind den einzelnen Mitwirkenden des
https://www.drupal.org/documentation[Dokumentations-Teams der Drupal-Community] vorbehalten.


// The following is the copyright statement to appear at the bottom of
// each page in the HTML display of this guide.

[role="copyright"]
Rechtlicher Hinweis: Alle Rechte von 2015 - copyright_upper_year sind den einzelnen Mitwirkenden vorbehalten.
Weitere Informationen finden Sie unter <<copyright>>
Dieses Handbuch unterliegt den Bedingungen der
https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0].
