[[copyright]]
=== Rechtliche Angaben

[role="summary"]
Rechtliche Informationen zu diesem Handbuch

(((Copyright for this document)))

Dieses Handbuch wurde von Mitwirkenden am Open-Source-Projekt Drupal erstellt.
Alle Rechte sind von 2015 - copyright_upper_year den einzelnen Mitwirkenden,
vorbehalten und werden unter der
https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons License,
Attribution-ShareAlike 2.0] (CC BY-SA 2.0) zur Verfügung gestellt.
Jede Seite in diesem Dokument (einschließlich dieser) hat am unteren Rand eine
Erklärung zu den Mitwirkenden Personen, die die jeweilige Seite geschrieben und
bearbeitet haben. Siehe auch: <<attributions>> um Informationen zur,
Übersetzung und zum Projektmanagement für das gesamte Handbuch zu erhalten.

Die CC BY-SA-Lizenz (sehr ähnlich der GPL) erlaubt es jedem, die Inhalte
dieses Handbuchs zu kopieren, zu modifizieren, und eine geänderte Version dieser
Arbeit komplett oder in Teilen weiterzugeben, solange folgendes eingehalten wird:

* Sie bringen eine entsprechende Namensnennung an (weitere Informationen finden Sie in der Lizenz).
* Sie fügen einen Link zur Lizenz ein (weitere Informationen finden Sie in der Lizenz).
* Sie geben an, ob und wo Änderungen vorgenommen wurden.
* Sie verbreiten Ihr Werk unter der gleichen Lizenz die von diesem Dokument verwendet wird.

*Mitwirkende*

Diese Seite wurde von
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
und https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle] von der Seite 
https://www.drupal.org/terms["Urheberrecht und Lizenzierung der Dokumentation (englisch)"] adaptiert und angepasst.
Alle Rechte von 2000 - copyright_upper_year ist den einzelnen Mitwirkenden des
https://www.drupal.org/documentation[Dokumentations-Teams der Drupal-Community] vorbehalten.


// The following is the copyright statement to appear at the bottom of
// each page in the HTML display of this guide.

[role="copyright"]
Rechtlicher Hinweis: Alle Rechte von 2015 - copyright_upper_year sind den einzelnen Mitwirkenden vorbehalten. 
Weitere Informationen finden Sie unter <<copyright>> 
Dieses Handbuch unterlieg denBedingungen der 
https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0].
