[[extend-config-versions]]

=== Synchronisieren von Konfigurationsversionen

[role="summary"]
Die Konfiguration einer Entwicklungs- und einer Produktivsite
mit dem Kernsystemmodul Configuration Manager austauschen.

(((Configuration,synchronizing between development and live site)))
(((Development site,synchronizing with live site)))
(((Live site,synchronizing with development site)))
(((Configuration Manager module,using to synchronize the configuration between a development and live site)))
(((Module,Configuration Manager)))

==== Zielsetzung

Synchronisieren Sie die Konfiguration zwischen einer Entwicklungs- und einer
Produktiv-Website.

==== Erforderliche Vorkenntnisse

* <<understanding-data>>
* <<install-prepare>>
* <<install-dev-sites>>
* <<install-dev-making>>

==== Anforderungen an die Website

* Sie müssen eine Entwicklungskopie Ihrer Live-Website besitzen. Siehe
<<install-dev-making>>.

* Das Modul Configuration Manager, das mit dem Kernsystem ausgeliefert wird,
muss sowohl in der Entwicklungs- und der Live-Umgebung installiert sein.
Lesen Sie <<config-install>> um Anweisungen dazu zu erhalten, wie Sie Module,
die mit dem Kernsystem ausgeliefert werden, installieren.

* Sie müssen die Konfiguration entweder auf der Live-Website oder auf der
Entwicklungs-Website geändert haben. Von der Entwicklungs-Website
(der _Quell-Website_) aus sollen Änderungen mit der anderen Website
(der _Ziel-Website_) synchronisiert werden.  Sie können zum Beispiel
einen neuen Inhaltstyp entwickeln oder Felder und Ansichten auf Ihrer
Entwicklungs-Website hinzufügen. Wenn in der lokalen Entwicklungsumgebung alles
korrekt funktioniert, können Sie die Änderungen auf die Live-Website anwenden.

* Alle Konfigurationen, die nicht zwischen der Quell-Website und
 der Ziel-Website synchronisiert werden sollen,  müssen in
 Konfigurationsüberschreibungen in der Datei _settings.php_ und nicht in der
 Datenbank erfasst werden. Siehe: <<install-dev-making>>.

==== Arbeitsschritte

. Navigieren Sie auf der Quell-Website im Menü _Verwalten_ zum Menüpunkt
_Konfiguration_ > _Entwicklung_ > _Konfigurationssynchronisation_ > _Export_
(_admin/config/development/configuration/full/export_).

. Klicken Sie auf _Exportieren_. Ihre Website wird ein Archiv mit der vollständigen
Konfiguration der Website erstellen. Speichern Sie die Datei auf Ihrem
lokalen Computer.

. Navigieren Sie auf der Ziel-Website im Menü _Verwalten_ zum Menüpunkt
_Konfiguration_ > _Entwicklung_ > _Konfigurationssynchronisation_ > _Importieren_
(_admin/config/development/configuration/full/import_).

. Suchen Sie nach dem heruntergeladenen Konfigurationsarchiv und klicken Sie auf
_Datei hochladen_. Ihr Konfigurationsarchiv wird auf die Ziel-Website hochgeladen
und Sie werden auf die Konfigurationsseite _„Synchronisieren“_
(_admin/config/development/configuration_) weitergeleitet.
Außerdem wird eine Meldung ausgegeben, die besagt,
dass das Archiv hochgeladen wurde.

. Überprüfen Sie, ob die auf der Seite angezeigten Unterschiede Ihren
Erwartungen entsprechen. Sie sehen möglicherweise Konfigurationselemente,
die hinzugefügt, gelöscht oder geändert wurden. Bei geänderten Elementen können
Sie auf _„Unterschiede anzeigen“_ klicken, um die Änderungen einzusehen.

. Wenn Sie zufrieden sind, klicken Sie auf _„Alle importieren“_,
um die Konfigurationsänderungen zu importieren.

==== Vertiefen Sie Ihr Wissen

* Wenn die Änderungen, die Sie vorgenommen haben, nur ein Konfigurationsobjekt
betreffen (z. B. eine Ansicht), können Sie die Export-/Import-Funktion für eine
einzelne Konfiguration verwenden, um die Konfigurationsänderung zwischen
beiden Websites durchzuführen. Siehe: <<extend-deploy>>.

* Nach dem Schritt, in dem Sie die vollständige Konfiguration von der
Quell-Website exportieren, können Siue das Archiv auch entpacken und an ein
System zur Versionskontrolle, wie z.B. Git übergeben, um Änderungen an der
Konfiguration einer Website zu protokollieren. Siehe: <<extend-git>>.

// ==== Verwandte Begriffe

==== Videos

// Video von Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/dLUGQk8GKa0[title="Konfigurationsversionen synchronisieren (englsch)"]]

// ==== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
