[[glossary]]
== Glossar

(((Glossary)))
(((Terminology (Glossary))))

(((Ajax,definition)))
[glossary]
[[glossary-ajax]] Ajax::
Eine Web-Technologie, die zum Datenaustausch mit einem Server verwendet wird, um dynamisch
Teile einer Webseite (zum Beispiel Formulare) zu aktualisieren, ohne die gesamte neu laden zu müssen.
(((Alias,definition)))
[[glossary-alias]] Alias::
   Ein benutzerfreundlicher Name, der den internen <<glossary-path,path>> ersetzt, den
   das System einer URL auf der Website zuweist. Sie könnten zum Beispiel einen
   Alias _/about_ für die Seite About auf Ihrer Website vergeben, um den internen
   Pfad _/node/5_. Dadurch würde die Seite die URL _http://example.com/about_
   anstelle von _http://example.com/node/5_. Siehe <<content-paths>> für weitere
   Informationen.
(((Anonymous,definition)))
[[glossary-anonymous]] Gast::
   Eine Person (<<glossary-user,user>>), die mit der Website interagiert und nicht angemeldet ist.
    Siehe <<user-concept>> für weitere Informationen.
(((Block,definition)))
[[glossary-block]] Block::
   Ein Stück <<glossary-content,content>> (Text, Bild, Link, usw.) dasa auf einer Seite innerhalb eine Website angezeigt werden kann. Blöcke werden in
   <<glossary-region,regions>> angezeigt. Siehe:<<block-concept>> für weiterte Information.
(((Breakpoint,definition)))
[[glossary-breakpoint]] Breakpoint::
   Breakpoints werden verwendet, um die Höhe oder Breite von Browsern, Bildschirmen,
   Druckern und weiteren Medienausgabetypen in Bereiche zu unterteilen. Eine
   <<glossary-responsive,responsive>> Seite passt ihre Präsentation anhand dieser 
   Breakpoints an. Siehe: <<structure-image-responsive>> für weitere Informationen.
(((Bundle,definition)))
[[glossary-bundle]] Subtyp::
   Synonym für <<glossary-entity-subtype,Entity subtype>>.
(((Cache,definition)))
[[glossary-cache]] Cache::
   Der interne Cache der Website, der auch Zwischenspeicher genannt wird, speichert die Ausgabe zeitaufwändiger Berechnungen, wie z.B. die Berechnung der Ausgabe für eine HTML-Seitenanfrage, und gibt das Ergebnis dieser Berechnung direkt aus, anstatt die Berechnung beim bei jedem Seitenaufruf neu durchführen.
   Externe Caching-Systeme können auch auf dem Webserver verwendet werden, um die
   Antwortzeit einer Website zu verkürzen. Siehe: <<prevent-cache>> für weitere Informationen über den internen Cache.
(((CMS (Content Management System),definition)))
(((Content Management System (CMS),definition)))
[[glossary-cms]] CMS::
   Akronym für
   <<glossary-content-management-system,Content Management System>>.
(((Configuration,definition)))
[[glossary-configuration]] Konfiguration::
   Informationen über Ihre Website, die nicht <<glossary-content,content>> sind,
   und die dauerhafter sein sollen als <<glossary-state,state>> Informationen,
   wie zum Beispiel der Name Ihrer Website, der <<glossary-content-type,content types>>
   und <<glossary-view,views>>, die Sie definiert haben, usw. Siehe <<understanding-data>>
   für weitere Informationen.
(((Content,definition)))
[[glossary-content]] Inhalt::
   Informationen, die auf Ihrer Website angezeigt werden sollen, z. B. Texte, Bilder,
   Downloads, usw. Siehe auch: <<glossary-configuration,Configuration>> und
   <<glossary-state,State>>. Siehe: <<understanding-data>> für weitere Informationen.
(((Content item,definition)))
[[glossary-content-item]] Inhalt::
   Ein Element von <<glossary-content,content>>, das normalerweise als
   als Hauptinhalt einer Seite auf Ihrer Website angezeigt wird. Dies ist ein
   <<glossary-entity-type,entity type>>.
   Siehe <<planning-data-types>> für weitere Infromationen.
(((Content Management System (CMS),definition)))
[[glossary-content-management-system]] Content Management System (CMS)::
   Eine Sammlung von Tools, die die Erstellung, Änderung,
   Organisation, die Suche, den Abruf und  die Entfernung von Informationen auf einer Website vereinfacht.
   Siehe: <<understanding-drupal>> für weitere Informationen.
(((Content type,definition)))
[[glossary-content-type]] Inhaltstyp::
   Ein/eine <<glossary-entity-subtype,entity subtype>> eines
   <<glossary-content-item,content item>> <<glossary-entity-type,entity type>>.
   Jeder Inhaltstyp wird für einen bestimmten Zweck auf der Website verwendet und
   hat seine eigenen Felder. Zum Beispiel könnte eine Website für einen Wochenmarkt über einen
   Inhaltstyp für einfache Seiten und einen anderen für eine Seite mit Lieferantenlisten.
   Siehe <<planning-data-types>> für weitere Informationen.
(((Contextual link,definition)))
[[glossary-contextual-link]] Kontextlink::
   Ein Link zu einer administrativen Seite zum Bearbeiten oder Konfigurieren einer Funktion der
   Website, die in dem Kontext angezeigt wird, in dem diese Funktion mit dem jewiligen Element auf einer Website 
   in  Zusammenhang steht. Beispiel: Ein
   Link zur Konfiguration eines <<glossary-menu,menu>> der angezeigt wird, wenn Sie den Mauszeiger über
   das Menü bewegen. Siehe <<config-overview>> für weitere Informationen.
(((Contributed,definition)))
(((Contributed module,definition)))
(((Contributed theme,definition)))
[[glossary-contributed]] Von der Commuinity bereitgestellt::
   <<glossary-module,Modules>>, <<glossary-theme,themes>> und
   <<glossary-distribution,distributions>> die nicht Teil des
   <<glossary-drupal-core,Drupal core>> sind und seperat von der Website https://www.drupal.org[_Drupal.org_] heruntergeladen werden könnnen.
(((Cron task,definition)))
(((Cron command scheduler,definition)))
[[glossary-cron]] Cron::
   Auf einigen Betriebssystemen ist _Cron_ eine Anwendung zur Planung von Aufgaben, das
   Befehle oder Skripte in regelmäßigen Abständen ausführt.
   Ihre Website definiert periodische Aufgaben, auch Cron-Wartungsaufgaben genannt, die entweder
   durch einen Cron-Aufgabenplaner des Betriebssystems oder intern ausgelöst werden müssen. Siehe
   <<security-cron-concept>> für weitere Informationen.
(((Distribution,definition)))
[[glossary-distribution]] Distribution::
   Ein einzelner Download, der eine schnelle Lösung für die Einrichtung einer bestimmten Art von Website enthält.
Beispiele sind: Eine Website für einen Verein oder für den Onlinehandel. Eine Distribution enthält <<glossary-drupal-core,Drupal core>>und   
<<glossary-contributed,contributed>> <<glossary-module,modules>> sowie
   <<glossary-theme,themes>>. Viele Distributionen konfigurieren die Website auch vorkonfiguriert
   oder erstellen sogar Beispielinhalte bei der Installation. Siehe
   <<understanding-distributions>> für weitere Informationen.
(((Drupal core,definition)))
[[glossary-drupal-core]] Drupal-Kernsytem::
   Die Dateien, Themes, Profile und Module, die im Lieferumfang der Standard
   Projekt-Software enthalten sind. Siehe: <<understanding-drupal>> für weitere Informationen.
(((Entity,definition)))
[[glossary-entity]] Entität::
   Ein Element, das entwerder <<glossary-content,content>> oder
   <<glossary-configuration,configuration>> Daten sein kann, obwohl der Begriff im Allgemeinen für Inahltsentitäten verwendet wird. Beispiele sind:
   <<glossary-content-item,content items>>,benutzerdefinierte <<glossary-block,blocks>>,
   <<glossary-taxonomy-term,taxonomy terms>>, und definitionen von
   <<glossary-content-type,content types>>; die erten drei sind Inhaltsentitäten,und das letzte ist ein Konfigurationselement. Siehe auch
   <<glossary-entity-type,Entity type>>,
   <<glossary-entity-subtype,Entity subtype>>, und
   <<glossary-field,Field>>. Siehe: <<planning-data-types>> für
  weitere Informationen.
(((Entity subtype,definition)))
[[glossary-entity-subtype]] Entitätssubtyp::
   Within a <<glossary-content,content>> <<glossary-entity-type,entity type>>, eine
   Gruppe von Entitäten die sich die seleben <<glossary-field,fields>> teilen. Beispielsweise wird in
   <<glossary-content-item,content item>> beschreiben, dass Entitätstypen auf der Wochenmarkt-Website Subtypen (bekannt als
   <<glossary-content-type,content types>>) enthalten sind. Einer für Statische Seiten und einer für Lieferanten.Jeder Subtyp enthält dabei seine eigenen Felder. Auch der Begriff _Bündel/Bundle_ kann solche Elemente beschreiben
   (besonders in Dokumentationen für Entwickler).
   Siehe: <<planning-data-types>> für weitere Informationen.
(((Entity type,definition)))
[[glossary-entity-type]] Entitätstyp::
   The overall type of an <<glossary-entity,entity>>; im allgemeinen Sprachgebrauch wird es
   nur auf eine Entität vom Typ <<glossary-content,content>>. Beispiele sind:
   <<glossary-content-type,content types>>,
   <<glossary-taxonomy-term,taxonomy terms>> und benutzerdefinierte
   <<glossary-block,blocks>>. Siehe: <<planning-data-types>> für weitere Informationen.
(((Field,definition)))
[[glossary-field]] Feld::
   Eine bestimmte Art Daten, die an Elemente wie
   <<glossary-content,content>> und <<glossary-entity,entity>> angehängt wird. Zum Beispiel könnten Sie auf
   der Website eines Wochenmarktes Felder für ein Bild, die Beschreibung eines Lieferanten und einen
   <<glossary-taxonomy-term,taxonomy term>> enthatlen. Siehe
   <<planning-data-types>> für weitere Informationen.
(((Field bundle,definition)))
[[glossary-field-bundle]] Bündel::
   Synonym für <<glossary-entity-subtype,Entity subtype>>.
(((Formatter,definition)))
(((Field formatter,definition)))
[[glossary-field-formatter]] Anzeigeformat::
   <<glossary-configuration,Configuration>> die angibt, wie ein <<glossary-field,field>> angezeigt wird. Zum Beispiel könnte ein Textfeld
   mit einem Präfix und/oder Suffix angezeigt werden, und die darin zulässigen HTML-Tags können
   eingeschränkt werden. Siehe auch: <<glossary-view-mode,View mode>> und
   <<glossary-field-widget,Field widget>>. Siehe: <<structure-view-modes>> für weitere Informationen.
(((Widget,definition)))
(((Field widget,definition)))
[[glossary-field-widget]] Steuerelement für Felder::
   <<glossary-configuration,Configuration>> die festlegt, auf welche Weise jemand
   Daten in ein <<glossary-field,field>> eingeben oder die darin vorhandenen Daten über ein Bearbeitungsformular bearbeiten kann. Beispielsweise könnte ein Textfeld eine Einzeilige Eingabemaske oder eine Mehrzeileige Eingabemaske verwenden und es kann eine Einstellung für die Größe des Eingabefelds enthalten sien.. Siehe auch:
   <<glossary-field-formatter,Field formatter>>. Siehe: <<structure-widgets>> für weitere Informationen.
[[glossary-formatter]] Anzeigeformat::
   Siehe: <<glossary-field-formatter,Field formatter>>.
(((FOSS (Free and Open Source Software),definition)))
(((Free and Open Source Software (FOSS),definition)))
[[glossary-foss]] FOSS::
   Akronym für _Freie und Quelloffene Software_, d.h. Software, die von einer
   Gemeinschaft verschiedener Menschen entwickelt und unter einer nicht-kommerziellen Lizenz veröffentlicht wird. 
   Siehe auch: <<glossary-gpl,GPL>>. Siehe: <<understanding-project>> für weitere Informationen.
(((GPL (General Public License or GNU General Public License),definition)))
(((GNU General Public License,definition)))
[[glossary-gpl]] GPL::
   Akronym für die _GNU General Public License_, eine nicht-kommerzielle Software
   Lizenz. Software, die Sie von
   der Webseite https://www.drupal.org[_Drupal.org_] herunterladen können, ist unter der
   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html["GNU General Public
   License, Version 2"] lizensiert. Sioehe auch: <<glossary-foss,FOSS>>. Siehe;   <<understanding-gpl>> für weitere Informationen.
(((Image style,definition)))
[[glossary-image-style]] Bildstil::
   Eine Reihe von Verarbeitungsschritten, die ein Ausgangsbild in ein neues Bild umwandeln.
Die typische Verarbeitungsmethode beinhaltet die Arbeitsschritte Skalieren und Zuschneiden. Siehe:
   <<structure-image-styles>> für weitere Informationen.
(((LAMP (Linux Apache MySQL PHP),definition)))
(((Linux Apache MySQL PHP (LAMP),definition)))
[[glossary-lamp]] LAMP::
   Akronym für _Linux, Apache, MySQL, und PHP_: die Software auf dem Webserver
   auf dem die Skripte üblicherweise ausgeführt werden (obwohl auch andere Betriebssysteme,
   Webserver und Datenbanken verwendet werden können). Siehe: <<install-requirements>> für weitere
   Informationen.
(((Log,definition)))
[[glossary-log]] Protokoll::
   Eine Liste der aufgezeichneten Ereignisse auf der Website, wie Nutzungsdaten, Leistungsdaten,
   Fehler, Warnungen und Betriebsinformationen. Siehe
   <<prevent-log>> für weitere Informationen.
(((Menu,definition)))
[[glossary-menu]] Menü::
   Eine Sammlung von Links zur Navigation auf einer Website, die hierarchisch angeordnet sein können. Siehe: <<menu-concept>> für weitere Informationen.
(((Module, definition)))
[[glossary-module]] Modul::
   Software (in der Regel PHP, JavaScript und/oder CSS), die die Funktionen der Website
   und Funktionalität hinzufügt. Drupal unterscheidet zwischen
   _<<glossary-drupal-core,core>>_ und _<<glossary-contributed,contributed>>_
   Modulen. Siehe: <<understanding-modules>> für weitere Informationen.
(((Path,definition)))
[[glossary-path]] Pfad::
   Der eindeutige, letzte Teil der internen URL, den das System einer Seite zuweist. 
   Dabei kann es sich um einen Teil der Website oder einen Teil des erwaltungsbereichs von Drupal handeln. Die interne URL für die Seite „Über“ auf Ihrer Website könnte zum Beispiel 
   _http://example.com/node/5_ lauten. in diesem Fall währe der POfad der Seite _node/5_. Siehe auch:
   <<glossary-alias,Alias>>. Siehe: <<content-paths>> für weitere Informationen.
(((Permission,definition)))
[[glossary-permission]] Berechtigung::
   Die Möglichkeit, eine bestimmte Aktion auf der Website durchzuführen, wie z.B. die Bearbeitung
   einer bestimmten Art von <<glossary-content,content>>, oder das Anzeigen von Benutzerprofilen.
   Siehe auch: <<glossary-role,Role>>. Siehe: <<user-concept>> für weitere Informationen.
(((Reference field,definition)))
[[glossary-reference-field]] Referenzfeld::
   Ein <<glossary-field,field>> das eine Beziehung zwischen einer
   <<glossary-entity,entity>> und einer oder mehreren anderen Entitäten repräsentiert. Diese Entitäten können dabei vom selben <<glossary-entity-type,entity type>> sein oder einen anderen Typ aufweisen. Beispielsweise
   Kann ein Rezept auf der Website des Wochenmarktesein Referenzfeld zum Eintrag eines Leiferanten enthalten der das Rezept eingereicht hat. Der Eintrag des Lieferanten wurde in diesem Fall ebenfalls als Inhalt erzeugt. 
   Felder mit <<glossary-taxonomy-term,Taxonomy term>> sind ebenfalls Referenzfelder. Siehe: <<structure-reference-fields>> für weitere Informationen.
(((Region,definition)))
[[glossary-region]] Region::
   Ein bestimmter Bereich auf einer Seite in dem <<glossary-content,content>> wie eine Kopfzeile, eine fußzeile, der Hauptiinhalt der Website, 
   die linke Seitenleiste, usw platziert werden kann. 
   Regionen werden in <<glossary-theme,themes>> definiert, Der Inahlt, der in jeder dieser Regionen dargestellt wird, ist Inahalt, der mit Hilfe von <<glossary-block,blocks>> dargestellt wird. 
   Siehe: <<block-regions>> für weitere Informationen.
(((Responsive,definition)))
[[glossary-responsive]] Responsiv::
   Eine Website oder ein <<glossary-theme,theme>> wird als responsiv bezeichnet, wenn es sich
   an die Größe des Anzeigegeräts, des Druckers,
   oder an einen Anderen Medienausgabetyp anpassen kann. Siehe auch: <<glossary-breakpoint,Breakpoint>>. Siehe:
   <<structure-image-responsive>> für weitere Infromationen.
(((Revision,definition)))
[[glossary-revision]] Revision::
   Eine Aufzeichnung über den vergangenen oder gegenwärtigen Zustand eines <<glossary-content,content>>
   <<glossary-entity,entity>>, im Verlauf der Bearbeitung. Siehe:
   <<planning-workflow>> für weitere Infromationen.
(((Role,definition)))
[[glossary-role]] Rolle::
   A named set of <<glossary-permission,permissions>> that can be applied to
   a <<glossary-user,user account>>. See <<user-concept>> for more information.
(((Security update,definition)))
[[glossary-security-update]] Security update::
   An <<glossary-update,update>> that fixes a security-related bug, such as a
   hacking vulnerability. See <<security-concept>> for more information.
(((State,definition)))
[[glossary-state]] State::
   Information of a temporary nature about the current state of your
   site, such as the time when <<glossary-cron,cron>> was last run, etc.
   See also <<glossary-content,Content>> and
   <<glossary-configuration,Configuration>>.  See <<understanding-data>> for
   more information.
(((Taxonomy,definition)))
[[glossary-taxonomy]] Taxonomy::
   The process of classifying <<glossary-content,content>>. See
   <<structure-taxonomy>> for more information.
(((Taxonomy term,definition)))
[[glossary-taxonomy-term]] Taxonomy term::
   A term used to classify <<glossary-content,content>>, such as a tag or
   a category. See also <<glossary-vocabulary,Vocabulary>>. See
   <<structure-taxonomy>> for more information.
(((Text format,definition)))
[[glossary-text-format]] Text format::
   <<glossary-configuration,Configuration>> that defines the processing that
   happens to user-entered text before it is shown in the browser. This might
   include stripping or limiting HTML tags, or turning URLs into links. See
   <<structure-text-formats>> for more information.
(((Theme,definition)))
[[glossary-theme]] Theme::
   Software and asset files (images, CSS, PHP code, and/or templates) that
   determine the style and layout of the site. The Drupal project distinguishes
   between  _<<glossary-drupal-core,core>>_ and
   _<<glossary-contributed,contributed>>_ themes. See <<understanding-themes>>
   for more information.
(((UI (User Interface),definition)))
[[glossary-ui]] UI::
   Acronym for <<glossary-user-interface,_User Interface_>>.
(((Update,definition)))
[[glossary-update]] Update::
   A newer version of your site's software, either
   <<glossary-drupal-core,Drupal core>> or a <<glossary-module,module>> or
   <<glossary-theme,theme>>. See also
   <<glossary-security-update,Security update>>. See <<security-concept>> for
   more information.
(((User,definition)))
[[glossary-user]] User::
   A person interacting with the site, either logged-in or
   <<glossary-anonymous,anonymous>>. See <<user-concept>> for more information.
(((User Interface (UI),definition)))
[[glossary-user-interface]] User interface::
   The text, styles, and images that are visible on a site, separated logically
   into the user interface for site visitors and the administrative user
   interface.
(((User one,definition)))
[[glossary-user-one]] User one (User 1)::
   The initial <<glossary-user,user>> account that is created when you install
   the site (whose ID number is 1). It automatically has all
   <<glossary-permission,permissions>>, even if it is not assigned an
   administrative <<glossary-role,role>>. See <<user-admin-account>> for more
   information.
(((View,definition)))
[[glossary-view]] View::
   A formatted listing of data; typically, the data comes from
   <<glossary-content,content>> <<glossary-entity,entities>>. For example, on
   a farmers market site, you might create a
   <<glossary-content-item,content item>> for each vendor. You could then
   make view that generates a listing page that shows a thumbnail image and
   short description of each vendor, linking to the full-page content
   item. Using the same data, you could also make a view that generates a new
   vendors block, which would show information from the most recently added
   vendors. See <<planning-modular>> for more information.
(((View mode,definition)))
[[glossary-view-mode]] View mode::
   A set of <<glossary-field-formatter,field formatter>>
   <<glossary-configuration,configuration>> for all of the
   <<glossary-field,fields>> of a <<glossary-content,content>>
   <<glossary-entity,entity>>, some of which may be hidden. Each
   <<glossary-entity-subtype,entity subtype>> can have one or more view modes
   defined; for example, <<glossary-content-type,content types>> typically have
   _Full_ and _Teaser_ view modes, where the _Teaser_ view mode displays fewer
   or trimmed-down fields. See <<structure-view-modes>> for more information.
(((Vocabulary,definition)))
[[glossary-vocabulary]] Vocabulary::
   A group of <<glossary-taxonomy-term,taxonomy terms>> to choose from when
   classifying <<glossary-content,content>> in a particular way, such as the
   list of all of the vendor categories on a farmers
   market site. Technically, vocabularies are the
   <<glossary-entity-subtype,entity subtype>> for the taxonomy term
   <<glossary-entity-type,entity type>>. See
   <<structure-taxonomy>> for more information.
(((Widget,definition)))
[[glossary-widget]] Steuerelement::
   Siehe <<glossary-field-widget,Field widget>>.
(((Wizard,definition)))
[[glossary-wizard]] Wizard::
   Ein Webformular, in das Sie einige Werte eingeben können und das dann etwas
   mit sinnvollen Voreinstellungen auf der Grundlage der von Ihnen gewählten Werte ausgibt. Zum Beispiel gibt es
   Assistenten für die Erstellung von <<glossary-view,views>>. Siehe   
   <<views-create>> für weitere Informationen.
(((WYSIWYG (What You See Is What You Get),definition)))
(((What You See Is What You Get (WYSIWYG),definition)))
[[glossary-wysiwyg]] WYSIWYG::
   Acronym für _What You See is What You Get_, beschreibt eine Bearbeitungsmethode für
   <<glossary-content,content>> bei der die eingabe auf dem Bearbeitungsformular dem späteren Ergebnis sehr nahe kommt. Siehe: <<structure-text-format-config>> für
   weitere Informationen.
