[[glossary]]
== Glossar

(((Glossary)))
(((Terminology (Glossary))))

(((Ajax,definition)))
[glossary]
[[glossary-ajax]] Ajax::
Eine Web-Technologie, die zum Datenaustausch mit einem Server verwendet wird, um dynamisch
Teile einer Webseite (zum Beispiel Formulare) zu aktualisieren, ohne die gesamte neu laden zu müssen.
(((Alias,definition)))
[[glossary-alias]] Alias::
   Ein benutzerfreundlicher Name, der den internen <<glossary-path,path>> ersetzt, den
   das System einer URL auf der Website zuweist. Sie könnten zum Beispiel einen
   Alias _/about_ für die Seite About auf Ihrer Website vergeben, um den internen
   Pfad _/node/5_. Dadurch würde die Seite die URL _http://example.com/about_
   anstelle von _http://example.com/node/5_. Siehe <<content-paths>> für weitere
   Informationen.
(((Anonymous,definition)))
[[glossary-anonymous]] Gast::
   Eine Person (<<glossary-user,user>>), die mit der Website interagiert und nicht angemeldet ist.
    Siehe <<user-concept>> für weitere Informationen.
(((Block,definition)))
[[glossary-block]] Block::
   Ein Stück <<glossary-content,content>> (Text, Bild, Link, usw.) dasa auf einer Seite innerhalb eine Website angezeigt werden kann. Blöcke werden in
   <<glossary-region,regions>> angezeigt. Siehe:<<block-concept>> für weiterte Information.
(((Breakpoint,definition)))
[[glossary-breakpoint]] Breakpoint::
   Breakpoints werden verwendet, um die Höhe oder Breite von Browsern, Bildschirmen,
   Druckern und weiteren Medienausgabetypen in Bereiche zu unterteilen. Eine
   <<glossary-responsive,responsive>> Seite passt ihre Präsentation anhand dieser 
   Breakpoints an. Siehe: <<structure-image-responsive>> für weitere Informationen.
(((Bundle,definition)))
[[glossary-bundle]] Subtyp::
   Synonym für <<glossary-entity-subtype,Entity subtype>>.
(((Cache,definition)))
[[glossary-cache]] Cache::
   Der interne Cache der Website, der auch Zwischenspeicher genannt wird, speichert die Ausgabe zeitaufwändiger Berechnungen, wie z.B. die Berechnung der Ausgabe für eine HTML-Seitenanfrage, und gibt das Ergebnis dieser Berechnung direkt aus, anstatt die Berechnung beim bei jedem Seitenaufruf neu durchführen.
   Externe Caching-Systeme können auch auf dem Webserver verwendet werden, um die
   Antwortzeit einer Website zu verkürzen. Siehe: <<prevent-cache>> für weitere Informationen über den internen Cache.
(((CMS (Content Management System),definition)))
(((Content Management System (CMS),definition)))
[[glossary-cms]] CMS::
   Akronym für
   <<glossary-content-management-system,Content Management System>>.
(((Configuration,definition)))
[[glossary-configuration]] Konfiguration::
   Informationen über Ihre Website, die nicht <<glossary-content,content>> sind,
   und die dauerhafter sein sollen als <<glossary-state,state>> Informationen,
   wie zum Beispiel der Name Ihrer Website, der <<glossary-content-type,content types>>
   und <<glossary-view,views>>, die Sie definiert haben, usw. Siehe <<understanding-data>>
   für weitere Informationen.
(((Content,definition)))
[[glossary-content]] Inhalt::
   Informationen, die auf Ihrer Website angezeigt werden sollen, z. B. Texte, Bilder,
   Downloads, usw. Siehe auch: <<glossary-configuration,Configuration>> und
   <<glossary-state,State>>. Siehe: <<understanding-data>> für weitere Informationen.
(((Content item,definition)))
[[glossary-content-item]] Inhalt::
   Ein Element von <<glossary-content,content>>, das normalerweise als
   als Hauptinhalt einer Seite auf Ihrer Website angezeigt wird. Dies ist ein
   <<glossary-entity-type,entity type>>.
   Siehe <<planning-data-types>> für weitere Infromationen.
(((Content Management System (CMS),definition)))
[[glossary-content-management-system]] Content Management System (CMS)::
   Eine Sammlung von Tools, die die Erstellung, Änderung,
   Organisation, die Suche, den Abruf und  die Entfernung von Informationen auf einer Website vereinfacht.
   Siehe: <<understanding-drupal>> für weitere Informationen.
(((Content type,definition)))
[[glossary-content-type]] Inhaltstyp::
   Ein/eine <<glossary-entity-subtype,entity subtype>> eines
   <<glossary-content-item,content item>> <<glossary-entity-type,entity type>>.
   Jeder Inhaltstyp wird für einen bestimmten Zweck auf der Website verwendet und
   hat seine eigenen Felder. Zum Beispiel könnte eine Website für einen Wochenmarkt über einen
   Inhaltstyp für einfache Seiten und einen anderen für eine Seite mit Lieferantenlisten.
   Siehe <<planning-data-types>> für weitere Informationen.
(((Contextual link,definition)))
[[glossary-contextual-link]] Kontextlink::
   Ein Link zu einer administrativen Seite zum Bearbeiten oder Konfigurieren einer Funktion der
   Website, die in dem Kontext angezeigt wird, in dem diese Funktion mit dem jewiligen Element auf einer Website 
   in  Zusammenhang steht. Beispiel: Ein
   Link zur Konfiguration eines <<glossary-menu,menu>> der angezeigt wird, wenn Sie den Mauszeiger über
   das Menü bewegen. Siehe <<config-overview>> für weitere Informationen.
(((Contributed,definition)))
(((Contributed module,definition)))
(((Contributed theme,definition)))
[[glossary-contributed]] Von der Commuinity bereitgestellt::
   <<glossary-module,Modules>>, <<glossary-theme,themes>> und
   <<glossary-distribution,distributions>> die nicht Teil des
   <<glossary-drupal-core,Drupal core>> sind und seperat von der Website https://www.drupal.org[_Drupal.org_] heruntergeladen werden könnnen.
(((Cron task,definition)))
(((Cron command scheduler,definition)))
[[glossary-cron]] Cron::
   Auf einigen Betriebssystemen ist _Cron_ eine Anwendung zur Planung von Aufgaben, das
   Befehle oder Skripte in regelmäßigen Abständen ausführt.
   Ihre Website definiert periodische Aufgaben, auch Cron-Wartungsaufgaben genannt, die entweder
   durch einen Cron-Aufgabenplaner des Betriebssystems oder intern ausgelöst werden müssen. Siehe
   <<security-cron-concept>> für weitere Informationen.
(((Distribution,definition)))
[[glossary-distribution]] Distribution::
   Ein einzelner Download, der eine schnelle Lösung für die Einrichtung einer bestimmten Art von Website enthält.
Beispiele sind: Eine Website für einen Verein oder für den Onlinehandel. Eine Distribution enthält <<glossary-drupal-core,Drupal core>>und   
<<glossary-contributed,contributed>> <<glossary-module,modules>> sowie
   <<glossary-theme,themes>>. Viele Distributionen konfigurieren die Website auch vorkonfiguriert
   oder erstellen sogar Beispielinhalte bei der Installation. Siehe
   <<understanding-distributions>> für weitere Informationen.
(((Drupal core,definition)))
[[glossary-drupal-core]] Drupal-Kernsystem::
   Die Dateien, Themes, Profile und Module, die im Lieferumfang der Standard
   Projekt-Software enthalten sind. Siehe: <<understanding-drupal>> für weitere Informationen.
(((Entity,definition)))
[[glossary-entity]] Entität::
   Ein Element, das entwerder <<glossary-content,content>> oder
   <<glossary-configuration,configuration>> Daten sein kann, obwohl der Begriff im Allgemeinen für Inahltsentitäten verwendet wird. Beispiele sind:
   <<glossary-content-item,content items>>,benutzerdefinierte <<glossary-block,blocks>>,
   <<glossary-taxonomy-term,taxonomy terms>>, und definitionen von
   <<glossary-content-type,content types>>; die erten drei sind Inhaltsentitäten,und das letzte ist ein Konfigurationselement. Siehe auch
   <<glossary-entity-type,Entity type>>,
   <<glossary-entity-subtype,Entity subtype>>, und
   <<glossary-field,Field>>. Siehe: <<planning-data-types>> für
  weitere Informationen.
(((Entity subtype,definition)))
[[glossary-entity-subtype]] Entitätssubtyp::
   Within a <<glossary-content,content>> <<glossary-entity-type,entity type>>, eine
   Gruppe von Entitäten die sich die seleben <<glossary-field,fields>> teilen. Beispielsweise wird in
   <<glossary-content-item,content item>> beschreiben, dass Entitätstypen auf der Wochenmarkt-Website Subtypen (bekannt als
   <<glossary-content-type,content types>>) enthalten sind. Einer für Statische Seiten und einer für Lieferanten.Jeder Subtyp enthält dabei seine eigenen Felder. Auch der Begriff _Bündel/Bundle_ kann solche Elemente beschreiben
   (besonders in Dokumentationen für Entwickler).
   Siehe: <<planning-data-types>> für weitere Informationen.
(((Entity type,definition)))
[[glossary-entity-type]] Entitätstyp::
   The overall type of an <<glossary-entity,entity>>; im allgemeinen Sprachgebrauch wird es
   nur auf eine Entität vom Typ <<glossary-content,content>>. Beispiele sind:
   <<glossary-content-type,content types>>,
   <<glossary-taxonomy-term,taxonomy terms>> und benutzerdefinierte
   <<glossary-block,blocks>>. Siehe: <<planning-data-types>> für weitere Informationen.
(((Field,definition)))
[[glossary-field]] Feld::
   Eine bestimmte Art Daten, die an Elemente wie
   <<glossary-content,content>> und <<glossary-entity,entity>> angehängt wird. Zum Beispiel könnten Sie auf
   der Website eines Wochenmarktes Felder für ein Bild, die Beschreibung eines Lieferanten und einen
   <<glossary-taxonomy-term,taxonomy term>> enthatlen. Siehe
   <<planning-data-types>> für weitere Informationen.
(((Field bundle,definition)))
[[glossary-field-bundle]] Bündel::
   Synonym für <<glossary-entity-subtype,Entity subtype>>.
(((Formatter,definition)))
(((Field formatter,definition)))
[[glossary-field-formatter]] Anzeigeformat::
   <<glossary-configuration,Configuration>> die angibt, wie ein <<glossary-field,field>> angezeigt wird. Zum Beispiel könnte ein Textfeld
   mit einem Präfix und/oder Suffix angezeigt werden, und die darin zulässigen HTML-Tags können
   eingeschränkt werden. Siehe auch: <<glossary-view-mode,View mode>> und
   <<glossary-field-widget,Field widget>>. Siehe: <<structure-view-modes>> für weitere Informationen.
(((Widget,definition)))
(((Field widget,definition)))
[[glossary-field-widget]] Steuerelement für Felder::
   <<glossary-configuration,Configuration>> die festlegt, auf welche Weise jemand
   Daten in ein <<glossary-field,field>> eingeben oder die darin vorhandenen Daten über ein Bearbeitungsformular bearbeiten kann. Beispielsweise könnte ein Textfeld eine Einzeilige Eingabemaske oder eine Mehrzeileige Eingabemaske verwenden und es kann eine Einstellung für die Größe des Eingabefelds enthalten sien.. Siehe auch:
   <<glossary-field-formatter,Field formatter>>. Siehe: <<structure-widgets>> für weitere Informationen.
[[glossary-formatter]] Anzeigeformat::
   Siehe: <<glossary-field-formatter,Field formatter>>.
(((FOSS (Free and Open Source Software),definition)))
(((Free and Open Source Software (FOSS),definition)))
[[glossary-foss]] FOSS::
   Akronym für _Freie und Quelloffene Software_, d.h. Software, die von einer
   Gemeinschaft verschiedener Menschen entwickelt und unter einer nicht-kommerziellen Lizenz veröffentlicht wird. 
   Siehe auch: <<glossary-gpl,GPL>>. Siehe: <<understanding-project>> für weitere Informationen.
(((GPL (General Public License or GNU General Public License),definition)))
(((GNU General Public License,definition)))
[[glossary-gpl]] GPL::
   Akronym für die _GNU General Public License_, eine nicht-kommerzielle Software
   Lizenz. Software, die Sie von
   der Webseite https://www.drupal.org[_Drupal.org_] herunterladen können, ist unter der
   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html["GNU General Public
   License, Version 2"] lizensiert. Sioehe auch: <<glossary-foss,FOSS>>. Siehe;   <<understanding-gpl>> für weitere Informationen.
(((Image style,definition)))
[[glossary-image-style]] Bildstil::
   Eine Reihe von Verarbeitungsschritten, die ein Ausgangsbild in ein neues Bild umwandeln.
Die typische Verarbeitungsmethode beinhaltet die Arbeitsschritte Skalieren und Zuschneiden. Siehe:
   <<structure-image-styles>> für weitere Informationen.
(((LAMP (Linux Apache MySQL PHP),definition)))
(((Linux Apache MySQL PHP (LAMP),definition)))
[[glossary-lamp]] LAMP::
   Akronym für _Linux, Apache, MySQL, und PHP_: die Software auf dem Webserver
   auf dem die Skripte üblicherweise ausgeführt werden (obwohl auch andere Betriebssysteme,
   Webserver und Datenbanken verwendet werden können). Siehe: <<install-requirements>> für weitere
   Informationen.
(((Log,definition)))
[[glossary-log]] Protokoll::
   Eine Liste der aufgezeichneten Ereignisse auf der Website, wie Nutzungsdaten, Leistungsdaten,
   Fehler, Warnungen und Betriebsinformationen. Siehe
   <<prevent-log>> für weitere Informationen.
(((Menu,definition)))
[[glossary-menu]] Menü::
   Eine Sammlung von Links zur Navigation auf einer Website, die hierarchisch angeordnet sein können. Siehe: <<menu-concept>> für weitere Informationen.
(((Module, definition)))
[[glossary-module]] Modul::
   Software (in der Regel PHP, JavaScript und/oder CSS), die die Funktionen der Website
   und Funktionalität hinzufügt. Drupal unterscheidet zwischen
   _<<glossary-drupal-core,core>>_ und _<<glossary-contributed,contributed>>_
   Modulen. Siehe: <<understanding-modules>> für weitere Informationen.
(((Path,definition)))
[[glossary-path]] Pfad::
   Der eindeutige, letzte Teil der internen URL, den das System einer Seite zuweist. 
   Dabei kann es sich um einen Teil der Website oder einen Teil des erwaltungsbereichs von Drupal handeln. Die interne URL für die Seite „Über“ auf Ihrer Website könnte zum Beispiel 
   _http://example.com/node/5_ lauten. in diesem Fall währe der POfad der Seite _node/5_. Siehe auch:
   <<glossary-alias,Alias>>. Siehe: <<content-paths>> für weitere Informationen.
(((Permission,definition)))
[[glossary-permission]] Berechtigung::
   Die Möglichkeit, eine bestimmte Aktion auf der Website durchzuführen, wie z.B. die Bearbeitung
   einer bestimmten Art von <<glossary-content,content>>, oder das Anzeigen von Benutzerprofilen.
   Siehe auch: <<glossary-role,Role>>. Siehe: <<user-concept>> für weitere Informationen.
(((Reference field,definition)))
[[glossary-reference-field]] Referenzfeld::
   Ein <<glossary-field,field>> das eine Beziehung zwischen einer
   <<glossary-entity,entity>> und einer oder mehreren anderen Entitäten repräsentiert. Diese Entitäten können dabei vom selben <<glossary-entity-type,entity type>> sein oder einen anderen Typ aufweisen. Beispielsweise
   Kann ein Rezept auf der Website des Wochenmarktesein Referenzfeld zum Eintrag eines Leiferanten enthalten der das Rezept eingereicht hat. Der Eintrag des Lieferanten wurde in diesem Fall ebenfalls als Inhalt erzeugt. 
   Felder mit <<glossary-taxonomy-term,Taxonomy term>> sind ebenfalls Referenzfelder. Siehe: <<structure-reference-fields>> für weitere Informationen.
(((Region,definition)))
[[glossary-region]] Region::
   Ein bestimmter Bereich auf einer Seite in dem <<glossary-content,content>> wie eine Kopfzeile, eine fußzeile, der Hauptiinhalt der Website, 
   die linke Seitenleiste, usw platziert werden kann. 
   Regionen werden in <<glossary-theme,themes>> definiert, Der Inahlt, der in jeder dieser Regionen dargestellt wird, ist Inahalt, der mit Hilfe von <<glossary-block,blocks>> dargestellt wird. 
   Siehe: <<block-regions>> für weitere Informationen.
(((Responsive,definition)))
[[glossary-responsive]] Responsiv::
   Eine Website oder ein <<glossary-theme,theme>> wird als responsiv bezeichnet, wenn es sich
   an die Größe des Anzeigegeräts, des Druckers,
   oder an einen Anderen Medienausgabetyp anpassen kann. Siehe auch: <<glossary-breakpoint,Breakpoint>>. Siehe:
   <<structure-image-responsive>> für weitere Infromationen.
(((Revision,definition)))
[[glossary-revision]] Revision::
   Eine Aufzeichnung über den vergangenen oder gegenwärtigen Zustand eines <<glossary-content,content>>
   <<glossary-entity,entity>>, im Verlauf der Bearbeitung. Siehe:
   <<planning-workflow>> für weitere Infromationen.
(((Role,definition)))
[[glossary-role]] Rolle::
   Eine beannte Sammlung von <<glossary-permission,permissions>> die einem
   <<glossary-user,user account>> zugewiesen wird. Siehe: <<user-concept>> für weitere Informationen.
(((Security update,definition)))
[[glossary-security-update]] Sicherheitsaktualisierung::
   Eine <<glossary-update,update>> das einen sicherheitsrelevanten Fehler behebt, z.B. eine
Sicherheitslücke. Siehe: <<security-concept>> für weitere Informationen.
(((State,definition)))
[[glossary-state]] Status::
   Informationen vorübergehender Natur über den aktuellen Zustand Ihrer
   Website, wie z.B. die Zeit, zu der <<glossary-cron,cron>> zum letzten mal ausgeführt wurde, usw.
   Siehe auch: <<glossary-content,Content>> und
   <<glossary-configuration,Configuration>>.  Siehe: <<understanding-data>> für weitere Informationen.
(((Taxonomy,definition)))
[[glossary-taxonomy]] Taxonomie::
   Der Prozess der Klassifizierung von <<glossary-content,content>>. Siehe
   <<structure-taxonomy>> für weitere Informationen.
(((Taxonomy term,definition)))
[[glossary-taxonomy-term]] Taxonomiebegriff::
   Ein Begriff zur Klassifizierung von <<glossary-content,content>>, wie beisppielsweise ein Tag oder eine Kategrie. Siehe auch: <<glossary-vocabulary,Vocabulary>>. Siehe:
   <<structure-taxonomy>> für weitere Informationen.
(((Text format,definition)))
[[glossary-text-format]] Textformat::
   <<glossary-configuration,Configuration>> dcie festlegt, wei von Benutzern eingeebener Text verarbeitet wird, bevor dieser im Browser dargestellt wird. Dieser vorgang kann das Entfernen oder die Limitierung der HTML-Tags enthalten die verwendet werden können. Urls können über Textformate automatisch in Links umgewandelt werden. Siehe:
   <<structure-text-formats>> für weitere Informationen.
(((Theme,definition)))
[[glossary-theme]] Theme::
   Software und Asset-Dateien (Bilder, CSS, PHP-Code und/oder Vorlagen), die
   die den Stil und das Layout der Website bestimmen. Das Projekt Drupal unterscheidet zwischen _<<glossary-drupal-core,core>>_ und
   _<<glossary-contributed,contributed>>_ Themes. Siehe: <<understanding-themes>>
   für weitere Informationen.
(((UI (User Interface),definition)))
[[glossary-ui]] UI::
   Akronym für <<glossary-user-interface,_User Interface_>>.
(((Update,definition)))
[[glossary-update]] Update::
   Eine neuere Version der Software für Ihre Website, entweder
   <<glossary-drupal-core,Drupal core>> oder ein <<glossary-module,module>> bzw.
   <<glossary-theme,theme>>. Siehe auch:
   <<glossary-security-update,Security update>>. Siehe: <<security-concept>> for
   more information.
(((User,definition)))
[[glossary-user]] User::
   Eine Person, die mit der Website interagiert, entweder angemeldet oder
   <<glossary-anonymous,anonymous>>. Siehe: <<user-concept>> für weitere Informationen.
(((User Interface (UI),definition)))
[[glossary-user-interface]] Benutzeroberfläche::
   Der Text, die Stile und die Bilder, die auf einer Website sichtbar sind, logisch getrennt
   in Benutzeroberfläche für Besucher der Website und den Verwaltungsbereich.
(((User one,definition)))
[[glossary-user-one]] Benutzer Eins (User 1)::
   Das erste <<glossary-user,user>> Konto, das bei der Installation der Website erstellt wird (und deshalb die Nummer 1 erhält). Es besitzt automatisch alle 
   <<glossary-permission,permissions>>, selbst, wenn dem Benutzekonto keeine
   administrative <<glossary-role,role>> zugewiesen wurde. Siehe: <<user-admin-account>> für weitere Informationen.
(((View,definition)))
[[glossary-view]] Ansicht::
   Eine formatierte Liste von Daten; typischerweise beziehen Ansichten ihre zugrundeligenden Daten aus
   <<glossary-content,content>> bzw. <<glossary-entity,entities>>. Auf der Website des Wochemartktes könnten Sie beispielsweise einen 
   <<glossary-content-item,content item>> für jeden Lieferanten erstellen. Sie könnten dann
   eine Ansicht erstellen, die eine Auflistungsseite generiert, die ein Miniaturbild und eine
   kurze Beschreibung jedes Lieferanten mit einem Link zu einem ganzseitigen
   Artikel über den Leiferanten ausgibt. Mit denselben Daten könnten Sie auch eine Ansicht erstellen, die einen neuen
   Block generiert, der Informationen zu den zuletzt hinzugefügten Lieferanten anzeigt.
   Siehe: <<planning-modular>> für weitere Informationen.
(((View mode,definition)))
[[glossary-view-mode]] Anzeigemodus::
   Eine Sammlung von <<glossary-field-formatter,field formatter>>
   <<glossary-configuration,configuration>> für alle
   <<glossary-field,fields>> innerhalb von <<glossary-content,content>>
   <<glossary-entity,entity>>, einige Felder können ausgeblendet sein. Jede/r
   <<glossary-entity-subtype,entity subtype>> kabb eine oder mehrere Definitionen für einen Ansichtsmodus enthalten. Beispielsweise enthalten <<glossary-content-type,content types>> normalerweise
   den Ansichtsmodus _Vollständig_ und den Ansichtsmodus _Anrisstext_. Dabei enthält der Ansichtsmodus _Anrisstext_ weniger Felder als der Ansichtsmodus _Vollständig_. Siehe: <<structure-view-modes>> für weitere Informationen.
(((Vocabulary,definition)))
[[glossary-vocabulary]] Vokabular::
   Eine Gruppe von <<glossary-taxonomy-term,taxonomy terms>> aus denen gewählt werden kann wenn <<glossary-content,content>> auf eine bestimmte Airt und Weise klassifiziert werden soll. Bieispielsweise so, wei die Liste aller Leiferanten des wopchenmarktes. Technisch gesheen sind Vokabulare ein
   <<glossary-entity-subtype,entity subtype>> eines Taxonomiebegriffs
   <<glossary-entity-type,entity type>>. Siehe
   <<structure-taxonomy>> für weitere Informationen.
(((Widget,definition)))
[[glossary-widget]] Steuerelement::
   Siehe: <<glossary-field-widget,Field widget>>.
(((Wizard,definition)))
[[glossary-wizard]] Assistent::
   Ein Webformular, in das Sie einige Werte eingeben können und das dann etwas
   mit sinnvollen Voreinstellungen auf der Grundlage der von Ihnen gewählten Werte ausgibt. Zum Beispiel gibt es
   Assistenten für die Erstellung von <<glossary-view,views>>. Siehe   
   <<views-create>> für weitere Informationen.
(((WYSIWYG (What You See Is What You Get),definition)))
(((What You See Is What You Get (WYSIWYG),definition)))
[[glossary-wysiwyg]] WYSIWYG::
   Acronym für _What You See is What You Get_, beschreibt eine Bearbeitungsmethode für
   <<glossary-content,content>> bei der die eingabe auf dem Bearbeitungsformular dem späteren Ergebnis sehr nahe kommt. Siehe: <<structure-text-format-config>> für
   weitere Informationen.
