[[glossary]]
== Glossar

(((Glossary)))
(((Terminology (Glossary))))

(((Ajax,definition)))
[glossary]
[[glossary-ajax]] Ajax::
Eine Web-Technologie, die zum Datenaustausch mit einem Server verwendet wird, um dynamisch
Teile einer Webseite (zum Beispiel Formulare) zu aktualisieren, ohne die gesamte  Website neu laden zu müssen.
(((Alias,definition)))
[[glossary-alias]] Alias::
   Ein benutzerfreundlicher Name, der den internen <<glossary-path,Pfad>> ersetzt, den
   das System einer URL auf der Website zuweist. Sie könnten zum Beispiel den
   Alias _/über für die Seite „Über uns“ auf Ihrer Website vergeben, um den internen
   Pfad _/node/5_ hinter dem Alias zu verstecken. Dadurch würde die Seite über die URL _http://example.com/über_ erreichbar werden
   und nicht über den internen Pfad _http://example.com/node/5_. Siehe <<content-paths>> für weitere
   Informationen.
(((Anonymous,definition)))
[[glossary-anonymous]] Gast::
   Ein <<glossary-user,Benutzer>>, der mit der Website interagiert und nicht angemeldet ist.
    Siehe <<user-concept>> für weitere Informationen.
(((Block,definition)))
[[glossary-block]] Block::
   Ein Stück <<glossary-content,Inhalt>> (Text, Bild, Link, usw.) das auf einer Seite angezeigt werden kann, die Teil einer Website ist. Blöcke werden in
   <<glossary-region,Regionen>> angezeigt. Siehe: <<block-concept>> für weitere Informationen.  
(((Breakpoint,definition)))
[[glossary-breakpoint]] Breakpoint::
   Breakpoints werden verwendet, um die Höhe oder Breite von Browsern, Bildschirmen,
   Druckern und weiteren Medienausgabetypen in Bereiche zu unterteilen. Eine
   <<glossary-responsive,responsive>> Seite passt ihre Präsentation anhand dieser 
   Breakpoints an. Siehe: <<structure-image-responsive>> für weitere Informationen.
(((Bundle,definition)))
[[glossary-bundle]] Subtyp::
   Synonym für <<glossary-entity-subtype,Entität oder Entitätssubtyp>>.
(((Cache,definition)))
[[glossary-cache]] Cache/Zwischenspeicher::
   Der interne Cache der Website, der auch Zwischenspeicher genannt wird, speichert die Ausgabe zeitaufwändiger Berechnungen, wie z.B. die Berechnung der Ausgabe für eine HTML-Seitenanfrage, und gibt das Ergebnis dieser Berechnung direkt aus, anstatt die Berechnung bei jedem Seitenaufruf neu durchzuführen.
   Externe Caching-Systeme können auch auf dem Webserver verwendet werden, um die
   Antwortzeit einer Website zu verkürzen. Siehe: <<prevent-cache>> für weitere Informationen über den internen Cache.
(((CMS (Content Management System),definition)))
(((Content Management System (CMS),definition)))
[[glossary-cms]] CMS::
   Akronym für
   <<glossary-content-management-system,Content Management System>>.
(((Configuration,definition)))
[[glossary-configuration]] Konfiguration::
   Informationen über Ihre Website, die keine <<glossary-content,Inhalte>> sind,
   und die dauerhafter sein sollen als ein <<glossary-state,Status>>. Informationen,
   wie zum Beispiel der Name Ihrer Website, eines <<glossary-content-type,Inhaltstyps>>
   oder <<glossary-view,Ansichten>>, die Sie definiert haben, usw. Siehe <<understanding-data>>
   für weitere Informationen.
(((Content,definition)))
[[glossary-content]] Inhalt::
   Informationen, die auf Ihrer Website angezeigt werden sollen, z. B. Texte, Bilder,
   Downloads, usw. Siehe auch: <<glossary-configuration,Konfiguration>> und
   <<glossary-state,Status>>. Siehe: <<understanding-data>> für weitere Informationen.
(((Content item,definition)))
[[glossary-content-item]] Hauptinhalt::
   Ein <<glossary-content,Inhalt>>, der normalerweise als
   Haupbestandteil einer Bestimmten Seite innerhalb einer Website angezeigt wird. Dies ist ein
   <<glossary-entity-type,Entitätstyp>>.
   Siehe <<planning-data-types>> für weitere Informationen.
(((Content Management System (CMS),definition)))
[[glossary-content-management-system]] Content Management System (CMS)::
   Eine Sammlung von Tools, die das Erstellen,das Bearbeiten, die
   Organisation, die Suche, den Abruf und  das Löschen von Informationen auf einer Website vereinfacht.
   Siehe: <<understanding-drupal>> für weitere Informationen.
(((Content type,definition)))
[[glossary-content-type]] Inhaltstyp::
   Eine <<glossary-entity-subtype,Entität oder ein Entitätssubtyp>> eines
   <<glossary-content-item,Inhalts>>. Inhaltstypen sind <<glossary-entity-type,Entitätstypen>>.
   Jeder Inhaltstyp wird für einen bestimmten Zweck auf der Website verwendet und
   hat seine eigenen Felder. Zum Beispiel könnte eine Website für einen Wochenmarkt über einen
   Inhaltstyp für statische Seiten und daneben einen weiteren Inhaltstyp enthalten, mit dem Lieferantenlisten erzeugt werden können.
   Siehe <<planning-data-types>> für weitere Informationen.
(((Contextual link,definition)))
[[glossary-contextual-link]] Kontextlink::
   Ein Link zu einer bestimmten Seite im Verwaltungsbereich auf der  Inhalte oder Einstellungen bearbeitet werden könnnen. Dabei sthet der Link immer im Kontext mit dem jeweiligen Element auf einer Website. 
   Beispiel: Ein Link zur Konfiguration eines <<glossary-menu,Menüs>>, der angezeigt wird, wenn Sie mit dem Mauszeiger über
   das entsprechende Menü fahren. Siehe <<config-overview>> für weitere Informationen.
(((Contributed,definition)))
(((Contributed module,definition)))
(((Contributed theme,definition)))
[[glossary-contributed]] Von der Community bereitgestellt::
   <<glossary-module,Module>>, <<glossary-theme,Themes>> und
   <<glossary-distribution,Distributionen>> die nicht im
   <<glossary-drupal-core,Drupal Kernsystem>> enthalten sind und seperat von der Website https://www.drupal.org[_Drupal.org_] heruntergeladen werden könnnen.
(((Cron task,definition)))
(((Cron command scheduler,definition)))
[[glossary-cron]] Cron::
   Auf einigen Betriebssystemen ist _Cron_ eine Anwendung zur Planung von Aufgaben, die
   Befehle oder Skripte in regelmäßigen Abständen ausführt.
   Ihre Website definiert periodische Aufgaben, auch Cron-Wartungsaufgaben genannt, die entweder
   durch einen Aufgabenplaner des Betriebssystems oder intern ausgelöst werden müssen. Siehe
   <<security-cron-concept>> für weitere Informationen.
(((Distribution,definition)))
[[glossary-distribution]] Distribution::
   Ein einzelner Download, der eine schnelle Lösung für die Einrichtung einer Website enthält, die einen spezifischen Anwendungsfall abdeckt.
Beispiele sind: Eine Website für einen Verein oder für den Onlinehandel. Eine Distribution enthält das <<glossary-drupal-core,Drupal-Kernsystem>> und   
<<glossary-contributed,von der Community bereitgestellte>> <<glossary-module,Module>> sowie
   <<glossary-theme,Themes>>. Viele Distributionen konfigurieren die Website auch vorkonfiguriert
   oder erstellen sogar Beispielinhalte während der Installation. Siehe
   <<understanding-distributions>> für weitere Informationen.
(((Drupal core,definition)))
[[glossary-drupal-core]] Drupal-Kernsystem::
   Die Dateien, Themes, Profile und Module, die im Lieferumfang von Drupal enthalten sind und anschließend durch Module und Themes erweitert werden können, die von der Community bereitgestellt werden. Siehe: <<understanding-drupal>> für weitere Informationen.
(((Entity,definition)))
[[glossary-entity]] Entität::
   Ein Element, das entweder  dem Typ <<glossary-content,Inhalt>> oder
   <<glossary-configuration,Konfiguration>> entsprechen kann. Der Begriff  wird im allgemeinen bestimmte Arten von Inhalten auf einer Website verwendet. Beispiele sind:
   <<glossary-content-item,Inhalte>>,benutzerdefinierte <<glossary-block,Blöcke>>,
   <<glossary-taxonomy-term,Taxonomiebegriffe>>, und 
   <<glossary-content-type,Inhaltstypen>>; die ersten drei genannten Elemente sind Inhaltsentitäten,und das zuletzt genannte Element ist eine Konfiguration. Siehe auch:
   <<glossary-entity-type,Entitätstyp>>,
   <<glossary-entity-subtype,Entitätssubtyp>>, und
   <<glossary-field,Feld>>. Siehe: <<planning-data-types>> für
  weitere Informationen.
(((Entity subtype,definition)))
[[glossary-entity-subtype]] Entitätssubtyp::
   Eine Gruppe von Entitäten innerhalb eines <<glossary-content,Inhalts>> bzw, eines <<glossary-entity-type,Entitätstyps>>, die sich die selben <<glossary-field,Felder>> teilen. Beispielsweise wird im Eintrag über
   <<glossary-content-item,Inhalt>> beschrieben, dass die auf der Wochenmarkt-Website verwendeten Entitätstypen Entitätssubtypen des Entitätstyps <<glossary-content-type,Inhalt>>) sind. Ein Subtyp wird auf der Website für statische Seiten verwendet, während ein anderer Subtyp dazu verwendet wird, Informationen über Lieferanten zu erfassen und auf der Website darzustellen.
   Jeder Subtyp enthält dabei seine eigenen Felder. Auch der Begriff _Bündel_ wird als Bezeichnung solcher Elemente verwendet
   (besonders in Dokumentationen für Entwickler, wo meist das englische Wort Bundle verwendet wird).
   Siehe: <<planning-data-types>> für weitere Informationen.
(((Entity type,definition)))
[[glossary-entity-type]] Entitätstyp::
   Der allgemeine Typ einer <<glossary-entity,Entität>>; im allgemeinen Sprachgebrauch wird oft nur von
   <<glossary-content,Inhalt>> gesprochen. Beispiele für Inhalte sind:
   <<glossary-content-type,Inhaltstypen>>,
   <<glossary-taxonomy-term,Taxonomiebegriffe>> und benutzerdefinierte
   <<glossary-block,Blöcke>>. Siehe: <<planning-data-types>> für weitere Informationen.
(((Field,definition)))
[[glossary-field]] Feld::
   Eine bestimmte Art Daten, die an Elemente wie
   <<glossary-content,Inhalte>> und <<glossary-entity,Entitäten>> angehängt wird. Zum Beispiel könnten Sie auf
   der Website des Wochenmarktes Felder für ein Bild, die Beschreibung eines Lieferanten und einen
   <<glossary-taxonomy-term,Taxonomiebegriff>> anlegen. Siehe
   <<planning-data-types>> für weitere Informationen.
(((Field bundle,definition)))
[[glossary-field-bundle]] Bündel::
   Synonym für <<glossary-entity-subtype,Entitätssubtyp>>.
(((Formatter,definition)))
(((Field formatter,definition)))
[[glossary-field-formatter]] Anzeigeformat eines Feldes::
   Eine <<glossary-configuration,Konfiguration>> die festlegt, wie ein <<glossary-field,Feld>> angezeigt wird. Zum Beispiel könnte ein Textfeld
   mit einem Präfix und/oder Suffix angezeigt werden, und die darin zulässigen HTML-Tags können
   eingeschränkt werden. Siehe auch: <<glossary-view-mode,Anzeigemodus>> und
   <<glossary-field-widget,Steuerelement>>. Siehe: <<structure-view-modes>> für weitere Informationen.
(((Widget,definition)))
(((Field widget,definition)))
[[glossary-field-widget]] Feldsteuerelement::
   Eine <<glossary-configuration,Konfiguration>> die festlegt, auf welche Weise jemand
   Daten in ein <<glossary-field,Feld>> eingeben oder die darin vorhandenen Daten über ein Bearbeitungsformular bearbeiten kann. Beispielsweise könnte ein Textfeld eine einzeilige Eingabemaske oder eine mehrzeilige Eingabemaske verwenden und es kann eine Einstellung für die Größe des Eingabefelds enthalten sein. Siehe auch:
   <<glossary-field-formatter,Feldsteuerelement>>. Siehe: <<structure-widgets>> für weitere Informationen.
[[glossary-formatter]] Anzeigeformat::
   Siehe: <<glossary-field-formatter,Anzeigeformat eines Feldes>>.
(((FOSS (Free and Open Source Software),definition)))
(((Free and Open Source Software (FOSS),definition)))
[[glossary-foss]] FOSS::
   Akronym für _Freie und Quelloffene Software_, d.h. Software, die von einer
   Gemeinschaft verschiedener Menschen entwickelt und unter einer nicht-kommerziellen Lizenz veröffentlicht wird. 
   Siehe auch: <<glossary-gpl,GPL>>. Siehe: <<understanding-project>> für weitere Informationen.
(((GPL (General Public License or GNU General Public License),definition)))
(((GNU General Public License,definition)))
[[glossary-gpl]] GPL::
   Akronym für die _GNU General Public License_, eine nicht-kommerzielle Software
   Lizenz. Software, die Sie von
   der Webseite https://www.drupal.org[_Drupal.org_] herunterladen können, ist unter der
   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html["GNU General Public
   License, Version 2"] lizensiert. Siehe auch: <<glossary-foss,FOSS>>. Siehe: <<understanding-gpl>> für weitere Informationen.
(((Image style,definition)))
[[glossary-image-style]] Bildstil::
   Eine Reihe von Verarbeitungsschritten, die ein Originalbild in ein neues Bild umwandeln.
Die typische Verarbeitungsmethode beinhaltet die Arbeitsschritte Skalieren und Zuschneiden. Siehe:
   <<structure-image-styles>> für weitere Informationen.
(((LAMP (Linux Apache MySQL PHP),definition)))
(((Linux Apache MySQL PHP (LAMP),definition)))
[[glossary-lamp]] LAMP::
   Akronym für _Linux, Apache, MySQL, und PHP_: die Software auf dem Webserver
   auf dem die Skripte üblicherweise ausgeführt werden (obwohl auch andere Betriebssysteme,
   Webserver und Datenbanken verwendet werden können). Siehe: <<install-requirements>> für weitere
   Informationen.
(((Log,definition)))
[[glossary-log]] Protokoll::
   Eine Liste der aufgezeichneten Ereignisse auf der Website, wie Nutzungsdaten, Leistungsdaten,
   Fehler, Warnungen und Betriebsinformationen. Siehe
   <<prevent-log>> für weitere Informationen.
(((Menu,definition)))
[[glossary-menu]] Menü::
   Eine Sammlung von Links zur Navigation auf einer Website, die hierarchisch angeordnet sein können. Siehe: <<menu-concept>> für weitere Informationen.
(((Module, definition)))
[[glossary-module]] Modul::
   Software (in der Regel PHP, JavaScript und/oder CSS), die die Funktionen der Website
   und Funktionalität hinzufügt. Drupal unterscheidet zwischen dem
   _<<glossary-drupal-core,Kernsystem>>_ und _<<glossary-contributed,von der Community bereitgestellten>>_
   Zusatzmodulen. Siehe: <<understanding-modules>> für weitere Informationen.
(((Path,definition)))
[[glossary-path]] Pfad::
   Der eindeutige, letzte Teil der internen URL, den das System einer Seite zuweist. 
   Dabei kann es sich um einen Teil der Website oder einen Teil des Verwaltungsbereichs von Drupal handeln. Die interne URL für die Seite „Über“ auf Ihrer Website könnte zum Beispiel 
   _http://example.com/node/5_ lauten. in diesem Fall währe der Pfad der Seite _node/5_. Siehe auch:
   <<glossary-alias,Alias>>. Siehe: <<content-paths>> für weitere Informationen.
(((Permission,definition)))
[[glossary-permission]] Berechtigung::
   Die Möglichkeit, eine bestimmte Aktion auf der Website durchzuführen, wie z.B. die Bearbeitung
   einer bestimmten Art von <<glossary-content,Inhalt>>, oder das Anzeigen von Benutzerprofilen.
   Siehe auch: <<glossary-role,Rolle>>. Siehe: <<user-concept>> für weitere Informationen.
(((Reference field,definition)))
[[glossary-reference-field]] Referenzfeld::
   Ein <<glossary-field,Feld>> das eine Beziehung zwischen einer
   <<glossary-entity,Entität>> und einer oder mehreren anderen Entitäten repräsentiert. Diese Entitäten können dabei vom selben <<glossary-entity-type,Entitätstyp>> sein oder einen anderen Typ aufweisen. Beispielsweise
   kann ein Rezept auf der Website des Wochenmarktes ein Referenzfeld zum Artikel über den Lieferanten enthalten der das Rezept eingereicht hat. Der Eintrag des Lieferanten wurde in diesem Fall ebenfalls als Inhalt erzeugt. 
   Felder mit <<glossary-taxonomy-term,Taxonomiebegriff>> sind ebenfalls Referenzfelder. Siehe: <<structure-reference-fields>> für weitere Informationen.
(((Region,definition)))
[[glossary-region]] Region::
   Ein bestimmter Bereich auf einer Seite in dem <<glossary-content,Inhalt>> wie eine Kopfzeile, eine Fußzeile, der Hauptiinhalt der Website, 
   die linke Seitenleiste, usw. platziert werden kann. 
   Regionen werden in <<glossary-theme,Themes>> definiert, Inhalte, die sich in diesen Regionen befinden, werden mit Hilfe von <<glossary-block,Blöcken>> dargestellt. 
   Siehe: <<block-regions>> für weitere Informationen.
(((Responsive,definition)))
[[glossary-responsive]] Responsiv::
   Eine Website oder ein <<glossary-theme,Theme>> wird als responsiv bezeichnet, wenn es sich
   an die Größe des Anzeigegeräts, des Druckers,
   oder an einen Anderen Medienausgabetyp anpassen kann. Siehe auch: <<glossary-breakpoint,Breakpoint>>. Siehe:
   <<structure-image-responsive>> für weitere Infromationen.
(((Revision,definition)))
[[glossary-revision]] Revision::
   Eine Aufzeichnung über den vergangenen oder gegenwärtigen Zustand eines bestimmten <<glossary-content,Inalts>>
   bzw. einer <<glossary-entity,Entität>>, im Verlauf der Bearbeitung. Siehe:
   <<planning-workflow>> für weitere Infromationen.
(((Role,definition)))
[[glossary-role]] Rolle::
   Eine genau bezeichnete Sammlung von <<glossary-permission,Berechtigungen>> die einem
   <<glossary-user,Benutzerkonto>> zugewiesen wird. Siehe: <<user-concept>> für weitere Informationen.
(((Security update,definition)))
[[glossary-security-update]] Sicherheitsaktualisierung::
   Eine <<glossary-update,Aktualisierung>> die einen sicherheitsrelevanten Fehler behebt, z.B. eine
Sicherheitslücke. Siehe: <<security-concept>> für weitere Informationen.
(((State,definition)))
[[glossary-state]] Status::
   Informationen vorübergehender Natur über den aktuellen Zustand Ihrer
   Website, wie z.B. die Zeit, zu der <<glossary-cron,Cron>> zum letzten mal ausgeführt wurde, usw.
   Siehe auch: <<glossary-content,Inhalt>> und
   <<glossary-configuration,Konfiguration>>.  Siehe: <<understanding-data>> für weitere Informationen.
(((Taxonomy,definition)))
[[glossary-taxonomy]] Taxonomie::
   Der Prozess der Klassifizierung von <<glossary-content,Inhalten>>. Siehe
   <<structure-taxonomy>> für weitere Informationen.
(((Taxonomy term,definition)))
[[glossary-taxonomy-term]] Taxonomiebegriff::
   Ein Begriff zur Klassifizierung von <<glossary-content,Inhalten>>, wie beisppielsweise ein Tag oder eine Kategorie. Siehe auch: <<glossary-vocabulary,Vokabular>>. Siehe:
   <<structure-taxonomy>> für weitere Informationen.
(((Text format,definition)))
[[glossary-text-format]] Textformat::
   Eine <<glossary-configuration,Konfiguration>> die festlegt, wie von Benutzern eingegebener Text verarbeitet wird, bevor dieser im Browser dargestellt wird. Dieser vorgang kann das Entfernen oder die Limitierung der HTML-Tags enthalten die verwendet werden können. Urls können über Textformate automatisch in Links umgewandelt werden. Siehe:
   <<structure-text-formats>> für weitere Informationen.
(((Theme,definition)))
[[glossary-theme]] Theme::
   Software und Asset-Dateien (Bilder, CSS, PHP-Code und/oder Vorlagen),
   die den Stil und das Layout der Website bestimmen. Das Projekt Drupal unterscheidet zwischen dem _<<glossary-drupal-core,Kernsystem>>_ und
   _<<glossary-contributed,von der Commuinty bereitgestellten>>_ Themes. Siehe: <<understanding-themes>>
   für weitere Informationen.
(((UI (User Interface),definition)))
[[glossary-ui]] UI::
   Akronym für <<glossary-user-interface,_User Interface_>>.
(((Update,definition)))
[[glossary-update]] Aktualisierung::
   Eine neuere Version der Software für Ihre Website, entweder
   <<glossary-drupal-core,Drupal-Kernsystem>> oder ein <<glossary-module,Modul>> bzw.
   <<glossary-theme,Theme>>. Siehe auch:
   <<glossary-security-update,Sicherheitsaktualisierung>>. Siehe: <<security-concept>> für weitere Informationen.
(((User,definition)))
[[glossary-user]] Benutzer::
   Eine Person, die mit der Website entweder als angemeldeter Benutzer oder als
   <<glossary-anonymous,Gast>> interagiert. Siehe: <<user-concept>> für weitere Informationen.
(((User Interface (UI),definition)))
[[glossary-user-interface]] Benutzeroberfläche::
   Der Text, die Stile und die Bilder, die auf einer Website sichtbar sind, logisch unterteilt
   in die Benutzeroberfläche, die für Besucher der Website zugänglich ist  und den Verwaltungsbereich, der nur mit entsprechender <<glossary-permission,Berechtigung>> eingesehen werden kann.
(((User one,definition)))
[[glossary-user-one]] Der erste Benutzer (User 1)::
   Das  erste <<glossary-user,Benutzer>>konto, welches bei der Installation der Website erstellt wird (und deshalb die Nummer 1 erhält). Es besitzt automatisch alle 
   <<glossary-permission,Berechtigungen>>. Dies ist auch dann der Fall, wenn dem Benutzekonto keine
   administrative <<glossary-role,Rolle>> zugewiesen wurde. Siehe: <<user-admin-account>> für weitere Informationen.
(((View,definition)))
[[glossary-view]] Ansicht::
   Eine formatierte Liste von Daten. Typischerweise beziehen Ansichten die ihnen zugrundeligenden Daten aus
   <<glossary-content,Inhalten>> bzw. <<glossary-entity,Entitäten>>. Auf der Website des Wochemarktes könnten Sie beispielsweise einen 
   <<glossary-content-item,Hauptinhalt>> für jeden Lieferanten erstellen. Sie könnten dann
   eine Ansicht erstellen, die eine Auflistungsseite generiert, die ein Miniaturbild und eine
   kurze Beschreibung jedes Lieferanten mit einem Link zu einem ganzseitigen
   Artikel über den Lieferanten ausgibt. Mit denselben Daten könnten Sie auch eine Ansicht erstellen, die einen neuen
   Block generiert, der Informationen zu den zuletzt hinzugefügten Lieferanten anzeigt.
   Siehe: <<planning-modular>> für weitere Informationen.
(((View mode,definition)))
[[glossary-view-mode]] Anzeigemodus::
   Eine Sammlung von <<glossary-field-formatter,Anzeigeformat>>
   <<glossary-configuration,Konfiguration>> für alle
   <<glossary-field,Felder>> innerhalb von <<glossary-content,Inhalten>> und
   <<glossary-entity,Entitäten>>. Einige Felder können ausgeblendet sein. Jede/r
   <<glossary-entity-subtype,Entität bzw. Subtyp>> kann eine oder mehrere Definitionen für einen Ansichtsmodus enthalten. Beispielsweise enthalten <<glossary-content-type,content types>> normalerweise
   den Ansichtsmodus _Vollständig_ und den Ansichtsmodus _Anrisstext_. Dabei enthält der Ansichtsmodus _Anrisstext_ weniger Felder als der Ansichtsmodus _Vollständig_. Siehe: <<structure-view-modes>> für weitere Informationen.
(((Vocabulary,definition)))
[[glossary-vocabulary]] Vokabular::
   Eine Gruppe von <<glossary-taxonomy-term,Taxonomiebegriffe>> aus denen gewählt werden kann wenn <<glossary-content,Inhalte>> auf eine bestimmte Art und Weise klassifiziert werden soll. Bieispielsweise so, wei die Liste aller Leiferanten des wopchenmarktes. Technisch gesheen sind Vokabulare ein
   <<glossary-entity-subtype,Entität Subtyp>> eines Taxonomiebegriffs
   <<glossary-entity-type,Entitätssubtyp>>. Siehe
   <<structure-taxonomy>> für weitere Informationen.
(((Widget,definition)))
[[glossary-widget]] Steuerelement::
   Siehe: <<glossary-field-widget,Steuerelement>>.
(((Wizard,definition)))
[[glossary-wizard]] Assistent::
   Ein Webformular, in das Sie einige Werte eingeben können und das dann etwas
   mit sinnvollen Voreinstellungen auf der Grundlage der von Ihnen gewählten Werte ausgibt. Zum Beispiel gibt es
   Assistenten für die Erstellung von <<glossary-view,Ansichten>>. Siehe   
   <<views-create>> für weitere Informationen.
(((WYSIWYG (What You See Is What You Get),definition)))
(((What You See Is What You Get (WYSIWYG),definition)))
[[glossary-wysiwyg]] WYSIWYG::
   Akronym für _What You See is What You Get_, beschreibt eine Bearbeitungsmethode für
   <<glossary-content,content>> bei der die eingabe auf dem Bearbeitungsformular dem späteren Ergebnis sehr nahe kommt. Siehe: <<structure-text-format-config>> für
   weitere Informationen.
