[[install-dev-making]]
=== Eine Entwicklungs-Website erstellen

[role="summary"]
Eine Kopie einer Live-Site für Entwicklungszwecke erstellen.

(((Development site,making)))
(((Staging site,making)))

==== Zielsetzung

Erstellen Sie die Kopie einer Website, die Sie als Entwicklungsumgebung für neue Funktionen
und zum Testen von Aktualisierungen verwenden können.

==== Erforderliche Vorkenntnisse

<<install-dev-sites>>

==== Anforderungen an die Website

* Sie haben eine fertig entwickelte Live-Website, von der Sie eine Kopie
  für Entwicklungsaufgaben erstellen wollen.

* Wenn Sie Drush zur Ausführung einiger der Arbeitsschritte dieser
  Aufgabe verwenden möchten, muss Drush installiert sein.
  Siehe: <<install-tools>>.

==== Arbeitsschritte

. Folgen Sie den Arbeitsschritten im Kapitel <<install-prepare>>, so dass Sie
  das Hosting für Ihre Entwicklungsumgebung vollständig eingerichtet haben und wissen,
  wo sich das Hauptverzeichnis Ihrer Entwicklungs-Website befindet.
  Sie haben außerdem eine leere Datenbank inklusive des dazugehörigen Datenbankbenutzers für ihre Entwicklungs-Website eingerichtet.

. Der nächste Schritt ist, eine aktuelle Kopie ihrer Datenbank anzulegen, diese beinhaltet alle Inhalte (Datensätze) ihrer Website.
Diese Datei kann sehr groß sein, aber es gibt zwei Dinge, die sie tun können, um die Dateigröße zu verringern:
+  
  * Komprimieren Sie die Datei, beispielsweise mit gzip oder einem anderen Kompressionswerkzeug.
  * Schliessen sie aus der Datenbank die Daten der Tabellen für das interne Caching-System aus, indem Sie diese leeren (Truncate). 
  Diese Daten sind temporär. Daher benötigen Sie nur die Struktur der Tabellen und nicht deren Inhalte um eine Kopie der Website anzufertigen.
+
Exportieren Sie die Datenbank Ihrer Live-Website. verwenden Sie dazu eine der folgenden Methoden:

+
  * Wenn Sie MySQL als Datenbank verwenden und auf dem Server Ihrer Live-Site
    phpMyAdmin installiert ist
    (die Software ist in vielen Hosting-Kontrollzentren verfügbar),
    leeren sie die temporären Tabellen durch das Auswählen in der phpMyAdmin-Tabellenstrukturliste und anklicken von _Empty_ am Ende der Seite. 
    Verwenden Sie danach die Registerkarte _Export_ in phpMyAdmin, um die Datenbank Ihrer
    Website im Format _SQL_ zu exportieren. Komprimieren Sie die
    ausgegebene Datei mittels _gzip_ um die Dateigröße des Exports zu verringern.
+
  * Wenn Sie MySQL benutzen und Zugriff auf die Befehlszeile haben, benutzen Sie
    folgenden Befehl (Ersetzen sie den Datenbanknahmen, den Benutzernamen und
    das Passwort mit den entsprechenden Daten Ihrer Website):
+
----
mysqldump -u'BENUTZERNAME' -p'PASSWORT' DATENBANKNAME | \ gzip > PFAD/ZUR/DATEI.sql.gz
----

  * Wenn Sie lieber Drush benutzen möchten, verwenden Sie den folgenden Befehl:
  (Die Datei enthält die Struktur der temporären Tabellen und wird mit gzip komprimiert)
+
----
drush sql:dump --gzip --structure-tables-list="cache,cache_*" \ --result-file='PFAD/ZUR/DATEI.sql.gz
----
+
* Verwenden Sie das von der Community bereitgestellte Zusatzmodul
https://www.drupal.org/project/backup_migrate[Backup and Migrate]
von Ihrer Live-Website aus. Siehe <<extend-module-install>> um Anweisungen
zur Installation von Zusatzmodulen zu erhalten.
+
Sie haben jetzt einen komprimierten Datenbank-Export in der Datei _DATEI.sql.gz_ gespeichert.
Aus Sicherheitsgründen sollten Sie es vermeiden, diese Datei auf Ihrem Hosting-Server
und vor allem im Hauptverzeichnis von Druoal abzulegen.
Diese Maßnahme verhindert, dass dritte Personen eine Kopie Ihrer Datenbank
herunterladen können.

. Kopieren Sie alle Dateien aus dem Hauptverzeichnis Ihrer Live-Website in das
Hauptverzeichnis der Installation innerhalb Ihrer Entwicklungsumgebung.
Möglicherweise möchten Sie hierfür Git verwenden. Wenn Sie Git verwenden möchten,
lesen Sie <<extend-git>>.

. Bearbeiten Sie die Datei _sites/default/settings.php_ in  Ihrer
Entwicklungsumgebung mit einem Texteditor. Suchen Sie folgende Zeilen
in der Nähe des Dateiendes. Diese enthalten Angaben zum Datenbanknamen,
zum Benutzernamen des Datenbankbenutzers und das dazugehörige Passwort.
Aktualisieren Sie diese Angaben so, dass Sie zu den Daten Ihrer
Entwicklungsumgebung passen. Die Zeilen sehen (vor der Bearbeitung) in etwa
so aus:
+
----
$databases['default']['default'] = array (
  'database' => 'live_site_datenbankname',
  'username' => 'live_site_datenbank_passwort',
  'password' => 'live_site_datenbank_passwort',
----

. Prüfen Sie, ob Ihre Datei _settings.php_ die folgende Einstellung enthält. Ist dies der Fall,
  müssen Sie diese  Einstellung so bearbeiten, dass die URL auf Ihre
  Entwicklungs-Website  anstatt auf die URL Ihrer Produktiv-Website verweist:
+
----
$settings['trusted_host_patterns']
----

. Prüfen Sie, ob in Ihrer Datei _settings.php_ die folgende Einstellung vorhanden ist, und ob sie
  auf einen zufälligen String-Wert eingestellt ist. Wenn dies nicht der Fall ist,
  müssen Sie einen zufälligen Wert hinzufügen oder die Einstellung bearbeiten, um fatale Fehler zu vermeiden:
+
----
$settings['hash_salt'] = 'any_string_value';
----

Eine Möglichkeit, eine zufällige Zeichenfolge für das Salt-Hash zu erzeugen, ist der folgende Drush
Befehl:

----
drush php-eval 'echo
  \Drupal\Component\Utility\Crypt::randomBytesBase64(55) . "\n";'
----

Wenn Sie Drush nicht verwenden, gibt es zahlreiche Websites und Anwendungen, die
Generatoren für zufällige Zeichenketten anbieten. Für den Wert der Einstellung
sollten Sie eine Zeichenkette erzeugen, die 74 Zeichen lang ist.

. Importieren Sie die Datei, die den Datenbank-Export enthält,
  in die Datenbank der Entwicklungsumgebung. Verwenden Sie dazu eine der
  folgenden Methoden:
+
  * Wenn Sie MySQL als Datenbank verwenden und der Server Ihrer Live-Site über
  PHPMyAdmin verfügt (die  Software ist in vielen Hosting-Kontrollzentren verfügbar),
  Verwenden Sie die Registerkarte _Import_ in PHPMyAdmin. Möglicherweise müssen
  Sie den Import ein paar mal wiederholen, wenn es sich um eine sehr große
  Datenbank handelt.

  * Wenn Sie MySQL benutzen und Zugriff auf die Kommandozeile Ihres Web-Servers
  haben, benutzen Sie folgenden Befehl
  (ersetzen Sie dabei DATENBANKNAME, BENUTZERNAME und PASSWORT durch die  für
  Ihre Website gültigen Daten. Wenn Sie eine gzip-komprimierte Sicherungskopie
  erstellt haben, müssen Sie diese zunächst entpacken:
+
----
gunzip < PFAD/TO/DATEINAME.sql.gz | \
mysql -u'BENUTZERNAME' -p'PASSWORT' DATENBANKNAME < DATEINAME.sql
----
+
  * Wenn Sie lieber Drush verwenden möchten, verwenden Sie diesen Befehl:
+
----
drush sql:query --file=PFAD/TO/DATEINAME.sql.gz
----

. Wenn Ihre Entwicklungs- und Live-Websites unterschiedliche Konfigurationen
aufweisen müssen, dann verwenden Sie Konfigurationsüberschreibungen in der Datei _settings.php_ . 
Die _$config_-Variable hilft Ihnen, die Überschreibungswerte getrennt von den Standardkonfigurationsdaten zu verwalten.
Beispielsweise könnte der Name der Website in der Produktivumgebung bzw. auf der (Live)-Website „Anytown Farmers Market"  lauten. In der
Entwicklungsumgebung aber soll er „Arbeitsversion der Website des Wochenmarktes"
lauten. Um das zu erreichen, könnten Sie diese Einstellung der Live-Website in der Datenbank
(Standardkonfiguration) anlegen und auf der
Website in der Entwicklungsumgebung, in der Datei settings.php, mit
folgendem Eintrag übersteuern:
+
----
$config['system.site']['name'] = "Arbeitsversion der Website des Wochenmarktes";
----

==== Vertiefen Sie Wissen

* Überprüfen Sie, ob die Website in Ihrer Entwicklungsumgebung korrekt
funktioniert.

* Melden Sie sich bei der Website in der Entwicklungsumgebung als Administrator
an und leeren Sie den Cache.

Siehe:

* <<prevent-cache-clear>>.

* <<extend-deploy>>

* <<extend-git>>

// ==== Verwandte Konzepte

==== Videos

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/FSBNm4oAkaA[title="Eine Entwicklungs-Website einrichten (englisch)"]

==== Zusätzliche Ressourcen

* https://www.drupal.org/docs/7/backing-up-and-migrating-a-site/backing-up-a-site[_Drupal.org_ Community-Dokumentationsseite „Sichern einer Website (englisch)"]
* https://www.drupal.org/docs/develop/local-server-setup/how-to-create-a-test-site[_Drupal.org_ Community-Dokumentationsseite „Erstellen einer Testsite (englisch)"]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
https://www.drupal.org/u/eojthebrave[Joe Shindelar] bei
https://drupalize.me[Drupalize.Me], und
https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle].
Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
