[[install-prepare]]
=== Vorbereiten der Installation

[role="summary"]
Das Kernsystem herunterladen und die Systemvoraussetzungen erfüllen.

(((Downloading,core software)))
(((Drupal core,preparing install)))

==== Zielsetzung

Laden Sie das Kernsystem herunter und kümmern Sie sich darum,
dass alle erforderlichen Systemvoraussetzungen erfüllt sind.

==== Erforderliche Vorkenntnisse

* <<install-requirements>>

* <<install-tools>>

* <<install-decide>>

* Wie man Server-Software installiert und konfiguriert (falls Sie die Installation selbst vornehmen)

* Wie man das Hosting einer Website im allgemeinen einrichtet

* Wie man eine Datenbank erstellt

==== Anforderungen an die Website

Die Server-Software muss auf dem Computer installiert sein, auf dem Sie Ihre
Website entwickeln. Siehe <<install-requirements>>.

Je nachdem, wie Sie das Kernsystem herunterladen möchten, müssen Sie
möglicherweise  zunächst zusätzliche Software-Tools installieren.

Siehe: <<install-decide>> und <<install-tools>>.

==== Arbeitsschritte

. Wählen Sie eine der Methoden zum Herunterladen und Installieren
des Kernsystems aus, die im Kapitel <<install-decide>> aufgelistet sind.
Der Rest dieser Anweisungen gilt für den Download mittels Composer, die manuelle
Installation und das interaktive Installationsprogramm gleichermaßen.

. Richten Sie eine URL und ein Hosting für Ihre Website auf dem Server ein.
Überprüfen Sie, ob das Hosting funktioniert, indem Sie eine einfache HTML-Datei im
Stammverzeichnis Ihres Webservers platzieren und testen, ob diese den Besuchern
Ihrer Website angezeigt wird.

. Erstellen Sie eine Datenbank und ein dazugehöriges Benutzerkonto, dass über
Vollzugriff auf die Datenbank verfügt.

. Laden Sie die Dateien des Kernsystems in das Hauptverzeichnis Ihrer Website,
indem Sie die von Ihnen gewünschte Methode verwenden.
Siehe: <<install-decide>>  für weitere Informationen.

==== Vertiefen Sie Ihr Wissen

Siehe: <<install-run>> um das interaktive Installationsprogramm auszuführen.

Alternativ können Sie den folgenden Drush-Befehl in dem
Verzeichnis ausführen, in das Sie die Software heruntergeladen haben, wobei
_DATENBANKKNAME_, _DATENBANKBENUTZER_ und _DATENBANKPASSWORT_ durch die
Zugangsdaten zu Ihrer Datenbank ersetzt werden müssen:

----
drush site:install standard --db-url='mysql://DATENBNAKBENUTZER:DATENBANKPASSWORT@localhost/DATENBANKNAME' --site-name=Meine-Website
----

// ==== Verwandte Konzepte

==== Videos

// Video von Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/7Aib3y9DM80[title="Die Installation vorbereiten (englisch)"]

==== Zusätzliche Ressourcen

http://www.drush.org[Drush (englisch)]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] bei
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
und https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[RedCrackle].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
