[[install-requirements]]

=== Konzept: Systemvoraussetzungen an den Server

[role="summary"]
Überblick über die Systemanforderungen an den Webserver zum Betrieb des Kernsystems.

(((Installation requirements,overview)))
(((Installation requirements,disk space)))
(((Installation requirements,web server)))
(((Installation requirements,database)))
(((Installation requirements,PHP programming language)))
(((Installing,core software)))
(((Core software,installation requirements)))
(((Disk space,installation requirements)))
(((Web server,installation requirements)))
(((Apache web server,version requirements)))
(((Nginx web server,version requirements)))
(((Microsoft IIS web server,version requirements)))
(((Database,installation requirements)))
(((MySQL database,version requirements)))
(((PostgreSQL database,version requirements)))
(((SQLight database,version requirements)))
(((PHP programming language,version requirements)))

// ==== Erforderliche Vorkenntnisse

==== Was sind die Voraussetzungen für den Betrieb des Kernsystems?

===== Festplattenspeicherplatz

Die Gesamtmenge des für Ihre Website benötigten Speicherplatzes
ist keine feste Größe. Der Benötigte Speicherplatz hängt von Ihrer Website ab.
Die Basisdateien des Kernsystems nehmen etwa 100 MB Speicherplatz
auf dem Webserver in Anspruch. Weiterer Speicherplatz wird benötigt, sobald Sie
zusätzliche Module oder Themes installieren. Außerdem wird Speicherplatz auch
für Mediendateien (Bilder, Videos), Backups und andere Dateien benötigt, die
von  Ihnen und anderen Benutzern auf Ihre Website hochgeladen werden.
Die Datenbank benötigt ebenfalls Festplattenspeicherplatz, obwohl diese
sich typischerweise nicht am gleichen Ort, wie die eigentliche Website
(und in einigen Fällen nicht einmal auf dem gleichen
Server) befindet.

===== PHP

PHP 7.3 oder höher. PHP muss mindestens 64 MB Arbeitsspeicher
zur Verfügung stehen. Wenn Sie
mehrere Module auf Ihrer Website ausführen oder speicherintensive PHP-basierte
Kommandozeilen-Tools (wie Composer) verwenden, wird wesentlich mehr
Arbeitsspeicher für PHP benötigt.

Bestimmte PHP-Erweiterungen sind ebenfalls erforderlich. die vollständige Liste
der erforderlichen PHP-Erweiterungen hängt davon ab, wie Sie das  Kernsystem
installieren und welche Module Sie auf Ihrer Website verwenden. Im Allgemeinen
sind bei Hosting-Service-Providern alle PHP-Erweiterungen, die Sie benötigen,
um Drupal verwenden zu können vorinstalliert. Wenn Sie Ihre Website selbst
hosten oder auf Ihrem lokalen Computer betreiben, erhalten Sie während der
Installation gegebenenfalls Fehlermeldungen die darauf hinweisen, dass
erforderliche PHP-Erweiterungen fehlen damit Sie diese Installieren und die
Installation von Drupal fortsetzen können.

===== Web-Server

Apache (empfohlen)::
  Apache ist der am häufigsten verwendete Webserver. Die Kernsoftware funktioniert auf
Apache 2.4.7 oder höher, die auf UNIX/Linux, OS X oder Windows gehostet werden und auf denen das
Apache mod_rewrite Modul installiert und aktiviert ist. Die Apache VirtualHost
Konfiguration muss die Anweisung AllowOverride All enthalten, damit die
.htaccess-Datei verwendet werden kann.

Lokaler PHP-Server::
  Sie können vorübergehend eine lokale Demo-Website auf Ihrem Computer
  installieren, die den in PHP eingebauten Webserver verwendet,
  damit zur Evaluierung von Drupal kein zusätzlicher Webserver installiert
  werden muss.

Nginx::
  Nginx ist ein weit verbreiteter Webserver, der sich auf hohe Gleichzeitigkeit,
Leistung und geringen Speicherverbrauch konzentriert. Das Kernsystem läuft auf Nginx 0.7 oder höher
oder höher, die auf UNIX/Linux, OS X oder Windows gehostet wird. Das ngx_http_rewrite_module
muss installiert und aktiviert sein.

Microsoft IIS::
  Microsoft IIS ist ein Webserver und ein Satz von Funktionserweiterungsmodulen
  zur Verwendung mit Microsoft Windows. Die Kernsoftware arbeitet mit IIS 5,
  IIS 6 oder IIS 7, wenn PHP korrekt konfiguriert ist. Da lesbare URLs
  erforderlich sind, könnte es sein, dass Sie ein Produkt eines Drittanbieters
  verwenden müssen. Für IIS 7 können Sie das Microsoft-URL
  Rewrite-Modul oder die Lösung eines Drittanbieters verwenden.

===== Datenbank

Verwenden Sie eine der folgenden Datenbanken:

* MySQL - 5.7.8 (MariaDB 5.5.20, Percona 5.5.8) oder höher mit einer
InnoDB-kompatiblen Primärspeicher-Engine

* PostgreSQL - 10.0 oder höher mit der pg_trgm Erweiterung

* SQLite - 3.26 oder höher. Temporäre lokale Demo-Websites verwenden SQLite,
das als Teil von PHP ausgeliefert wird und keine Installation einer separaten
Datenbank-Software erfordert.

//===== Verwandte Themen

==== Zusätzliche Ressourcen

* https://www.drupal.org/docs/8/system-requirements[_Drupal.org_ Community-Dokumentationsseite „Systemanforderungen“ (englisch)]
* https://secure.php.net/manual/en/configuration.php[PHP-Laufzeitkonfiguration (PHP-Speicherlimit und andere Einstellungen) (englisch)]


*Mitwirkende*

Bearbeitet von https://www.drupal.org/u/KarlKedrovsky[Karl Kedrovsky],
https://www.drupal.org/u/bemery987[Brian Emery], und
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] entnommen aus
https://www.drupal.org/docs/8/system-requirements["Systemvoraussetzungen (englisch)"],
copyright 2000 - copyright_upper_year liegt bei den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Comunity].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
