[[language-concept]]

=== Konzept: Übersetzung der Benutzeroberfläche, der Konfiguration und von Inhalten

[role="summary"]
Übersicht der Sprachen und Übersetzungen auf einer Website.

(((User interface,translating)))
(((Configuration,translating)))
(((Content,translating)))
(((Translating,overview)))
(((Languages,overview)))
(((Module,Language)))
(((Module,Content Translation)))
(((Module,Configuration Translation)))
(((Module,Interface Translation)))
(((Content Translation module,overview)))
(((Configuration Translation module,overview)))
(((Interface Translation module,overview)))
(((Language module,overview)))

==== Vorausgesetztes Wissen

* <<understanding-data>>
* <<understanding-modules>>
* <<planning-data-types>>

==== Welche Sprachen unterstützt die Software?

Die Basissprache der Software, mit der Ihre Website betrieben wird
(Kernsystem, Module, und Themes) ist Englisch. Mit dieser Software können Sie
jedoch eine Website erstellen, deren Standardsprache eine andere Sprache als
Englisch ist. In diesem Fall sollte jeder, der die Website besucht
nur diese Sprache sehen (immer vorausgesetzt die Website ist vollständig in die jeweilige Sprache übersetzt).
Sie können diese Software auch verwenden, um eine mehrsprachige Website mit einer
Funktion zum Umschalten der Anzeigesprache zu erstellen,
mit der Besucher die Website in ihrer bevorzugten Sprache ausgeben lassen können.
Sie müssen das mit dem Kernsystem ausgelieferte Modul Language installiert haben,
damit Ihre Website eine andere Sprache als Englisch verwenden kann.

==== Was kann auf Ihrer Website übersetzt werden?

Es gibt drei Arten von Informationen, die Sie übersetzen können,
jede dieser Informationsarten muss mit einer anderen Methode übersetzt werden.

Text der Benutzeroberfläche::
  Mit der Software ausgelieferter Text, der im Kernsystem, den Modulen und in
  Themes vorhanden ist. Diese Art von Text kann
  aus dem englischen, also aus der Basissprache der Software heraus in die Sprache
  übersetzt werden, die Ihre Website normalerweise verwendet (Standardsprache).
  Im Regelfall müssen Sie diesen Text nicht selbst übersetzen.
  Sie können die  Übersetzung der Benutzeroberfläche stattdessen einfach
  herunterladen. Sie benötigen dazu nur das Modul User Interface Translation,
  das mit dem Kernsystem ausgeliefert wird.
  Installieren Sie die Module User Interface Translation und Update Manager,
  um Übersetzungen für die Benutzeroberfläche herunterladen zu können.

Text der Konfiguration::
  Hierbei handelt es sich um Text, dessen Struktur- und Ausgangswerte durch das
  Kernsystem und von Modulen und Themes vordefiniert werden.
  Texte, die sich innerhalb der Konfiguration befinden können jedoch bearbeitet
  und an die Anforderungen Ihrer Website angepasst werden.
  Beispiele für Texte, die aus der Konfiguration stammen sind die Bezeichnungen,
  der Felder innerhalb Ihrer Inhaltstypen, die Texte von Kopfzeilen
  vordefinierter Ansichten, der Name Ihrer Website und die Inhalte der
  automatischen E-Mails, die in Zusammenhang mit den Ereignissen rund um
  Benutzerkonten versendet werden. Nach dem Erstellen eines
  Konfigurationstextes in Ihrer Standardsprache, können Sie den Text in
  andere Sprachen übersetzen. Für die vom Kernsystem ausgelieferte
  Standardkonfiguration, die Konfiguration von Modulen und Themes, sind die
  Ausgangswerte im Download der Übersetzung der Benutzeroberfläche enthalten.
  Sie müssen das mit dem Kernsystem ausgelieferte Modul Configuration
  Translation installieren um diese Texte übersetzen zu können.

Inhaltliche Texte und Dateien::
  Wenn Ihre Website mehrsprachig ist, können Sie die Felder, die die Inhalte
  Ihrer Website enthalten so konfigurieren, dass die darin enthaltenen Inhalte
  in alle für Ihre Website notwendigen Sprachen übersetzt werden können.
  Nachdem Sie Inhalte in einer Ausgangssprache übersetzt haben, können Sie diese
  dann in andere Sprachen übersetzen. Felder können Textinformationen oder
  hochgeladene Dateien enthalten und für jedes Feld in jedem Inhaltstyp können
  Sie über die Konfiguration festlegen, ob der Inhalt eines Feldes übersetzt
  werden können soll, oder nicht. Um Inhalte übersetzbar machen zu können müssen
  Sie das Modul Content Translation installieren, dass mit dem Kernsystem
  ausgeliefert wird.

==== Welche Informationen werden auf der Website englisch bleiben?

Selbst wenn die Standardsprache Ihrer Website nicht Englisch ist, sehen Sie
englische Texte auf bestimmten Seiten im Verwaltungsbereich, die zur Verwaltung
der Konfiguration verwendet werden. Der Grund hierfür ist, dass Sie beim
Bearbeiten der Konfiguration die Ausgangswerte bearbeiten, bei denen es sich um
nicht übersetzte Werte handelt. Das Übersetzen der Konfiguration ist eine separate
Aufgabe. Wenn Sie zum Beispiel die Seite _Menüs_ aufrufen, werden Sie
Menünamen in Englisch (für die Menüs, die bei der Installation
Ihrer Website eingerichtet wurden) sehen können. Wenn Sie auf den Link
 _Menü Bearbeiten_ klicken, bearbeiten Sie den englischen Namen und
 die englische Beschreibung, des Menüs, wenn keine Übersetzung für den
 entsprechenden Ausgangswert in Ihrer Sprache vorliegt. Um Menünamen in einer
 anderen Sprache bearbeiten zu können müssen Sie das mit dem Kernsystem
 ausgelieferte Modul Configuration Translation installieren und den Link
 _Übersetzen_ verwenden, um Übersetzung der Menüinformationen zu bearbeiten.

==== Verwandte Themen


* <<language-add>>
* <<language-content-config>>
* <<language-content-translate>>
* <<language-config-translate>>

//===== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
