[[menu-concept]]

=== Konzept: Menüs

[role="summary"]
Übersicht über das Menükonzept und die mit dem Standardprofil des Kernsystems automatisch erstellten Menüs.

(((Menu,overview)))
(((Menu,main)))
(((Menu,administrative)))
(((Menu,user account)))
(((Menu,footer)))
(((Menu,custom)))
(((Administrative menu,overview)))
(((User account menu,overview)))
(((Footer menu,overview)))
(((Custom menu,overview)))

// ==== Erforderliche Vorkenntnisse

==== Was ist ein Menü?

Menüs sind eine Sammlung von Links (Menüpunkten), die zum Navigieren auf einer Website verwendet werden. Die
Kernmodul der Menü-Benutzeroberfläche bietet eine Schnittstelle zur Steuerung und Anpassung des Menüs
System. Menüs werden in erster Linie als hierarchische Linkliste angezeigt. Über
Standardmäßig werden neue Menüpunkte innerhalb eines integrierten Menüs mit der
Bezeichnung _Hautnavigation_, aber Administratoren können auch benutzerdefinierte
Menüs erstellen.

Das Kerninstallationsprofil Standard, das mit dem Kernsystem ausgeliefert wird,
enthält fünf Menüs:

Hauptnavigation::
  Links zu Abschnitten, die für Besucher der Website bestimmt sind. Sie werden normalerweise von Site
  Administratoren.

Verwalten::
  Links zu administrativen Aufgaben. Dieses Menü enthält hauptsächlich Links, die von
  Module auf Ihrer Website.

Menü Benutzermenü::
  Links zu den mit dem Benutzerkonto verbundenen Aufgaben wie _Mein Konto_ und _Protokoll
  aus_.

Fußzeile::
  Links zu wichtigen Seiten innerhalb der Website, die für die Fußzeile bestimmt sind. Sie sind
  in der Regel von Site-Administratoren erstellt.

Werkzeuge::
  Links zu Aufgaben, die für Website-Besucher notwendig sind. Einige Module enthalten ihre Links
  hier.

Über die Menüverwaltung können Sie die Menüs auf folgende Weise anpassen
Funktionalität:

* Erstellen neuer benutzerdefinierter Menüs.

* Hinzufügen neuer Menüpunkte.

* Neuordnung von Menüeinträgen durch Einstellen ihres "Gewichts" oder durch Ziehen in
Ort.

* Umbenennen von Menüpunkten.

* Ändern des Linktitels und des  Tooltips (der angezeigt wird, wenn Sie mit der
Maus über einen Menüpunkt fahren).

* Verschieben eines Menüeintrags in ein anderes Menü durch Bearbeiten seiner _Parent_-Eigenschaft.

Ein Menüeintrag wird einem Besucher nur dann angezeigt, wenn er die Rechte hat, die
Seite, auf die sie verlinkt. Zum Beispiel wird der Admin-Menüpunkt nicht für Besucher angezeigt, die
sind nicht eingeloggt.

==== Verwandte Themen

* <<menu-link-from-content>>

* <<menu-reorder>>

* Um ein Menü anzuzeigen, müssen Sie den Block platzieren, der dem
Menü in einer Region Ihres Themas; siehe <<block-concept>>, <<block-regions>>, und
<<block-place>>. Standardinstallationsprofil des Kernsystems platziert alle
definierten Menüs, außer dem Menü Verwaltung, in den Abschnitten des Themes Bartik.
Das Theme des Kernsystems zeigt das Menü Verwalten über das Menü Toolbar an,
das mit dem Kernsystem ausgeliefert und über das Installationsprofil Standard
installiert wird. Das Menü Verwalten wird auch  vom von der Community
bereitgestellten Zusatzmodul Admin Toolbar angezeigt.

//==== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/ajayvi[Ajay Viswambharan],
https://www.drupal.org/u/jojyja[Jojy Alphonso] unter
http://redcrackle.com[Rotes Knistern],
und https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
