[[planning-modular]]
=== Konzept: Modularer Inhalt

[role="summary"]
Überblick über modulare Inhalte und wie der Inhalte einer Website aus anderen Quellen bezogen werden kann.

(((Content,modular)))
(((Modular content,overview)))
(((Page,composite)))
(((Composite page,creating with modular content)))
(((View,and modular content)))
(((Views module,overview)))

==== Erforderliche Vorkenntnisse

* <<planning-data-types>>
* <<planning-layout>>

==== Was sind modulare Inhalte?

Da die Inhalte Ihrer Website in einer Datenbank gespeichert sind, ist es wünschenswert
Inhalte _modular_ anzulegen, d.h. definierte Seiten auf Ihrer Website zu erstellen, anstatt
die Website als Ganzes bearbeiten zu müssen. Die Seiten der Website werden dann
aus mehreren Inhaltselementen zusammengesetzt. Im Szenario der Wochenmarktwebsite
könnten Sie zum Beispiel einzelne Inhaltselemente für Rezepte anlegen.
Wenn die einzelnen Zutaten eines Rezeptes in einem Feld abgespeichert werden,
kann die Zutatenliste eines einzelnen Rezeptes aus diesen Zutaten zusammengesetzt werden.
Ihre Website kann auch eine Seite enthalten, auf der man Rezepte mittels der Zutaten suchen
kann, die man auf dem Wochenmarkt gekauft hat.

Kleinere Seitenabschnitte können ebenfalls aus verschiedenen Inhaltselementen zusammengesetzt werden.
Rezepte können Beispielsweise ein Feld enthalten, das Auskunft darüber gibt, welcher
Lieferant das Rezept eingereicht hat (siehe: <<structure-reference-fields>>).
So können die Details zum jeweiligen Lieferanten in separaten
Inhaltselementen bearbeitet werden. So ist es Ihnen möglich,
folgendes auf Ihrer Website umzusetzen:

* Auf jedem Rezept kann es einen Abschnitt geben, der einige Informationen
über den Lieferanten anzeigt, der das Rezept eingereicht hat, wie z.B. dessen
Name und die Nummer seines Marktstandes.

* Jede Lieferantenseite kann einen Abschnitt enthalten, in dem die Rezepte
  aufgelistet werden, die der Lieferant eingereicht hat.

Der Gedanke dahinter ist, dass jede Information nur an einer Stelle auf der
Website bearbeitet wird. Wenn Lieferanteninformationen geändert werden,
werden diese Informationen auf allen Rezepten des jeweiligen Lieferanten
aktualisiert angezeigt, nachdem Sie nur an einer Stelle auf der Website
aktualisiert wurden. Wird ein neues Rezept von einem Lieferanten eingereicht,
werden die Informationen zum Lieferanten automatisch auf dem neu eingestellten
Rezept angezeigt, ohne dass diese auf der Rezeptseite selbst manuell
eingetragen werden müssen. Das Modul Views, das mit dem Kernsystem ausgeliefert
wird, ist das Modul, das üblicherweise verwendet wird, um modulare Inhalte zu
Seitenabschnitten oder vollständigen Webseiten zusammenzusetzen.
Siehe: <<views-concept>> für weitere Informationen. Außerdem sind
_Ansichtsmodi_ nützlich um unterschiedliche  Anzeigearten für den selben Inhalt
zu definieren. Siehe: <<structure-view-modes>> für weitere Informationen.

==== Verwandte Themen

* <<planning-structure>>
* <<structure-content-type>>
* <<structure-fields>>
* <<structure-reference-fields>>
* <<structure-view-modes>>
* <<views-concept>>

// ==== Weiterführende Quellen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
