[[planning-workflow]]

=== Konzept: Redaktionelle Arbeitsabläufe

[role="summary"]
Überblick über redaktionelle Arbeitsabläufe zur Verwaltung von Inhalten auf einer Website.

(((Editorial Workflow,overview)))
(((Published flag,overview)))
(((Unpublished flag,overview)))
(((Revision,overview)))

==== Vorausgesetztes Wissen

* <<understanding-drupal>>
* <<planning-data-types>>

==== Was ist ein redaktioneller Arbeitsablauf?

Ein _Redaktions-Workflow_ ist der Prozess, den Organisationen zur Erstellung Bearbeitung, Veröfentlichung und Überprüfung  von Inhalten befolgen,
Mehrere Personen in verschiedenen Positionen innerhalb einer Organisation können an diesem Prozess beteiligt sein. Autoren könnten zum Beispiel
Informationen sammeln und Inhalte verfassen. Redakteure könnten Informationen überprüfen, bearbeiten und die Inhalte nach Abschluss eventueller Korrekturarbeiten veröffentlichen. Später könnten inhaltliche Überarbeitungen mittels eines schlankeren Prozesses durchgeführt werden, um kleinere Anpassungen überprüfbar zu machen. Es kann auch ein SDeperater Prozess für größere Änderungen festgelegt werden, damit diese nach der Aktualisierung erneut veröffentlicht  werden können.

==== Welche Werkzeuge stehen zur Implementierung von Arbeitsabläufen zur Verfügung?

Status veröffentlicht/nicht veröffentlicht::
  Der Entitätstyp Inhalt unterstützt die Kennzeichnung aller Inhalte als
  Veröffentlicht oder nicht veröffentlicht. Anzeigeberechtigungen für veröffentlichte und nicht
  veröffentlichte Inhalte  sind voneinander getrennt; zum Beispiel könnten alle Besucher der Website in der Lage sein
  veröffentlichte Inhalte anzuzeigen, während nur Autoren und Redakteure nicht oder noch nicht veröffentlichte Inhalte sehen können.
Änderungsverfolgung mittels Revisionierung::
  Einige Entitätstypen unterstützen die Revisionierung, d.h. wenn Inhalt
  überarbeitet wird, speichert die Software die älteren Revisionen, so dass Inhaltsversionen verglichen und Änderungen zurückgesetzt werden können.
Arbeitsabläufe::
  Mit dem Modul  Workflow, dass mit dem Kernsystem ausgeliefert wird, können Sie Zustände und Übergänge innerhalb eines Arbeitsablaufes definieren,
  Die Möglichkeiten gehen dabei über das bloße Veröffentlichen oder depublizieren von Inhalten hinaus. Die Funktionalität für Arbeitsabläufe wird durch das mit dem Kernsystem ausgelieferte Modul Content Moderation ergänzt, mit dem Sie Berechtigungen und Rollen für Übergänge innerhalb von Arbeitsabläufen festlegen können.
  Beide Module können sowohl für Inhalte als auch für benutzerdefinierte Blöcke verwendet werden.
Platzierung von Blöcken::
  Mit der Inhaltsentität „Benutzerdefinierter Block” können Sie einen benutzerdefinierten Block
  erstellen und bearbeiten und erst dann auf der Website veröffentlichen, wenn der Blockinhalt
  fertig erstellt wurde.

==== Verwandte Themen


* <<content-create>>
* <<content-edit>>
* <<block-create-custom>>
* <<block-place>>

// ==== Weiterführende Quellen

*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/dianalakatos[Diána Lakatos] bei
https://pronovix.com//[Pronovix],
https://www.drupal.org/u/gdunham[Grant Dunham],
und https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
