[[preface-organization]]
=== Organisation

[role="summary"]
Die Struktur dieses Handbuchs verstehen, um besser durch die Themen des Handbuchs navigieren zu können.

Dieses Benutzerhandbuch enthält eine Reihe von Themen, von denen jedes entweder
eine _Arbeitsaufgabe_ (wie man etwas tut) oder ein _Konzept_ (Hintergrundwissen,
Terminologie und dergleichen) enthält. Konzeptthemen haben Namen, die mit
_Konzept:_ beginnen, während Themen, die Aufgaben enthalten Namen besitzen, die
Verben enthalten. z. B. _Grundlegende Informationen der Website bearbeiten_.

Die Themen sind in einer logischen Reihenfolge angeordnet und in Kapitel
unterteilt. Außerdem sind die Konzepte und Aufgaben verzahnt, so dass Konzepte
vor verwandten Aufgaben präsentiert werden und die Aufgaben aufeinander
aufbauen. Um dies bestens nutzen zu können, sollten Sie das gesamte Handbuch in
der vorgegebenen Reihenfolge lesen, wobei  Sie Themen, die für Sie nicht von
Interesse sind oder die Ihnen bereits bekannte Informationen enthalten,
möglicherweise überspringen können. Denken Sie daran, die Aufgaben auf
Ihrer Website auszuprobieren,
während Sie das Handbuch lesen. Die meisten Menschen lernen besser, indem Sie
etwas selbst tun, als es nur zu lesen.

Wenn Sie möchten, können Sie auch den Index oder das Inhaltsverzeichnis
verwenden, um direkt zu einem Thema zu springen, über das Sie gerne mehr
erfahren möchten, anstatt das gesamte Handbuch durch zu arbeiten.
Um diesen Ansatz zu erleichtern, sind zu jedem Thema die erforderlichen
Vorkenntnisse (mit Links zu den Themen, die
dieses Wissen aufbereiten) aufgeführt. Alle Aufgabenthemen führen außerdem auch
die _Anforderungen an die Website_ (Dinge, die
Sie auf Ihrer Website konfiguriert oder erstellt haben müssen, um
die Aufgabe ausführen zu können) auf. Des weiteren haben die meisten Themen am
Ende Abschnitte, in denen Sie verwandte Themen und/oder Aufgaben zum vertiefen
Ihrer Kenntnisse finden, damit Sie noch mehr lernen können.

Vielleicht möchten Sie sich auch den Abschnitt <<glossary>> ansehen, während Sie
Das Benutzerhandbuch durchlesen. Dieser Abschnitt enthält
kurze Definitionen der meisten im Handbuch verwendeten Begriffe, mit Links zu
Themen die eine ausführliche Erklärung des jeweiligen Begriffs enthalten.


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Übersetzt und bearbeitet von https://www.drupal.org/u/joachim-namyslo[Joachim Namyslo].
