[[preface-audience]]

=== Zielgruppe und Zielsetzung

[role="summary"]
Die Zielgruppe dieses Handbuchs verstehen und was Sie daraus lernen können

Dieses Handbuch wurde hauptsächlich für Personen mit minimalen Kenntnissen über das CMS-System Drupal erstellt.
Die Themen werden ihnen helfen, sich Kenntnisse in den Bereichen
Installieren, Verwalten und Aufbauen und/oder Warten von Inhalten einer
Drupal-basierte Website zu erweitern. Das Handbuch richtet sich auch an Personen, die bereits einige
Erfahrung mit einer aktuellen oder früheren Version von Drupal besitzen und ihre Fähigkeiten und Kenntnisse
zu erweitern oder diese auf den neuesten Stand bringen möchten.

Dieses Handbuch geht davon aus, dass Sie sich bereits entschieden haben Drupal lernen und anwenden zu wollen.
Wenn Sie erst mehr über Drupal erfahren möchten, bevor Sie sich für Drupal entscheiden lesen Sie:
<<understanding-drupal>>.

Je nachdem, welche Aspekte von Drupal Sie lernen möchten, benötigen Sie einiges an
Hintergrundwissen zum Verständnis dieses Handbuchs: Allgemeine Internetkenntnisse werden vorausgesetzt.
Das Handbuch selbst konzentriert sich eher auf die Verwendung der Software Drupal
selbst. Der abschnitt über die Installation von Drupal auf einem Webserver setzt beispielsweise voraus, dass Sie wissen,
wie sie einen Webserver für Ihr Projekt auswählen ud wie Sie Daten auf diesen Webserver übertragen können.
In ähnlicher Weise gehen die Abschnitte über Content Management davon aus, dass Sie
wissen, wie Sie sich auf Webseiten anmelden und Webformulare ausfüllen können.

Nachdem Sie dieses Handbuch gelesen haben, können Sie folgendes:

* Die Inhaltsarchitektur für eine Drupal-basierte Website planen.

* Die Website zusammensetzen, die Sie geplant haben.

* Ihre Website verwalten und administrieren.

* Dokumentationen und Blog-Beiträge zu hier nicht behandelten Themen verstehen, um
Ihr Wissen und Ihre Fähigkeiten zu erweitern

* Mit der globalen Drupal-Community in Kontakt treten.


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
