[[preface-scenario]]
=== Szenario des Handbuchs

[role="summary"]
Das in diesem Handbuch verwendete Szenario begreifen,
um die behandelten Themen besser zu verstehen.

(((Szenario diese Handbuchs (Wochenmarkt),Überblick)))
(((Durch das Handbuch leitende Szenario (Wochenmark))))
(((Anwendungsbeispiel für dieses Handbuch (Wochenmarkt))))
(((Wochenmarkt,Anwendungsfall in diesem Handbuch)))

Beim Lesen dieses Handbuchs ist es hilfreich, eine Website vor dem geistigen
Auge zu haben, die Sie erstellen möchten.
Das folgende Projektszenario liefert den Kontext und verbindet
die Beispiele in diesem Handbuch miteinander:

Sie erstellen eine Website für einen Wochenmarkt. Die Website wird am Ende des Handbuches folgendes
anzeigen:

* Informationen über den Standort und die Öffnungszeiten des Wochenmarktes.

* Eine „Über uns“-Seite, die die Geschichte des Wochenmarktes erzählt.

* Außerdem müssen die Lieferanten aufgelistet werden.

* Die Lieferanten sollten außerdem in der Lage sein,
  ihre Firmeninformationen (einschließlich eines Logos oder Fotos) und Rezepte
  zu veröffentlichen.

* Website-Besucher sollten in der Lage sein, Rezepte zu durchsuchen oder Rezepte
  zu finden die bestimmte Zutaten enthalten. die sie auf dem Wochenmarkt gekauft
  haben.

* Einige Besucher Ihrer Website sprechen eine andere Sprache, so dass die
  Seiten, die den Hauptinhalt enthalten und die Seiten, über die Lieferanten
  Informationen erfassen können übersetzt werden müssen.

Wenn Sie das Handbuch durchlesen und die darin beschriebenen Aufgaben
ausprobieren, können Sie die im Szenario beschriebene Website genau nachbauen.
Sie könnten die Arbeitsaufgaben auch an Ihre eigenen Zwecke anpassen.
Wenn Sie das Szenario exakt nachbauen wollen, benötigen Sie dazu einige
Bilddateien. Diese sind im Verzeichnis _Assets_ in der
_.zip_ oder _.tgz_ Datei auf der
https://www.drupal.org/project/user_guide[Projektseite des Benutzerhandbuchs]
verfügbar.

*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
