[[preface-audience]]

=== Zielgruppe und Zielsetzung

[role="summary"]
Die Zielgruppe dieses Handbuchs verstehen und was Sie daraus lernen können

Dieses Handbuch wurde hauptsächlich für Menschen geschrieben, die über keine
oder nur minimale Kenntnisse im Umgang mit dem CMS-System Drupal verfügen.
Die Themen in diesem Handbuch werden Ihnen dabei helfen, sich Kenntnisse in
folgenden Bereichen anzueignen:

* Installieren von Drupal.
* Verwalten einer Drupal Website
* Aufbau und/oder Pflege der Inhalte einer Drupal-basierten Website.

Das Handbuch richtet sich auch an Menschen, die bereits einige
Erfahrung mit einer aktuellen oder älteren Version von Drupal sammeln konnten
und ihre Fähigkeiten und Kenntnisse im Umgang mit Drupal erweitern oder auf den
neuesten Stand bringen möchten.

Dieses Handbuch geht davon aus, dass Sie sich bereits entschieden haben, Drupal
lernen und verwenden zu wollen. Wenn Sie erst mehr über Drupal erfahren möchten,
bevor Sie sich für Drupal entscheiden lesen Sie:
<<understanding-drupal>>.

Je nachdem, welche Aspekte von Drupal Sie lernen möchten, benötigen Sie einiges
an Hintergrundwissen zum Verständnis dieses Handbuchs: Allgemeine Kenntnisse
im Umgang mit dem Internet werden vorausgesetzt.
Das Handbuch konzentriert sich eher auf die Verwendung der Software Drupal
selbst. Der Abschnitt über die Installation von Drupal auf einem Webserver setzt
beispielsweise voraus, dass Sie wissen, wie sie den richtigen Webserver für Ihr
Projekt auswählen und wie Sie Daten auf diesen Webserver übertragen können.
In ähnlicher Weise gehen die Abschnitte über Content-Management davon aus,
dass Sie wissen, wie Sie sich auf Webseiten anmelden und Webformulare ausfüllen
können.

Nachdem Sie dieses Handbuch gelesen haben, können Sie folgendes:

* Die Informationsarchitektur einer auf Drupal basierenden Website planen.

* Die Website, die Sie geplant haben, zusammenbauen.

* Eine Drupal-Website verwalten und konfigurieren.

* Dokumentationen und Blog-Beiträge zu hier nicht behandelten Themen verstehen,
um Ihr Wissen und Ihre Fähigkeiten zu erweitern.

* Mit der globalen Drupal-Community in Kontakt treten.


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Übersetzt und bearbeitet von https://www.drupal.org/u/joachim-namyslo[Joachim Namyslo].
