[[preface-reporting]]
=== Probleme melden
[role="summary"]
Wie man ein Problem mit diesem Benutzerhandbuch meldet (mit detaillierten Anweisungen).

==== Zielsetzung

Melden Sie ein Problem mit diesem Handbuch, wie beispielsweise:

* Information that is incorrect or does not follow best practices
* Arbeitsschritte, die nicht funktionieren
* Screenshots oder Text, der nicht mit dem übereinstimmt, was Sie auf dem Bildschirm sehen
* Unklare Arbeitsanweisungen
* Stellen, an denen eine Tabelle oder ein Screenshot zur Verdeutlichung des Textes helfen würden würde
* Stellen an denen es versäumt wurde die entsprechenden Technologieren zu beschreiben
* Stellen an denne Erforderliche Vorkenntnisse oder die Anforderungen an die Website, die notwendig sind, um eine Aufgabe abzuschließen, nicht vorhanden sind.
* Typiache Fehler in der Rechtschreibung, Grammatik oder der Formatierung
* Kaputte Links

// ==== Erforderliche Vorkenntnisse

// ==== Anforderungen an die Website

==== Arbeitsschritte

. Notieren Sie sich das Thema oder die Themen, in denen Sie ein Problem gefunden haben.

. Melden Sie sich auf der Seite https://www.drupal.org[_Drupal.org_] an (Sie müssen ein Benutzerkonto anlegen, falls Sie noch kein Konto haben).

. Rufen Sie die Seite https://www.drupal.org/project/issues/user_guide[User Guide issues
auf _Drupal.org_] auf.

. Prüfen Sie, ob das von Ihnen gefundene Problem nicht bereits in eiem anderen Problmbericht gemeldet wurde:
  * If there are only a few open issues, scan the _Summary_ column to see if
  any of their descriptions match the problem you found. You may also need to
  read some of the issues to make sure, which you can do by clicking the links
  in the _Summary_ column.
  * If the open issue list is long, enter either a keyword related to the
  problem you found or the title of the topic where the problem occurs in the
  _Search for_ box, and click _Search_ to reduce the issue list. Then either
  scan the summaries or read the issues to see if they match your problem.

. If you determine that your problem has not already been reported, click
_Create a new issue_, and fill in the issue report as follows:
+
[width="100%",frame="topbot",options="header"]
|================================
| Feldname | Bedeutung | Beispielwert
| Titel | Kurze Zusammenfassung des Problems, das Sie gefunden haben | Instructions in "Adding
  a Content Type" do not work
| Category | Type of issue being reported | Bug report
| Version | Version of the guide you found the problem in | 8.x-0.x-dev
| Issue summary | Details of the problem you found | In the "Adding a Content
  Type" topic, in step 3, when I clicked _Save_, I got the following error
  message: ...
|================================

. Lesen Sie den _Title_ und die _Issue summary_ den/die sie Eingegegeben haben
und prüfen Sie, dass die von Ihnen bereitgestellten Informationen folgendes enthalten:
  * Eine komplette Beschreibung, des von Ihnen gefundenen Problems (in englisch)
  * Der Name des Themas oder der Themen, in dem/denen Sie das Problem gefunden haben
  * Die Sprache, in der Sie das Benutzerhandbuch gelesen haben (Wenn es sich um eine ander Sprache alös Englisch handelt)
  * Wenn Sie das Benutzerhandbuch auf eienr Website gelesen haben, einen Link zur eintsprechenden Seite oder Links zu den entsprechenden Seiten
    auf denen das Problem auftritt

. Klicken Sie auf _Save_ um den Problembereicht (Issue) zu erstellen.

. Rufen Sie den Problembericht ein paar Tage später wieder auf. um zu prüfen, ob einer der Projektbetreuer Rückfragen
 zu Ihrem Problembericht hat und kommentieren Sie den Problembericht, falls das notwendig ist..

// ==== Vertiefen Sie Ihre Kenntnisse

// ==== Verwandte Konzepte

// ==== Weiterführende Quellen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
