[[prevent-backups]]

=== Konzept: Datensicherungen

[role="summary"]
Überblick über Datensicherungen und was auf einer Website gesichert werden sollte.

(((Backup,overview)))
(((Content,backing up)))
(((File,backing up)))
(((Database,backing up)))

==== Erforderliche Vorkenntnisse

* <<understanding-drupal>>
* <<install-prepare>>

==== Was ist eine Datensicherung?

Für den Fall das mit dem Computer (oder den Computern) die Ihre Website und deren
Datenbank enthalten, etwas passiert oder wenn Sie den Zugriff auf diesen Computer verlieren, könnten Sie
einige oder alle Daten Ihrer Website sichern. Sie könnten auch Daten verlieren, wenn Ihre Website
gehackt wurde, oder wenn jemand mit administrativen Rechten Daten fälschlicherweise über
den Verwaltungsbereich der Website ändert. Um zu verhindern
Szenarien wie dieses vor dauerhaften, teuren Datenverlusten schützen, ist es wichtig
regelmäßige Backups der Daten Ihrer Website zu erstellen und sie an einem Ort zu speichern
die von dem Computer, auf dem Ihre Website läuft, getrennt ist.

Die Häufigkeit, mit der Sie Datensicherungen durchführen sollten, und wie viele Sicherungen Sie
halten sollte, hängt davon ab, wie häufig sich Ihre Website ändert. Wenn Sie eine sehr
große Menge an Inhalten auf Ihrer Website, die zu vielen hinzugefügt oder aktualisiert werden
Mal pro Tag würden Sie häufiger Backups erstellen wollen, als Sie es bei einer
Website, die sich nur selten ändert. Bedenken Sie auch, dass einige Zeit vergehen könnte, wenn eine
Datenproblem auftritt und wenn Sie merken, dass es sich um ein Problem handelt, so speichern Sie eine
Sequenz von Sicherungen (so dass Sie zu den letzten bekannten guten Daten zurückgehen können und
retrieve that), anstatt eine einzelne Sicherung wiederholt zu überschreiben, ist
gute Praxis.

Eine weitere Überlegung ist, dass unabhängig davon, in welchem Format Sie Ihre Backups speichern, es sich um ein
gute Idee, zu überprüfen, ob Sie tatsächlich verlorene Daten von Ihrem
Sicherungen. Vielleicht möchten Sie mehrere mögliche Datenverlustszenarien testen und
sicher, dass Ihre Daten in jedem Fall auf der Website wiederhergestellt werden können.

Um ein vollständiges Backup Ihrer Website zu erstellen, müssen Sie Kopien erstellen von
die folgenden:

* Die Daten im Verzeichnis _sites_, einschließlich der Datei _sites/default/settings.php_
Datei.

* Die Daten in der Datenbank Ihrer Website. Einige wenige Tabellen können abgeschnitten werden, wie zum Beispiel
Speicherung des temporären Daten-Cache und der Sitzungsinformationen für die Benutzeranmeldung, aber es ist
immer sicher, die gesamte Datenbank zu sichern.

* Hochgeladene Dateien, wie Bilder und andere Anhänge. Der Speicherort dieser
Dateien ist konfigurierbar; der Standardspeicherort ist die _Sites/default/files_
Verzeichnis unter Ihrem Site-Root. Navigieren Sie im Verwaltungsmenü _Verwalten_ zu
zu _Konfiguration_ > _Medien_ > _Dateisystem_ (_admin/configuration/media/filesystem_)
um die Speicherorte der Datei-Uploads zu überprüfen; um sie zu ändern, müssen Sie Ihre
_settings.php_ Datei editieren.

* Module, Themes und alle anderen Software-Dateien, die Sie angepasst haben. Sie finden
kundenspezifische Module und Themen in den Verzeichnissen _modules_ und _themes_
entsprechend. Einige Leute ziehen es vor, alle Software-Dateien zu sichern, einschließlich der
Dateien des Kernsystems und der Dateien der von der Community bereitgestellten Zusatzmodule und Themes (die Sie mittels Herunterladen aus der selben Quelle wiederherstellen können), anstatt zu versuchen, bestimmte Dateien herauszusuchen, die
die auf jeden Fall gesichert werden müssen.

Sie können einen Test durchführen, um zu prüfen, ob Ihre Sicherung richtig durchgeführt wurde, indem Sie
einee Kopie der Website in einer Entwicklungsumgebung erstellen (siehe <<install-dev-making>>).

==== Verwandte Themen


* <<security-update-core>>
* <<install-dev-making>>
* <<prevent-cache>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/docs/7/backing-up-and-migrating-a-site/backing-up-a-site[_Drupal.org_ Community-Dokumentationsseite "Sichern einer Website"]

* Das https://www.drupal.org/project/backup_migrate[beigetragene Sicherungs- und Migrationsmodul],
die zum Einrichten automatischer Sicherungen der Datenbank verwendet und hochgeladen werden können
Dateien.


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
