[[prevent-cache-clear]]

=== Leeren des Cache

[role="summary"]
So löschen Sie den Cache mittels Drush oder über die Benutzeroberfläche.

(((Cache,clearing)))
(((Cache,rebuilding)))

==== Zielsetzung

Löschen sie die internen Caches Ihrer Website,  bzw. bauen Sie diese neu auf, um sicherzustellen, dass die Website auf dem neuesten Stand ist. Verwenden Sie dazu entweder die Benutzeroberfläche oder drush.

==== Erforderliche Vorkenntnisse

* <<prevent-cache>>
* <<install-tools>>

==== Anforerungen´an die Website

Wenn Sie Drush zum Löschen des Caches verwenden möchten, muss Drush installiert sein. Siehe
<<install-tools>>.

==== Arbeitsschritte

Sie können entweder die Benutzeroberfläche oder Drush verwenden, um den Cache zu leerem. Sie können
auch das Skript „Rebuild" oder Drush verwenden, um einen vollständigen Neuaufbau des Cache durchzuführen.

====== Verwendung der der Benutzeroberfläche zum Leeren des Caches

. Navigieren Sie im Menü _Verwalten_ zum Menüpunkt _Konfiguration_ >
_Entwicklung_ > _Leistung_ (_admin/configuration/development/preformance_). Wenn Sie
nicht auf diese Seite des Verwaltungsbereichs zugreifen können, verwenden Sie eine der anderen
Methoden zum Leeren oder  zum Neuaufbau des Cache.

. Klicken Sie auf _Alle Caches leeren_.

. Eine Meldung, die besagt, dass der Cache geleert wurde, erscheint im oberen Teil der Seite.

. Wenn dies nicht das Problem löst, das dazu geführt hat, dass Sie den
Cache der Seite leeren wollten, versuchen Sie stattdessen den Cache komplett neu aufzubauen.

====== Neuaufbau des Cache mit dem Skript Rebuild

. Öffnen Sie die Datei _settings.php_ (_/sites/default/settings.php_) in einem beliebigen Texteditor. 
Fügen Sie folgende Zeile am Ende der Datei ein und speichern Sie die Datei ab:
+
----
$settings['rebuild_access'] = TRUE;
----

. Rufen Sie die Seite _http://www.example.com/core/rebuild.php_ in Ihrem Browser auf (wobei
_www.example.com_ als Beispiel für die URL Ihrer Website dient). Nach einer kurzen Wartezeit sollten Sie
auf die Startseite Ihrer Website umgeleitet werden, und der Neuaufbau des Caches sollte begonnen haben.

. Öffnen Sie die Datei _settings.php_ (_/sites/default/settings.php_)  erneut in einem Texteditor. Suchen Sie die
Zeile _$settings['rebuild_access']_, die Sie soeben hinzugefügt haben. Entfernen Sie diese Zeile und speichern
die Datei ab.

====== Mit Drush den Cache neu aufbauen oder leeren

Sie können einen von zwei Befehlen verwenden, um den Cache neu aufzubuen oder zu leeren:

* Verwenden Sie den Befehl `drush cache:rebuild`, um alle gecachten Daten einer Website zu löschen und den Chche neu aufzubauen. 
Nachdem der Behl ausgeführt wurde, wird die Meldung „Cache rebuild
complete" ausgegeben.

* Verwenden Sie den Befehl `drush cache:clear`, um eine Liste der einzelnen Caches zu sehen und
wählen Sie dann den spezifischen Cache, den Sie leeren möchten. Wenn sie diesen Befehl ausführen, sollte Ihnen ungefähr folgendes angezeigt werden:
+
----
> drush cache:clear
Enter a number to choose which cache to clear.
 [0]  :  Cancel
 [1]  :  drush
 [2]  :  theme-registry
 [3]  :  menu
 [4]  :  css-js
 [5]  :  block
 [6]  :  module-list
 [7]  :  theme-list
 [8]  :  render
 [9]  :  views
----
Wählen Sie einen zu leerenden Cache aus, indem Sie die diesem Cache zugewiesene Nummer eingeben. Drücken Sie
„Enter" um fortzufahren.


//===== 
Vertiefen Sie Ihr Wissen


//===== Verwandte Konzepte

==== Videos

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/-evRieC6Y3U[title="Den Cache leeren (englishc)"]

==== Zusätzliche Ressourcen

https://www.drupal.org/docs/7/administering-drupal-7-site/clearing-or-rebuilding-drupals-cache[_Drupal.org_ Community-Dokumentationsseite "Drpals Cache leeren oder neu aufbauen" (englisch)]


*Mitwirkende*

Bearbeitet und herausgegeben von https://www.drupal.org/u/eojthebrave[Joe Shindelar]
und https://www.drupal.org/u/jerseycheese[Jack Haas] übernommen aus
https://www.drupal.org/docs/7/administering-drupal-7-site/clearing-or-rebuilding-drupals-cache["Drpals Cache leeren oder neu aufbauen" (englisch)"],
copyright 2000 - copyright_upper_year iiegt bei den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].
