[[prevent-cache]]

=== Konzept: Cache

[role="summary"]
Übersicht über den Cache und die Daten der Website, die zwischengespeichert werden können.

(((Cache,overview)))
(((Page cache,overview)))
(((Module,Internal Page Cache)))
(((Module,Dynamic Page Cache)))
(((Internal Page Cache module,overview)))
(((Dynamic Page Cache module,overview)))

==== Vorausgesetztes Wissen

<<understanding-drupal>>

==== Was ist der Cache?

Die Software, die Ihre Website ausführt, muss bei jeder Anfrage an Ihre Website folgende Aufgabe abarbeiten:

* Berechnungen durchführen und Daten aus der Datenbank abrufen, um die Seite zusammenzustellen
die an den Web-Browser oder eine andere Anwendung gesendet werden, die auf die
Website zugreift. 

Diese Berechnungen benötigen Zeit. Das bedeutet das die Ladezeit Ihrer Website länger ist, als gewünscht.

Es gibt verschiedene Möglichkeiten, die Ladezeit einer Website zu beschleunigen. Darunter fällt auch die Installation entsprechender Zusatzsoftware auf dem Web-Server. Das System umfasst den internen Cache der Website und das Modul
Dynamic-Page-Cache. Hierfür wird keine zusätzliche Software auf dem Web-Server benötigt. Zum Cachen der Website wird ein Mechanismus verwendet, der 
_Teile der Datenbank in aufbereiteter Form zwischenspeichert_, um den Ladeforgang Ihrer Website zu beschleunigen. Die beiden Module funktionieren wie folt:

* Bei der Berechnung der Website werden Zwischenergebnisse der auszuliefernden Inhalte in einem bestimmten Speicherbereich abgelegt.

* Die endgültigen Die entgültige Ausgabe der Website wird in einem spezellen Bereich der Datenbankbereich (der als
_Cache_ bekannt ist) gespeichert. 

Wird danach erneut eine Anfrage an die Website gestellt, könnnen die zwishcengespeicheten Daten
gegebenenfalls abgerufen werden, um so die Berechnung der Ausgabe, der Website zu beschleunigen, ohne, dass die fertige Website jedes mal komplett neu berechnet werden muss. Darüber hinaus werden betriffe Teiele der zwischengespeicherten Daten aus dem Cache entfernt, wenn Inhalte oder Daten, auf der Website aktualisiert wurden. So wird erzungen, dass aktualisierte Daten auf der Website neu berechnet und zwischengespeichert werden, wen eine betroffene Seite nach der Aktualiierung des darauf enthaltenne Inhalts zum ersten mal neu aufgerufen wird.

Die Cache-Module funktionieren normalerweise recht gut und sorgen zumindest auf einigen Websites für bessere Ladezeiten. Manchmal kann der Cache jedoch Probleme machen.

Beispielsweise wenn:

* Beschädigte Daten im Cache enthalten sind. Dies führt zu einer korrupten oder falschen Ausgabe der Website.

* Alte Daten zu lange im Cache bleiben. Dies führt zur Ausgabe alter Versionen von Inhalten.

* Der Cache zu klein ist. Was zu einem verzögerten Aufbau und zu längerne Ladezeiten der Website führt. 

==== Welche Daten werden ausßerdem zwischengespeichert?

Unabhängig davon, ob die beiden Cache-Module auf Ihrer Website installiert sind,
legt die Software, mit der Ihre Website betrieben wird, immer noch jede Menge Daten in optimierter From im Zwischenspeicher ab. Folgende Daten werden vom Kernsystem zwischengespeichert:

* Das Theme-System speichert im Datenbank-Cache Informationen darüber, welche Template-Dateien 
zur Darstellung verschiedener Arten von Daten verwendet werden. Wenn Sie ein neues
Theme und eine neue Template-Datei hinzufügen, müssen Sie den cache leeren, damit diese neue Templete-Datei oder das neue Theme erkannt wird.

* CSS- und JavaScript-Dateien können (abhängig von den für die Website festgelgten Einstellunngen) optional optimiert und komprimiert werden. 
Ist die Optimierung und Komprimierung für diees Dateien aktiviert, werden die optimierten und komprimierten Versionen dieser Datein im Dateisystem der Website abgelegt, damit diese nicht zu oft neu optimiert werden müssen. Deshalb müssen Sie den Cahce bei der entwicklung eines Moduls oder Themes evetuell abschalten, damit Änderungen an CSS- oder JavaScript-Dateien erkannt werden können.

* Das System erkennt bestimmte Low-Level-PHP-Funktionen und -Klassen, wie z.B.
_Hooik-Implementierungen_ und _Plugin-Klassen_ die von den Modulen verwendet werden, die auf Ihrer Wbsite aktiviert sind und
speichert Informationen darüber ab, welches Modul welche Funktionalität zu Verfügung stellt.
Wenn Sie ein neues Modul entwickeln oder einem zu einem vorhandenen Modul Funktionen hinzufügen möchten, müssen Sie den Cahce der Websit möchlicherweise leeren, damit diese neuen Funktionen erkannt werden.

==== Verwandte Themen

Wenn Sie Probleme mit Ihrer Website haben, sollten Sie als erstes versuchen, den cahce zu leeren. Siehe <<<prevent-cache-clear>> für weitere Informationen.

==== Zusätzliche Ressourcen

Erfahren Sie mehr über zusätzliche Caching- und Leistungsoptimierungsmethoden auf der
https://www.drupal.org/docs/7/managing-site-performance-and-scalability/caching-to-improve-performance/caching-overview[_Drupal.org_ Community-Dokumentationsseite „Caching zur Leistungsverbesserung" (englisch)].


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].