[[prevent-cache]]

=== Konzept: Cache

[role="summary"]
Übersicht über den Cache und die Site-Daten, die zwischengespeichert werden können.

(((Cache,overview)))
(((Page cache,overview)))
(((Module,Internal Page Cache)))
(((Module,Dynamic Page Cache)))
(((Internal Page Cache module,overview)))
(((Dynamic Page Cache module,overview)))

==== Vorrausgesetztes Wissen
<<understanding-drupal>>

==== Was ist der Seiten-Cache?

Die Software, die Ihre Website ausführt, muss bei jeder Seitenanforderung Folgendes ausführen
Berechnungen durchführen und Daten aus der Datenbank abrufen, um die Seite zusammenzustellen
die an den Web-Browser oder eine andere Anwendung gesendet wird, die auf die
Standort. Diese Berechnungen benötigen Zeit, was bedeuten kann, dass die Ladezeit Ihrer Seite
länger als wünschenswert wäre.

Es gibt verschiedene Möglichkeiten, die Seitenladezeit zu beschleunigen, einschließlich der Installation von
Software auf dem Server. Das System umfasst den zentralen internen Seiten-Cache und
Dynamische Seiten-Cache-Module, die keinen zusätzlichen Server benötigen
Software; sie benutzen einen _Datenbank-Cache_-Mechanismus, um Ihre Website zu beschleunigen. Der Weg
Diese Module funktionieren so, dass bei Seitenberechnungen, Zwischenergebnissen und
Die endgültigen Seitenausgaben werden in einem speziellen Datenbankbereich gespeichert (bekannt als
_cache_). Wenn dann das nächste Mal ein kompatibler Antrag gestellt wird, Zwischen- oder Endantrag
Ergebnisse können gegebenenfalls abgerufen und verwendet werden, anstatt die
gesamte Berechnung. Darüber hinaus, wenn Inhalte oder Daten, die eine bestimmte
Berechnung aktualisiert wird, werden die betroffenen zwischengespeicherten Daten aus dem Cache entfernt,
erzwingen, dass dieser Teil der Berechnung beim nächsten Mal, wenn er benötigt wird, erneut durchgeführt wird.

Diese Cache-Module funktionieren normalerweise recht gut und bieten zumindest einige
Beschleunigung für die meisten Standorte. Manchmal kann der Seiten-Cache jedoch Probleme haben,
wie zum Beispiel:

* Beschädigte Daten im Cache, was zu einer verstümmelten oder falschen Seitenausgabe führt

* Alte Daten bleiben zu lange im Cache, was zu veralteter Seitenausgabe führt

* Unzureichender Cache, was zu langsamen Seitenladevorgängen führt

==== Welche anderen Daten werden zwischengespeichert?

Unabhängig davon, ob die beiden Seiten-Cache-Module auf Ihrer Site installiert sind,
die Software, die auf Ihrer Website läuft, wird immer noch die Ausgabe vieler interner
Berechnungen. Zu den Kernsystemen, die Daten zwischenspeichern, gehören

* Das Theme-System speichert im Datenbank-Cache Informationen darüber, welche Vorlage
Dateien werden zur Darstellung verschiedener Arten von Daten verwendet. Wenn Sie eine neue
Thema und eine neue Vorlagendatei hinzufügen, müssen Sie diesen Cache löschen, um
Ihre Themendatei erkannt.

* CSS- und JavaScript-Dateien können optional optimiert und komprimiert werden (abhängig
auf Ihren Website-Einstellungen). Wenn ja, werden die komprimierten Versionen in der Datei
System, damit sie nicht zu oft neu optimiert werden müssen. Wenn Sie
bei der Entwicklung eines Moduls oder Themas müssen Sie dies möglicherweise entweder ausschalten oder löschen
Datei-Cache, damit Änderungen an CSS- oder JavaScript-Dateien erkannt werden können.

* Das System lokalisiert bestimmte Low-Level-PHP-Funktionen und -Klassen, wie z.B.
_Implementierungen_ und _Plugin-Klassen_ von Ihren installierten Modulen abhaken und
speichert Informationen darüber, welches Modul welche Funktionalität hat. Wenn Sie
Wenn Sie ein neues Modul entwickeln oder einem bestehenden Modul Funktionen hinzufügen möchten, benötigen Sie möglicherweise
um diesen Cache zu leeren, damit Ihre neuen Funktionen erkannt werden können.

==== Verwandte Themen

Wenn Sie Probleme mit Ihrer Website haben, sollten Sie als erstes versuchen, sie zu beheben
normalerweise, um den Cache zu leeren. Siehe <<<prevent-cache-clear>> für weitere Informationen.

==== Zusätzliche Ressourcen

Erfahren Sie mehr über zusätzliche Caching- und Leistungsoptimierungsmethoden in der
https://www.drupal.org/docs/7/managing-site-performance-and-scalability/caching-to-improve-performance/caching-overview[_Drupal.org_ Community-Dokumentationsseite "Caching zur Leistungsverbesserung"].


*Angaben*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].