[[security-cron-concept]]

=== Konzept: Cron

[role="summary"]
Überblick über Cron und darüber wie dieses Modul sich vom Unix-Dienst Cron unterscheidet.

(((Cron task,overview)))
(((Automated Cron module,overview)))

//===== Vorkenntnisse

==== Was sind Cron-Aufgaben?

Um sicherzustellen, dass Ihre Website und ihre Module weiterhin gut funktionieren, sollten bestimmte Verwaltungsaufgaben in regelmäßigen Abständen, auf Ihrer Website ausgeführt werden. 

Diese Aufgben werden _Cron_-Jobs genannnt

Beispiele für Cron-Aufgaben sind:

* Das Prüfen auf Aktualisierungen für Module und Themes, 

* Die Indexierung von Inhalten für die Suche oder

* das entfernen temporärer Dateien.

==== Wie hängen Cron-Aufgaben und der Unix-Dienst Cron zusammen?

Linux/Unix-basierte Betriebssysteme verfügen über einen Dienst, der Cron-Aufgaben zeitgesteuert, d. h. in regelmäßigen Abständen ausführt. 
Sie können den Zeitplaner Cron, der sich auf Ihrem Webserver befindet verwenden, um Wartungsaufgaben auf Ihrer Website auszuführen. Alternativ können Sie das mit dem Kernsystem ausgelieferte Modul Automated Cron verwenden, um diese Aufgaben ausführen zu lassen.
Sie können den Status der Cron-Aufgaben Ihrer Website im Statusbericht überprüfen.

==== Verwandte Themen

* <<security-cron>>
* <<prevent-status>>

==== Zusätzliche Ressourcen

https://www.drupal.org/docs/7/setting-up-cron/overview[_Drupal.org_ Community-Dokumentationsseite "Einrichten von Cron (englisch)"]


*Mitwirkende*

Geschrieben und herausgegeben von
https://www.drupal.org/u/dianalakatos[Diána Lakatos] bei
https://pronovix.com/[Pronovix],
https://www.drupal.org/u/dalin[Dave Hansen-Lange] bei
https://www.advomatic.com/[Advomatic],
und https://www.drupal.org/u/batigolix[Boris Doesborg].
