[[security-concept]]

=== Konzept: Sicherheit und regelmäßige Aktualisierungen

[role="summary"]
Überblick über Sicherheitsaktualisierungen, die Behandlung von Fehlern und nicht sicherheitsrelevante Aktualisierungen.

(((Security,overview)))
(((Update,overview)))
(((Bug,reporting)))
(((Security bug,reporting)))
(((Security team,overview)))

==== Erfoprderliche Vorkenntnisse
* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>
* <<understanding-project>>

==== Was sind Sicherheitsaktualisierungen?

Jede Software hat gelegentlich Fehler, und manchmal haben diese Fehler Sicherheitslücken zur Folge.
Wenn Sicherheitslücken  im Kernsystem, den Modulen oder
Themes, die Ihre Website verwendet bekannt werden, wird ein entsprechendes _Sicherheitsupdate_ veröffentlicht. Sie werden
dieses _Sicherheitsupdate_ anwenden müssen, damit die Sicherheit Ihrer Website weiterhin gewährleistet ist. Siehe
<<<security-announce>> um zu erfahren, wie man über Sicherheitsupdates  per E-Mail benachrichtigt wird und
<<security-update-core>>, <<security-update-module>> sowie
<<security-update-theme>>, um zu lernen, wie man Aktualisierungen durchführt.

==== Was ist das Security-Team?

Das Open-Source-Projekt Drupal hat ein Team von Freiwilligen, die
sicherheitsbezogene Fehler bearbeiten und Sicherheitsupdates veröffentlichen. Dieses Team hilft auch anderen
Entwicklern dabei, Fehler zu beheben und pflegt Informationen, darüber, wie Benutzer ihre
Websites sicher halten können. Auf der Seite
https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team (englisch)] können Sie mehr über das Security-Team, sowie dessen vorgehenswesie und die entsprechenden Prozesse erfahren. 

==== Wie werden Sicherheitslücken gemeldet?

Es ist wichtig, dass Sicherheitsprobleme vertraulich behandelt werden, bis sie
behoben worden sind. Dadurch sind Websites weniger gefährdet, solange noch keinen Patch für eine gemeldete Sicherheitslücke existiert. Wenn Sie eine potentielle Sicherheitslücke in einem Teil der Software finden
die von der Website _Drupal.org_ heruntergeladen wurde, folgen Sie dem Verfahren, das auf der
https://www.drupal.org/drupal-security-team/general-information[Seite des _Drupal.org_ Security-Teams] beschrieben wird, um das Problem zu melden.

==== Was sind regelmäßige (nicht sicherheitsrelevante) Aktualisierungen?

Auch das Kernsystem, die Module und Themes werden regelmäßig aktualisiert, um
neue Funktionen hinzuzufügen und Fehler  zu beheben. Diese Aktualisierungen sind weniger kritisch als Sicherheits-Updates. Allgemein hat es sich in der Praxis bewährt, Aktualisierungen anzuwenden, solange diese keine Probleme auf Ihrer Website verursachen. Tests an einer Kopie, die zur Entwicklung Ihrer Website dient, sind inmmer eine gute Sache. Daher sollten sie solche Tests durchführen, bevor sie eine Website, die sich im Produktiveinsatz befindet, aktualisieren. Der Grund hierfür ist, das einige Aktualisierungen Änderungen enthalten können, die nicht mit den Modulen oder
Themes kompatibel sind, die Sie auf Ihrer Website einsetzen. Es kann auch sein, dass Aktualisierungen unter bestimmten Umständen eine bestimmte Funkion auf Ihrer Website unbrauchbar machen.

==== Verwandte Themen

* <<security-announce>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>
* <<install-dev-making>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/security/secure-configuration[_Drupal.org_ Community-Dokumentationsseite "Sichern Ihrer Website" (englisch)]
* https://www.drupal.org/security["Sicherheitshinweise" auf Drupal.org (englisch)]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Sicherheitsteam (englisch)]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/batigolix[Boris Doesborg]
und https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
