[[security-announce]]

=== Aktualisierungen im Blick behalten
[role="summary"]
Wie man eine Website sichert, indem man über die neuesten Sicherheitsupdates informiert bleibt.

(((Update,keeping track of)))
(((Security update,keeping track of)))
(((Update Manager module,overview)))
(((Security announcement,subscribing to by email)))
(((Security announcement,subscribing to on Twitter)))

==== Zielsetzung

Schützen Sie Ihre Website vor Sicherheitslücken, indem Sie Ihre Website auf dem neuesten Stand halten.

==== Erforderliche Vorkenntnsse

<<security-concept>>

//===== Anforderungen an die Website

==== Arbeitsschritte

Es gibt ein paar empfohlene Methoden, mit denen Sie sich über Sicherheitsaktualisierungen für Ihre Website informieren können:

* Navigieren Sie im Menü _Verwalten_ zum Menüpunkt _Berichte_ > _Verfügbare
Aktualisierungen_ > _Einstellungen_. Geben Sie die E-Mail-Adressen ein, die benachrichtigt werden sollen, wenn Aktualisierungen für die Website
verfügbar sind. Sie können auch angeben, ob Sie täglich oder wöchentlich über verfügbare Aktualisierungen informiert werden möchten. Klicken Sie auf 
_Konfiguration speichern_.

* Abonnieren Sie die E-Mail-Liste der Sicherheitsankündigungen. Zum Abonnieren der Mailing-Liste melden Sie sich auf
_Drupal.org_ an, rufen Ihr Benutzerprofil auf und abonieren den Seccurity
Newsletter über die Registerkarte _Bearbeiten_ > _Meine Newsletter_.

* Folgen Sie @drupalsecurity auf Twitter.

* Abonnieren Sie den RSS-Feed für
https://www.drupal.org/security/rss.xml[core Sicherheitsaktualierungen (englisch)],
https://www.drupal.org/security/contrib/rss.xml[Updates zu von der Community bereitgestellten Zusatzmodulen und Themes (englisch)] und die
https://www.drupal.org/security/psa/rss.xml[öffentlichen Service-Ankündigungen (englisch)].

//===== Vertiefen Sie Ihr Wissen

==== Verwandte Konzepte

* <<security-concept>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>

==== Videos

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/GcamYLNeGAs[title=Aktualisierungen im blick behalten (englisch)"]

==== Zusätzliche Ressourcen

* https://www.drupal.org/security["Sicherheitshinweise" auf _Drupal.org_ (englisch)]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Sicherheitsteam (englisch)]
* https://twitter.com/drupalsecurity[@drupalsecurety auf Twitter]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/hey_germano[Sarah Deutsch] bei
https://www.advomatic.com[Advomatic].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
