[[structure-image-styles]]

=== Konzept: Bildstile

[role="summary"]
Überblick über Bildstile und wie sie verwendet werden, um ein einzelnes Bild in
mehrere Variationen anzuzeigen.

(((Image style,overview)))
(((Style,image)))
(((Image effect,overview)))
(((Effect,image)))



==== Erforderliche Vorkenntnisse

<<structure-fields>>


===== Was sind Bildstile?
Mit Bildstilen können Sie ein einzelnes Bild hochladen, es aber auf verschiedene Arten anzeigen.
jede Darstellungsvariante, oder _Bildstil_, ist das Ergebnis der Anwendung eines oder mehrerer
_Effekte_ auf das Originalbild.

Sie können beispielsweise ein hochauflösendes Bild mit einem Seitenverhältnis von 4:3 hochladen,
und dieses verkleinert, quadratisch zugeschnitten oder schwarz-weiß anzeigen lassen (Sie können auch eine beliebige Kombination dieser Effekte verwenden). Das Kernsystem, stellt hierzu einen effizienten Weg zur Verfügung:

. Konfigurieren Sie einen Bildstil mit den gewünschten Effekten auf der Seite _Bildstile_.
(_admin/config/media/image-styles_).

. Die Effekte werden angewendet, wenn ein bestimmtes Bild zum ersten Mal unter Verwendung dieses Bildstils angefordert  wird.

. Das so erzeugte Bild wird gespeichert.

. Wenn derselbe Bildstil das nächste Mal angefordert wird, wird das gespeicherte Bild abgerufen, 
ohne das der Bildstil neu berechnet werden muss.

Das Kernsystem bietet mehrere Effekte, welche Sie zur Definition von Bildstilen verwenden können;
weitere können durch beigesteuerte Module bereitgestellt werden.

Rufen Sie die Seite _Bildstile_ über das Menü _Verwalten_ auf, indem Sie zum Menüpunkt
_Konfiguration_ > _Medien_ > _Bildstile_ (_admin/configuration/media/imagesyles_)
navigieren, um die Bildstile einzusehen, die standardmäßig definiert sind.

==== Verwandte Themen

* <<structure-image-style-create>>
* <<structure-image-responsive>>
* <<structure-fields>>


==== Zusätzliche Ressourcen

https://www.drupal.org/docs/8/core/modules/image/working-with-images[_Drupal.org_ Community-Dokumentationsseite "Arbeiten mit Bildern in Drupal 7 und 8" (englisch)]


*Mitwirkende*

Adaptiert und herausgegeben von https://www.drupal.org/u/batigolix[Boris Doesborg],
und https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle], von
https://www.drupal.org/docs/8/core/modules/image/working-with-images["Arbeiten mit Bildern in
Drupal 7 und 8" (englisch)],
copyright 2000 - copyright_upper_year liegt bei den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community]
