[[structure-reference-fields]]

=== Konzept: Referenzfelder

[role="summary"]
Überblick über Referenzfelder und die am häufigsten verwendeten Typen.

(((Reference field,overview)))
(((Reference field,content)))
(((Reference field,taxonomy term)))
(((Reference field,user)))
(((Field,reference)))
(((Field,content reference)))
(((Field,taxonomy term reference)))
(((Field,user reference)))
(((Taxonomy term reference field,overview)))
(((User reference field,overview)))
(((Content reference field,overview)))

==== Erforderliche Vorkenntnisse

<<planning-data-types>>

==== Was ist ein Referenzfeld?

Ein _Referenzfeld_ ist ein Feld, das eine Beziehung zwischen einer Entität
und einer oder mehreren anderen Entitäten herstellt. Diese können derselben oder einer anderen Entität angehören.
Die drei am häufigsten verwendeten Referenzfeldtypen sind:

Inhaltsreferenz::
  Ein Verweis auf ein Inhaltselement. Zum Beispiel könnten Sie Rezepte den Lieferanten zuordnen wollen, 
  die sie eingereicht haben. Dazu würden Sie ein Inhaltsreferenzeld anlegen, dass den Namen „Eingereicht von“ trägt und von den 
  eingereichten Rezepten aus auf das Profil des Lieferanten verweist, der das Rezept eingereicht 
  hat.

Taxonomie-Begriffsreferenz::
  Eine Referenz auf einen Taxonomiebegriff. Beispielsweise könnten Sie auf Rezepten eine Liste von Zutaten
  anlegen und diese als Taxonomiebegriffe abspeichern. Auf einem Rezept würden Sie dann die Zutaten für das jeweilige Gericht referenzieren. #
  Dazu würden Sie im Inhaltstyp Rezept ein Referenzfeld anlegen, dass auf das Taxonomievokabular verweist, welches die Zutaten enthält, die es auf
  dem Wochenmarkt zu kaufen gibt. Das Referenzfeld selbst würde das Taxonomievokabular 
  Zutaten referenzieren.

Benutzer-Referenz::
  Eine Referenz auf ein Benutzerkonto. Zum Beispiel könnten Sie auf Rezepten die Küchenchefs referenzieren, die auf dem Wochenmarkt Ihre Zutaten
  für das jewielige Rezept beziehen. Dafür würden Sie im Inhaltstyp Rezept ein Referenfeld vom Typ 
  Benutzer anlegen.

==== Verwandte Themen

<<structure-taxonomy>>

//==== Weiterführende Quellen


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/surendramohan[Surendra Mohan],
und https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Red Crackle].
