[[structure-widgets]]

=== Konzept: Formulare und Steuerelemente

[role="summary"]
Überblick über Formulare und Steuerelemente.

(((Content editing form,overview)))
(((Widget,overview)))
(((Field,overview)))
(((Form,overview)))

==== Erforderliche Vorkenntnisse

<<planning-data-types>>

==== Was sind Formulare und Steuerelemente?

Die Content-Management-System-Software, die auf Ihrer Website läuft, ermöglicht
Administratoren, Inhalte zu bearbeiten und Einstellungen online zu konfigurieren, unter Verwendung verschiedener Web
Formulare. Insbesondere _Inhaltsbearbeitungsformulare_ werden verwendet, um die Inhalte Ihrer Website zu bearbeiten.
Inhalt, und sie sind von Administratoren konfigurierbar; Konfiguration der Einstellungen
Formulare werden von Modulen bereitgestellt und können selbst nicht konfiguriert werden.

Die Daten im Inhalt Ihrer Website werden in einem oder mehreren Feldern gespeichert, die
die an den Inhaltstyp und/oder Untertyp angehängt sind. Wenn Sie den Inhalt konfigurieren
Bearbeitungsformular für jeden Inhaltsuntertyp können Sie

* Ein _Steuerelement_ für jedes Feld auswählen. Ein Steuerelement definiert die Methode zur Eingabe der
Daten die das Feld enthält. Beispielsweise kann ein Taxonomiebegriff über ein
Autovervollständigungsfeld, eine Auswahlliste oder ein Feld im Stil von Tags, über das Editoren
neue Tags automatisch hinzufügen könnnen, ausgewählt werden.

* Steuerelemnteinstellungen festlegen. Sie können zum Beispiel die Länmge des Zulässigen Textes in einem
Klartext-Eingabefeld festlegen.

* Ein oder mehrere Felder aus dem dem Bearbeitungsformular ausblenden, indem Sie das Feld bzw. die felder in den Bereich Deaktiviert verschiebn.

* Felder neu anordnen.

Prinzipiell können auch mehrere Inhaltsbearbeitungsformulare zur Verfügung gestellt werden. Für
jeder Inhalts-Untertyp wird in diesem Fall ein eigenes Formular angelegt. Diese Funktion wird jedoch nur selten verwendet; die einzige Ausnahme
im täglichen Einsatz  hierbei gilt für die Felde von Benutzerprofilen: Sie können untersschiedliche Formulare für die
Benutzerregistrierung und die Bearbeitung von Benutzerkonten verwenden. Zum Beispiel könnten Sie einen begrenzten Satz von
Feldern, der bei der ersten Registrierung eines Benutzers auf der Website angezeigt werden soll definieren und weitere Felder, nur dann angezeigt werden, wenn der Benutzer sein Profil bearbeitet.

==== Verwandte Themen

* <<structure-form-editing>>
* <<structure-view-modes>>

//===== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
