[[structure-view-modes]]

=== Konzept: Ansichtsmodi und Anzeigeformate

[role="summary"]
Überblick über Ansichtsmodi und Anzeigeformate.

(((View mode, overview)))
(((Entity view mode, overview)))
(((Formatter, overview)))
(((Field formatter, overview)))

==== Erforderliche Vorkenntnisse

<<structure-content-type>>

==== Was ist ein Ansichtsmodus?

Wie eine Entität (z. B. ein Inhalt, ein Benutzer oder ein Kommentar) angezeigt wird, hängt vom Kontext ab, 
in dem die jeweige information angeziegt werden solll. Dieser Kontext wird als _Anschtsmodus_ bezeichnet.
Beispiele für einen Ansichtsmodus sind:

* Eine Seite, die den volltändigen Inhalte mit allen darin vorhandenen Feldern anzeigt.
* Ein Anrisstext des Inhalts mit einem Miniaturbild und einem _Weiterlesen_-Link
* Ein vollständiges Benutzerprofil mit einem zoombaren Porträtfoto
* Ein Benutzer-Avatar mit Benutzername und einem Link zum Profil

Jeder Ansichtsmodus kann über die entsprechende Seite im Verwaltungsbereich konfiguriert werden. 
Zur Anzeige der Konfigurationsoptionen für die Ansichtsmodi des Inhaltstyps „Rezept", navigeiren Sie im Menü zu 
_Verwalten_ zum Menüpunkt  _Struktur_ > _Inhaltstypen_
(_admin/structure/types_) und klicken Sie im Drop-Button hinter dem Inhaltstyp Rezepte auf _Anzeige verwalten_.
In jedem Ansichtsmodus können alle Felder ein- oder ausgeblendet werden. Für Felder, die angezeigt werden sollen, kann das jeweilige Anzeigeformat festgelegt werden.

==== Was ist ein Anzeigeformat?

Ein Anzeigeformat ist eine Einstellung für die Anzeige von Feldwerten. Zum Beispiel können felder vom Typ _lang_ gekürzt oder in voller Länge angezeigt werden. 
Taxonomiebegriffe können entweder als Klartext oder als Link zur Seite des jeweiligen Taxonomiebegriffs angezeigt werden. 
Auf der Seite _Anzeige verwalten_ finden Sie die Anzeigeformate für die Felder des Inhaltstyps Rezept.

==== Verwandte Themen

* <<structure-content-type>>
* <<structure-content-display>>

==== Zusätzliche Ressourcen

https://www.drupal.org/node/1577752[_Drupal.org_ community documentation page "View modes"]


*Mitwirkende*

Adaptiert von https://www.drupal.org/u/batigolix[Boris Doesborg] aus
https://www.drupal.org/node/1577752["Ansichtsmodi"],
copyright 2000 - copyright_upper_year von den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Gemeinschaft].
