[[structure-widgets]]

=== Konzept: Formulare und Steuerelemente

[role="summary"]
Überblick über Formulare und Steuerelemente.

(((Content editing form,overview)))
(((Widget,overview)))
(((Field,overview)))
(((Form,overview)))

==== Erforderliche Vorkenntnisse

<<planning-data-types>>

==== Was sind Formulare und Steuerelemente?

Die Content-Management-System-Software, die die die Grundlage für Ihre Webiste bildet, ermöglicht
Administratoren, Inhalte zu bearbeiten und Einstellungen unter Verwendung verschiedener 
Formulare direkt im Webbrowser festzulgen. Insbesondere werden _Formulare zum Bearbetien von Inhalten_ verwendet, um die Inhalte Ihrer Website zu bearbeiten und Einstelungen für den jeweiligen Inhalt vorzunehemen.
Diese Einstellungen können von den Administratoren der Website festgelt werden.

Die Daten der Inhalte Ihrer Website werden in einem oder in mehreren Feldern gespeichert, die
an den jeweiligen Inhaltstyp oder an den Subtyps eines inhaltstyps angehängt werden. Wenn Sie das Bearbeitungsformular für einen 
Inhaltstyp konfigueren könnnen Sie: 

* Ein _Steuerelement_ für jedes Feld auswählen. Ein Steuerelement definiert die Methode zur Eingabe der
Daten die das Feld enthält. Beispielsweise kann ein Taxonomiebegriff über ein
Autovervollständigungsfeld, eine Auswahlliste oder ein Feld im Stil von Tags, über das Redakteure
neue Tags automatisch hinzufügen könnnen, ausgewählt werden.

* Steuerelemnteinstellungen festlegen. Sie können zum Beispiel die Länmge des Zulässigen Textes in einem
Eingabefeld für Klartext festlegen.

* Ein oder mehrere Felder aus dem dem Bearbeitungsformular ausblenden, indem Sie das Feld bzw. die Felder in den Bereich „Deaktiviert“ verschiebn.

* Felder neu anordnen.

Prinzipiell können auch mehrere Inhaltsbearbeitungsformulare zur Verfügung gestellt werden. Für
jeder Inhalts-Untertyp wird in diesem Fall ein eigenes Formular angelegt. Diese Funktion wird jedoch nur selten verwendet; die einzige Ausnahme
im täglichen Einsatz  hierbei gilt für die Felde von Benutzerprofilen: Sie können untersschiedliche Formulare für die
Benutzerregistrierung und die Bearbeitung von Benutzerkonten verwenden. Zum Beispiel könnten Sie einen begrenzten Satz von
Feldern, der bei der ersten Registrierung eines Benutzers auf der Website angezeigt werden soll definieren und weitere Felder, nur dann angezeigt werden, wenn der Benutzer sein Profil bearbeitet.

==== Verwandte Themen

* <<structure-form-editing>>
* <<structure-view-modes>>

//===== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
