[[thoughts-connecting]]
=== Mit der Community in Verbindung treten

[role="summary"]
Wie Sie sich mit der Open-Source-Community verbinden und sich in ihr engagieren können.

(((Community,connecting with)))
(((Drupal project,connecting with)))
(((Event,Drupal)))
(((Interest group,finding)))
(((User group,finding)))
(((Group,finding)))
(((Drupal user group,finding)))
(((IRC (Internet Relay Chat),using to chat online)))
(((Internet Relay Chat (IRC),using to chat online)))
(((Chatting online)))
(((Contributing to the project)))
(((Bug,reporting)))

==== Erforderliche Vorkenntnisse

<<understanding-project>>

===== Wie können Sie sich mit der Community verbinden?

Das Open-Source Projekt Drupal ist eine weltweite Gemeinschaft von Entwicklern und Benutzern. Eine der
besten Möglichkeiten, Ihre Kenntnisse über die Plattform zu verbessern,
ist es, sich mit anderen zu vernetzen, die die Software Drupal ebenfalls verwenden
und sich selbst in der Community zu engagieren. Es gibt viele Möglichkeiten, wie Sie damit anfangen können:

Besuchen Sie eine Veranstaltung::
  Es gibt sowohl regionale als auch internationale Drupal-Veranstaltungen, rund um
  die Welt. Rufen Sie die Seite https://events.drupal.org["DrupalCon" auf _Drupal.org_] (englisch) auf,
  um internationale Veranstaltungen zu finden, und besuchen Sie den
  https://groups.drupal.org/events["Veranstaltungskalender" auf _groups.drupal.org_]
  oder https://www.drupical.com/[_drupical.com_] (englisch), um regionale Veranstaltungen zu finden.
Einer lokalen User Group beitreten::
  Drupal-User-Groups gibt es auf der ganzen Welt. Viele von ihnen halten regelmäßige
  Treffen ab, an denen Sie teilnehmen können, um mehr über Drupal zu erfahren und sich mit anderen
  Drupal-Benutzern zu verbinden. Lokale Benutzergruppen finden Sie unter
  https://groups.drupal.org/[_grops.drupal.org_] (englisch).
An einer Gruppe zu einem Bestimmten Thema oder in einer bestimmten Sprache teilnehmen::
  Es gibt auch Interessengruppen für eine breite Palette von Themen, die online
  Diskussionsforen betreiben. Aktuelle Gruppen finden Sie unter
  https://groups.drupal.org/[_groups.drupal.org_]. Viele Sprachen haben
  auch ihre eigenen Websites; Sie finden diese auf der Seite
  https://www.drupal.org/language-specific-communities["Sprachspezifisch
  Communitys" auf _Drupal.org_ (englisch)].
Chatten Sie online::
  Das Drupal-Projekt verwendet Slack für Online-Chats. Es sind regionale sowie Themen zugeordnete Chats als auch
  Allzweck-Chatgruppen verfügbar. Erfahren Sie mehr über die
  https://www.drupal.org/slack[„Slack-Seite“ auf _Drupal.org_] (englisch) und https://www.drupal.org/drupalchat[„Drupal Chat“ auf _Drupal.org_] (englisch).
  
Ein Problem melden::
  Siehe unten.
Mitwirken::
  Sie können Ihre Zeit und Ihr Fachwissen auf vielfältige Weise in die
  Gemeinschaft einbringen. z. B. mit:
  * Der Entwicklung von Modulen oder Themes. Lesen Sie dazu die Seite
    https://www.drupal.org/contribute/development["Zur Entwicklung beitragen"] (englisch).
    auf _Drupal.org_] (englisch), oder sie inem Sie mithelfen Module und Themes zu verbessern (unter Verwendung der Issue-Queues von bestehenden
    Projekten).
  * Der Übersetzung der Benutzeroberfläche. Siehe
    https://localize.drupal.org[_localize.drupal.org_].
  * Dem Schreiben von Dokumentationen. Siehe
    https://www.drupal.org/contribute/documentation["An der
    Dokumentation" auf _Drupal.org_ mitwirken] (englisch).
  * Mit der Beantwortung von Support-Anfragen. Siehe: <<thoughts-support>>.

==== Wie können Sie ein Problem melden oder eine Funktion vorschlagen?

Jedes Projekt innerhalb der Gemeinschaft (wie z.B. das Drupal Projekt Core, das das Kernsystem von Drupal enthält
und Projekte für alle von der Community bereitgestellten Module und Themes) verwendet _Themen_, um
Software-Fehler und Pläne für neue Funktionen zu verfolgen. Sie können sich beteiligen, indem Sie einen Fehlerbericht erstellen, wenn Sie ein Problem finden,
eine Anfrage für ein neues Feature stellen, oder bestehende Fragen kommentieren.
Bevor Sie damit beginnen, suchen Sie zunächst nach dem Problem oder nach dem Feature, für das Sie ein Ticket erstellen möchten, um
sicherstellen, dass das Problem oder die Funktion nicht bereits gemeldet oder
angefordert worden ist. Lesen Sie hierzu auch:
https://www.drupal.org/issue-queue["Issue-Queques verwenden" auf _Drupal.org_ (englisch)] und
https://www.drupal.org/node/314185["Ein Problem melden" auf _Drupal.org_], um weitere Informationen zu erhalten.

Wenn Sie ein Problem finden, das Ihrer Meinung nach sicherheitsrelevant ist, wie z.B. eine
Cross-Site-Scripting-Schwachstelle, melden Sie dieses nicht in den normalen Issue-Queues.
Melden Sie es stattdessen dem Sicherheitsteam. Lesen Sie hierzu
https://www.drupal.org/node/101494["Wie man ein Sicherheitsproblem meldet" auf _Drupal.org_  ] um Einzelhieten zu diesem Prozess zu erfahren.

==== Verwandte Themen

<<thoughts-support>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/dcoc["Verhaltenskodex" auf _Drupal.org_]

* https://groups.drupal.org/events["Veranstaltungskalender" auf _groups.drupal.org_] oder
https://www.drupical.com/[_drupical.com_]

* https://www.drupal.org/community["Wo ist die Drupal-Gemeinschaft?" Seite auf
_Drupal.org_]

* https://groups.drupal.org/[_groups.drupal.org_ (englisch)]

* https://www.drupal.org/ircchat["IRC"-Seite auf _Drupal.org_  (englisch)]

* https://www.drupal.org/contribute["Wege, sich zu engagieren" Seite auf _Drupal.org_  (englisch)]

* https://www.drupal.org/node/2486391[_Drupal.org_ Seite "Warum sich engagieren?"  (englisch)]

* https://www.drupal.org/contributor-tasks[_Drupal.org_ Seite "Aufgaben der Mitwirkenden  (englisch)"]

* https://www.drupal.org/issue-queue[_Drupal.org_ Seite "Verwenden Sie die Problemwarteschlange"  (englisch)]

* https://www.drupal.org/node/314185[_Drupal.org_ Seite "Ein Problem melden"  (englisch)]

* https://www.drupal.org/node/101494[_Drupal.org_ Seite "Wie man ein Sicherheitsproblem meldet"  (englisch)]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
und https://www.drupal.org/u/eojthebrave[Joe Shindelar] bei
https://drupalize.me[Drupalize.Me].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
