[[thoughts-support]]
=== Unterstützung erhalten

[role="summary"]
Wie Sie Unterstützung bei Problemen mit der Entwicklung einer Website finden.

(((Support,finding)))
(((Forum,user support)))
(((IRC (Internet Relay Chat),using to chat online)))
(((Internet Relay Chat (IRC),using to chat online)))
(((Chatting online)))

==== Erforderliche Vorkenntnisse

* <<understanding-project>>
* <<thoughts-connecting>>

==== Wo können Sie Unterstützung finden?

Das Drupal-Projekt ist Open-Source. 
Wenn Sie Fragen oder Probleme mit der Software haben, haben Sie verscheidene Möglichkeiten, Antworten und Hilfestellungen bei Problemen zu finden. Diese unterscheiden sich von den Möglichkeiten, die es in der Regel bei kommeerzieller Software gibt, Support zu erhalten.

Es gibt mehrere Optionen für kostenlosen Support durch die Community der durch
Freiwillige geleistet wird. 

Zum einen gibt es einige IRC- oder Slack-Kanäle, lokale Gruppen und Gemeinschaften, die in einer bestimmten Landessprache, Möglichkeiten bieten, Unterstützungsfragen via Online-Chat,  auf persönliche Treffen oder über
Websites zu stellen. (mehr darüber erfahren Sie unter <<thoughts-connecting>>).

Zum andern ermutigen einige (aber nicht alle) von der Community bereitgestllten Zusatzmodule, Distributionen, sowie einige der von der Community bereitgestellten Zusatz-Themes Sie dazu, Support-Anfragen zu stellen. 

Projekte, die eine sehr große Anzahl von Benutzern haben, erlauben in der Regel keine Support-Anfragen in ihren Issue Queues. Das Drupal Kernsystem (Projektname: Drupal Core) gehört in diese Kategorie. 

Projekte mit einer kleineren Anzahl von Nutzern begrüßen es, wenn Sie in den Issue-Queues um Support bitten. Gehen Sie respektvoll mit der Zeit der Entwickler um und
lesen Sie die Dokumentation des jeweiligen Projektes, bevor Sie eine Frage stellen. 

Alle Projekte ermutigen dazu, Fehler und Sicherheitsprobleme zu melden. Mehr darüber erfahren Sie unter <<thoughts-connecting>>.

Zusätzlich zu diesen Ressourcen bieten die folgenden Seiten kostenlose Foren, in denen
Freiwillige Support-Fragen zu Drupal beantworten:

* Die https://www.drupal.org/forum[_Drupal.org_ Foren]
* https://drupal.stackexchange.com/[„Drupal Answers" auf StackExchange]

Wenn Sie es vorziehen, für Support zu zahlen (vermutlich im Austausch gegen umfangreichere
Dientleistungen oder bessere Verfügbarkeit), finden Sie Dienstleister auf dem
https://www.drupal.org/drupal-services["Drupal-Marktplatz" auf _Drupal.org_].

==== Verwandte Themen

* <<thoughts-learn-more>>
* <<thoughts-connecting>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/support[„Support"-Seite auf _Drupal.org_]
* https://www.drupal.org/drupal-services[„Drupal-Marktplatz" auf _Drupal.org_]
* Die https://www.drupal.org/forum[Foren auf _Drupal.org_ ]
* https://drupal.stackexchange.com/[„DrupalAnswers" auf StackExchange]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].