[[thoughts-support]]
=== Unterstützung erhalten

[role="summary"]
Wie Sie Unterstützung bei Problemen mit der Entwicklung einer Website finden.

(((Support,finding)))
(((Forum,user support)))
(((IRC (Internet Relay Chat),using to chat online)))
(((Internet Relay Chat (IRC),using to chat online)))
(((Chatting online)))

==== Erforderliche Vorkenntnisse

* <<understanding-project>>
* <<thoughts-connecting>>

==== Wo können Sie Unterstützung finden?

Das Drupal-Projekt ist Open-Source. 
Wenn Sie Fragen oder Probleme mit der Software haben, haben Sie andere Möglichkeiten, Antworten und Hilfestellungen bei Problemen zu finden, die Möglichkeiten, die es in der Regel bei kommeerzieller Software gibt.

Es gibt mehrere Optionen für kostenlosen Support durch die Community der durch
Freiwillige geleistet wird. 

Zum einen gibt es einige IRC- oder Slack-Kanäle, lokale Gruppen und Gemeinschaften in einer bestimmten Landessprache, Möglichkeiten bieten, Unterstützungsfragen via Online-Chat,  auf persönliche Treffen oder über
Websites zu stellen. (mehr darüber erfahren Sie unter <<thoughts-connecting>>).

Zweitens ermutigen einige (aber nicht alle) Modul-, Verbreitungs- und Themenprojekte 
Sie dazu, Support-Anfragen zu Themen zu stellen. Projekte, die
eine sehr große Anzahl von Benutzern haben, erlauben in der Regel keine Support-Anfragen in ihren Foren.
(Drupal Core gehört in diese Kategorie), während Projekte mit einer kleineren Anzahl von Nutzern
die gelegentliche Unterstützungsfrage begrüßen. Seien Sie respektvoll gegenüber der Entwicklerzeit und
lesen Sie die Dokumentation für das Projekt, bevor Sie eine Frage stellen. 
Andererseits ermutigen alle Projekte dazu, Fehler und Sicherheitspropbleme zu melden; mehr darüber erfahren Sie unter <<thoughts-connecting>>.

Zusätzlich zu diesen Ressourcen bieten die folgenden Seiten kostenlose Foren, in denen
Freiwillige Support-Fragen zu Drupal beantworten:

* Die https://www.drupal.org/forum[_Drupal.org_ Foren]
* https://drupal.stackexchange.com/["Drupal-Antworten" auf StackExchange]

Wenn Sie es vorziehen, für Unterstützung zu zahlen (vermutlich im Austausch für umfangreichere
Service oder bessere Verfügbarkeit), finden Sie Dienstleister in der
https://www.drupal.org/drupal-services["Drupal-Marktplatz" auf _Drupal.org_].

==== Verwandte Themen

* <<thoughts-learn-more>>
* <<thoughts-connecting>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/support["Support"-Seite auf _Drupal.org_]
* https://www.drupal.org/drupal-services["Drupal-Marktplatz" auf _Drupal.org_]
* Die https://www.drupal.org/forum[_Drupal.org_ Foren]
* https://drupal.stackexchange.com/["Drupal-Antworten" auf StackExchange]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
