[[thoughts-learn-more]]
=== Mehr lernen

[role="summary"]
How to find additional material to gain advanced site-building skills.

(((Learning resource,link to)))
(((Training,resource)))
(((Drupal training,resources for)))
(((Documentation,about Drupal)))
(((Resource,documentation and training)))
(((Documentation,available on drupal.org)))
(((Documentation,contributed by the Drupal Community)))
(((Documentation,about the Drupal API)))
(((Documentation,for programmers)))
(((Documentation,Drupal Planet blog posts)))
(((Training,Training Marketplace)))
(((Training,Global Training Days)))

==== Erforderliche Vorkenntnisse

* <<understanding-project>>
* <<thoughts-connecting>>

===== Wo können Sie mehr erfahren?

Die folgenden Ressourcen sollten sich für Sie als nützlich erweisen, wenn Sie Ihre Fähigkeiten wieter ausbauen möchten:

https://www.drupal.org/documentation["Drupal Community Dokumentation" Abschnitt auf _Drupal.org_]::
  Wiki-ähnliche Dokumentation, die von der Drupal-Gemeinschaft beigesteuert wird, von
  grundlegend bis fortgeschritten, über alle Aspekte von Drupal (Site-Building und
  Verwaltung, Entwicklung von Themes, Entwicklung und bereitstellen von Modulen).
https://api.drupal.org[_api.drupal.org_]::
  Referenzdokumentation für Programmierer zur Drupal-API.
https://www.drupal.org/planet["Drupal Planet"-Seite auf _Drupal.org_]::
  Eine Ansammlung von Blog-Beiträgen über Drupal aus dem gesamten Web, gepostet von
  bloggenden Mitglieder der Drupal-Community, deren Beiträge hier zusammengefasst werden.
  Die Themen reichen von Programmierung über Site-Building bis hin zu Neuigkeiten zu Drupal.
Gruppen, Veranstaltungen und Treffen::
  Lesen Sie <<thoughts-connecting>>, um mehr über aktuelle Gruppen, regionale Gruppen
  und Gruppen in Ihrer Muttersprache sowie lokale, regionale und internationale Veranstaltungen zu erfahren.
https://www.drupal.org/training["Ausbildungsmarktplatz"-Seite auf _Drupal.org_]::
Der Marketplace listet kostenpflichtige Schulungsanbieter auf. Wenn Sie an kostenlosen Trainings interessiert sind, sehen sie nahc mauf welchgen Veranstaltungen kostenlose Trainings angeboten werden.
Auf folgender Seite finden Sie ebenfalls kostenlose oder seht günstige Trainings:
https://groups.drupal.org/global-training-days["Global Training Days" auf
_Drupal.org_].
Support-Seiten::
Lesen Sie das Thema <<thoughts-support>> um Supportforen zu finden. Danach zu suchen kann nützlich sien, wenn Sie etwas über ein bestimmtes Thema lernen möchten.

// ==== Verwandte Themen

// ==== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
und https://www.drupal.org/u/eojthebrave[Joe Shindelar] bei
https://drupalize.me[Drupalize.Me].
