[[understanding-distributions]]

=== Konzept: Distributionen

[role="summary"]
Übersicht über Distributionen, die zur Einrichtung von Websites für bestimmte
Zwecke dienen.

(((Distribution,overview)))
(((Distribution,full-featured)))
(((Distribution,quick-start)))
(((Full-featured distribution,overview)))
(((Quick-start distribution,overview)))

==== Erforderliche Vorkenntnisse

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>

==== Was sind Distributionen?

_Distributionen_ bieten Website-Features und -Funktionen für einen bestimmten Website-Typ
als ein einziger Download, der die Kern-Software sowie von der Community bereitgestellte Module und Themes
und vordefinierte Konfiguration enthält. Eine Distribution ermöglicht das Einrichten einer
komplexen Website für einen bestimmten Einsatzzweck, in weniger Schritten als die Installation und anschließend folgende Indiviedualisierung des Kernsystems und dessen Konfiguration.

Es gibt zwei Haupttypen von Distributionen:

Voll funktionsfähige Distributionen::
  Eine Full-Featured-Distribution ist ein Projekt, das eine vollständige Lösung für ein bestimtes Einsatzgebiet anbietet.
  So kaann eine Website zum Beispiel für akademische oder geschäftliche Zwecke,
  sowie für Kommunialverwaltungen, gemeinnützige Organisationen oder Unternehmen in den Bereicheb Verlagswesen, Sozialwesen usw mit    
  Hilfe einer Drupal-Distribution eingerichtet werden. Beispielsweise könnten Sie eine
  vorhandene Distribution für Wochenmärkte verwenden, um Ihre eigene Website zu erstellen, oder Sie
  könnte Ihre eigens erstellte Wochenmarkt-Website als Distribution anbieten, damit andere Personen diese zukünftig für ihre eigenen
  Zwecke verwenden und anpassen können.

Andere Distributionen::
  Distributionen können auch Schnellstart-Tools sein, die Entwickler und Site Buildern als Ausgangspunkt verwenden können.

==== Verwandte Themen

<<thoughts-connecting>>

==== Zusätzliche Ressourcen

https://www.drupal.org/project/project_distribution[_Drupal.org_ Drupal-Distributionen herunterladen]


*Mitwirkende*

Adaptiert und herausgegeben von https://www.drupal.org/u/dianalakatos[Diána Lakatos]
und https://www.drupal.org/u/ifrik[Antje Lorch],
aus https://www.drupal.org/docs/7/distributions["Distributionen"]
und https://www.drupal.org/project/project_distribution["Herunterladen & Erweitern -- Distributionen"]]
copyright 2000 - copyright_upper_year liegt bei den jeweiligen Mitwirkenden der 
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].
