[[understanding-themes]]

=== Konzept: Themes

[role="summary"]
Überblick über die Themen und wo man sie erhalten kann.

(((Theme,overview)))
(((Theme,core)))
(((Core theme,overview)))
(((Theme,third-party)))
(((Third-party theme,overview)))
(((Theme,custom)))
(((Custom theme,overview)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Was ist ein Theme?

Ein Theme ist ein Satz von Dateien, die das visuelle Erscheinungsbild Ihrer Website definieren.
Die Kern-Software und Module, die auf Ihrer Website laufen, bestimmen, welche
_Inhalt_ (einschließlich HTML-Text und anderer in der Datenbank gespeicherter Daten, hochgeladen
Bilder und alle anderen Asset-Dateien) wird auf den Seiten Ihrer Website angezeigt. Die
Thema bestimmt das HTML-Markup und CSS-Styling, das den Inhalt umhüllt.

Die Kern-Software stellt mit der Kerndistribution mehrere grundlegende Themen zur Verfügung.
Diese Themen wurden größtenteils von der Community in den letzten Jahren entworfen und erstellt.
mehrere Jahre und wird allesamt eine gute Wahl für den Bau Ihrer ersten Standorte sein und
sich mit der Funktionsweise der Kernsoftware besser vertraut zu machen.

Drupal ist ein gut etabliertes CMS, so dass der Markt für 3rd-Party-Themen - sowohl kostenlose
und bezahlt - ist sehr robust.

Wenn keine der 3rd-Party-Optionen Ihren Bedürfnissen entspricht, müssen Sie eine benutzerdefinierte
Thema. Ein benutzerdefiniertes Thema kann so einfach wie eine einzelne CSS-Datei sein, die das Styling von
das von der Kern-Software bereitgestellte Markup. Anleitung zum Erstellen benutzerdefinierter Themen in
Drupal 8 finden Sie in der
https://www.drupal.org/docs/8/theming[_Drupal.org_ Community-Dokumentationsseite
"Theming Drupal"].

==== Verwandte Themen

* <<extend-theme-find>>
* <<extend-theme-install>>
* <<understanding-modules>>

==== Zusätzliche Ressourcen

https://www.drupal.org/docs/8/theming[_Drupal.org_ Community-Dokumentationsseite
"Theming Drupal"]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/jgrubb[John Grubb] und
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
