[[understanding-distributions]]

=== Konzept: Distributionen

[role="summary"]
Übersicht über Distributionen, die zur Einrichtung von Websites für bestimmte
Zwecke dienen.

(((Distribution,Überblick)))
(((Distribution,voll funktionsfähig)))
(((Distribution,Schnellstart)))
(((Full-featured distribution,Überblick)))
(((Schnellstartstart-Distribution,Überblick)))

==== Erforderliche Vorkenntnisse

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>

==== Was sind Distributionen?

_Distributionen_ bieten Features und Funktionen für Websites, die einen spezifischen Anwendungszweck abdecken,
als ein Download-Paket an, welches das Kernsystem sowie von der Community bereitgestellte Zusatzmodule und Themes
sowie eine passend vordefinierte Konfiguration enthält. Eine Distribution ermöglicht das Einrichten einer
komplexen Website für einen bestimmten Einsatzzweck, in weniger Schritten
als die Installation und anschließend folgende Individualisierung des Kernsystems und dessen Konfiguration.

Es gibt zwei Haupttypen von Distributionen:

Voll funktionsfähige Distributionen::
  Eine Full-Featured-Distribution ist ein Projekt, das eine vollständige Lösung
  für ein bestimmtes Einsatzgebiet anbietet.
  So kann eine Website zum Beispiel für akademische oder geschäftliche Zwecke,
  sowie für Kommunalverwaltungen, gemeinnützige Organisationen oder Unternehmen
  in den Bereichen Verlagswesen, Sozialwesen usw. mit
  Hilfe einer Drupal-Distribution eingerichtet werden. Beispielsweise könnten Sie eine
  vorhandene Distribution für Wochenmärkte verwenden, um Ihre eigene Website zu erstellen oder Sie
  könnten die von Ihnen erstellte Wochenmarkt-Website als Distribution anbieten,
  damit andere Personen diese zukünftig für Ihre eigenen Zwecke verwenden und
  anpassen können.

Andere Distributionen::
  Distributionen können auch Schnellstart-Tools sein, die Entwickler und
  Site Builder als Ausgangspunkt verwenden können.

==== Verwandte Themen

<<thoughts-connecting>>

==== Zusätzliche Ressourcen

https://www.drupal.org/project/project_distribution[_Drupal.org_ Drupal-Distributionen herunterladen]


*Mitwirkende*

Adaptiert und herausgegeben von https://www.drupal.org/u/dianalakatos[Diána Lakatos]
und https://www.drupal.org/u/ifrik[Antje Lorch],
aus https://www.drupal.org/docs/7/distributions["Distributionen"]
und https://www.drupal.org/project/project_distribution["Herunterladen & Erweitern -- Distributionen"]
copyright 2000 - copyright_upper_year liegt bei den jeweiligen Mitwirkenden der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].