[[understanding-gpl]]

=== Konzept: Drupal-Lizenzierung

[role="summary"]
Überblick über Drupals Lizenzbedingungen und die von den Anwendern und Mitwirkenden zu befolgenden Richtlinien.

(((Licensing,overview)))
(((Drupal licensing,overview)))
(((GPL (General Public License or GNU General Public License),overview)))
(((GNU General Public License,overview)))
(((Legal,overview)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Welcher Lizenz unterliegt Drupal?

Drupal und alle beigetragenen Dateien, die auf _Drupal.org_ gehostet werden, sind unter der
GNU General Public License (GPL), Version 2 oder später. Das bedeutet, dass Sie die Freiheit haben
Herunterladen, Wiederverwenden, Ändern und Verteilen aller Dateien, die Teil eines Projekts sind, auf
_Drupal.org_ unter den Bedingungen der GPL Version 2 oder 3. Sie können auch den Kern
Software in Kombination mit jedem Code mit jeder Lizenz, die kompatibel ist mit
Version 2 oder 3.

Mensche, die an Drupal mitwirken sollten sich an folgende Richtlinien halten:

* Alle Dateien (PHP, JavaScript, Bilder, Flash, etc.), die Teil eines Projekts sind
auf _Drupal.org_ müssen unter der GPL Version 2 oder später stehen.

* Alle Personen, die an Drupal mitwirken behalten das Urheberrecht an ihrem Code, stimmen aber der Veröffentlichung zu.
unter der gleichen Lizenz zu, der auch Drupal unterliegt.

* Drupal-Module und -Themes sind derivative Werke von Drupal. Wenn Sie Drupal weitergeben
müssen Sie dies unter den Bedingungen der GPL Version 2 oder neuer tun.

* Alle Rechte an den Inhalten auf auf Drupal.org selbst liegen bie den ursprünglichen Mitwirkenden Community-Mitglidern und sind unter den Bedingunen der Creative Commons Attribution-ShareAlike-Lizenz 2.0 lizenziert.

* Beispielcode auf _Drupal.org_ ist ebenfalls unter der GPL Version 2 oder oder neuer lizensiert.

==== Verwandte Themen

<<thoughts-connecting>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/about/licensing[_Drupal.org_ Seite über "Lizenzierung"]]

* https://api.drupal.org/api/drupal/core!LICENSE.txt/8.2.x["Drupal 8 LICENSE.txt" Seite auf _api.drupal.org_]

* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU Allgemeine Öffentliche GNU-Lizenz, Version 2]

* http://www.gnu.org/licenses/gpl-3.0.en.html[GNU Allgemeine Öffentliche GNU-Lizenz, Version 3]

* https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons Namensnennung-ähnliche Lizenz 2.0.]

* https://groups.drupal.org/legal["Legal Group" auf _groups.drupal.org_]


*Mitwirkende*

Adaptiert von https://www.drupal.org/u/dianalakatos[Diána Lakatos] unter
https://pronovix.com/[Pronovix] von
https://www.drupal.org/about/licensing["Lizenzierung"]]
copyright 2000 - copyright_upper_year von den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].