[[understanding-data]]
=== Konzept: Arten von Daten

[role="summary"]
Überblick über gängige Datentypen, die in einer Website verwendet werden.

(((Datentypen,Überblick)))
(((Datentypen,Konfiguration)))
(((Datentyp,Inhalt)))
(((Datentyp,Status)))
(((Datentyp,Sitzung)))
(((Konfiguration,als Datentyp)))
(((Inhalte, als Datentyp)))
(((Status,als Datentyp)))
(((Sitzung,als Datentyp)))


//==== Erforderliche Vorkenntnisse

==== Welche Arten von Daten gibt es?

Die Daten und Informationen auf Ihrer Website sind in vier Typen unterteilt.
(jede Datenart, wird auf andere Art und Weise bearbeitet, übersetzt und abgespeichert).
Diese vier Typen sind:

Inhalt::
  Informationen (Text, Bilder usw.), die den Besuchern der Website angezeigt werden sollen. Diese
  Art von Informationen werden in der Regel dauerhaft gespeichert, können aber normalerweise bearbeitet werden.
Konfiguration::
  Informationen über Ihre Website, die  keine Inhalte sind und eher dauerhaft 
  gespeichert werden. Sie definieren,
  wie sich Ihre Website verhält oder angezeigt wird.
  Diese Art Daten werden manchmal auch den Besuchern der Website angezeigt,
  In der Regel handelt es sich dann aber nur um kurze Texte (wie Beschriftungen
  von Feldern, den Namen Ihrer Website usw.).
  Konfigurationsdaten sind jedoch keine größeren Ansammlungen von Daten,
  die man normalerweise als Inhalt bezeichnen würde.
Status::
  Informationen vorübergehender Art über den aktuellen Zustand Ihrer
  Website, wie z. B. die Zeit, zu der eine Cron-Wartungsaufgabe zuletzt ausgeführt wurde.
Sitzung::
  Informationen über die Interaktionen einzelner Website-Besucher, wie z. B.
  ob diese an der Website angemeldet sind oder ob für den jeweiligen Benutzer
  ein bestimmtes Cookie gesetzt wurde. Diese Art Daten ist technisch eine
  Unterart der Daten vom Typ Zustand, da sie ebenfalls nur vorübergehend
  aufbewahrt werden.

==== Verwandte Themen

* <<planning-data-types>>
* <<security-cron-concept>>
* <<user-concept>>
* <<language-concept>>

//==== Weiterführende Quellen


*Mitwirkende*

Adaptiert von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] aus
https://www.drupal.org/node/2120523["Überblick über die Konfiguration (vs. andere Arten von Informationen (englisch))"], copyright 2000 - copyright_upper_year liegt bei den jeweiligen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community]

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].