[[understanding-gpl]]

=== Konzept: Drupal-Lizenzierung

[role="summary"]
Überblick über Drupals Lizenzbedingungen und die von den Anwendern und Mitwirkenden zu befolgenden Richtlinien.

(((Licensing,overview)))
(((Drupal licensing,overview)))
(((GPL (General Public License or GNU General Public License),overview)))
(((GNU General Public License,overview)))
(((Legal,overview)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Welcher Lizenz unterliegt Drupal?

Drupal und alle von der Drupal Community bereitgestellen Dateien, die auf _Drupal.org_ gehostet werden, sind unter der
GNU General Public License (GPL), Version 2 oder neuer. lizensiert. Das bedeutet, dass Sie die Freiheit haben diese Dateien
herunter zu laden, Wiederverwenden, zu ändern und Dateien, die Teil eines Projekts auf _Drupal.org_ sind unter den Bedingungen der GPL Version 2 oder 3 weiter zu geben. Sie können auch das Kernsystem in Kombination mit jeder Art von Quelltext ausliefern, der einer Lizenz unterlieget, die mit der GPL Version 2 oder Version 3 kompatibel ist.
Version 2 oder 3.

Menschen, die an Drupal mitwirken sollten sich an folgende Richtlinien halten:

* Alle Dateien (PHP-Dateien, JavaScript-Dateien, Bilder, Flash-Dateien, usw.), die Teil eines Projekts auf _Drupal.org_  sind
müssen unter der GPL Version 2 oder neuer lizensiert sein.

* Alle Personen, die an Drupal mitwirken behalten das Urheberrecht an ihrem Code, stimmen aber der Veröffentlichung
unter der gleichen Lizenz zu, der auch Drupal unterliegt.

* Drupal-Module und -Themes sind derivative Werke von Drupal. Wenn Sie Drupal weitergeben
müssen Sie dies unter den Bedingungen der GPL Version 2 oder neuer tun.

* Die Rechte an den Inhalten auf auf Drupal.org selbst liegen bie den Community-Mitglidern, die diese OInhalte erstellt haben. Die Inhalte auf _Drupal.org_und sind unter den Bedingunen der Creative Commons Attribution-ShareAlike-Lizenz 2.0 lizenziert.

* Beispielcode auf _Drupal.org_ ist ebenfalls unter der GPL Version 2 oder oder neuer lizensiert.

==== Verwandte Themen

<<thoughts-connecting>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/about/licensing[_Drupal.org_ Seite über "Lizenzierung"]]

* https://api.drupal.org/api/drupal/core!LICENSE.txt/8.2.x["Drupal 8 LICENSE.txt" Seite auf _api.drupal.org_]

* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU Allgemeine Öffentliche GNU-Lizenz, Version 2]

* http://www.gnu.org/licenses/gpl-3.0.en.html[GNU Allgemeine Öffentliche GNU-Lizenz, Version 3]

* https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons Namensnennung-ähnliche Lizenz 2.0.]

* https://groups.drupal.org/legal["Legal Group" auf _groups.drupal.org_]


*Mitwirkende*

Adaptiert von https://www.drupal.org/u/dianalakatos[Diána Lakatos] bei
https://pronovix.com/[Pronovix] von
https://www.drupal.org/about/licensing["Lizenzierung"]]
copyright 2000 - copyright_upper_year liegt bei den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].