[[understanding-themes]]

=== Konzept: Themes

[role="summary"]
Überblick über Themes und darüber wo diese bezogen werden können.

(((Theme,overview)))
(((Theme,core)))
(((Core theme,overview)))
(((Theme,third-party)))
(((Third-party theme,overview)))
(((Theme,custom)))
(((Custom theme,overview)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Was ist ein Theme?

Ein Theme ist ein Satz von Dateien, die das visuelle Erscheinungsbild Ihrer Website definieren.
Das Kernystem und  die Module, die auf Ihrer Website laufen, bestimmen, welche
_Inhalte_ (einschließlich HTML-Text und anderer in der Datenbank gespeicherter Daten, hochgeladen
Bilder und alle anderen Asset-Dateien) auf Ihrer Website angeziegt werden.
Themes bestimmen das HTML-Markup und CSS-Styling, in das diese Inhalte eingebttet werderden.

Das Kernsystem stellt mehrere grundlegende Themes zur Verfügung.
Diese Themes wurden größtenteils von der Community in den letzten Jahren entworfen und erstellt.
und sind allesamt eine gute Wahl wenn es darum geht, Ihre erste Website zusammenzubauen und
sich mit der Funktionsweise des Drupal-Kernsystems besser vertraut zu machen.

Drupal ist ein gut etabliertes CMS, so dass der Markt für 3rd-Party-Themes - sowohl für kostenlose
und kodtenpflichtige - sehr robust ist.

Wenn keine der 3rd-Party-Optionen Ihren Bedürfnissen entspricht, müssen Sie ein benutzerdefiniertes
Theme erstellen. Ein benutzerdefiniertes Theme kann so einfach wie eine einzelne CSS-Datei sein, die das Styling das Styling des vom Kernsystem bereitgestellten Markups verändert. Eine Anleitung zum Erstellen benutzerdefinierter Themes für Drupal 8 finden Sie auf der
https://www.drupal.org/docs/8/theming[_Drupal.org_ Community-Dokumentationsseite
"Theming Drupal (englisch)"].

==== Verwandte Themen

* <<extend-theme-find>>
* <<extend-theme-install>>
* <<understanding-modules>>

==== Zusätzliche Ressourcen

https://www.drupal.org/docs/8/theming[_Drupal.org_ Community-Dokumentationsseite
"Theming Drupal (englisch)"]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/jgrubb[John Grubb] und
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
