[[understanding-modules]]
=== Konzept: Module

[role="summary"]
Überblick über die Module und die Funktionalität, für die sie verwendet werden können.

(((Module,overview)))
(((Contributed module,overview)))
(((Core module,overview)))
(((Field module,overview)))
(((Field UI module,overview)))
(((Menu UI module,overview)))
(((Node module,overview)))
(((User module,overview)))
(((Views module,overview)))
(((Views UI module,overview)))
(((Module,core)))
(((Module,contributed)))
(((Module,Field)))
(((Module,Field UI)))
(((Module,Menu UI)))
(((Module,Node)))
(((Module,User)))
(((Module,Views)))
(((Module,Views UI)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Was ist ein Modul?

Ein Modul ist ein Satz von PHP-, JavaScript- und/oder CSS-Dateien, der die Website
Features und zusätzliche Funktionalität. Sie können die Features und Funktionen einschalten
durch _Installation_ des Moduls, und Sie können es durch _Deinstallation_ der
Modul; vor der Deinstallation müssen Sie möglicherweise Daten und Konfiguration entfernen
die sich auf das Merkmal oder die Funktionalität beziehen. Jedes Modul, das installiert wird, fügt hinzu
die Zeit, die benötigt wird, um Seiten auf Ihrer Website zu generieren, daher ist es eine gute Idee
deinstallieren Sie Module, die nicht benötigt werden.

Der Kerndownload bietet Module für Funktionen wie

* Verwaltung von Benutzerkonten (das Kernmodul User)

* Verwaltung des grundlegenden Inhalts (das Kern-Knoten-Modul) und der Felder (das Kern-Feld und
Feld-UI-Module; es gibt auch Kernmodule, die Feldtypen bereitstellen)

* Verwaltung von Navigationsmenüs (das Kernmodul der Menü-Benutzeroberfläche)

* Erstellen von Listen, Gitternetzen und Blöcken aus vorhandenen Inhalten (die Kernansichten und
Ansichten der UI-Module)

Sie können zusätzliche _beitragspflichtige Module_ von der
https://www.drupal.org/project/project_module[_Drupal.org_ Modul-Downloads], oder erstellen Sie Ihr eigenes
_benutzerdefinierte Module_.

==== Verwandte Themen

* <<understanding-themes>>
* <<understanding-distributions>>
* <<config-uninstall>>
* <<extend-module-find>>
* <<extend-module-install>>
* <<security-concept>>
* <<security-update-module>>

==== Zusätzliche Ressourcen

https://www.drupal.org/developing/modules[_Drupal.org_ Community-Dokumentationsseite "Leitfaden für Modulentwickler"]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
