[[understanding-project]]

=== Konzept: Das Drupal-Projekt

[role="summary"]
Overview of Free and Open Source Software (FOSS), Drupal project, and Drupal
Association.

(((Drupal project,overview)))
(((Drupal Association,overview)))
(((FOSS (Free and Open Source Software),overview)))
(((Free and Open Source Software (FOSS),overview)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Was ist freie und quelloffene Software?

Freie und Open-Source-Software (FOSS) ist Software, die von einer
Gemeinschaft von Personen entwickelt wird, die sich dazu entschiedne hat, disee Software unter einer nicht-kommerziellen Lizenz zu veröffentlichen und deren _Quelltext_ (die Programmdateien, aus denen die Software besteht) frei verfügbar ist. Für
weitere Informationen über die von Drupal verwendete nicht-kommerzielle Lizenz, siehe:
<<understanding-gpl>>.

==== Was ist das Drupal-Projekt?

Das Drupal-Projekt ist ein FOSS-Projekt, dessen Zweck es ist, das Kernsystem
der Content-Management-System-Software Drupal sowie von der Community bereitgestellte Zusatzmodule und, zusätzliche
Themes sowie Übersetzungen, die Dokumentation und auf bestimmte Zwecke zugeschnittene Distributionen bereitzustellen.
Die Menschen, die Dem Projekt Drupal ihre Zeit und ihr Geld zur Verfügung stellen, kommen aus der ganzen Welt und sind eine vielfältige Gemeinschaft, die sich den oben genannten Zwecken verschrieben hat.

Die Community umfasst viele kleinere Gruppen, die viele verschiedene Aufgaben erfüllen.
Zu diesen aufgaben zählt z.B. die Entwicklung eines bestimmten Teils von Drupal, das Schreiben der 
Dokumentation, die Aufrechtung der Sicherheit des Content-Managesystems Drupal, Das Übersetzen von Drupal
in eine bestimmte Sprache. Außerdem prüft die Community Anwendungszwecke für Drupal und stellt entsprechende Distributionen bereit und trifft sich regelmäßig Nicht nur Online, sondern auch offline.

Weitere Informationen darüber, wie Sie sich mit der weltweiten
Community verbinden können finden Sie iin folgenden Abschnitten: <<thoughts-connecting>> und <<thoughts-support>>.

==== Was ist die Drupal Association?

Die https://www.drupal.org/association[Drupal Association] ist eine gemeinnützige Organisation.
die sich der Unterstützung des Drupal-Projekts und der Community widmet. Die Hauptaufgaben der Drupal Association
sind:

* Das Veranstalten großer Kongresse auf der ganzen Welt.
* Die Wartung der Website_Drupal.org_ sowie die der daran angeschlossenen Seiten und der Server, auf denen diese laufen.
* Die Förderung von Drupal als Web-Plattform.
* Die Unterstützung bei Schulungen und Trainings rund um Drupal.
* Die Bereitstellung von Zuschüssen für die Drupal-Community zur Unterstützung ihrer Mission.
* Die Geldbeschaffung für diese Zwecke.

==== Verwandte Themen



* <<understanding-gpl>>
* <<security-concept>>
* <<thoughts-connecting>>
* <<thoughts-support>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/governance[Drupal-Projekt-Governance]
* https://www.drupal.org/dcoc[Drupal-Verhaltenskodex]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
