[[understanding-distributions]]

=== Konzept: Distributionen

[role="summary"]
Übersicht über Distributionen, die zur Einrichtung von Websites für bestimmte
Zwecke dienen.

(((Distribution,overview)))
(((Distribution,full-featured)))
(((Distribution,quick-start)))
(((Full-featured distribution,overview)))
(((Quick-start distribution,overview)))

==== Erforderliche Vorkenntnisse

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>

==== Was sind Distributionen?

_Distributionen_ bieten Website-Features und -Funktionen für einen bestimmten Website-Typ
als ein einziger Download, der die Kern-Software, beigetragene Module und Themes enthält,
und vordefinierte Konfiguration. Eine Verteilung ermöglicht das Einrichten einer
komplexe Website für einen bestimmten Zweck, in weniger Schritten als die Installation und
Elemente individuell zu konfigurieren.

Es gibt zwei Haupttypen von Distributionen:

Voll funktionsfähige Distributionen::
  Eine Full-Featured-Distribution ist ein Projekt, das eine vollständige Lösung bietet.
  eine Website für einen speziellen Zweck einzurichten, z.B. für akademische oder geschäftliche Zwecke,
  Regierung, gemeinnützig, Verlagswesen, Sozialwesen usw. Beispielsweise könnten Sie eine
  bestehende Verteilung für Bauernmärkte, um Ihre eigene Website zu erstellen, oder Sie
  könnte Ihre Einrichtung für die Wochenmarkt-Website als Vertrieb für
  andere zu verwenden.

Andere Distributionen::
  Distributionen können auch Schnellstart-Tools sein, die Entwickler und Website
  Bauherren als Ausgangspunkt verwenden können.

==== Verwandte Themen

<<thoughts-connecting>>

==== Zusätzliche Ressourcen

https://www.drupal.org/project/project_distribution[_Drupal.org_ Drupal-Verteilung Downloads]


*Mitwirkende*

Adaptiert und herausgegeben von https://www.drupal.org/u/dianalakatos[Diána Lakatos]
und https://www.drupal.org/u/ifrik[Antje Lorch],
von https://www.drupal.org/docs/7/distributions["Ausschüttungen"]
und https://www.drupal.org/project/project_distribution["Herunterladen & Erweitern -- Verteilungen"]]
copyright 2000 - copyright_upper_year von den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Gemeinschaft].
