[[understanding-modules]]
=== Konzept: Module

[role="summary"]
Überblick über die Module und die Funktionalität, für die sie verwendet werden können.

(((Module,overview)))
(((Contributed module,overview)))
(((Core module,overview)))
(((Field module,overview)))
(((Field UI module,overview)))
(((Menu UI module,overview)))
(((Node module,overview)))
(((User module,overview)))
(((Views module,overview)))
(((Views UI module,overview)))
(((Module,core)))
(((Module,contributed)))
(((Module,Field)))
(((Module,Field UI)))
(((Module,Menu UI)))
(((Module,Node)))
(((Module,User)))
(((Module,Views)))
(((Module,Views UI)))

==== Erforderliche Vorkenntnisse

<<understanding-drupal>>

==== Was ist ein Modul?

Ein Modul ist ein Satz von PHP-, JavaScript- und/oder CSS-Dateien, der bestimmte neue Funktionen innerhalb einer 
Drupal-Website bereitstellt. Eine Neue Funktion, können Sie durch die _Installation_ eines zusätzlichen Moduls aktivieren Durch die _De-Installation_ eines Moduls, kann eine bestimmte Funktion auf Wunsch auch abgeschahlten werden. Vor der Deinstallation müssen Sie möglicherweise Daten und Konfiguration entfernen die mit der Funktionsweise eines Moduls in Zusammenhang stehehen. Jedes Modul, das installiert wird, erhöht die Ladezeit der Website. Daher ist es eine gute Idee, Module die nicht benötigt werden, zu deinstallieren, um die Ladezeit einer Website so kurz wie möglich zu halten.

Das Kernsystem bietet Module für Funktionen wie:

* Das Verwalten von Benutzerkonten (mittels des Kernsystemmoduls User),

* Das Verwalten des grundlegenden Inhalts (mittels des Kernsystemmoduls Node) und der im Inhalt enthaltennen Felder (mittiels der Kernsystemmodule Field und Field-UI. Es gibt auch Kernsystemmodule, die zusätzliche Feldtypen bereitstellen).

* Das Verwalten von Navigationsmenüs (mittels des Kernsystemmoduls Menu-UI)

* Das Erstellen von Listen, Rastern und Blöcken aus vorhandenen Inhalten (mittels der Kernsystemmodule Views und
Views-Ui).

Sie können die _von der Community bereitgestellten Zusatzmodule_ von der Website
https://www.drupal.org/project/project_module[_Drupal.org_ Modul-Downloads] herunterladen oder eigene
_benutzerdefinierte Module_ erstellen.

==== Verwandte Themen

* <<understanding-themes>>
* <<understanding-distributions>>
* <<config-uninstall>>
* <<extend-module-find>>
* <<extend-module-install>>
* <<security-concept>>
* <<security-update-module>>

==== Zusätzliche Ressourcen

https://www.drupal.org/developing/modules[_Drupal.org_ Community-Dokumentationsseite "Leitfaden für Modulentwickler"]


*Mitwirkende*

Geschrieben von https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
