[[user-admin-account]]

=== Konzept: Das Konto von Benutzer 1

[role="summary"]
Übersicht über das Konto User 1, auch bekannt als Root-Konto oder administratives Konto.

(((User,root)))
(((User,user one)))
(((User,administrative)))
(((Security,user one account)))

==== Erforderliche Vorkenntnisse

<<user-concept>>

==== Was ist das Konto des ersten Benutzers?

Während der Installation Ihrer Website haben Sie das erste Benutzerkonto erstellt. Jedes
Benutzerkonto hat intern eine numerische Benutzer-ID, und da die ID des zuerst erstellten Benutzerkontos 1 ist, 
wird es allgemein als _Benutzerkonto 1_ bezeichnet. Dieses Benutzerkonto ist ein spezielles Konto, 
denn dieses Benutzerkonto hat unabhängig von den ihm zugewisenen Rollen, die Möglichkeit, alle Aktionen auf der Website durchzuführen, einschließlich der Anzeige und
Bearbeitung des gesamten Inhalts,  der Bearbeitung jedes Benutzerkontos, und des Änderns der Konfiguration der Website.
Das Benutzerkonto darf auch Module installieren und deinstallieren und das Skript zur Aktualisierung der Website ausführen.

Aufgrund dieser Berechtigungsstufe bezeichnen einige Leute dieses Konto als
_Root-Benutzer_, ähnlich dem Benutzerkonto „root", das auf Linux-Betriebssystemen alle Berechtigungen eines Systemadministrators besitzt.

Es ist normalerweise besser, für jeden administrativen Benutzer ein gesondertes Benutzerkonto einzurichten,
und diesem die Rolle eines _Administrators_ zuzuweisen, anstatt allen Benutzern, mit administrativen Aufgaben, die Möglichkeit zu geben, sich über das erste Benutzerkonto der Installation anzumelden. Hierfür gibt es mehrere Gründe:

* Einige Aktionen und Aktualisierungen auf der Website werden protokolliert. Wenn mehrere Benutzer das selbe Benutzerkonto verwenden, ist es schwieriger nachzuvollziehen, welcher Benutzer eine Änderung durchgeführt hat, wenn sich aus einer solchen Änderung weitere Fragen ergeben.

* Die Berechtigungen der Rolle _Administrator_ können soo geändert werden, dass sie sicherer sind als dies beim Vollzugriff des ersten auf der Website angelegten Benutzerkontos der Fall ist. Auf diese Weise können Personen nicht versehentlich die Konfiguration von Funktionen der Website ändern, die nicht geändert werden sollten.

* Die Verantwortlichkeiten der Menschen, die gemeinsam eine Website betreuen, können sich mit der Zeit ändern. Für gewöhnliche Benutzerkonten kann eine solche Entwicklung über die Berechtigungen gespiegelt werden, indem man Benutzerkonten bestimmte Rollen zuweist oder ihnen diese wieder aberkennt. Wenn mehrere Benutzer das Benutzerkonto 1 verwenden, kann eine solche Entwicklung nicht abgebildet werden.

* Auf einigen Websites wird der Autor von Inhalten oder Kommentaren angezeigt oder aufgezeichnet. 
Wenn alle Benutzer dasselbe Benutzerkonto zur Erstellung von Inhalten verwenden, ist es schwierig nachzuvollziehen
wer den Inhalt erstellt hat.

Es ist nicht möglich, das Benutzerkonto mit der ID 1 über den Verwaltungsbereich, bzw die Benutzeroberfläche von Drupal zu löschen. 
Mittels einer Datenbankabfrage könnte das Benutzerkonto zwar entfernt werden, dies würde aber zu Problemen mit der Website führen. 
Daher ist es nicht ratsam, das Benutzerkonto mit der ID 1 zu löschen.
//===== Verwandte Themen

==== Zusätzliche Ressourcen

https://www.drupal.org/node/22284[_Drupal.org_ Community-Dokumentationsseite "Benutzerkonten und Rollen (englisch)"]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/mark-lacroix[Mark LaCroix]
und https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
