[[user-admin-account]]

=== Konzept: Das Konto von Benutzer 1

[role="summary"]
Übersicht über das Konto User 1, auch bekannt als Root-Konto oder administratives Konto.

(((User,root)))
(((User,user one)))
(((User,administrative)))
(((Security,user one account)))

==== Erforderliche Vorkenntnisse

<<user-concept>>

==== Was ist das Konto des ersten Benutzers?

Während der Installation Ihrer Website haben Sie das erste Benutzerkonto erstellt. Jedes
Benutzerkonto hat intern eine numerische Benutzer-ID, und da die ID des zuerst erstellen Benutzerkontos 1 ist, 
wird es allgemein als _Benutzerkonto 1_ bezeichnet. Dieses Benutzerkonto ist
speziell, denn unabhängig davon, welche Rollen ihm zugewiesen werden, hat sich jemand als
Benutzer 1 hat die Erlaubnis, alle Aktionen auf der Website durchzuführen, einschließlich der Anzeige und
Bearbeitung des gesamten Inhalts, Bearbeitung jedes Benutzerkontos, Änderung der Website-Konfiguration,
Installieren und Deinstallieren von Modulen und Ausführen des Aktualisierungsskripts.

Aufgrund dieser Berechtigungsstufe bezeichnen einige Leute dieses Konto als
_Root-Benutzer_, ähnlich dem "root"-Benutzerkonto, das voll administrativ
Berechtigungen in Linux und anderen Betriebssystemen.

Es ist normalerweise besser, getrennte Konten für jeden administrativen Benutzer einzurichten,
ihnen die Rolle des _Verwalters_ zu geben, anstatt alle administrativen
Benutzer melden sich mit dem Konto Benutzer 1 an. Dafür gibt es mehrere Gründe:

* Einige Aktionen und Aktualisierungen auf der Website werden protokolliert, und wenn alle dasselbe benutzen
Konto, ist es schwierig zu wissen, wer sie gemacht hat, wenn Sie Fragen haben.

* Die Berechtigungen der Rolle _Administrator_ können geändert werden, um sicherer zu sein als die
volle Berechtigungen des Benutzerkontos 1, so dass Personen nicht versehentlich
Website-Funktionen ändern, die nicht geändert werden sollten.

* Die Verantwortlichkeiten der Menschen auf einer Website können sich mit der Zeit ändern. Mit gewöhnlichem Benutzer
Konten, kann dies in Berechtigungen gespiegelt werden, indem man die Zuweisung oder Aufhebung der Zuweisung
Rollen zu ihren Benutzerkonten. Wenn sie alle das Benutzerkonto 1 verwenden,
das ist schwieriger.

* Auf einigen Websites wird der Autor von Inhalten oder Kommentaren angezeigt oder verfolgt, und
wenn alle dasselbe Konto zur Erstellung von Inhalten verwenden, ist es schwierig zu wissen
wer den Inhalt erstellt hat.

Es ist nicht möglich, das Konto Benutzer 1 aus dem administrativen Benutzer zu löschen.
Schnittstelle. Es wäre möglich, mit einer Datenbankabfrage zu tun, aber es könnte
Probleme auf Ihrer Website und ist nicht ratsam.

//===== Verwandte Themen

==== Zusätzliche Ressourcen

https://www.drupal.org/node/22284[_Drupal.org_ Community-Dokumentationsseite "Konten und Rollen"]


*Mitwirkende*

Geschrieben und herausgegeben von https://www.drupal.org/u/mark-lacroix[Mark LaCroix]
und https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
