[[user-concept]]

=== Konzept: Benutzer, Rollen und Berechtigungen

[role="summary"]
Überblick über Benutzerkonten, Berechtigungen und Rollen.

(((User,overview)))
(((Role,overview)))
(((User role,overview)))
(((Permission,overview)))
(((Anonymous user,overview)))
(((Authenticated user,overview)))
(((Administrative user account,overview)))

// ==== Erforderliche Vorkenntnisse

==== Was sind Benutzer?

Jeder, der Ihre Website besucht, ist ein _Benutzer_, auch Sie. Es gibt drei
Gruppen von Benutzern:

* Benutzer, die nicht angemeldet sind, oder _anonyme Benutzer_, auch _Gäste_ genannt

* Benutzer, die eingeloggt sind, oder _authentifizierte Benutzer_

* Das administrative Benutzerkonto, welches automatisch erstellt wurde, als Sie
Ihre Website installiert haben, oder auch _Benutzer 1_ genannt.
Siehe <<<user-admin-account>>.

==== Was sind Berechtigungen?

Die Möglichkeit, Aktionen auf der Website auszuführen (einschließlich der Anzeige von Inhalten, deren Bearbeitung und Änderungen von Konfigurationen) wird über _Berechtigungen_ geregelt. Jede
Berechtigung hat einen Namen (z.B. _Veröffentlichte Inhalte anzeigen_) und umfasst eine Aktion
oder eine kleine Teilmenge von Aktionen. Ein Benutzer muss über eine Berechtigung verfügen, um
die entsprechende Aktion auf der Website ausführen zu können. Die einzelnen Berechtigungen wereden 
jeweils durch das Modul definiert, das die mit der Berechtigung verbundene Aktion bereitstellt. 

==== Was sind Rollen?

Anstatt jedem Benutzer individuelle Berechtigungen direkt zuzuweisen, werden Berechtigungen
in _Rollen_ gruppiert. Sie können eine oder mehrere Rollen auf Ihrer Site definieren und
jeder Rolle die für die Rolle erforderlichen Berechtigungen zuweisen. Die Berechtigungen, für authentifizierte
Benutzer und Gäste sind in den Rollen _Angemeldeter Benutzer_ und _Gast_ enthalten.
Die Bezeichnungen und die Anzahl der vorhandenen _Rollen_ sind von dem bei der Installation der Website 
verwendeten Installationsprofil abhängig. Es kann auch eine Rolle mit der Bezeichnung _Administrator_ vorhanden sein, 
die automatisch über alle auf der Website vorhandenen Berechtigungen verfügt.

Jedem Benutzerkonto auf Ihrer Website wird automatisch die Rolle _Angemeldeter Benutzer_ zugewiesen.
Optional kann jedes Benutzerkonto mit einer oder mehrerne weiteren Rollen ausgestaettet werden. Wenn Sie
einem Benutzerkonto eine Rolle zuweisen, hat der Benutzer alle Berechtigungen die der jeweiligen Rolle zugewiesen wurden, sobald er sich auf der Website angemeldet hat.

In der Praxis hat sich gezeigt, dass es eine gut Idee ist, mehrere Rollen für eine Website einzurichten. Im Beispiel der Wochebmakt-Website 
könnte man sich beispielsweise folgende Rollen wünschen:

* Eine Rolle für Lieferanten, die es den Lieferanten ermöglicht, ihre eignes Profil zu bearbeiten.

* Eine Rolle für Inhaltsredakteure die es diesen Benutzern ermöglicht, die allgemeinen Seiten der Wochenmarkt-Website zu bearbeiten.

* Eine Rolle zur Verwaltung von Benutzern, mit der sich Benutzer, um die Verwaltung von ihrem Kundenkonto auf der Website kümmern könnnen.

* Die Rolle _Administrator_, die über das Installationsprofil Ihrer Website installiert wurde, dient erfahrenen Benutzern zur Verwaltung und Konfguration der Website.



==== Verwandte Themen

* <<user-new-role>>
* <<user-permissions>>
* <<user-roles>>
* <<user-new-user>>
* <<user-admin-account>>
* <<user-content>>

==== Zusätzliche Ressourcen

* https://www.drupal.org/node/120614[_Drupal.org_ Community-Dokumentationsseite „Benutzerkonten, Rollen und Berechtigungen" (englisch)]
* https://www.drupal.org/docs/7/managing-users[_Drupal.org_ Community-Dokumentationsseite „Benutzer verwalten"  (englisch)"]
* https://www.drupal.org/node/1803614[_Drupal.org_ Community-Dokumentationsseite „Benutzerrollen"  (englisch)]


*Mitwirkende*

Angepasst von https://www.drupal.org/u/mark-lacroix[Mark LaCroix],
https://www.drupal.org/u/batigolix[Boris Doesborg], und
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] aus
https://www.drupal.org/node/1803614["Benutzerrollen"],
copyright 2000 - copyright_upper_year von den einzelnen Mitwirkenden an der
https://www.drupal.org/documentation[Dokumentation der Drupal-Community].
