[[views-concept]]
=== Konzept: Verwendung von Ansichten

[role="summary"]
Übersicht über die Ansichten und die Daten, die durch sie angezeigt oder ausgegeben werden können.

(((View,overview)))
(((Views module,overview)))

==== Erforderliche Vorkenntnisse

* <<planning-modular>>
* <<planning-data-types>>

==== Was ist eine Ansicht?

Eine _Ansicht_ ist eine Auflistung von Inhalten auf einer Website. Das Kernsystemmodul Views kümmert sich um die
Anzeige von Ansichten (Views), und das Kernsystemmodul Views-UI ermöglicht Ihnen das Erstellen und Bearbeiten
solcher Ansichten im Verwaltungsbereich von Drupal. Wenn Sie Ansichten definieren, sind Sie daran interessiert
Daten aus Ihrer Website zu entnehmen und dem Benutzer anzuzeigen.

==== Welche Arten von Daten können über Ansichten angezeigt werden?

Sie können Ansichten anlegen, um praktisch jede Inhaltsentität auszugeben, die in dem 
System gespeichert ist. Sie können z. B. die folgenden Listen für die Lieferanten auf der Website des Wochenmarktes 
erstellen:

* Eine Liste von Verkäufern
* Eine Liste der auf der Website vorhandenen Rezepte.
* Eine Liste der neuesten Inhalte auf der Website.
* Eine Liste der Benutzer, die auf der Website registiert sind.

===== Welche Möglichkeiten der Datenausgabe über Ansichten gibt es?

Eine mittels einer Ansichterstellte Auflistung kann in einer der folgenden Formen vorliegen:

* Tabelle mit sortierbaren Feldern
* Raster-Layouts
* Anrisstext oder Bilder, die auf Artikel verweisen
* Blöcke
* JSON-Ausgabe
* RSS-Feeds
* Kalender
* Slideshow auf dem Bildschirm

==== Verwandte Themen

* <<views-parts>>
* <<views-create>>

// ==== Zusätzliche Ressourcen


*Mitwirkende*

Geschrieben und herausgegeben von
https://www.drupal.org/u/michaellenahan[Michael Lenahan] bei
https://erdfisch.de[erdfisch], und
https://www.drupal.org/u/jojyja[Jojy Alphonso] bei
http://redcrackle.com[Rotes Knistern].

Ins Deutsche übersetzt von https://www.drupal.org/u/Joachim-Namyslo[Joachim Namyslo].
