<?php

/**
 * @file
 * Form alters for making screenshots.
 *
 * Note that this module, if enabled, must be given a higher weight in
 * core.extension config than the locale module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for language_admin_add_form().
 */
function screenshot_alters_form_language_admin_add_form_alter(&$form, FormStateInterface $form_state) {
  // Remove the custom submit that the locale module added, to avoid bulk
  // operations.
  $form['predefined_submit']['#submit'] = array_diff(
    $form['predefined_submit']['#submit'],
    ['locale_form_language_admin_add_form_alter_submit']);
}
