<?php

/**
 * @file
 * Fixes and alters for running tests and making screenshots.
 *
 * Note that this module must be given a higher weight in core.extension config
 * than the locale module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for language_admin_add_form().
 */
function screenshot_alters_form_language_admin_add_form_alter(&$form, FormStateInterface $form_state) {
  // Remove the custom submit that the locale module added, to avoid bulk
  // operations.
  $form['predefined_submit']['#submit'] = array_diff(
    $form['predefined_submit']['#submit'],
    ['locale_form_language_admin_add_form_alter_submit']);
}

/**
 * Implements hook_module_preinstall().
 *
 * Fools the locale module into not doing its batch.
 */
function screenshot_alters_module_preinstall($module) {
  if (!drupal_installation_attempted()) {
    // This makes drupal_installation_attempted() return TRUE, so the locale
    // module will not run its batch.
    $GLOBALS['install_state'] = ['foo'];
  }
}

/**
 * Implements hook_page_attachments().
 *
 * Adds the CSS library that turns off transitions, to avoid random test
 * fails. This can be removed if
 * https://www.drupal.org/project/drupal/issus/2901792
 * is fixed.
 */
function screenshot_alters_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'screenshot_alters/screenshot_disable_transitions';
}
