[[understanding-project]]

=== 概念：Drupal 项目

[role="summary"]
自由及开放源代码软件（FOSS）、Drupal 项目以及 Drupal 协会概述。

(((Drupal 项目,overview)))
(((Drupal 协会,overview)))
(((FOSS (自由及开放源代码软件),概述)))
(((自由及开放源代码软件 (FOSS),概述)))

==== 预备知识

<<understanding-drupal>>

==== 什么是自由及开放源代码软件？

自由和开源软件（FOSS）是由一种由社区的人共同开发，以非商业许可进行发布，其源代码（组成软件的
程序文件）可以免费获取的软件。关于 Drupal 使用的非商业许可证的更多信息，请查看<<understanding-gpl>>。

==== 什么是 Drupal 项目？

Drupal 项目是一个 FOSS 项目，它的目的是开发内容管理核心软件，以及模块，主题、翻译、文档和
发行版。为 Drupal 项目贡献时间和金钱的人来自世界各地，因为这个共同目的相聚在这个多元化的社区。

社区包括许许多多小的群组，他们执行许多不同的任务，比如开发一小块 Drupal 相关的软件、写作文档、
维护 Drupal 软件的安全、翻译 Drupal 软件、以及因为使用 Drupal 的一些特定目的，聚集在一个
特定地理区域亲自见面。

有关如何与世界范围内的社区建立连接和进行沟通，请查看 <<thoughts-connecting>> 和 <<thoughts-support>>。

==== 什么是 Drupal 协会？

https://assoc.drupal.org[Drupal 协会] 是一个致力于 Drupal 项目和社区的非营利性组织。
它的主要功能有：

* 负责世界范围内的大型 Drupal 会议
* 维护 Drupal.org 及其服务器
* 推广 Drupal 作为一个网络平台
* 支持 Drupal 教育和培训
* 为 Drupal 社区提供资助以支持其使命
* 为这些目的筹集资金

==== 相关话题

* <<understanding-gpl>>
* <<security-concept>>
* <<thoughts-connecting>>
* <<thoughts-support>>

==== 相关资料

* https://www.drupal.org/governance[Drupal 项目管理]
* https://www.drupal.org/dcoc[Drupal 行为准则]


*贡献者*

写作： https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

翻译： https://www.drupal.org/u/jungle[冉强军] @ https://intergreat.com[InterGreat Education Group]
