[[attributions]]
=== Автори посібника

[role="summary"]
Перелік учасників, які беруть участь в управлінні проєктом та написанні
й редагуванні посібника.

(((Автори вмісту цього документу)))
(((Автори цього документу)))
(((Авторські права цього документу)))

Цей посібник написаний учасниками проєкту з відкритим кодом Drupal.
і ліцензований у відповідності з ліцензією
https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0]. Більше відомостей дивіться у
<<copyright>>. Подробиці учасників роботи над посібником наведені нижче. У кожному розділі в кінці
вказані автори тексту, редактори та/або перекладачі відповідного розділу.


==== Керування проєктом оригінального тексту (English, Drupal 8)

Створення початкової версії цього посібника координувалося наступними
особами:

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] - Коородинація учасників та 
керівництво проєктом

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] - Перевірка вмісту

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] - Перевірка вмісту

* https://www.drupal.org/u/ifrik[Antje Lorch] - Перевірка вмісту


==== Написання, редагування та перевірка оригінального тексту

Наступні особи приймали участь у написанні посібника:

* Написання та адаптація глосарію
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
з частин https://www.drupal.org/docs/7/understanding-drupal/glossary["Glossary"],
https://www.drupal.org/node/2120523["Overview of Configuration (vs. other
types of information)"], та
https://www.drupal.org/docs/8/theming-drupal-8/working-with-breakpoints-in-drupal-8["Working with
breakpoints in Drupal 8"],
авторські права кожної частини 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation].

* Зміст покращений та курувався
https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst].

* Огляд розділів написаний
https://www.drupal.org/u/jojyja[Jojy Alphonso] з
http://redcrackle.com[Red Crackle].


Написання посібника було здійснено наступними особами:

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] з
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst]

* https://www.drupal.org/u/ifrik[Antje Lorch]

* https://www.drupal.org/u/balu-ertl[Balu Ertl]

* https://www.drupal.org/u/batigolix[Boris Doesborg]

* https://www.drupal.org/u/cleverington[Charles Leverington]

* https://www.drupal.org/u/chishah92[chirag shah]

* https://www.drupal.org/u/gdunham[Grant Dunham]

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] з
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/jojyja[Jojy Alphonso] з
http://redcrackle.com[Red Crackle] -- відредагував більшу частину
цього посібника

* https://www.drupal.org/u/kamalkantpansari[Kamal Kant Pansari] з
http://www.intelliswift.com/[Intelliswift]

* https://www.drupal.org/u/michaellenahan[Michael Lenahan]
з https://erdfisch.de[erdfisch]

* https://www.drupal.org/u/swarad07[Swarad Mokal] з
http://www.blisstering.com[Blisstering Solutions]


Вміст був перевірений:

* https://www.drupal.org/u/zachcarter[Zach Carter]

* Спринт був огранізований https://groups.drupal.org/spokane-wa["Spokane
Drupal User Group" у groups.drupal.org], зі студентами програми Web Development
Certificate в http://scc.spokane.edu[Spokane Community College]


==== Зображення

Більшість зображень у посібнику є знімками екрану системи Drupal,
що згенероване програмою, котру написала
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Слово Drupal, логотип Druplicon (що з'являється як частина кількох зображень
в усьому посібнику), і слово з логотипа Drupal (яке є частиною обкладинки посібника), є
https://www.drupal.org/about/media-kit/logos[зареєестрованими торговими марками Dries Buytaert]).

Зображення обкладинки є ліцензованою за CC BY-SA 2.0 ілюстрацією від
https://www.drupal.org/u/mndonx[Amanda Luker] з
https://www.advomatic.com/[Advomatic].

Логотип Anytown Farmers Market, що з'являється як частина кількох зображень
у всьому посібнику, є ліцензованою за CC BY-SA 2.0 ілюстрацією
від Justin Harrell з https://drupalize.me/[Drupalize.Me].

Зображення бджоли, що з'являється як частина кількох зображень
у всьому посібнику, є суспільним здобутком, створеним
https://en.wikipedia.org/wiki/User:Severnjc[John Severns] для
https://en.wikipedia.org/wiki/Main_Page[English Wikipedia project] і отримане з
https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg[Wikimedia Commons].

Зображення бджоли, що з'являється як частина кількох зображень
у всьому посібнику, є суспільним здобутком, створеним Xianmin Chang і отримане з
https://commons.wikimedia.org/wiki/File:Bere%26ModernBarley.jpg[Wikimedia Commons].

Зображення салату, що з'являється як частина кількох зображень
у всьому посібнику, є суспільним здобутком, створеним
https://www.goodfreephotos.com/[Yinan Chen] і отримане з
https://commons.wikimedia.org/wiki/File:Gfp-salad.jpg[Wikimedia Commons].

Зображення моркви, що з'являється як частина кількох зображень
у всьому посібнику, є суспільним здобутком 
https://www.ars.usda.gov/oc/images/photos/nov04/k11611-1/[K11611-1], створеним
Stephen Ausmus для
https://en.wikipedia.org/wiki/Agricultural_Research_Service[Agricultural Research Service of the United States Department of Agriculture] і отримане з
https://commons.wikimedia.org/wiki/File:Carrots_of_many_colors.jpg[Wikimedia Commons].

==== Переклад українською мовою

Український переклад цього посібника координований:

* https://www.drupal.org/u/podarok[Andrii Podanenko]

* https://www.drupal.org/u/anprok[Andrii Prokopenko]

Переклад українською виконано

* https://www.drupal.org/u/alexmazaltov[Oleksii Bondarenko]
