[[block-concept]]

=== Основи: Блоки

[role="summary"]
Огляд блоків.

(((Блок, огляд)))

// ==== Prerequisite knowledge

==== Що таке блок?

_Блоки_ є окремими частинами макета веб-сторінки вашого сайту. Вони розміщуються
всередині регіонів (дивіться <<block-regions>>) вашої теми, і можуть бути створені,
видалені, і переміщені в _Схемі блоків_ (_admin/structure/block_)
адміністративної сторінки. Приклади блоків включають в себе список _Хто на сайті_,
меню основної навігації, і хлібні крихти. Зміст головної сторінки також
є блоком.

Деякі модулі роблять нові блоки доступними для розміщення на вашому сайті. наприклад,
коли модуль ядра Search встановлений і налаштований, він забезпечує блок,
який містить форму пошуку. Ви також можете створити і розмістити свої власні
блоки.

Кожен блок має свої налаштування, які дозволяють вибрати
на яких сторінках вашого сайту буде відображатися блок. Також можна розмістити
кілька копій блоку, кожна зі своєю конфігурацією і
правилами видимості.

==== Схожі теми

* <<block-regions>>
* <<block-create-custom>>
* <<block-place>>

// ==== Additional resources


*Автори*

Адаптовано https://www.drupal.org/u/les-lim[Les Lim] з
https://www.drupal.org/docs/core-modules-and-themes/core-modules/block-module/managing-blocks["Managing blocks "]
авторські права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переклав https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].