[[content-paths]]

=== Основи: шляхи, синоніми URL і URL-адреси

[role="summary"]
Огляд шляхів, синонімів і URL-адрес (з прикладами)

(((Шлях, огляд)))
(((Синонім, огляд)))
(((URL (Uniform Resource Locator), огляд)))
(((Uniform Resource Locator (URL), огляд)))
(((URL синонім, огляд)))

// ==== Prerequisite knowledge


==== Що таке URL?

URL - це абревіатура від "Uniform Resource Locator", який є
адресою сторінки в мережі. Це "ім'я", за яким браузер ідентифікує
сторінку, На прикладі "Відвідайте нас за адресою _example.com_",
_example.com_ - це URL-адреса головної сторінки вашого веб-сайту. Відвідувачі
використовують URL-адреси для знаходження інформації в мережі.

==== Що таке шлях?

Шлях - це унікальна, остання частина URL для певної функції або частини
вмісту. Наприклад, для сторінки з повним URL _http://example.com/node/7_
шляхом є _node/7_.

Ось кілька прикладів шляхів, які ви можете зустріти на вашому сайті:

* _node/7_
* _taxonomy/term/6_
* _admin/content/comment_
* _user/login_
* _user/3_

==== Що таке синонім?

Програмне забезпечення ядра має функцію під назвою "Синоніми URL",
яка дозволяє вам дати більш зрозумілу назву вмісту. Отже, якщо у
вас є сторінка "About Us" з шляхом _node/7_, ви можете налаштувати псевдонім
так, щоб ваші відвідувачі бачили його як _http://www.example.com/AboutUs_.
Цю функціональність забезпечує модуль ядра Path, який підтримує
синоніми в URL.

==== Пов'язані поняття

* <<content-create>>
* <<content-edit>>

// The following topic has been deferred, so remove the link for now.
// @todo Put this link back in when/if the topic gets added back.
// * <<structure-pathauto>>


// ==== Additional resources


*Автори*

Адаптовано https://www.drupal.org/u/dianalakatos[Diána Lakatos] з
https://pronovix.com/[Pronovix] з
https://www.drupal.org/node/120631["URL aliases"], і
https://www.drupal.org/docs/7/understanding-drupal/url-paths["URL paths"]
авторські права 2000-copyright_upper_year за окремими учасниками, що роблять свій внесок у
https://www.drupal.org/documentation[Drupal Community Documentation]

Переклав https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].
