[[extend-config-versions]]

=== Синхронізація Версій Конфігурацій

[role="summary"]
Як синхронізувати конфігурацію між сайтом в розробці і діючим сайтом, використовуючи модуль ядра Drupal Configuration Manager.

(((Конфігурація, синхронізація між розробляємим і діючим сайтом)))
(((Розробка сайту, синхронізація з діючим сайтом)))
(((Діючий сайт, синхронізація із технічно розробляємим сайтом)))
(((Модуль Configuration Manager, який використовується для синхронізації конфігурації між сайтом в розробці і діючим сайтом)))
(((Модуль, Configuration Manager)))

==== Мета

Синхронізація конфігурації між розробляємим і діючим сайтом.

==== Необхідні знання

* <<understanding-data>>
* <<install-prepare>>
* <<install-dev-sites>>
* <<install-dev-making>>

==== Вимоги до сайту

* У вас повинна бути копія в розробці вашого діючого сайту. Дивіться
<<install-dev-making>>.

* Модуль ядра Drupal Configuration Manager повинен бути встановлений як на сайті
розробки, так і на діючому сайті. Дивіться <<config-install>> для інструкції як
встановити модуль ядра.

* Повинно бути, ви змінили конфігурацію на діючому сайті або на сайті розробки(_вихідний сайт_), і хочете синхронізувати зміни з іншим сайтом
(_кінцевий сайт_). Як приклад, ви можете розробити новий тип контенту,
поля(fields), і види(views) на вашому сайті розробки, і коли це все працює
правильно, ви хочете розгорнути зміни на кінцевому діючому сайті.

* Вся конфігурація, яка не повинна бути синхронізована між вихідним і
кінцевим сайтами повинна зберігатися в конфігураційному перевизначеному _settings.php_ файлі, а не в базі даних. Дивіться <<install-dev-making>>.

==== Кроки

. У вихідному сайті, в _Керування_ адміністративного меню, перейдіть в
_Конфігурація_ > _Розробка_ > _Синхронізація конфігурації_ > _Експорт_
(_admin/config/development/configuration/full/export_).

. Натисніть _Експорт_. Ваш сайт згенерує архів повної конфігурації
сайту. Збережіть файл на вашому локальному комп'ютері.

. В кінцевому сайті, в _Керування_ адміністративного меню, Перейдемо в
_Конфігурація_ > _Розробка_ > _Синхронізація конфігурації_ > _Імпорт_
(_admin/config/development/configuration/full/import_).

. Знайдіть завантажений архів конфігурації, і натисніть _Завантажити_. Ваш
конфігураційний архів буде завантажений на кінцевий сайт, і ви будете
перенаправлені на сторінку конфігурації _Синхронізувати_
(_admin/config/development/configuration_) з повідомленням про те, що ваші файли були
завантажені.

. Переконайтеся, що відмінності, показані на сторінці, відповідають вашим очікуванням. Ви можете побачити
елементи конфігурації, які були додані, видалені або змінені; для змінених
елементів, ви можете натиснути _Переглянути зміни_ щоб побачити різницю.

. Коли ви будете задоволені, натисніть _Імпортувати все_ щоб імпортувати зміни
конфігурації.

==== Поліпшіть своє розуміння

* Якщо внесені зміни стосуються тільки одного елемента конфігурації (наприклад одного виду(view)), ви можете використовувати одну конфігурацію export/import можливість для розгортання змін між сайтами. Дивіться <<extend-deploy>>.

* Після кроку, на якому ви експортуєте повну конфігурацію з вихідного сайту,
Ви можете розпакувати архів і зафіксувати це в системі контролю
версій, такій як Git, що відстежує зміни в конфігурації вашого сайту. дивіться
<<extend-git>>.

// ==== Related concepts

==== Відео

// Відео Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/dLUGQk8GKa0[title="Synchronizing Configuration Versions"]

// ==== Додаткові матеріали


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко].