[[install-requirements]]

=== Основи: Вимоги до сервера

[role="summary"]
Огляд вимог до сервера для установки і запуску Drupal.

(((Вимоги до установки, огляд)))
(((Вимоги до установки, місце на диску)))
(((Вимоги до установки, веб сервер)))
(((Вимоги до установки, база даних)))
(((Вимоги до установки, PHP мова програмування)))
(((Установка, ядро ​​Drupal)))
(((Ядро Drupal, Вимоги до установки)))
(((Місце на диску, Вимоги до установки)))
(((Веб сервер, Вимоги до установки)))
(((Apache веб сервер, вимоги до версії)))
(((Nginx веб сервер, вимоги до версії)))
(((Microsoft IIS веб сервер, вимоги до версії)))
(((База даних, вимоги до версії)))
(((MySQL база даних, вимоги до версії)))
(((PostgreSQL база даних, вимоги до версії)))
(((SQLight база даних, вимоги до версії)))
(((PHP мова програмування, вимоги до версії)))

// ==== Необхідні знання

==== Які вимоги для запуску ядра Drupal?

===== Місце на диску

Сумарне місце на диску, яке необхідно для вашого сайту необмежено, все
залежить від розміру вашого сайту. Основні файли для ядра Drupal займають близько 100 МБ
на веб сервері. Вам буде потрібно більше місця якщо ви встановлюєте додаткові модулі або
теми оформлення і вам також буде потрібно місце для зображень, бекапів та інших файлів що генеруються і завантажуються на ваш сайт. База даних також використовує місце на диску, хоча
зазвичай це не те саме місце де зберігається ядро (і в деяких випадках навіть не той же
сервер), що використовується для файлів сайту.

===== PHP

PHP 7.2 або вище. PHP повинен бути встановлений з мінімальним обмеженням на пам'ять в 64MB (налаштування memory_limit); і якщо ви
запускаєте кілька модулів на вашому сайті або використовуєте важкий по пам'яті PHP інструмент для командного рядка (такий як Composer), передбачається використовувати більше пам'яті, ніж може бути
необхідно.

Певні PHP розширення також необхідні; точний список необхідних PHP
розширень залежить від того як ви встановлюєте ядро Drupal і які модулі ви
використовуєте на своєму сайті. Головним чином, хостинг провайдери вже встановлюють всі
необхідні PHP розширення. Якщо ви хостите свій сайт самі або запускаєте ваш сайт
на вашому локальному комп'ютері, то вам буде видаватися повідомлення про помилку під час установки якщо яке-небудь
з необхідних PHP розширень відсутнє то ви повинні встановити його щоб
продовжити.

===== Веб сервер

Apache (Рекомендовано)::
  Apache найпоширеніший веб сервер. Ядро друпал буде працювати на
  Apache 2.x встановленому на UNIX / Linux, OS X або Windows, який має
  встановлений і включений mod_rewrite модуль. Конфігурація віртуального хоста Apache
  повинна містити налаштування _AllowOverride All_, щоб дозволяти файлу _.htaccess_
  працювати.
PHP локальний сервер::
  Ви можете тимчасово запускати локальний демо сайт на вашому комп'ютері використовуючи тільки PHP,
  без установки додаткового веб сервера.
Nginx::
  Nginx широко використовуваний веб сервер, який спеціалізується на багатопоточності,
  продуктивності та малому споживанні пам'яті. Ядро Drupal може використовувати Nginx 1.1 або
  вище що має бути встановлений на UNIX / Linux, OS X або Windows. ngx_http_rewrite_module
  повинен бути встановлений і включений.
Microsoft IIS::
  Microsoft IIS - це веб сервер і набір модулів розширень для використання
  на Microsoft Windows. Ядро Drupal може працювати з IIS 5, IIS 6 або IIS
  7 якщо PHP налаштований правильно. Тому що чисті URLи вимагають, щоб ви
  використовували сторонні продукти. Для IIS 7, ви можете використовувати модуль Microsoft URL
  Rewrite або сторонні рішення.

===== База даних

Використовуйте одну з наступних баз даних:

* MySQL - 5.5.3 (MariaDB 5.5.20, Percona 5.5.8) або вище з
InnoDB-сумісним первинним сховищем даних

* PostgreSQL - 9.1.2 або вище

* SQLite - 3.4.2 або вище. Тимчасові локальні демо сайти використовують SQLite, який
поставляється як частина PHP і не потребує встановлення окремого ПО для
бази даних.

//==== Пов'язані теми

==== Додаткові матеріали

* https://www.drupal.org/docs/system-requirements[_Drupal.org_ сторінка документації спільноти "System requirements"]
* https://secure.php.net/manual/en/configuration.php[PHP Runtime Configuration (PHP memory limit and other settings)]
* https://www.drupal.org/docs/official_docs/en/_local_development_guide.html[Installing a new Drupal application on your local machine]
* https://www.drupal.org/docs/official_docs/en/_evaluator_guide.html[Creating a Drupal demo application for evaluation purposes]


*Автори*

Адаптовано https://www.drupal.org/u/KarlKedrovsky[Karl Kedrovsky],
https://www.drupal.org/u/bemery987[Brian Emery], та
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] з
https://www.drupal.org/docs/system-requirements["System requirements"],
copyright 2000-copyright_upper_year by the individual contributors to the
https://www.drupal.org/documentation[Drupal Community Documentation].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].