[[install-prepare]]
=== Підготовка до встановлення

[role = "summary"]
Як завантажити Drupal і задовольнити вимоги по встановленню.

(((Завантаження, основне програмне забезпечення)))
(((Ядро Drupal, підготовка установки)))

==== Мета

Завантажити основне програмне забезпечення, і забезпечити всі необхідні умови.

==== Необхідні знання

* <<install-requirements>>

* <<install-tools>>

* <<install-decide>>

* Як встановити і налаштувати серверне програмне забезпечення (при установці на Ваш особистий
комп'ютер)

* Як налаштувати хостинг для стандартного веб-сайту

* Як створити базу даних

==== Вимоги сайту

Серверне програмне забезпечення повинно бути встановлено на комп'ютер, де ви плануєте розгорнути свій
сайт. Дивіться <<install-requirements>>.

Залежно від того, як Ви плануєте завантажити основне програмне забезпечення, можливо буде потрібно спершу встановити
додаткові інструменти до програмного забезпечення. Дивіться <<install-decide>> і <<install-tools>>.

==== Етапи

. Вибрати методи завантаження і установки основного програмного забезпечення, з
перерахованих в <<install-decide>>. Решта інструкції відносяться до
параметрів завантаження Composer та інтерактивної програми установки; якщо Ви вибрали
інші опції, програмне забезпечення повинно бути встановлено для Вас.

. Налаштування URL і хостингу для вашого сайту на сервері. Підтвердіть, що хостинг
працює, помістивши простий HTML-файл у веб-кореневий каталог хостингу,
і відвідавши URL для Вашого сайту.

. Створіть базу даних, разом з обліковим записом користувача бази даних з повним доступом.

. Завантажте файли основного програмного забезпечення в кореневий каталог, використовуючи метод,
який Ви вибрали. Дивіться <<install-decide>> для посилань на інструкції.

==== Розширте своє розуміння

Дивіться <<install-run>>, щоб запустити інтерактивну програму установки.

Крім того, Ви можете використовувати наступну Drush-команду, з каталогу,
в який Ви завантажили програмне забезпечення, де _DB_NAME_, _DB_USER_ і
_DB_PASS_ є обліковими даними Вашої бази даних (database credentials):

----
drush site:install standard --db-url = 'mysql://DB_USER:DB_PASS@localhost/DB_NAME' --site-name=example
----

// ==== Пов'язані концепції

==== Відео

// Відео з Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/7Aib3y9DM80[title="Preparing to Install"]

==== Додаткові ресурси

http://www.drush.org[Drush]


*Автори*

Написано і відредаговано https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] із
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
і https://www.drupal.org/u/jojyja[Jojy Alphonso] із
http://redcrackle.com[Red Crackle].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].
