[[install-dev-sites]]

=== Основи: Сайти для розробки

[role="summary"]
Огляд використання сайтів для розробки з прикладом робочого процесу для створення сайту.

(((Сайт для розробки, огляд)))
(((Робочий процес розгортання, огляд)))
(((Тестовий сайт, огляд)))
(((Установка, сайт для розробки)))
(((Установка, тестовий сайт)))

// ==== Prerequisite knowledge

==== Що таке сайт для розробки?

Сайти для розробки це різні копії одного і того ж сайту що використовуються для розробки,
оновлення та тестування сайту без ризику внесення змін на живий сайт.

Приклад робочого процесу з розгортанням сайтів для розробки зазвичай включає сайти
названі наступним чином:

Локальне оточення::
  Процес розробки починається з того, що розробники працюють над новим функціаналом, правкою
  багів, темізацією і конфігурацією на їх локальних сайтах.

Дев сайт::
  Розробники відправляють зміни, які вони робили на дев
  сайт. Для команди з більш ніж одного розробника, використовується зазвичай контроль версій.
  Git - це система контролю версій, яка відстежує, які зміни відбулися у всіх ваших
  файлах. Ви можете закомітити ці зміни в ваш репозиторій. Використання Git дозволяє
  членам команди працювати на одному і тому ж сайті без перезапису роботи кожного. це
  також робить можливим легко відкотити до попереднього стану
  перед внесеними змінами.

Тестовий сайт::
  Тестовий сайт може бути також використаний для тестування або перенесення змін для
  підтвердження клієнтом. QA (Quality Assurance, Контроль якості) і UAT (User Acceptance Testing, Тестування користувачами)
  найчастіше проводяться саме на тестовому сайті. Рекомендується мати той же контент
  що і на живому сайті на дев і тестових сайтах, щоб ви могли тестувати як
  новий функціонал буде працювати з існуючим контентом.

Живий сайт::
  Живий сайт викладений в Інтернет і доступний користувачам. Він містить нові зміни, які
  підтверджені як безпечні для перенесення на живий сайт.

Залежно від розмірів проекту, обсягу робіт, вимог і зацікавлених сторін, етапи з
вищеописаного процесу можуть бути видалені або додані додаткові етапи. Наприклад,
тестування сайту перед перенесенням правок на тестовий сайт, може бути додано окреме тестування функціоналу та інтерфейсу користувача.

==== Пов'язані теми

* <<install-dev-making>>
* <<planning-workflow>>
* <<extend-git>>

// ==== Additional resources

*Автори*

Написано і відредаговано https://www.drupal.org/u/dianalakatos[Diána Lakatos],
і https://www.drupal.org/u/jojyja[Jojy Alphonso] із
http://redcrackle.com[Red Crackle].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].