[[install-dev-making]]
=== Створення сайту для розробки

[role = "summary"]
Як створити копію живого сайту для розробки.

(((Сайт для розробки, створення)))
(((Тестовий сайт, створення)))

==== Мета

Зробити копію сайту, яка може бути використана для розробки нового функціоналу і тестування оновлень
на ньому.

==== Необхідні знання

<<install-dev-sites>>

==== Вимоги до сайту

* У вас повинен бути живий сайт в розробці, з якого ви хочете копію для
розробки.

* Якщо ви хочете використовувати Drush для деяких кроків в цьому завданні, Drush повинен бути
встановлено. Дивіться <<install-tools>>.

==== Кроки

. Пройдіть кроки з <<install-prepare>>, так щоб у вас був хостинг для
вашого сайту для розробки, ви повинні знати, де ваш корінь сайту (webroot) для вашого сайту для розробки і
мати порожню базу даних і користувача бази даних для вашого сайту для
розробки.

. Наступний крок, створіть дамп файл бази даних, з даними вашого сайту. Цей файл може бути великим, але
 є два способи скоротити розмір дампа::
+
  * Заархівуйте файл, використовуючи gzip або іншу утиліту для архівації.
  * Виключіть дані з таблиць кеша, використовуючи очищення цих таблиць. Це тимчасові дані і нам потрібна тільки
  структура таблиць.
+
Створіть дамп бази даних, використовуючи один з наступних методів:
+
  * Якщо ви використовуєте Drush, то використовуйте цю команду, яка буде включати тільки структуру
  а не контент таблиць кеша і використовуйте gzip для стиснення файлу дампа:
+
----
drush sql:dump --gzip --structure-tables-list="cache,cache_*" \
  --result-file='PATH/TO/BACKUPFILE.sql'
----
+
  * Якщо ви використовуєте MySQL і маєте доступ до командного рядка, то використовуйте цю
  команду після очищення таблиць кеша (з заміною на ім'я бази даних,
  користувача і пароля бази даних вашого сайту):
+
----
mysqldump -u'USERNAME' -p'PASSWORD' DATABASENAME | \
  gzip> PATH/TO/BACKUPFILE.sql.gz
----

  * Якщо ви використовуєте MySQL для бази даних і сервер вашого живого сайту має
  phpMyAdmin (який доступний для багатьох панелей управління хостингом),
  ви можете очистити таблиці кеша вибравши їх в списку таблиць phpMyAdmin
  і вибравши операцію _Очистити_ внизу сторінки.
  Тоді використовуйте вкладку _Експорт_ в phpMyAdmin для вивантаження в формат _SQL_, з
  стисненням _gzip_ для зменшення розміру файлу.

  * Використовуйте https://www.drupal.org/project/backup_migrate[Додатковий модуль Backup and Migrate]
  на живому сайті. Дивіться <<extend-module-install>> для інструкцій по
  установці додаткових модулів.
+
Зараз у вас є копія бази даних, що зберігається в файлі _BACKUPFILE.sql_. з міркувань
безпеки, уникайте зберігання цього файлу на вашому хостингу або на сервері всередині
кореня сайту Drupal. Це запобіжить отримання іншими людьми копії вашої
бази даних.

. Скопіюйте всі файли з кореня сайту вашого живого сайту в корінь сайту
для розробки. Якщо ви хочете використовувати Git для цього, тоді дивіться
<<extend-git>>.

. Відредагуйте файл _sites/default/settings.php_ на вашому сайті для розробки
в текстовому редакторі. Знайдіть рядки ближче до кінця файлу, які
містять ім'я бази даних, користувача і пароль, оновіть
їх відповідно до налаштування бази даних вашого сайту для розробки.
Рядки виглядають наступним чином (перед редагуванням):
+
----
$ Databases ['default']['default'] = [
  'database' => 'live_site_database_name',
  'username' => 'live_site_database_username',
  'password' => 'live_site_database_password',
  ...
----

. Перевірте, що ваш файл _settings.php_ має наступні налаштування, якщо має, тоді
ви повинні відредагувати їх відповідно до URL адреси вашого сайту для розробки, замість
адреси живого сайту:
+
----
$settings['trusted_host_patterns']
----

. Імпортуйте файл бази даних, який ви створили, в базу даних сайту для
розробки. Спробуйте один з наступних методів:
+
  * Якщо ви використовуйте MySQL для бази даних і ваш сервер живого сайту має встановлений
  phpMyAdmin (який доступний з багатьох панелей управоленія хостингів),
  використовуйте вкладку _Імпортувати_ в phpMyAdmin. Вам можливо буде потрібно перезапустити вкладку
  імпорту кілька разів, якщо ваша база даних була великою.

  * Якщо ви використовуєте MySQL і маєте доступ до командного рядка, то використовуйте цю
  команду (з заміною імені бази даних, користувача і пароля,
  якщо ви зробили файл копії стисненим в gzip, ви повинні спершу розархівувати
  його):
+
----
gunzip <PATH/TO/BACKUPFILE.sql.gz | \
  mysql -u'USERNAME' -p'PASSWORD' DATABASENAME
----
+
  * Якщо ви віддаєте перевагу використовувати Drush, то використовуйте наступну команду:
+
----
drush sql:query --file='PATH/TO/ BACKUPFILE.sql.gz'
----

. Якщо ваш сайт для розробки і живий сайт повинні мати різну конфігурацію, тоді
ви повинні використовувати перезаписані конфігурації у файлі _settings.php_. Змінна
_$config_ може допомогти перезаписати значення окремо від
стандартних даних конфігурації. Наприклад, вам може знадобитися ім'я сайту
"Ярмарок міста N" на живому сайті, але "Сайт Ярмарки міста N
для розробки" на сайті для розробки. Щоб це зробити, ви повинні мати
значення для живого сайту в конфігурації (в базі даних) і на
сайті для розробки в файлі settings.php, вам буде потрібно дописати:
+
----
$config['system.site']['name'] = "Сайт Ярмарки міста N для розробки";
----

==== Розширте своє розуміння

* Перевірте, що сайт для розробки працює коректно.

* Авторизуйтесь на сайті для розробки під адміністратором і очистіть кеш. дивіться
<<prevent-cache-clear>>.

* <<extend-deploy>>

* <<extend-git>>

// ==== Related concepts

==== Відео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/FSBNm4oAkaA[title="Making a Development Site"]

==== Додаткові матеріали

* https://www.drupal.org/docs/official_docs/en/_local_development_guide.html[Installing a new Drupal application on your local machine]
* https://www.drupal.org/docs/official_docs/en/_evaluator_guide.html[Creating a Drupal demo application for evaluation purposes]


*Автори*

Написано і змінено https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
https://www.drupal.org/u/eojthebrave[Joe Shindelar] з
https://drupalize.me[Drupalize.Me] і
https://www.drupal.org/u/jojyja[Jojy Alphonso] з
http://redcrackle.com[Red Crackle].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].