[[install-decide]]
=== Основи: Способи завантаження та устанвоки ядра програмного забезпечення Drupal

[role="summary"]
Огляд методів, якими ви можете завантажити Drupal.

(((Завантаження,ядро Drupal)))
(((Встановлення,ядро Drupal)))
(((Ядро Drupal,завантаження)))
(((Ядро Drupal,встановлення)))

==== Необхідні знання

* <<install-tools>>
* <<install-requirements>>
* <<understanding-distributions>>

==== Які методи доступні для завантаження Drupal?

Перед тим як ви зможете створювати свій сайт, вам необхідно спершу завантажити Drupal.
Залежно від ваших планів, є кілька способів як ви можете скачати ядро
Drupal:

Спробуйте безкоштовне онлайн демо::
  Якщо ви визначаєтесь використовувати чи ні Drupal для створення сайту, ви можете використовувати онлайн сервіс для отримання демо установки Drupal за 20 хвилин або навіть менше. дивіться статтю
  https://www.drupal.org/try-drupal[_Drupal.org_ page "Спробуй Drupal"].

Використовуйте установщик в один клік у вашого хостинг провайдера::
  Якщо ви вибираєте CMS доступну на вашому хостингу, ваш хостинг може мати документацію про те як встановити в один клік CMS яка вам потрібна. Дивіться
  https://www.drupal.org/association/supporters/hosting[_Drupal.org's_ Список хостингів що підтримують Drupal].

Використовуйте попередньо налаштоване середовище::
  Як використовувати попередньо налаштоване оточення або віртуальну машину, яка містить Drupal і всі необхідні бібліотеки для установки Drupal локально. Дивіться розділ для вашої операційної системи https://www.drupal.org/docs/develop/local-server-setup[_Drupal.org_ сторінка документації спільноти "Посібник з налаштування локального сервера"] з можливими варіантами.
  
Завантажте вручну з веб-сайту::
  Якщо ви плануєте створювати сайт без додаткових модулів, ви можете завантажити Drupal або дистрибутив, що містить ядро Drupal і додаткові модулі і теми оформлення з сайту Drupal.org. Дивіться інструкції <<install-manual>>.

Використовуйте Composer::
  Якщо ви плануєте використовувати інструмент Drush (див. <<install-tools>>), або якщо ви створюєте веб-сайт, який може використовувати модулі зі складними залежностями слід використовувати Composer для завантаження Drupal, оскільки Composer буде керувати залежностями правильно. Якщо ви почнете робити свій сайт із завантаження вручну, то ви зможете перейти на використання Composer для управління залежностями пізніше. Інструкції щодо завантаження та перетворення дивіться у розділі <<install-composer>>.

==== Що відбувається, коли я встановлюю Drupal?

_Встановлення_ Drupal означає встановлення таблиць баз даних, імені сайту та аккаунта адміністратора, після цього ви зможете створювати та використовувати ваш сайт.

==== Які методи доступні для встановлення Drupal?

Є кілька способів встановити Drupal:

Установка в один клік::
  Якщо ви вибрали онлайн демо або установщикик в один клік на вашому хостингу, Drupal буде встановлено автоматично.

Інтерактивна установка::
  Drupal має інтерактивну установку, яка показує кілька форм і після заповнення цих форм Drupal буде встановлений. Дивіться <<install-prepare>> і <<install-run>>.

Установка демо сайту::
Якщо ви завантажили Drupal на ваш локальний комп'ютер, ви можете швидко створити тимчасовий демо сайт використовуючи вбудований веб сервер і базу даних SQLite, які є частиною PHP. Команда для налаштування демо сайту описана наприкінці <<install-manual>>. В цьому випадку, вам не потрібно запускати інтерактивну установку.

Установка через командний рядок::
Інструменти командного рядка (дивіться <<install-tools>>) також можуть бути використані для виконання установки Drupal.

// ==== Related topics

// ==== Additional resources

*Автори*

Написано та відредаговано https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] із
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
та https://www.drupal.org/u/jojyja[Jojy Alphonso] із
http://redcrackle.com[Red Crackle].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].