[[language-concept]]

=== Основи: Інтерфейс користувача, Конфігурація і Переклад контенту

[role="summary"]
Огляд мов і перекладу на сайті.

(((Інтерфейс, переклад)))
(((Конфігурація, переклад)))
(((Контент, переклад)))
(((Переклад, огляд)))
(((Мови, огляд)))
(((Модуль, Language)))
(((Модуль, Content Translation)))
(((Модуль, Configuration Translation)))
(((Модуль, Interface Translation)))
(((Content Translation модуль, огляд)))
(((Configuration Translation модуль, огляд)))
(((Interface Translation модуль, огляд)))
(((Language модуль, огляд)))

==== Необхідні знання

* <<understanding-data>>
* <<understanding-modules>>
* <<planning-data-types>>

==== Які мови підтримує Drupal?

Базова мова для Drupal, який використовується на вашому сайті (Ядро Drupal, модулі та
теми оформлення) це англійська. Однак, використовуючи Drupal ви можете створювати сайт, де
мова за замовчуванням буде не англійська, в цьому випадку будь-хто хто переглядає сайт буде
бачити тільки цю мову (передбачається що сайт повністю перекладений). Ви також можете
використовувати Drupal для створення мультимовного сайту, з перемикачем мови,
який користувачі можуть використовувати для вибору їх переважної мови. Ви повинні
встановити модуль ядра Language для того щоб використовувати мову відмінну від
англійської на вашому сайті.

==== Що може бути перекладено на вашому сайті?

Є три типи інформації, яку ви можете перекласти, кожен має свій власний
метод для перекладу:

Текст призначеного для користувача інтерфейсу::
  Вбудований текст представлений в ядрі Drupal, модулях і темах оформлення. Цей текст може бути
  переведений з базової англійської мови на будь-яку іншу мову(и)
  вашого сайту. Зазвичай, перш ніж перекладати текст самому,
  ви можете завантажити переклади. Ви повинні включити модуль ядра Interface Translation,
  щоб перевести цей текст і модуль ядра Update Manager
  щоб автоматично завантажити переклади.
Текст конфігурації::
  Текст який відноситься до структури і початкових значень визначених у ядрі Drupal,
  у модулях і темах оформлення, однак тільки той який ви можете змінити. Наприклад це заголовки
  полів в ваших типах матеріалу, текст в шапці видів, ім'я вашого сайту і
  контент автоматичних емейл повідомлень, що сайт посилає. Після створення
  конфігураційного тексту на мові за замовчуванням на вашому сайті, ви можете перекласти його
  на інші мови. За замовчуванням конфігурація надана ядром Drupal,
  модулями і темами оформлення, включає переклад разом завантаженими перекладами для
  інтерфейсу користувача. Ви повинні включити модуль ядра Configuration
  Translation для перекладу цього тексту.
Текст в контенті і файли::
  Якщо ваш сайт багатомовний, ви можете зробити поля контенту на вашому
  сайті перекладними. Після створення контенту на одній мові, ви можете
  перекласти його на інші мови. Поля можуть містити текстову інформацію або
  завантажені дані або для кожного поля в кожному типі матеріалу, ви можете налаштувати чи буде
  воно перекладним чи ні. Ви повинні включити модуль ядра Content
  Translation для перекладу цього тексту.

==== Яка інформація залишиться англійською на моєму сайті?

Навіть якщо мова за замовчуванням на вашому сайті не англійська, ви будете все одно бачити
англійський текст для певних сторінок адміністратора при управлінні конфігурацією. Причина
по якій це так працює, ви повинні редагувати конфігурацію, а також базові,
неперекладні значення конфігурації; переклад конфігурації це окрема
операція. Наприклад, якщо ви зайдете на сторінку _Меню_, ви
побачите англійські назви меню (для меню, які налаштовані при установці
вашого сайту) і якщо ви натиснете на посилання _Редагувати меню_, ви зможете відредагувати
англійську назва і опис меню. Для редагування імені меню на іншій
мові, ви повинні включити модуль ядра Configuration Translation
і використовувати посилання _Переклад_ для редагування перекладної інформації меню.

==== Пов'язані теми

* <<language-add>>
* <<language-content-config>>
* <<language-content-translate>>
* <<language-config-translate>>

// ==== Additional resources


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].