[[menu-concept]]

=== Основи: Меню

[role="summary"]
Огляд концепції меню і різних меню, автоматично створених за допомогою стандартного
профілю установки ядра.

(((Меню, огляд)))
(((Меню, основна навігація)))
(((Меню, адміністрування)))
(((Меню, обліковий запис)))
(((Меню, підвал)))
(((Меню, власне)))
(((Адміністративне меню, огляд)))
(((Меню облікового запису, огляд)))
(((Меню підвалу, огляд)))
(((Власне, огляд)))

// ==== Prerequisite knowledge

==== Що таке меню?

Меню - це набір посилань (пунктів меню), що використовуються для навігації по
веб-сайту. Основний модуль меню в інтерфейсі користувача надає
засоби управління і налаштування системи меню. Меню в основному відображаються в
вигляді ієрархічного списку посилань. За замовчуванням, нові пункти меню поміщаються
у вбудоване меню під назвою _Основна навігація_, але адміністратори
також можуть створювати власні меню.

Стандартний профіль установки ядра містить п'ять меню:

Основна навігація::
  Посилання на розділи, призначені для відвідувачів сайту. Зазвичай вони
  створюються адміністраторами сайту.

Адміністрування::
  Посилання на адміністративні завдання. Це меню в основному містить посилання,
  що надаються модулями вашого сайта.

Меню облікового запису::
  Посилання на завдання, пов'язані з обліковим записом користувача, такі як _Мій обліковий запис_ і _Вихід_.

Підвал::
  Посилання на важливі сторінки сайту, призначені для підвалу (нижнього
  колонтитула). Зазвичай вони створюються адміністраторами сайту.

Інструменти::
  Посилання на завдання, необхідні відвідувачам сайту. Деякі модулі мають
  тут свої посилання.

Меню можна змінити наступним чином, використовуючи наступний функціонал
адміністрування меню:

* Створення нових власних меню.

* Додавання нових пунктів меню.

* Зміна порядку пунктів меню шляхом установки їх "ваги" або переміщення
на інше місце.

* Перейменування пунктів меню.

* Зміна заголовка посилання (підказка, що з'являється при
наведенні курсору миші на пункт меню).

* Переміщення пункту меню в інше меню шляхом редагування параметра
_Батьківське посилання_.

Пункт меню буде показаний відвідувачеві тільки в тому випадку, якщо у нього є
право на перегляд сторінки, на яку він посилається. Наприклад, пункти меню
адміністратора не відображається відвідувачам, котрі ввійшли в систему.

==== Пов'язані поняття

* <<menu-link-from-content>>

* <<menu-reorder>>

* Для відображення меню необхідно помістити блок, відповідного меню, в
регіон теми, див. <<block-concept>>, <<block-regions>> і <<block-place>>.
Стандартний профіль установки містить всі обумовлені меню, за винятком
меню Адміністрування в регіонах основної теми Bartik. Модуль Toolbar,
який встановлюється за допомогою стандартного профілю установки, відображає
меню Адміністрування; він також відображається за допомогою додаткового
модуля Admin Toolbar.

// ==== Additional resources


*Автори*

Написано і змінено https://www.drupal.org/u/ajayvi[Ajay Viswambharan],
https://www.drupal.org/u/jojyja[Jojy Alphonso] з
http://redcrackle.com[Red Crackle],
і https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].