[[planning-data-types]]
=== Основи: Сутності контенту і Поля

[role="summary"]
Огляд сутностей контенту і полів.

(((Сутність, огляд)))
(((Термін таксономії, огляд)))
(((Словник таксономії, огляд)))
(((Контент, тип сутності)))
(((Тип сутності, огляд)))
(((Підтип сутності, огляд)))
(((Блок, тип сутності)))
(((Тип сутності Коментар, огляд)))
(((Тип сутності Контактна форма, огляд)))
(((Форма тип сутності, огляд)))
(((Контент тип матеріал, огляд)))
(((Власний блок, тип сутності)))
(((Поле, огляд)))
(((Профіль користувача тип матеріалу, огляд)))
(((Модуль, Comment)))
(((Модуль, Contact)))
(((Модуль, Taxonomy)))
(((Модуль, User)))
(((Модуль, Node)))
(((Модуль, Custom Block)))
(((Модуль, File)))
(((Comment модуль, тип сутності)))
(((Contact модулів, тип сутності)))
(((Custom block модуль, тип сутності)))
(((Node модуль, тип сутності)))
(((Taxonomy модуль, тип сутності)))
(((User модуль, тип сутності)))
(((File модуль, тип сутності)))

==== Необхідні знання

* <<understanding-data>>
* <<understanding-modules>>

==== Що таке контент сутність?

_Контент сутність_ (або зазвичай просто, _сутність_) - це елементи даних контенту,
який може складатися з тексту, HMTL тексту, зображень, прикріплених файлів та інших типів даних,
які створені для відображення відвідувачам сайту. Контент сутності можуть бути
визначені через ядро ​​Drupal або модулями.

Контет сутності згруповані в _типи сутностей_, які створені для однакових цілей
і відображаються в по різному в різних місцях на сайті. Більшість типів
сутностей також розділені на _підтипи сутностей_, які є підрозділом
типу сутності і дозволяє створювати різні варіації в яких сутності використовуються і
виводяться. Нижче таблиця з деякими загальними типами контент сутностей:

[width="100%", frame="topbot", options="header", grid="rows"]
|=============================================
|Тип Сутності |Підтип сутності |Визначальний модуль |Головне використання

|Елемент контенту |Тип контенту |Node модуль
  |Контент створений для виведення в головних регіонах сайту на сторінках сайту
  |3+ |*Приклад:* На сайті прикладу міського ярмарку, ви можете мати контент
  типи для Основних сторінок, сторінок продавців і сторінок рецептів.

|Коментар |Тип коментаря |Comment модуль
  |Коментарі додаються до контент сутностей (зазвичай до Матеріалів)
  |3+ |*Приклад:* На сайті блозі, записи в блозі можуть містити коментарі. Вони не потрібні
  на сайті прикладі міського ярмарку.

|Профіль користувача |(немає) |User модуль
  |Дані відносяться до користувача з аккаунтом (з можливістю авторизації) на сайті
  |3+ |*Приклад:* Кожен сайт має щонайменше базовий профіль користувача з іменем користувача
  і E-mail; сайти соціальних мереж можуть мати складніші профілі користувача
  з набагато більшою кількістю інформації.

|Власний блок |Тип Блоку |Custom Block модуль
  |Текст і зображення маленькими шматочками, відображені в шапці сайту,
   підвалі або колонках
  |3+ |*Приклад:* На сайті міського ярмарку, ви можете розмістити години роботи
  і адресу в блок у колонці.

|Термін таксономії |Словник таксономії |Taxonomy модуль
  |Використовується для класифікації інших типів контенту
  |3+ |*Приклад:* На сайті прикладі міського ярмарку, ви можете класифікувати Рецепт
  матеріал за допомогою словника таксономії Інгредієнти, термінів таксономії, таких як
  Морква і Помідори. На сайті блозі, записи в блог можуть бути класифіковані
  використовуючи словник Теги та можливо також словник Категорії.

|Файл |(немає) |File модуль
  |Зображення або прикріплений файл, які відстежуються і керуються через сайт, часто
   прикладаються до інших типів контенту
  |3+ |*Приклад:* На сайті прикладі міського ярмарку, обидві сторінки Рецепт і Продавець
  можуть мати прикріплені зображення, які могли б (через панель адміністрування)
   управлятися як сутності Файлів через сайт.

|Контактна форма |Тип форми |Contact модуль
  |Форма яка дозволяє відвідувачам сайту зв'язатися з власником сайту
  |3+ |*Приклад:* Контактна форма потрібна на сайті прикладі міського ярмарку.

|=============================================

==== Що таке поле?

В межах сутності, дані зберігаються як окремі _поля_, кожне з яких
містить один тип даних, такі як форматований або звичайний текст, зображення або інші файли
або дані. Типи полів можуть бути визначені через ядро ​​Drupal або у модулях.

Поля можуть бути додані адміністратором для підтипу сутності, так що всі
сутності цього підтипу мають однаковий набір доступних
полів. Наприклад, Продавець тип матеріалу на сайті міського ярмарку
може мати поля для Ім'я продавця, логотипу, URL сайту і
опису, в той час як тип матеріалу _Основна сторінка_ може мати тільки поля для
заголовка і тексту. Коли ви створюєте або редагуєте сутності, ви
визначаєте значення для полів по сутності.

==== Пов'язані теми

* <<planning-structure>>
* <<content-create>>
* <<structure-content-type>>
* <<structure-taxonomy>>
* <<user-concept>>
* <<block-concept>>

// ==== Additional resources


*Автори*

Написано і відредаговано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]
і https://www.drupal.org/u/gdunham[Grant Dunham].

Перевів https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov].