[[planning-layout]]
=== Проектування макетів сайту

[role="summary"]
Як планувати навігацію і макети вашого сайту (мобільні та десктопні браузери).

(((Планування, макет сайту)))
(((Макет сайту, планування)))
(((Макет, планування)))

==== Мета

Планувати навігацію і макет сайту для мобільних і десктопних
браузерів.

==== Необхідні знання

* <<understanding-themes>>
* <<block-regions>>
* <<preface-scenario>>

// ==== Site prerequisites

==== Кроки

Це відмінна ідея планувати макети сайту перед тим як почати створення
сайту і додавати контент; але, ваш план може вимагати перегляду якщо ви
попередньо вже почали реалізовувати сайт або після того як ви вже створили сайт з деяким
неопублікованим контентом, виходячи з бюджету вашого проекту або з фідбеків(відгуків) клієнта.

. Створіть список інформації, яку ваш сайт повинен представляти відвідувачам. В
сценарії міського ярмарку, це може включати:
+
  * Адреса ярмарки, з планом проїзду і картою
  * Години і дні роботи ярмарку
  * Історія ярмарки
  * Список продавців
  * Подробиці про кожного з продавців
  * Пошук по списку рецептів
  * Подробиці про кожен рецепт
  * Список з недавно доданими рецептами

. Вирішити яка інформація повинна бути на наступних сторінка або типах сторінок
на сайті:
+
  Інформація яка повинна бути на всіх сторінках::
    Адреса, годинник, недавно додані рецепти
  Сторінки з подробицями про продавців::
    Інформація про кожного продавця на своїй сторінці
  Сторінкі з подробицями про рецепти::
    Подробиці про кожен рецепт на кожній сторінці
  Головна сторінка::
    Адреса, карта, схема проїзду і години роботи
  Сторінка про ярмарок::
    Історія ярмарку
  Сторінка зі списком продавців::
    Список продавців з посиланнями на сторінку продавця з подробицями
  Сторінка зі списком рецептів::
    Пошук по списку рецептів з посиланнями на сторінку рецепта з подробицями

. Вирішити яка інформація найбільш важлива на кожній сторінці. Відвідувачі сайту, що
використовують мобільні пристрої або екрани з низькою роздільною здатністю, будуть часто бачити тільки контент, який
представлений першим і вони можуть не проскролити вниз і не подивитися всю інформацію на сторінці.

. Вирішити які з вищевказаних сторінок повинні з'явитися в головному меню сайту. Наприклад,
головне меню може складатися з посилань Головна, Про Ярмарку, Продавці та
Рецепти.

. Зробіть грубий начерк(скетч) дизайну для кожної сторінки, показуючи, як це може виглядати
переглядаючи сайт на маленькому екрані, такому як телефон, також як і на великих екранах, як наприклад
на настільному комп'ютері. Вважаючи що більшість відвідувачів сайту будуть використовувати маленькі
екрани, буде гарною ідеєю почати з макета для телефонів і переконатися,
що ці користувачі зможуть знайти інформацію, яка їм потрібна без занадто
довгої прокрутки.
+
У процесі створення планів для ваших сторінок, ви можливо знайдете, що вам необхідно і переглянути ваш
план для інформації, яка повинна бути на сторінках. Наприклад, ви можете
вирішити, що адреса, години роботи і недавно додані рецепти повинні бути винесені
в праву колонку сайту на всіх сторінках, коли сайт проглядається з
настільного комп'ютера. З іншого боку, ви можете вирішити, що для мобільних
браузерів, ви могли б помістити адресу та часи роботи в більш короткому форматі на
початку кожної сторінки сайту, але відображення списку останніх рецептів перенести вниз лише для
головної сторінки сайту.

==== Поліпшити розуміння теми

<<planning-structure>>

// ==== Related concepts

==== Відео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/35e16QDFE7k[ritle="Planning Your Site Layout"]

// ==== Additional resources


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Перевів https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov]