[[planning-workflow]]

=== Основи: Робочий процес редагування

[role="summary"]
Огляд робочого процесу редагування для управління контентом на сайті.

(((Робочий процес редагування, огляд)))
(((Статус опубліковано, огляд)))
(((Статус знято з публікації, огляд)))
(((Редакція, огляд)))

==== Необхідні знання

* <<understanding-drupal>>
* <<planning-data-types>>

==== Що таке робочий процес редагування?

_Рабочий процес редагування_ - це процес організації створення, перевірки,
редагування і публікації контенту. Багато людей на різних посадах в
організації можуть бути залучені в процес. Наприклад, творець контенту може
збирати інформацію і писати статті; редактор може перевіряти статті, редагувати, запитувати
зміни і публікувати контент, коли він буде готовий для
аудиторії. Пізніше, редакції контенту можуть бути змінені, використовуючи простий процес
для маленьких змін або більш складний процес з перевіркою для великих змін.

==== Які інструменти доступні для робочого процесу управління?

Опублікований/Знятий з публікації статус контенту::
  Сутності контенту підтримують позначку кожного елемента контенту як
  Опублікований або Знятий з публікації. Права на перегляд розділені для контенту опублікованого і
  знятого з публікації; наприклад, всі відвідувачі сайту можуть бачити
  опублікований контент, проте тільки творці контенту і редактори можуть переглядати
  контент знятий з публікації.
Відстеження редакцій::
  Деякі типи контенту підтримують відстеження редакцій, це означає, що такий контент
  може бути виправлений і друпал зберігає всі старі правки, так що вони можуть бути
  порівняні і відновлені.
Робочі процеси::
  Модуль ядра Workflows дозволяє визначити стан і переходи станів контенту в робочому процесі,
  що більше ніж просто публікація і зняття з публікації контенту. Додатковий модуль ядра
  Content Moderation дозволяє зв'язати права доступу і ролі з
  переходами станів контенту в робочому процесі. Обидва модулі можуть бути використані для сутностей Вмісту та
  Користувацьких блоків.
Розміщення блоку::
  Сутність користувацького блоку дозволяє вам створювати користувацький блок і редагувати його,
  і зробити його видимим, коли сайт буде готовий до його показу.

==== Пов'язані матеріали

* <<content-create>>
* <<content-edit>>
* <<block-create-custom>>
* <<block-place>>

// ==== Additional resources

*Автори*

Написано і змінено https://www.drupal.org/u/dianalakatos[Diána Lakatos] із
https://pronovix.com//[Pronovix],
https://www.drupal.org/u/gdunham[Grant Dunham],
і https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov].