[[planning-modular]]
=== Основи: Модульний Контент

[Role = "summary"]
Огляд модульного контенту і як контент на сторінці може бути взятий з іншого контенту сайту.

(((Контент, модульний)))
(((Модульний контент, огляд)))
(((Сторінка, композит)))
(((Складання сторінки, створення сторінки через модульний контент)))
(((Композитна сторінка, створення з модульним контентом)))
(((Views модуль, огляд)))


==== Необхідні знання

* << planning-data-types >>
* << planning-layout >>

==== Що таке модульний контент?

З огляду на, що контент вашого сайту зберігається в базі даних, бажано
зробити контент _діскретний_, що означає певні сторінки на вашому сайті,
не редагуються як ціла сторінка, замість цього автоматично генеруються з інших
елементів контенту. Наприклад, в сценарії сайту фермерського ринку ви можете
створити окремі елементи контенту для рецептів. Якщо в елементах вмісту рецепта є
поле, в якому відслідковуються інгредієнти, то на вашому сайті може бути складова
сторінка зі списком рецептів, що дозволяє відвідувачам шукати рецепт, який
містив якийсь конкретний інгредієнт, який вони купили на ринку.

Невеликі розділи сторінок також можуть бути згенеровані як композити. наприклад,
елементи вмісту рецепта можуть мати поле, яке відстежує, який постачальник
відправив рецепт (див. << structure-reference-fields >>), при цьому відомості про постачальника
редагуються в окремих елементах вмісту постачальника. Це дозволить вам зробити
наступне на вашому сайті:

* На кожній сторінці рецепта може бути область, яка відображає деяку інформацію
 про продавця, який представив рецепт, наприклад, його ім'я і номер ринкового прилавка.

* На кожній сторінці постачальника може бути розділ, в якому перераховані рецепти,
які вони відправили.

Основна ідея полягає в тому, що кожен фрагмент інформації редагується тільки в одному місці.
Коли інформація про продавця оновлюється, всі сторінки рецептів, які відображатимуть цю інформацію про продавця,
автоматично оновлюються; коли рецепт відправляється постачальником,
він автоматично відображається на сторінці постачальника. Основний модуль Views -
це звичайний спосіб використання модульного контенту для створення складових сторінок і розділів сторінок;
 см. << views-concept >> для отримання додаткової інформації. Крім того, _віди отображеній_ корисні для
визначення різних способів відображення кожного елемента контенту; см.
<< structure-view-modes >> для отримання додаткової інформації.

==== схожі теми

* << planning-structure >>
* << structure-content-type >>
* << structure-fields >>
* << structure-reference-fields >>
* << structure-view-modes >>
* << views-concept >>

// ==== Додаткові ресурси


* Автори *

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].
