[[planning-structure]]
=== Проектування структури контенту

[role="summary"]
Як планувати структуру контенту, яка пов'язує типи контентів і певний контент на сайті.

(((Структура контенту, планування)))
(((План сайту, структура контенту)))

==== Мета

Створіть план для структури контенту вашого сайту (які типи і підтипи
сутностей використовувати для контенту) і які сторінки будуть містити списки
матеріалів.

==== Необхідні знання

* <<planning-data-types>>
* <<planning-modular>>
* <<preface-scenario>>

// ==== Site prerequisites

==== Кроки

. Мозковий штурм про те який контент ваш сайт повинен відображати, серед якого буде
контент, що відвідувачі хотіли б знайти, також контент, який ви хотіли б
показати відвідувачам. Результат можна описати так само як це зроблено на цій сторінці
<<preface-scenario>>.

. Для кожного певного шматочка контенту, визначте який тип сутності найкраще
підходить для цього. Якщо ви це зробите, ви будете повинні розрахувати, де і як
контент буде відображатися і редагуватися на сайті. Наприклад, на сайті міського
ярмарку, ви можете відобразити години роботи і адресу
міського ярмарку в колонці на кожній сторінці. Для цього контенту, один користувацький
блок підійде найкраще. Як ще один приклад, ви можете вирішити що сторінки які повинні відображати
інформацію про кожного продавця найкраще зробити через матеріали керовані ядром Drupal в Node
модулі, тому що ви хочете щоб продавці мали можливість редагувати свої власні списки рецептів.
Дозволи(permissions) модуля ядря Node дозволяють легко це зробити.
+
Це рішення не обов'язково має завжди одну відповідь;
наприклад, ви могли б вирішити, що продавці повинні бути профілями користувачів замість
контенту, однак якщо ви зробили, так що контент буде пов'язаний з певним обліковим записом
користувача, то вам буде не легко змінити авторство сторінки продавця
на користь іншого користувача.

. Всередині кожної сутності, яку ви визначаєте, вирішите, які розділи в
підтипах сутностей мають місце бути. Наприклад, на сайті міської ярмарки
ви можливо вирішите, що Матеріали
повинні бути одним типом для звичайних сторінок (Головна і
Про нас), іншим типом для сторінок продавців і ще одним підтипом для сторінок рецептів.

. Для кожного підтипу сутності визначіться які вам поля вам потрібні. Наприклад, для
типу контенту Продавець необхідні поля назва продавця, шлях
URL, зображення і опис.

. Вирішіть які списки сутностей вам потрібні, які сутності будуть займати цілі сторінки а які будуть займати
менші області на сторінці. Для кожного списку, ви повинні будете визначити, які
сутності будуть відображені в списках. Тоді ви будете повинні вирішити, в якому порядку і з якими
параметрами фільтрів вони повинні будуть відображені; наприклад, ви можете захотіти
дати можливість відвідувачам сайту шукати за ключовими словами, фільтрувати список по
параметрам або вибирати параметри сортування. Ви також повинні будете вирішити яка інформація
з сутностей буде показана, і яка інформація буде виводитися на додаток до списку
полів визначених в минулих кроках. Сайт міського ярмарку, наприклад, Повинен мати сторінку списку рецептів, яка відображає контент тип
Рецепт, з можливістю фільтрувати за інгредієнтами, це означає, що Рецепт
тип матеріалу повинен мати поле Інгредієнти.

. Для кожного певного поля в кожному підтипі сутності, визначте який тип даних
вони повинні містити (наприклад простий текст, форматований текст, дату, файл зображення,
і т.д.), і як багато значень поля дозволяють зберігати. Більшість полів
мають одне значення, проте наприклад, Рецепт може містити і множинні значення наприклад
для поля Інгредієнти.

. Подумайте над полями, які найкраще зробити через зв'язку використовуючи терміни таксономії:
поля які мають значення вибрані зі списку доступних значень. Доступні
значення, які можливо змінити і додати через деякий час, кращими варіантами.
Наприклад поле Інгредієнти для типу матеріалів Рецепт.

. Подумайте які поля найкраще зробити через зв'язку до інших сутностей. Наприклад
коли продавці створюють рецепти, поле буде потрібно
щоб зв'язати тип матеріал Рецепт і Продавець,
який створює рецепт.

Нижче приклад структури для міського ярмарку
з нашого сценарію:

[width="100%",frame="topbot",options="header"]
|=============================================
|Тип сутності |Підтип сутності |Приклади |Поля

|Елемент контенту |Сторінка |Головна сторінка, Про нас |Тема, вміст

|Елемент контенту |Продавець |Сторінка для кожного продавця на ринку |
  Ім'я продавця, вміст, зображення, URL

|Елемент контенту |Рецепт |Сторінка для кожного збереженого рецепта |
  Ім'я рецепта, опис, зображення, зв'язати з продавцем, хто створив рецепт,
  Інгредієнт таксономія

|Користувацький блок |(основний) |Копірайт в футері,
  Години роботи і адреса в колонці |Немає спеціальний полів

|Терміни таксономії |Інгредієнти |Морква, помідори та інші інгредієнти в рецептах |
  Немає спеціальний полів

|Контактна форма |(основний) |Основна контактна форма |Ім'я, емейл, назва, повідомлення

|Профіль користувача |(немає) |Не відображається на сайті |Немає спеціальний полів

|=============================================

І нижче списки які потрібні на сайті:

[width="100%", frame="topbot", options="header"]
|=============================================
|Сторінка і основний контент сторінки |Тип сутності і підтип |Фільтри/сортування/пагінація |
  Відображені поля

|Сторінка продавця |Елементи контенту продавця |Всі продавці, алфавітний, посторінкова |
  Зображення, ім'я продавця, скорочений опис

|Сторінка рецептів |Елементи контенту рецепта |
  Фільтр за інгредієнтами, алфавітний, посторінкова |Зображення, ім'я рецепта

|Недавні рецепти в колонці |Елементи контенту рецепта |Список 5 останніх рецептів |
  Зображення, Ім'я рецепта

|=============================================

==== Покращимо своє розуміння

* <<structure-content-type>>
* <<structure-fields>>
* <<structure-taxonomy-setup>>

==== Пов'язані теми

<<structure-taxonomy>>

==== Відео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/CaNt4DEeIgU[title="Planning Your Content Structure"]

// ==== Additional resources


*Автори*

Написано і змінено https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]
і https://www.drupal.org/u/gdunham[Grant Dunham].

Перевів https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov].