[[preface-audience]]

=== Аудиторія та мета

[role="summary"]
Розуміння цільової аудиторії цього посібника та що вони з нього дізнаються.

Цей посібник був написаний в основному для людей з мінімальними знаннями про 
систему керування вмістом Drupal. Статті допоможуть їм отримати знання про
встановлення, адміністрування, створення сайтів та/або роботу з вмістом
веб-сайту на основі Drupal. Посібник також орієнтований на людей, у яких вже є певний
досвід роботи з поточною або попередньою версією Drupal, і вони бажають розширити
діапазон своїх навичок та знань або оновити їх до поточної версії.

Цей посібник передбачає, що ви вже вирішили, що хочете вчитися та використовувати
Drupal. Якщо вам потрібно дізнатися більше, перш ніж приймати рішення, перегляньте
розділ <<understanding-drupal>>.

Залежно від того, які аспекти Drupal ви хочете вивчити, для розуміння цього посібника 
вам знадобляться деякі базові знання: передбачається, що ви маєте загальні навички 
та знання роботи в Інтернеті, а посібник зосереджується на тому, як безпосередньо 
використовувати програмне забезпечення. Наприклад, розділи про встановлення Drupal
на веб-сервері припускають, ви знаєте, як отримати веб-хостинг і розбираєтесь,
як передавати файли на вибраний вами веб-хост. Аналогічно, розділи про керування
вмістом припускають, що ви здатні увійти на веб-сайт і заповнити веб-форму.

Прочитавши цей посібник, ви будете здатні:

* Спроектувати архітектуру вмісту Drupal-сайту

* Створити спроектований сайт

* Керувати сайтом та адмініструвати його

* Розуміти документацію та дописи в блогах на теми, які тут не висвітлюються,
щоб розширити свої знання та вміння

* Приєднатися до світової спільноти Drupal


*Автори*

Автор: https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]. Переклад: https://www.drupal.org/u/anprok[Andriy Prokopenko].
