[[preface-scenario]]
=== Основний сценарій

[role="summary"]
Детальне пояснення основного сценарію, який використаний в цьому керівництві міститься в наступних темах.

(((Сценарій в цьому документі (міський ярмарок), огляд)))
(((Сценарій керівництва в цьому документі (міський ярмарок))))
(((Використання сценарію в цьому документі (міський ярмарок))))
(((Міський ярмарок, використання сценарію в цьому документі)))

Коли читаєте це керівництво, необхідно тримати проект сайту
в голові. Наступний сценарій проекту описує контекст і вказує
на приклади цього керівництва:

Ви створите сайт для міського ярмарку. Сайт повинен відображати
інформацію про розміщення і години роботи ярмарку і сторінку Про Ярмарку з
історією заснування ярмарку. Також буде потрібно список продавців. Продавці повинні мати
можливість редагувати їх інформацію (включаючи логотип і фотографії), і публікувати рецепти. відвідувачі
сайту повинні мати можливість переглядати рецепти і шукати рецепти використовуючи інгредієнти,
які вони можуть купити на ярмарку. Деякі відвідувачі сайту говорять іншою
мовою, так що головна сторінка та сторінки продавців повинні бути перекладені.

Коли ви читаєте керівництво і пробуєте виконати завдання, які в ньому викладені, ви можете
слідувати за сценарієм точно; ви можете також змінити завдання під набір ваших
цілей. Якщо ви хочете слідувати за сценарієм точно, вам будуть потрібні
деякі зображення файлів, які знаходяться в папці _assets_ файлу _.zip_
або _.tgz_, які доступні для завантаження на сторінці
https://www.drupal.org/project/user_guide[User Guide project page].

*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].