[[preface-organization]]
=== Структура

[role="summary"]
Пояснення організаційної структури цього керівництва для кращої навігації по темам.

Це керівництво містить серії тем, кожна з яких покриває
певне завдання (як зробити щось) або основи (базові знання, термінологія).
Теми з основ починаються з "Основи:", тоді як теми по Завданням
містять в назві конкретну задачу, наприклад "Редагування основних налаштувань сайту".

Теми згруповані по Розділам в логічному порядку, основи і завдання
чергуються так що основи подаються перед завданнями які до них відносяться та завдання будуються
одне за одним. Якщо скористатися цим правильно, ви будете з натхненням читати все
керівництво в представленому порядку, можливо пропускаючи теми які вам не так цікаві
або ви вже знаєте інформацію про цю тему. Спробуйте виконати завдання
на вашому сайту, які ви читаєте в керівництві, більшість людей краще розуміють як це працює практично,
ніж читаючи статті.

Якщо вам подобається більше інший підхід, то ви можете також використовувати Покажчик для переходу
в потрібний розділ до теми яку ви хочете вивчити, перш ніж читати все
керівництво цілком. Для полегшення цього підходу, кожна тема має список необхідних знань
які були б необхідні для розуміння теми (з посиланнями на теми, які
необхідно знати); необхідні завдання які вказані в списку _вимоги до сайту_ (речі які
вам необхідно буде зробити щоб налаштувати або привести ваш сайт в порядок для виконання
завдання). Також, більшість тем мають розділи в кінці, де ви можете знайти пов'язану
інформацію або завдання для поліпшення вашого розуміння і продовжити вивчення.

Ви також можете звернутися до розділу <<glossary>>, де зібрані
короткі визначення великого числа термінів, які використовуються в цьому посібнику, з посиланнями на
теми що мають більш детальне пояснення.


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].
