[[prevent-backups]]

=== Основи: Резервна копія даних

[role="summary"]
Огляд створення резервних копій і як слід зберігати копії сайту.

(((Резервна копія, огляд)))
(((Контент, створення резервних копій)))
(((Файл, створення резервних копій)))
(((База даних, створення резервних копій)))

==== Необхідні знання

* <<understanding-drupal>>
* <<install-prepare>>

==== Що таке резервна копія сайту?

Якщо що-небудь трапиться з комп'ютером (або комп'ютерами), на якому ваш сайт і його
база даних працюють або в разі коли ви втратите доступ до цього комп'ютера, то ви втратите
деякі або всі дані вашого сайту. Ви можете також втратити дані, якщо ваш сайт
зламаний, або хтось з доступом в адмінку на вашому сайті видалив всі дані або
змінив дані на сайті з помилками. Щоб попередити всі ці
можливі ситуації втрат даних, важливо
робити регулярні резервні копії вашого сайту і зберігати їх в місці
окремому від комп'ютера, де ваш сайт працює.

Частота з якою ви повинні робити ваші резервні копії і як багато копій вам
слід зберігати, залежить від того як часто ваш сайт змінюється. Якщо ви маєте великий
обсяг інформації на вашому сайті, яка була додана чи оновлена ​​багато
раз за день, то вам слід робити резервні копії якомога частіше, на відміну коли
сайт змінюється рідко. Також розраховуйте, що деякий час має пройти,
коли проблема станеться і коли ви помітите проблему, так що зберігати потрібно
кілька послідовних копій (так щоб можна було повернутися до моменту, коли проблема ще не відбулася і
виправити її), перш ніж перезаписувати, якусь резервну копію негайно, переконайтеся
що помилки яка виникла, відсутня у вашій резервної копії.


Ще одне застереження, в якому форматі б ви не зберігали ваші резервні копії,
хорошою ідеєю буде перевіряти, що ви можете розгорнути вашу копію для відновлення ваших
даних. Вам можливо буде потрібно протестувати різні сценарії втрати даних, щоб
бути впевненим, що ви зможете відновити втрачені дані в усіх випадках.

Наступні кроки дозволять зробити повну резервну копію
вашого сайту:

* Дані в папці _sites_, включаючи файл _sites/default/settings.php_.

* Дані з бази даних вашого сайту. Деякі таблиці можуть бути очищені, наприклад ті що
зберігають тимчасовий дані з кешем і інформацією про сесії авторизованих користувачів, проте
завжди безпечніше створювати резервну копію всієї бази даних.

* Завантажені файли, такі як зображення та інші прикріплені файли. Місцезнаходження цих
файлів налаштовується; стандартне розташування це папка _sites/default/files_
щодо кореня сайту. В _Керування_ меню адміністратора, перейдіть
на сторінку _Конфігурація_ > _Медіа_ > _Файлова система_ (_admin/config/media/file-system_)
перевірте папку для завантаження файлів; ви можете змінити папку для файлової системи, ви також можете це зробити
в файлі _settings.php_.

* Модулі, теми оформлення і будь-які інші призначені для користувача файли, які ви додали. Ви можете знайти
призначені для користувача модулі і теми оформлення в папках _modules_ і _themes_
з усіма вкладеними папками. Деякі люди вважають за краще створити резервну копію всіх файлів, включаючи файли Drupal,
модулів і тем оформлення (які ви зможете відновити завантаживши
їх знову з висхідних кодів), перш ніж намагатися зібрати проект з джерел,
які необхідно використовувати.

Вам слід виконати тест, щоб підтвердити, що ваша резервна копія створена вірно
і ви можете розгорнути копію сайту (дивіться <<install-dev-making>>).

==== Пов'язані теми

* <<security-update-core>>
* <<install-dev-making>>
* <<prevent-cache>>

==== Додаткові матеріалу

* https://www.drupal.org/docs/7/backing-up-and-migrating-a-site/backing-up-a-site[_Drupal.org_ сторінка документації спільноти "Backing up a site"]

* The https://www.drupal.org/project/backup_migrate[contributed Backup and Migrate модуль],
який можна використовувати для створення автоматичних резервних копій бази даних і завантажених
файлів.

*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].