[[security-announce]]

=== Відстеження оновлень

[role="summary"]
Як убезпечити сайт, залишаючись в курсі останніх оновлень безпеки.

(((Оновлення, відстеження)))
(((Оновлення безпеки, відстеження)))
(((Update Manager модуль, огляд)))
(((Повідомлення про безпеку, підписатися на електронну пошту)))
(((Повідомлення про безпеку, підписатися на Twitter)))

==== Мета

Забезпечте безпеку і актуальність свого сайту, стежачи за останніми версіями поновлення
безпеки.

==== Необхідні знання

<<security-concept>>

// ==== Site prerequisites

==== Кроки

Існує кілька способів отримання повідомлень про випуски оновлення безпеки:

* У _Керування_ адміністративного меню, перейдіть в _Звіти_ > _Доступні оновлення_ > _Налаштування_. Введіть адресу електронної пошти, щоб отримувати повідомлення, коли вони будуть
доступні. Ви також можете вказати, чи хочете ви отримувати повідомлення щодня або щотижня. натисніть
_Зберегти конфігурацію_.

* Підписатися на розсилку по електронній пошті. Щоб підписатися зайдіть в аккаунт на
_Drupal.org_, перейдіть на сторінку свого профілю користувача і підпишіться
на розсилку про оновлення безпеки на вкладці _Edit_ > _My newsletters_.

* Слідкуйте за @drupalsecurity в Twitter.

* Підпишіться на RSS-канали для
https://www.drupal.org/security/rss.xml[core security updates],
https://www.drupal.org/security/contrib/rss.xml[contributed project updates] і
https://www.drupal.org/security/psa/rss.xml[public service announcements].

// ==== Expand your understanding

==== Схожі поняття

* <<security-concept>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>

==== Відео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/GcamYLNeGAs[title="Keeping Track of Updates"]

==== Додаткові ресурси

* https://www.drupal.org/security["Security advisories "on _Drupal.org_]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team]
* https://twitter.com/drupalsecurity[@drupalsecurity on Twitter]


*Автори*

Написано https://www.drupal.org/u/hey_germano[Sarah German] в
https://www.advomatic.com[Advomatic].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].