[[security-concept]]

=== Основи: Безпека та регулярні оновлення

[role="summary"]
Огляд оновлень безпеки, способи обробки помилок та оновлень, не пов'язаних з безпекою.

(((Безпека, огляд)))
(((Оновлення, огляд)))
(((Помилки, складання звітів)))
(((Помилка безпеки, складання звітів)))
(((Команда безпеки, огляд)))

==== Необхідні знання

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>
* <<understanding-project>>

==== Що таке оновлення безпеки?

Будь-яке програмне забезпечення іноді має помилки, а іноді ці помилки мають наслідки для
безпеки. Коли помилки безпеки виправлені в ядрі, модулях або
темах, які використовує ваш сайт, вони випускаються в оновленні _обновлення безопеки_. Необхідно
встановлювати оновлення безпеки для забезпечення безпеки вашого сайту. Дивіться
<<security-announce>>, щоб дізнатися як отримувати повідомлення про оновлення безпеки по
пошті, і <<security-update-core>>, <<security-update-module>> і
<<security-update-theme>>, щоб дізнатися як встановлювати оновлення.

==== Що таке команда безпеки?

Проект з відкритим вихідним кодом Drupal має команду добровольців, які відстежують
пов'язані з безпекою помилки і випускають оновлення безпеки. Вони також допомагають іншим
розробникам виправляти помилки і надають інформацію для користувачів про те, як зберегти свої
сайти в безпеці. Ви можете дізнатися більше про команду безпеки і їхні практики
і процеси на
https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Команда безпеки] сторінка.

==== Як отримувати повідомлення про помилки безпеки?

Важливо, щоб проблеми безпеки були конфіденційними, поки вони
НЕ будуть виправлені, так що сайти будуть менш схильні до ризику перш ніж безпека буде
забезпечена. Якщо ви виявите потенційну проблему безпеки в будь-якому програмному забезпеченні, яке ви
скачали з сайту _Drupal.org_, дотримуйтесь інструкцій на
https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Команда безпеки] це сторінка для
звітів.

==== Що таке регулярні (не пов'язані з безпекою) оновлення?

Ядро Drupal, модулі і теми також періодично отримують регулярні оновлення,
додають нові функції і виправляють помилки. Ці оновлення менш важливі, ніж поновлення
безпеки. Як правило, оновлення повинні застосовуватися до тих пір, поки вони
не викликають проблем з вашим сайтом. Тестування на копії розробки вашого сайту,
це завжди гарна ідея, перш ніж застосовувати оновлення на живому сайті. Тому що
деякі оновлення можуть включати зміни, які не сумісні з модулями або
темами на вашому сайті, або вони можуть порушити певну функціональність на вашому сайті.

==== Схожі теми

* <<security-announce>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>
* <<install-dev-making>>

==== Додаткові ресурси

* https://www.drupal.org/security/secure-configuration[_Drupal.org_ сторінка документації спільноти "Securing your site"]
* https://www.drupal.org/security["Поради з безпеки "на Drupal.org]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Команда безпеки]


*Автори*

Написано і змінено https://www.drupal.org/u/batigolix[Boris Doesborg]
і https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].