[[security-update-core]]

=== Оновлення ядра Drupal

[role="summary"]
Як оновити ядро ​​Drupal використовуючи інтерфейс адміністратора або Drush.

(((Ядро Drupal, оновлення)))
(((Drush, використання для поновлення ядра Drupal)))
(((Інтерфейс користувача, використання для поновлення ядра Drupal)))

==== Мета

Оновити ядро ​​Drupal через інтерфейс адміністратора або
використовуючи Drush.

// ==== Prerequisite knowledge

==== Вимоги до сайту

* Якщо ви хочете використовувати Drush, Drush повинен бути встановлений. Дивіться <<install-tools>>.

* Якщо сайт викладений в Інтернет, вам слід протестувати процес на копії сайту
локально перед тим як запускати оновлення на живому сайті. дивіться
<<install-dev-making>>.

==== Кроки

. Зробіть повну копію вашого сайту. Детально як це зробити тут <<prevent-backups>>.

. Відкрийте _settings.php_ (_/sites/default/settings.php_) в будь-якому текстовому
редакторі. Знайдіть рядок з _$settings['update_free_access']_ змінною. За
замовчуванням, змінна встановлена ​​як "FALSE" з міркувань безпеки. Змініть значення на
"TRUE":
+
----
$settings['update_free_access']=TRUE;
----

. Вимкніть будь-який кеш (memcache, varnish і так далі), який використовується на вашому
сайті.

. Увімкніть режим обслуговування на вашому сайті. Дивіться <<extend-maintenance>>.

. Якщо ви використовуєте Composer для управління залежностями, пропустіть наступні шість кроків і
замість цього використовуйте інструкції з <<install-composer>> для завантаження оновлених
файлів. Продовжіть з кроку _update.php_.

. Завантажте tar.gz або zip архів з останньою версією Drupal
8.x зі сторінки https://www.drupal.org/project/drupal[_Drupal.org_ Drupal Core
Downloads]. Дивіться <<install-prepare>> для більшої інформації про те, як знайти останню
версію.

. Завантажте файл архіву на сервер вашого хостингу.

. Розпакуйте файл до тимчасової папки на вашому сервері (повинен бути
зовні папки, де розташований сайт). Ваша панель управління на хостингу
повинна мати файловий менеджер здатний розпакувати файли. Якщо ви маєте
доступ до командного рядка на вашому сервері (наприклад використовуючи Linux), ви можете виконати команду:
+
----
tar -xzf drupal-8.3.2.tar.gz
----

. У папці сайту, видаліть папки _core_ і _vendor_
і всі файли, які знаходяться в корені сайту, включаючи _.htaccess_,
_composer.json_ і _autoload.php_. Не чіпайте додаткові і змінені файли,
тому що ви можете втрат частину додаткового функціоналу, який ґрунтується на цих файлах.

. Скопіюйте папки _core_ і _vendor_ і інші не додаткові і не призначені для користувача
файли, які ви видалили в попередньому кроці з тимчасової папки на
вашому сайті.

. Запустіть скрипт _update.php_ використовуючи такі інструкції:
+
  * Відкрийте в браузері _http://www.example.com/update.php_ (де
  _www.example.com_ це адреса URL вашого сайту). Натисніть _Продовжити_ на першому екрані
  для запуску оновлення і успішного завершення виконання скрипта.
  * Запустіть наступну Drush команду: `drush updatedb`

. Якщо ви отримали якісь помилки або попередження, запускайте _update.php_ скрипт
знову до тих пір поки всі оновлення не будуть виконані успішно.

. Відкрийте _settings.php_ (_/sites/default/settings.php_) в текстовому редакторі. Знайдіть
рядок з _$settings['update_free_access']_ змінною і обновіть її на
"FALSE":
+
----
$settings['update_free_access']=FALSE;
----

. Натисніть _Сторінка адміністрування_, щоб повернутися в розділ адміністрування вашого
сайту.

. Вимкніть режим обслуговування на вашому сайті. Дивіться <<extend-maintenance>>.

. Очистіть кеш. Дивіться <<prevent-cache-clear>>.

. Додайте всі додаткові кеші назад, які ви вимикали на Кроці 3.

. Після цього ви повинні мати оновлену працюючу версію Drupal. Ви можете перевірити поточну
версію Drupal на сторінці _Status report_ (Дивіться
<<prevent-status>>).

==== Поліпшите своє розуміння

* <<install-tools>>
* <<install-dev-making>>
* <<prevent-backups>>

==== Пов'язані концепції

<<prevent-status>>

==== Відео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/eLzAD83a9BY[title="Updating the Core Software"]

==== Додаткові матеріали

* https://www.drupal.org/project/drupal["Drupal Core Downloads "page on _Drupal.org_]
* https://www.drupal.org/project/registry_rebuild["Registry Rebuild "page on _Drupal.org_]
* The file _/core/UPDATE.txt_ within your installation.


*Автори*

Написано і змінено https://www.drupal.org/u/surendramohan[Surendra Mohan],
https://www.drupal.org/u/batigolix[Boris Doesborgh] і
https://www.drupal.org/u/jojyja[Jojy Alphonso] із
http://redcrackle.com[Red Crackle].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].