[[security-cron-concept]]

=== Основи: Крон

[role="summary"]
Огляд cron і чим він відрізняється від Unix cron.

(((Завдання Cron, огляд)))
(((Автоматизований модуль Cron, огляд)))

// ==== Prerequisite knowledge

==== Що таке cron завдання?

Щоб ваш сайт і його модулі продовжували нормально функціонувати, група
адміністративних операцій повинна виконуватися періодично. Ці операції
називаються завданнями _cron_. Приклади cron завдань: перевірка оновлень для модуля або
теми, індексація контенту для пошуку або очищення тимчасових файлів.

==== Який зв'язок між cron завданнями і Unix cron?

Операційні системи на основі Linux/Unix мають планувальник cron, який можна використовувати для запуску
періодичних задач. Ви можете використовувати планувальник cron сервера для планування запуску
cron завдань сайту. Крім того, ви можете використовувати модуль ядра Automated Cron для
запуску завдань. Ви можете перевірити статус cron завдань сайту в звіті про стан.

==== Схожі теми

* <<security-cron>>
* <<prevent-status>>

==== Додаткові ресурси

https://www.drupal.org/docs/7/setting-up-cron/overview[_Drupal.org_ сторінка документації спільноти "Setting up cron"]


*Автори*

Написано і змінено
https://www.drupal.org/u/dianalakatos[Diána Lakatos] із
https://pronovix.com/[Pronovix],
https://www.drupal.org/u/dalin[Dave Hansen-Lange] із
https://www.advomatic.com/[Advomatic],
і https://www.drupal.org/u/batigolix[Boris Doesborg].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].