[[structure-widgets]]

=== Основи: Форми та Віджети

[role="summary"]
Огляд форм та віджетів.

(((Форма редагування матеріалу, огляд)))
(((Віджет, огляд)))
(((Поле, огляд)))
(((Форма, огляд)))

==== Необхідні знання

<<planning-data-types>>

==== Що таке форми та віджети?

Система управління сайтом дозволяє вашим адміністраторам
сайту редагувати контент і змінювати налаштування онлайн, використовуючи різні веб
_форми_. Зокрема, _форма редагування матеріалу_ використовується для редагування вашого
контенту і ці форми налаштовуються адміністраторами налаштуваннь конфігурації
форм наданих модулями, не можуть бути налаштовані окремо від модуля.

Дані в контенті вашого сайту зберігаються в одному або кількох полях, які
прив'язані до типу сутності та/або підтипу. Коли ви налаштовуєте форму редагування
контенту для кожного підтипу контенту, ви можете:

* Вибрати _віджет_ для кожного поля. Віджет визначає метод що буде використовуватися для введення
даних в поле. Наприклад, термін таксономії може використовувати
поле з авто доповненням, вибір зі списку або поле з вибором тегів, які дозволяють редакторам
додавати нові теги автоматично.

* Налаштувати віджет поля. Наприклад, ви можете вибрати розмір
текстового поля введення.

* Сховати одне або кілька полів з форми редагування.

* Міняти поля місцями.

Головним чином, ви можете також мати різні форми редагування доступні для
кожного підтипу сутності. Цей функціонал рідко використовується, проте, як виняток
в загальному випадку для полів профілю користувача: ви можете використовувати різні форми для
реєстрації та редагування користувача. Наприклад, вам може бути необхідно обмежити набір
полів, які показуються, коли користувач реєструється на сайті і показувати більше полів пізніше,
коли користувач редагує свій профіль.

==== Пов'язані теми

* <<structure-form-editing>>
* <<structure-view-modes>>

// ==== Additional resources


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].