[[structure-reference-fields]]

=== Основи: Поле посилання на сутність

[role="summary"]
Огляд полів посилання на сутність і їх загальновживаних типів.

(((Поле посилання на сутність, огляд)))
(((Поле посилання на сутність, матеріал)))
(((Поле посилання на сутність, термін таксономії)))
(((Поле посилання на сутність, користувач)))
(((Поле, зв'язок)))
(((Поле, посилання на сторінку матеріалу)))
(((Поле, посилання на термін таксономії)))
(((Поле, посилання на користувача)))
(((Поле посилання на термін таксономії, огляд)))
(((Поле посилання на користувача, огляд)))
(((Поле посилання на матеріал, огляд)))

==== Необхідні знання

<<planning-data-types>>

==== Що таке поле посилання

_Поле посилання на сутність_ - це поле, яке представляє собою зв'язок між
сутністю і однією або декількома іншими сутностями, які можуть
належати до одного і того ж або різних типів сутностей. Найбільш часто
використовуються три види полів посилань на сутність:

Посилання на сторінку матеріал::
  Посилання на сторінку матеріалу. Наприклад, вам може знадобитися зв'язати
  рецепти з постачальниками, які їх надіслали. Ви можете вказати постачальника
  в полі "Надано"
  типу матеріалу Рецепт.

Посилання на термін таксономії::
  Наприклад, ви можете прив'язати рецепти до їх інгредієнтів. Ви можете створити поле
  посилання на таксономічний термін під назвою Інгредієнти в типі матеріалу
  Рецепт. У цьому поле посилання буде вказано словник Інгредієнти.

Посилання на користувача::
  Посилання на обліковий запис користувача. Наприклад, можете пов'язати рецепти страв з
  їх шеф-кухарями. Ви можете створити посилання на користувача
  "Шеф-кухар" в розділі "Тип вмісту рецепта".

==== Схожі теми

<<structure-taxonomy>>

// ==== Additional resources

*Автори*

Написано і змінено https://www.drupal.org/u/surendramohan[Surendra Mohan] і https://www.drupal.org/u/jojyja[Jojy Alphonso] з
http://redcrackle.com[Red Crackle].

Переклав https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].