[[structure-image-styles]]

=== Основи: Стилі зображень

[role="summary"]
Огляд стилів зображеннь і як вони використовуються для відображення одного зображення в декількох варіантах.

(((Стиль зображення, огляд)))
(((Стиль, зображення)))
(((Ефект зображення, огляд)))
(((Ефект, зображення)))



==== Необхідні знання

<<structure-fields>>


==== Що таке стилі зображення?

Стилі зображень дозволяють завантажувати одне зображення, але відображати його декількома способами;
кожен варіант відображення, або _стиль зображення_, є результатом застосування одного або декількох
_ефектів_ до вихідного зображення.

Наприклад, Ви можете завантажити зображення з високою роздільною здатністю з співвідношенням сторін 4:3,
і відобразити його зменшеним, квадратним або чорно-білим (або з будь-яким
іншим поєднанням кольорів). Drupal робить це
ефективно:

. Налаштуйте стиль зображення з необхідними ефектами на сторінці _Стилі зображень_
(_admin/config/media/image-styles_).

. Ефекти будуть застосовані при першому запиті певної картинки в
цьому стилі зображення.

. Отримане зображення зберігається.

. При наступному запиті того ж стилю збережене зображення буде відновлено
без необхідності вираховувати ефекти.

Ядро Drupal надає кілька ефектів, які ви можете використовувати для визначення стилів;
інші можуть бути надані модулями.

Відвідайте сторінку _Стилі зображень_ через _Керування_ адміністративного меню, перейдіть в
_Конфігурація_ > _Медіа_ > _Стилі зображень_ (_admin/config/media/image-styles_),
щоб побачити стилі зображеннь, які визначені за замовчуванням.

==== Схожі теми

* <<structure-image-style-create>>
* <<structure-image-responsive>>
* <<structure-fields>>


==== Додаткові ресурси

https://www.drupal.org/docs/core-modules-and-themes/core-modules/image-module/working-with-images[_Drupal.org_ сторінка документації спільноти "Working with images"]


*Автори*

Адаптовано і змінено https://www.drupal.org/u/batigolix[Boris Doesborg],
і https://www.drupal.org/u/jojyja[Jojy Alphonso] в
http://redcrackle.com[Red Crackle], з
https://www.drupal.org/docs/core-modules-and-themes/core-modules/image-module/working-with-images["Working with images"],
авторські права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Переклав https://www.drupal.org/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].