[[structure-view-modes]]

=== Основи: Режими перегляду та Форматери

[role="summary"]
Огляд режимів перегляду і форматерів полів.

(((Режими перегляду, огляд)))
(((Режими перегляду сутності, огляд)))
(((Форматер, огляд)))
(((Форматер поля, огляд)))

==== Необхідні знання

<<structure-content-type>>

==== Що таке режими перегляду?

Як відображається об'єкт (наприклад, вміст, користувач або коментар), залежить від
контексту, в якому він відображається. Цей контекст відомий як _режим перегляду_.
Прикладами режиму перегляду можуть бути:

* Повна сторінка вмісту з усіма значеннями полів
* Тизер вмісту з мініатюрою і посиланням «Читати далі»
* Повний профіль користувача масштабованою портретною фотографією
* Аватар користувача з ім'ям користувача і посиланням на профіль

Кожен режим перегляду може бути налаштований на сторінках адміністрування. Щоб побачити
параметри конфігурації для режиму перегляду типу матеріалу Рецепт, перейдіть
в _Керування_ адміністративного меню _Структура_ > _Типи матеріалів_
(_admin/structure/types_) і натисніть _Керувати відображенням_ з меню, випадаючої
кнопки. У кожному режимі перегляду всі поля можуть бути приховані або відображені, і якщо вони
відображаються, ви можете вибрати і налаштувати форматування поля.

==== Що таке форматер поля?

Форматер поля - це налаштування для відображення значень поля. Наприклад,
довгі текстові поля можуть відображатися як обрізані або повнорозмірні, так і в терміні таксономії
посилальні поля можуть бути відображені у вигляді простого тексту або бути посиланням на сторінку терміна
таксономії. Подивіться на сторінку _Керувати відображенням_, щоб побачити форматери поля для
полів типу матеріалу Рецепт.

==== Схожі теми

* <<structure-content-type>>
* <<structure-content-display>>

==== Додаткові ресурси

https://www.drupal.org/node/1577752[_Drupal.org_сторінка документації спільноти "View modes"]


*Автори*

Адаптовано https://www.drupal.org/u/batigolix[Boris Doesborg] з
https://www.drupal.org/node/1577752["View modes"],
авторські права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переклав https://www.drupal.org/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].