[[thoughts-learn-more]]
=== Продовження навчання

[role="summary"]
Де знайти додатковий матеріал, щоб отримати просунуті навички зі створення сайтів.

(((Навчальний ресурс, посилання на)))
(((Навчання, ресурс)))
(((Drupal навчання, ресурси для)))
(((Документація, про Drupal)))
(((Ресурс, документація і навчання)))
(((Документація, доступна на drupal.org)))
(((Документація, надана спільнотою Drupal)))
(((Документація, про Drupal API)))
(((Документація, для програмістів)))
(((Документація, Drupal Planet пости в блозі)))
(((Навчання, Навчальний майданчик)))
(((Навчання, Глобальні навчальні дні)))

==== Необхідні знання

* <<understanding-project>>
* <<thoughts-connecting>>

==== Куди ви можете піти, щоб дізнатися більше?

Наступні ресурси повинні виявитися корисними для вас, в міру просування
ваших навичок:

https://www.drupal.org/documentation[Drupal Community Documentation]::
  Wiki-подібна документація, надана спільнотою Drupal, починаючи від
  базового до просунутого, про всі аспекти Drupal (сайтобудування і
  адміністрації, темізаціі, розробки, і про модулі).
https://api.drupal.org[_api.drupal.org_]::
  Довідкова документація для програмістів про Drupal API.
https://www.drupal.org/planet["Drupal Planet "сторінка на _Drupal.org_]::
  Збірка повідомлень в блозі про Drupal з усього Інтернету, пости від членів спільноти Drupal що ведуть блоги хто подав заявку на
  включення. Теми варіюються від програмування до створення сайту для Drupal новин.
Групи, події і зустрічі::
  Дивіться <<thoughts-connecting>> для отримання додаткової інформації про тематичні, регіональні і мовні
  групи, а також про місцеві, регіональні та міжнародні заходи.
https://www.drupal.org/training["Training Marketplace "сторінка на _Drupal.org_] ::
  Торговий майданчик, який перелічує постачальників платного навчання. Для безкоштовного навчання, перевірте,
  чи включають заходи тренування; є також безкоштовні або дуже дешеві
  навчальні заходи, перераховані в
  https://groups.drupal.org/global-training-days["Global Training Days "сторінка на _Drupal.org_].
Підтримка сайтів::
  Дивіться <<thoughts-support>> знайти форуми підтримки; їх пошук може бути корисний для
  вивчення конкретних тем.

// ==== Related topics

// ==== Additional resources


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
і https://www.drupal.org/u/eojthebrave[Joe Shindelar] в
https://drupalize.me[Drupalize.Me].

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із
https://www.drupal.org/mazaltov[Mazaltov].