[[thoughts-support]]
=== Технічна підтримка

[role="summary"]
Де знайти підтримку для проблем, що виникли при розробці сайту.

(((Підтримка, виявлення)))
(((Форум, підтримка користувачів)))
(((IRC (Internet-чат), використання онлайн чату)))
(((Інтернет-чат (IRC), використання онлайн чату)))
(((Онлайн листування)))

==== Необхідні знання

* <<understanding-project>>
* <<thoughts-connecting>>

==== Де ви можете знайти підтримку?

Drupal має відкритий вихідний код, так що якщо у вас є питання або проблеми
з програмним забезпеченням ваші варіанти пошуку відповідей і виправлень будуть дещо
відрізнятися від того, якими вони будуть для комерційного програмного забезпечення.

Існує кілька варіантів безкоштовної підтримки, що надається спільнотою.
По-перше, деякі IRC-канали, місцеві групи і мовні співтовариства, що заохочують питання підтримки,
через онлайн-чат, особисті зустрічі, або
сайти (дізнатися більше про це в <<thoughts-connecting>>).

По-друге, в деяких (але не всіх) модулях, дистрибутивах і темах
можна публікувати питання щодо підтримки в проблемах (issues). Як правило, проекти, які мають
дуже велику кількість користувачів не дозволяють публікувати запити про підтримку в своїх проблемах
(Ядро Drupal в цій категорії), в той час як проекти з меншою кількістю користувачів
вітають питання щодо підтримки. З повагою ставтеся до часу розробників та
прочитайте документацію по проекту, перш ніж відправляти питання. Але
з іншого боку, у всіх проектах рекомендується задати питання по
Багам; дивіться <<thoughts-connecting>>, щоб дізнатися більше про це.

На додаток до цих ресурсів, такі сайти надають безкоштовні форуми, де
волонтери відповідають на питання підтримки про Drupal:

* https://www.drupal.org/forum[_Drupal.org_ Форуми]
* https://drupal.stackexchange.com/["Drupal Питання "на StackExchange]

Якщо ви віддаєте перевагу платити за підтримку (імовірно в обмін на більш великий набір
послуг або кращу доступність), ви можете знайти постачальників послуг на
https://www.drupal.org/drupal-services["Drupal Marketplace "на _Drupal.org_].

==== Схожі теми

* <<thoughts-learn-more>>
* <<thoughts-connecting>>

==== Додаткові ресурси
* https://www.drupal.org/support[сторінка "Підтримки" на _Drupal.org_]
* https://www.drupal.org/drupal-services["Drupal Marketplace "на _Drupal.org_]
* The https://www.drupal.org/forum[_Drupal.org_ Форуми]
* https://drupal.stackexchange.com/["Drupal Питання "на StackExchange]


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].