[[thoughts-connecting]]
=== Зв'язок зі Спільнотою Drupal

[role="summary"]
Як приєднатися і взяти участь в співтоваристві Drupal.

(((Спільнота, зв'язок)))
(((Drupal проект, зв'язок)))
(((Подія, Drupal)))
(((Група по інтересам, пошук)))
(((Призначена для користувача група, пошук)))
(((Група, пошук)))
(((Призначена для користувача група Drupal, пошук)))
(((IRC (Internet-чат), використання онлайн чату)))
(((Інтернет-чат (IRC), використання онлайн чату)))
(((Онлайн листування)))
(((Внесок в проект)))
(((Помилка, складання звіту)))

==== Необхідні знання

<<understanding-project>>

==== Як ви можете зв'язатися з спільнотою?

Проект Drupal має всесвітнє співтовариство розробників і користувачів. Один з
кращих способів поліпшити свої знання про платформу - це зв'язатися з
іншими людьми, які використовують її, і взяти участь в співтоваристві Drupal. Є
багато способів, як ви можете почати:

Відвідати захід::
  Навколо Drupal проводяться як регіональні, так і міжнародні заходи
  по світу. Дивіться https://events.drupal.org["DrupalCon" сторінка на _Drupal.org_],
  щоб знайти міжнародні події, і
  https://groups.drupal.org/events["Календар подій "на _groups.drupal.org_]
  або https://www.drupical.com/[_drupical.com_], щоб знайти регіональні події.
Приєднатися до місцевої групі::
  По всьому світу є групи користувачів Drupal. Багато з них мають регулярні
зустрічі, які ви можете відвідати, щоб дізнатися більше про Drupal і приєднатися до інших
користувачів Drupal. Знайти локальні групи користувачів на
  https://groups.drupal.org/[_groups.drupal.org_].
Беріть участь у тематичній або мовній групах::
  Існують також групи інтересів з широкого кола тем, які мають онлайн
дискусійні форуми. Знайти тематичні групи на
  https://groups.drupal.org/[_groups.drupal.org_]. Багато мов також мають
власні сайти; ви можете знайти їх на
  https://www.drupal.org/language-specific-communities["Мовні
  спільноти" сторінка на _Drupal.org_].
Онлайн чат::
  Проект Drupal використовує IRC для онлайн-чату. Є регіональні, тематичні,
і загальні чат групи. Дізнайтеся більше на
  https://www.drupal.org/ircchat["IRC" сторінка на _Drupal.org_].
Повідомити про проблему::
  Дивіться нижче.
Співробітництво::
  Ви можете поділитися своїм часом і досвідом з спільнотою різними способами, такими
як:
  * Розробка модулів або тем. Дивіться на
    https://www.drupal.org/contribute/development["Сприяння розвитку "
    сторінка на _Drupal.org_], або покращуючи їх (використання черги помилок для існуючих
    проектів).
  * Переклад призначеного для користувача інтерфейсу. Дивіться
    https://localize.drupal.org[_localize.drupal.org_].
  * Написання документації. Дивіться
    https://www.drupal.org/contribute/documentation["Сприяти
Документації" на _Drupal.org_].
  * Відповіді на питання щодо підтримки. Дивіться <<thoughts-support>>.

==== Як ви можете повідомити про проблему чи запропонувати додаткові можливості?

Кожен проект в співтоваристві (наприклад ядро ​​Drupal для бази
програмного забезпечення і проекти для кожної теми і модуля) використовують _проблеми (issues)_ для
відстеження помилок програмного забезпечення та планування нових додаткових можливостей. Ви можете брати участь
в створенні звіту про помилку при виявленні проблеми, створювати запит на додаткову можливість, або
коментувати існуючі проблеми. Перед створенням проблеми,
переконайтеся, що про проблему або додаткову можливості не було повідомлено.
дивіться
https://www.drupal.org/issue-queue[_Drupal.org_ сторінка "Використання черги помилок"] і
https://www.drupal.org/node/314185[_Drupal.org_ сторінка "Повідомлення про проблему"] для
додаткової інформації.

Якщо ви виявили проблему, яка, на вашу думку, пов'язана з безпекою, таку як
вразливість до Міжсайтового Скриптінгу, не повідомляйте про це в стандартній черзі
помилок. Замість цього повідомте про це в команду безпеки. дивіться
https://www.drupal.org/node/101494[_Drupal.org_ сторінка "Як повідомити про проблему безпеки"] для подробиць.

==== Схожі теми

<<thoughts-support>>

==== Додаткові ресурси

* https://www.drupal.org/dcoc["Норми поведінки" на _Drupal.org_]

* https://groups.drupal.org/events["Календар подій" на _groups.drupal.org_] або
https://www.drupical.com/[_drupical.com_]

* https://www.drupal.org/community["Community" сторінка на _Drupal.org_]

* https://groups.drupal.org/[_groups.drupal.org_]

* https://www.drupal.org/ircchat["IRC "сторінка на _Drupal.org_]

* https://www.drupal.org/contribute["Способи взяти участь" сторінка на _Drupal.org_]

* https://www.drupal.org/node/2486391[_Drupal.org_ сторінка "Навіщо втручатися?"]

* https://www.drupal.org/contributor-tasks[_Drupal.org_ сторінка "Завдання учасника"]

* https://www.drupal.org/issue-queue[_Drupal.org_ сторінка "Використання черги помилок"]

* https://www.drupal.org/node/314185[_Drupal.org_ сторінка "Повідомити про проблему"]

* https://www.drupal.org/node/101494[_Drupal.org_ сторінка "Як повідомити про проблему безпеки"]


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer hodgdon],
і https://www.drupal.org/u/eojthebrave[Joe Shindelar] із
https://drupalize.me[Drupalize.Me].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].