[[understanding-data]]
=== Основи: Типи даних

[role="summary"]
Огляд часто вживаних типів даних, що використовуються на сайтах.

(((Тип даних,огляд)))
(((Тип даних,конфігурація)))
(((Тип даних,контент)))
(((Тип даних,стан)))
(((Тип даних,сесія)))
(((Конфігурація як тип даних)))
(((Контент як тип даних)))
(((Стан як тип даних)))
(((Сеанс роботи як тип даних)))


//==== Prerequisite knowledge

==== Які існують типи даних?

Дані та інформація на вашій сторінці діляться на чотири типи, що редагуються,
переводяться і зберігаються по-різному. Ці чотири типи:

Контент::
Інформація (текст, зображення і т.д.) призначена для відвідувачів сайту.
Цей тип інформації, як правило, не змінюється, але він може редагуватися.

Конфігурація::
Інформація про вашу сторінку - не контент, але вона не змінюється і може
використовуватися для визначення того, як ваш сайт веде себе або відображається.
Ця інформіція іноді відображає на сайті відвідувачів, і швидше містить невеликі
частини тексту (такі, як мітки поля, назва вашого сайту і т.д.) ніж для великих
частин, про які ви зазвичай думаєте, як про вміст.

Стан (state)::
Інформація тимчасового характеру про поточний стан вашого сайту, така як час,
коли завдання крона були запущені в останній раз.

Сесія::
Інформація про взаємодію окремих відвідувачів сайту на сторінці, така як: чи
увійшли вони в систему і про їх куки. Технічно, це підтип інформації про стан,
оскільки це також тимчасово.

==== Пов'язані теми

* <<planning-data-types>>
* <<security-cron-concept>>
* <<user-concept>>
* <<language-concept>>

//==== Додаткові ресурси


*Автори*

Адаптовано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] з
https://www.drupal.org/docs/drupal-apis/configuration-api/overview-of-configuration-vs-other-types-of-information["Огляд конфігурації (порівняно з іншими типами даних"],
авторскі права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко].
