[[understanding-project]]

=== Основи: Проект Drupal

[role="summary"]
Огляд безкоштовного програмного забезпечення з відкритим вихідним кодом, проект Drupal, Асоціація Drupal.

(((Проект Drupal, огляд)))
(((Асоціація Drupal, огляд)))
(((Безкоштовне програмне забезпечення з відкритим вихідним кодом, огляд)))
(((Безкоштовне програмне забезпечення з відкритим вихідним кодом, огляд)))

==== Необхідні знання

<<understanding-drupal>>

==== Що таке безкоштовне програмне забезпечення з відкритим вихідним кодом?

Безкоштовне програмне забезпечення з відкритим вихідним кодом це програмне забезпечення, яке розробляє
спільнота людей і випускає під некомерційною ліцензією, і чий _вихідний
код_ (програмні файли, складові програмного забезпечення) у відкритому доступі. За
додатковою інформацією про некомерційну ліцензію, що використовує Drupal, дивіться
<<understanding-gpl>>.

==== Що таке проект Drupal?

Проект Drupal це проект Open Source, який націлений на розробку ядра програмного забезпечення
системи управління контентом так само, як і на додаткові модулі, додаткові
теми, переклади, документацію і дистрибутиви спеціального призначення. Люди,
які вкладають час і гроші в проект Drupal приїжджають
з усього світу, і є різнобічним співтовариством, яке об'єднується для
спільної мети.

Спільнота охоплює більш дрібні групи, які виконують різні завдання,
такі, як розробка певного програмного забезпечення, пов'язаного з Drupal, написання
документації, забезпечення безпеки програмного забезпечення Drupal, переклади програмного
забезпечення Drupal на певну мову, використання Drupal для конкретної мети,
і збираються разом, щоб зустрітися особисто на певній території.

Детальніше про те, як Ви можете встановити зв'язок і спілкуватися зі світовим співтовариством,
дивіться <<thoughts-connecting>> і <<thoughts-support>>.

==== Що таке Асоціація Drupal?

https://www.drupal.org/association[Ассоциация Drupal] це некомерційна організація
присвячена підтримці проекту та спільноти Drupal. Головними функціями є:

* Проведення з'їздів по всьому світу
* Підтримка _Drupal.org_ веб-сайтів і серверів, над якими йде робота
* Просування Drupal як веб-платформи
* Підтримка Drupal-навчання і підготовки
* Надання допомоги спільноті Drupal для підтримки мети
* Розвиток фондів для цих цілей

==== Пов'язані теми

* <<understanding-gpl>>
* <<security-concept>>
* <<thoughts-connecting>>
* <<thoughts-support>>

==== Додаткові ресурси

* https://www.drupal.org/governance[Drupal project governance]
* https://www.drupal.org/dcoc[Drupal Code of Conduct]


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov].