[[understanding-themes]]

=== Основи: Теми

[role="summary"]
Огляд тем і де їх отримати.

(((Теми,огляд)))
(((Теми,ядро)))
(((Теми ядра,огляд)))
(((Теми,сторонні)))
(((Сторонні теми,огляд)))
(((Теми,власні)))
(((Власні теми,огляд)))

==== Необхідні знання

<<understanding-drupal>>

==== Що таке тема?

Тема являє собою набір файлів, які визначають візуальний зовнішній вигляд вашого сайту.
Ядро Drupal та модулі, які працюють на вашому сайті, визначають який _вміст_ 
(сюди входять HTML-текст та інші дані, що зберігаються в базі даних, завантажені зображення,
а також будь-які інші мультимедійні ресурси) відображається на сторінках вашого сайту.
Тема визначає розмітку та css-стилі HTML, що обгортають вміст.

Ядро Drupal надає кілька простих тем з коробки дистрибутива. Ці теми здебільшого були
спроектовані та побудовані спільнотою протягом останніх кількох років, і кожна з них буде
хорошим вибором для створення ваших перших сайтів і надасть змогу більше ознайомитися з тим,
як працює ядро Drupal.

Drupal це - розповсюджена CMS, що зарекомендувала себе як добре влаштована система керування вмістом,
тому що теми, які розробляються для Drupal сторонніми розробниками можуть бути безкоштовними або платними,
але завжди надійними.

Якщо жодна зі сторонніх тем, що існує, не задовільнить ваші потреби, в такому разі можна створити власну тему.
Власна тема може бути дуже простою. Наприклад, тема лише з одним файлом CSS, який додає стилі до розмітки,
згенерованої ядром Drupal чи іншими модулями. Інструкцію зі створення власних тем в Drupal 8 можна знайти
за посиланням: https://www.drupal.org/docs/8/theming[_Drupal.org_ сторінка документації спільноти "Темізація Drupal"].

==== Пов'язані теми

* <<extend-theme-find>>
* <<extend-theme-install>>
* <<understanding-modules>>

==== Додаткові матеріали

https://www.drupal.org/docs/8/theming[_Drupal.org_ сторінка документації спільноти "Темізація Drupal"]


*Автори*

Написано та відредаговано https://www.drupal.org/u/jgrubb[John Grubb] та
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклад https://www.drupal.org/u/alexmazaltov[Alex Mazaltov]