[[understanding-drupal]]

=== Основи: Drupal як Система Управління Сайтом (CMS)

[role="summary"]
Огляд Drupal та причини його вибору як надійної системи управління сайтом (CMS).

(((CMS (Система Управління Сайтом),основи)))
(((Система Управління Сайтом (CMS),основи)))
(((Drupal система управіління сайтом,основи)))
(((Drupal система управіління сайтом,вимоги до сервера)))
(((Drupal ядро,основи)))
(((Drupal.org вебсайт,завантаження модулів і тем)))

//==== Необхідні знання

==== Що таке Система Управління Сайтом?

Система управління сайтом (CMS) це програмний інструмент, який дозволяє
користувачам додавати, публікувати, редагувати і видаляти контент на сайті,
використовуючи браузер на телефоні, планшеті, ноутбуці або комп'ютері.
Зазвичай CMS написана на скриптовій мові і ці скрипти запускаються на комп'ютері,
де є база даних і веб сервер. Контент і налаштування для сайту зазвичай
зберігаються в базі даних і для кожного запиту сторінки, який йде на веб сервер,
скрипти збирають інформацію з бази даних і додаткових файлів (JavaScript файли,
CSS файли, файли зображень і так далі, які є частиною CMS або були завантажені),
щоб відображатися на сторінках сайту.

Комбінація з операційної системи, на якій CMS працює, скриптова мова на якій CMS
написана, база даних в якій зберігатиметься інформація і веб сервер на якому
працюють скрипти отримуючи інформацію та повертають цю інформацію браузеру
відвідувача сайту, все це відомо як _стек_ (_stack_), на якому CMS працює.
Найбільш часто використовувана комбінація операційна система на Linux, веб сервер
Apache, база даних MySQL і скриптова мова PHP, все це відомо як _LAMP стек_.

==== Що таке Drupal?

Drupal це гнучка CMS заснована на LAMP стеку, з модульною структурою, що дозволяє
додавати і видаляти функціонал через установку і видалення _модулів_, і дозволяє
змінити зовнішній вигляд сайту через установку і видалення _тем_ оформлення.
Основа Drupal, відома як ядро Drupal, містить PHP скрипти необхідні для запуску
основного функціоналу CMS, декількох додаткових модулів і тем, і безлічі JavaScript,
CSS і файлів зображень. Безліч додаткових модулів і тем оформлення ви можете
завантажити з сайту https://www.drupal.org[_Drupal.org_].

Drupal також може бути запущений на інших технологічних стеках:

* Операційна система може бути Windows або Mac OS замість Linux.

* Веб сервер може бути Nginx або IIS замість Apache.

* База даних може бути PostgreSQL або SQLite замість MySQL або
інша MySQL-сумісна заміна, така як MariaDB або Percona.

Операційні системи, веб сервери і бази даних можуть також бути іншими, але
скрипти, які використовує Drupal, написані на PHP, будуть одні і ті ж.

==== Які причини використовувати Drupal?

При створенні сайту у вас є вибір між використанням одного з безлічі існуючих
пакетів CMS і хостингових послуг, розробкою власної CMS або створенням сайту
без використання CMS. Ось деякі з причин, за якими ви можете вибрати
використання Drupal:

* Створення простого, маленького сайту зі статичними HTML сторінками не так
складно і ви можете легко отримати простий сайт дуже швидко. Налаштування сайту
в CMS головним чином вимагає більше часу для установки, але це приносить вигоду
в онлайн редагуванні (простіше для менш досвідчених модераторів контенту),
уніфікацію (чим більше сайт, тим складніше поміняти одну і ту жу інформацію на
безлічі статичних HTML сторінках) і можливості для складнішого функціоналу
вимагають бази даних.

* Деякі CMS є вузькоспрямованими, наприклад, ви можете створити блог або групу
для організації на сайті. Drupal навпаки - це CMS для загальних цілей. Якщо ви
будуєте вузькоспрямований сайт, ви можете вибрати спеціалізовану CMS, але, якщо
ваш сайт вимагає більш глобальних речей, можливо вам краще використовувати CMS
для загальних цілей, ніж намагатися адаптувати вузькоспрямовану CMS.

* Створення своєї CMS здається привабливим. Але використання CMS для загальних
цілей, такої як Drupal для початку роботи ідея трохи краща, тому що базовий
функціонал CMS (такий як акаунти користувачів і управління контентом) увібрав
в себе тисячі годин розробки, включаючи багато років тестування користувачами,
правку багів і поліпшення безпеки.

* Деякі CMS дорогі, щоб купувати їх ліцензію. Деякі мають безкоштовну версію,
але з обмеженнями, які не дозволяють вам вносити зміни і розширювати функціонал.
Ви можете віддати перевагу використовувати CMS (як Drupal), яка має менше
обмежень у використанні і розробці та підтримується спільнотою по всьому світу.
Дивіться також <<understanding-project>> для більш детальної інформації.

==== Пов'язані теми

* <<understanding-modules>>
* <<understanding-themes>>
* <<understanding-distributions>>
* <<understanding-project>>

==== Додаткові ресурси

* https://www.drupal.org/docs/8/understanding-drupal-8/overview[_Drupal.org_ Сторінка документації спільноти
"Understanding Drupal: Overview"]

* https://www.drupal.org/about/faq[_Drupal.org_ page "FAQ" (Frequently Asked Questions)]

* https://www.drupal.org/case-studies[_Drupal.org_ page "Case Studies"]

* https://en.wikipedia.org/wiki/Content_management_system[Wikipedia page "Content management systems"]

* https://en.wikipedia.org/wiki/Modular_design[Wikipedia page "Modular design"]


*Автори*

Написано та відредаговано https://www.drupal.org/u/kvantomme[Kristof van Tomme]
в https://pronovix.com/[Pronovix],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
та https://www.drupal.org/u/michaellenahan[Michael Lenahan]
в https://erdfisch.de[erdfisch].

Перевів https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко].