[[understanding-modules]]
=== Основи: Модулі

[role="summary"]
Огляд модулів і функціональності, для якої вони можуть бути використані.

(((Модуль, огляд)))
(((Додатковий модуль, огляд)))
(((Модуль ядра Drupal, огляд)))
(((Модуль Field, огляд)))
(((Модуль Field UI, огляд)))
(((Модуль Menu UI, огляд)))
(((Модуль Node, огляд)))
(((Для користувача модуль, огляд)))
(((Модуль Views, огляд)))
(((Модуль Views UI, огляд)))
(((Модуль, ядро)))
(((Модуль, додатковий)))
(((Модуль, Field)))
(((Модуль, Field UI)))
(((Модуль, Field UI)))
(((Модуль, Node)))
(((Модуль, User)))
(((Модуль, Views)))
(((Модуль, Views UI)))

==== Необхідні знання

<<understanding-drupal>>

==== Що таке модуль?

Модуль - це набір PHP, JavaScript і CSS файлів, які розширюють можливості сайту
і додають функціональність. Ви можете включити можливості і функціональність сайту
за допомогою _установки_ модуля, і ви можете відключити їх за допомогою _видалення_
модуля; перед видаленням, вам може знадобитися видалити дані і конфігурації,
пов'язані з можливостями і функціональністю. Кожен встановлений модуль додає
час, необхідний для створення сторінок на вашому сайті, так що це гарна ідея
видаляти модулі, які не потрібні.

Ядро Drupal надає модулі для:

* Управління обліковими записами користувачів (модуль ядра User)

* Управління основним вмістом (модуль ядра Node) і полями (модуль Field і
Field UI; є також інші модулі ядра, що забезпечують різні типи полів Email, Phone і т.д.)

* Управління меню (модуль ядра Menu UI)

* Створення списків, таблиць і блоків з існуючого контенту (модуль ядра Views і
Views UI)

Ви можете завантажити _додаткові модулі_ на
https://www.drupal.org/project/project_module[_Drupal.org_ Module Downloads], або створити власний
_клієнтський модуль_.

==== Схожі теми

* <<understanding-themes>>
* <<understanding-distributions>>
* <<config-uninstall>>
* <<extend-module-find>>
* <<extend-module-install>>
* <<security-concept>>
* <<security-update-module>>

==== Додаткові ресурси

https://www.drupal.org/developing/modules[_Drupal.org_ сторінка документації спільноти "Module developer's guide"]


*Автори*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov].
