[[understanding-gpl]]

=== Концепція: Ліцензування Drupal

[role="summary"]
Огляд ліцензування Drupal і методичні рекомендації, яким повинні слідувати користувачі та учасники.

(((Ліцензування, огляд)))
(((Ліцензування Drupal, огляд)))
(((GPL (Універсальна загальнодоступна ліцензія або Відкрита ліцензійна угода), огляд)))
(((GNU Універсальна загальнодоступна ліцензія, огляд)))
(((Правовий, огляд)))

==== Необхідні знання

<<understanding-drupal>>

==== Що таке Ліцензування Drupal?

Drupal і всі вкладені файли, розташовані на _Drupal.org_, ліцензовані Універсальною
Загальнодоступною Ліцензією, версії 2 або більш пізньою. Це означає, що Ви можете безкоштовно
завантажити, повторно використовувати, змінити, і поширити файли, які є частиною проекту на
_Drupal.org_ відповідно до умов GPL версії 2 або 3. Ви також можете запустити основне
програмне забезпечення в поєднанні з будь-яким кодом з ліцензією, яка сумісна з
версіями 2 і 3.

Учасники Drupal повинні слідувати даним методичним рекомендаціям:

* Всі файли (PHP, JavaScript, зображення, Flash, і т.д.), які є частиною проекту
на _Drupal.org_ повинні бути ліцензовані версією 2 або пізнішою.

* Всі учасники Drupal зберігають авторські права на свій код, але погоджуються випустити
його на ту ж ліцензію, що і Drupal.

* Модулі і теми Drupal є похідною роботою Drupal. Якщо Ви поширюєте
їх, Ви повинні робити це відповідно до умов GPL версії 2 або більш пізньої.

* Всі матеріали на _Drupal.org_ належать його початковим
вкладникам, і ліцензовані the Creative Commons Attribution-ShareAlike
license версії 2.0.

* Приклад коду на _Drupal.org_ також доступний під ліцензією GPL версії 2 або більш пізньою.

==== Пов'язані теми

<<thoughts-connecting>>

==== Додаткові ресурси

* https://www.drupal.org/about/licensing[_Drupal.org_ page on "Licensing"]

* https://api.drupal.org/api/drupal/core!LICENSE.txt/8.2.x["Drupal 8 LICENSE.txt "page on _api.drюpal.org_]

* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU General Public License, version 2]

* http://www.gnu.org/licenses/gpl-3.0.en.html[GNе General Public License, version 3]

* https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons Attribution-ShareAlike license 2.0.]

* https://groups.drupal.org/legal["Legal Group "on _groups.drupal.org_]

*Автори*

Написано https:/юwww.drupal.org/u/dianalakatos[Diana Lakatos] на
https://pronovix.com/[Pronovix] з
https://www.drupal.org/about/licensing["Licensing "]
авторські права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Перевів https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov]