[[understanding-distributions]]

=== Основи: Дистрибутиви

[role="summary"]
Огляд дистрибутивів, які можуть бути використані для специфічних
сайтів.

(((Дистрибутив, огляд)))
(((Дистрибутив, повнофункціональний)))
(((Дистрибутив, швидкий старт)))
(((Повнофункціональний дистрибутив, огляд)))
(((Дистрибутив для швидкого початку, огляд)))

==== Необхідні знання

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>

==== Що таке дистрибутив?

_Дистрибутиви_ надають функції і можливості для сайту під певні завдання
у вигляді зібраних разом ядра Drupal, модулів, тем оформлення
і зумовлених налаштувань. Дистрибутив робить можливим налаштування
складного сайту під певні завдання в кілька кроків через установку і
настройку окремих елементів сайту.

Дистрибутиви поділяються на два типи:

Повнофункціональні дистрибутиви::
  Повнофункціональний дистрибутив - це проект що надає готове рішення
  для налаштування сайту під певні завдання, в таких сферах як навчання, сайт-візитка, інтернет магазин,
  сайт державної організації, некомерційна організація, медіа, соціальні мережі і так далі. Наприклад, ви можете використовувати
  існуючий дистрибутив для сайту міського ярмарку, щоб зробити свій власний сайт або ви
  можете поділитися своїми налаштуваннями сайту міського ярмарку як дистрибутивом, щоб
  інші змогли створити подібний сайт.

Інші дистрибутиви::
  Дистрибутиви можуть також допомогти швидко почати розробку для програмістів і творців
  сайтів.

==== Пов'язані теми

<<thoughts-connecting>>

==== Додаткові матеріали

https://www.drupal.org/project/project_distribution[_Drupal.org_ Drupal Distribution Downloads]


*Автори*

Адаптовано і змінено https://www.drupal.org/u/dianalakatos[Diána Lakatos]
і https://www.drupal.org/u/ifrik[Antje Lorch],
з https://www.drupal.org/docs/7/distributions["Distributions"]
і https://www.drupal.org/project/project_distribution["Download & Extend - Distributions"]
авторські права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Перекладено https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://www.drupal.org/mazaltov[Mazaltov].