[[user-admin-account]]

=== Основи: Аккаунт користувача з ID 1

[role="summary"]
Огляд аккаунта користувача з ID 1, також відомий як аккаунт root або адміністративний акаунт.

(((Користувач, root)))
(((Користувач, користувач з ID 1)))
(((Користувач, адміністративний)))
(((Безпека, аккаунт користувача з ID 1)))

==== Необхідні знання

<<user-concept>>

==== Що таке користувач з ID 1?

Під час установки вашого сайту ви створили перший аккаунт користувача. Кожен
аккаунт користувача має номер користувача ID, і оскільки ID цього користувача
один, зазвичай його називають аккаунтом _користувач з ID 1_. Цей обліковий запис користувача
спеціальний, тому що незалежно від того, які ролі йому призначені, той, хто увійшов як
користувач з ID 1, має дозвіл робити всі дії на сайті, включаючи перегляд і
редагування всього контенту, редагування будь-якого облікового запису користувача, зміна конфігурації сайту,
установка і видалення модулів, і запуск скрипта оновлення.

Через цей рівень дозволу, деякі люди називають цей аккаунт
_користувач root_, тому що він схожий на аккаунт користувача "root", який має повний адміністративний
доступ в Linux та інших операційних системах.

Зазвичай краще створити окремі акаунти для кожного адміністратора,
даючи їм роль _Адміністратор_, замість того, щоб всі адміністративні
користувачі входили в систему, використовуючи обліковий запис користувача з ID 1. На це є кілька причин:

* Деякі дії і поновлення на сайті реєструються, і якщо всі використовують один і той же
аккаунт, важко зрозуміти, хто їх зробив, якщо у вас виникли питання.

* Права доступу для ролі _Адміністратор_ можна змінити, щоб вона стала безпечнішою,
ніж повні права доступу для облікового запису користувача з ID 1, щоб люди випадково не змінили
функціонал сайту, який не повинен бути змінений.

* Відповідальність людей на сайті може з часом змінюватися. Із звичайним обліковим записом
користувача, це можна змінити шляхом призначення або скасування призначених
ролів для акаунтів користувачів. Якщо вони всі використовують аккаунт користувача з ID 1,
це стає складніше.

* На деяких сайтах, автор матеріалу або коментарів відображається, або відстежується, і
якщо всі використовують один і той же обліковий запис для створення матеріалу, стає важко зрозуміти
хто створив матеріал.

Неможливо видалити акаунт користувача з ID 1 через адміністративний
інтерфейс. Можна було б це зробити через запит до бази даних, але це може привести до
проблем на вашому сайті і не рекомендується.

// ==== Related topics

==== Додаткові ресурси

https://www.drupal.org/node/22284[_Drupal.org_ сторінка документації спільноти "Accounts and roles"]

*Автори*

Написано і змінено https://www.drupal.org/u/mark-lacroix[Mark LaCroix]
і https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/u/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].