[[user-concept]]

=== Основи: Користувачі, Ролі і Права доступу

[role="summary"]
Огляд облікових записів користувачів, прав доступу і ролей.

(((Користувач, огляд)))
(((Роль, огляд)))
(((Роль користувача, огляд)))
(((Права доступу, огляд)))
(((Анонімний користувач, огляд)))
(((Авторизований користувач, огляд)))
(((Аккаунт адміністратора, огляд)))

// ==== Prerequisite knowledge

==== Що таке Користувач?

Той, хто відвідує ваш сайт, є _користувач_, включаючи вас. Є три
групи користувачів:

* Користувачі, які не ввійшли в систему, або _Анонімний користувач_

* Користувачі, які увійшли в систему, або _Авторизований користувач_

* Обліковий запис адміністратора, який була автоматично створений при
установці вашого сайту, або Користувач 1. Дивіться <<user-admin-account>>.

==== Що таке Права доступу?

Можливість здійснювати дії на вашому сайті (включаючи перегляд контенту, додавання
контенту, і зміну конфігурації) регулюється _Правами доступу_. Кожне
право доступу має ім'я (таке, як _Перегляд опублікованих матеріалів_) і охоплює одну дію
або невелику підмножину дій. Користувач повинен отримати дозвіл для того, щоб зробити
відповідну дію на сайті; права доступу визначаються модулями,
які забезпечують дії.

==== Що таке Роль?

Замість того, щоб призначати індивідуальні дозволу безпосередньо кожному користувачеві, права доступу
згруповані в _ролі_. Ви можете визначити одну або кілька ролей на вашому сайті, і
потім надати права доступу кожної ролі. Права доступу, надані авторизованим
і анонімним користувачам містяться в ролях _Авторизований користувач_ і _Анонімний користувач_, і в залежності від інсталяційного профілю, який ви використовували, коли
встановлювали ваш сайт, також може бути роль _Адміністратор_, якій
автоматично призначаються всі дозволи на вашому сайті.

Кожен обліковий запис користувача на вашому сайті автоматично отримує роль _Авторизований користувач_, і при бажанні може бути призначена одна або кілька додаткових ролей. Коли ви
призначите роль для облікового запису користувача, користувач матиме всі права доступу
при вході в систему.

Доброю практикою є створення декількох ролей на вашому сайті. На прикладі сайту
міського ярмарку, вам можуть знадобитися наступні ролі:

* Роль постачальнника, яка дозволяє постачальнникам редагувати власну сторінку списку постачальнників.

* Роль редактора для редагування сторінок міського ярмарку

* Роль менеджера для управління рахунками постачальнника

* Роль _Адміністратор_, встановлена ​​на вашому сайті, для користувачів, які будуть
керувати конфігурацією сайту

==== Схожі теми

* <<user-new-role>>
* <<user-permissions>>
* <<user-roles>>
* <<user-new-user>>
* <<user-admin-account>>
* <<user-content>>

==== Додаткові ресурси

* https://www.drupal.org/node/120614[_Drupal.org_ сторінка документації спільноти "Users, roles and permissions"]
* https://www.drupal.org/docs/7/managing-users[_Drupal.org_ сторінка документації спільноти "Managing Users"]
* https://www.drupal.org/docs/7/managing-users/user-roles[_Drupal.org_ сторінка документації спільноти "User Roles"]


*Автори*

Адаптовано https://www.drupal.org/u/mark-lacroix[Mark LaCroix],
https://www.drupal.org/u/batigolix[Boris Doesborg], і
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] з
https://www.drupal.org/docs/7/managing-users/user-roles["User Roles "],
авторські права 2000-copyright_upper_year за окремими учасниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переклав https://www.drupal.org/alexmazaltov[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].