[[views-parts]]

=== Основи: Розділи Видів

[role="summary"]
Огляд адміністрування частин видів.

(((Вид, розділ)))
(((Відображення розділ виду, огляд)))
(((Формат розділ виду, огляд)))
(((Поля розділ виду, огляд)))
(((Критерії фільтрування розділ виду, огляд)))
(((Критерії впорядкування розділ виду, огляд)))
(((Контекстні фільтри розділ виду, огляд)))
(((Зв'язки розділ уявлення, огляд)))
(((Вид, відображення розділ)))
(((Вид, формат розділ)))
(((Вид, поля розділ)))
(((Вид, критерії фільтрування розділ)))
(((Вид, критерії впорядкування розділ)))
(((Вид, контекстні фільтри розділ)))
(((Вид, зв'язки розділ)))

==== Необхідні знання

* <<planning-data-types>>
* <<planning-modular>>
* <<views-concept>>
* <<content-paths>>
* <<block-concept>>

==== Які розділи є у виду?

Коли ви редагуєте вид через адміністративний інтерфейс, ви можете побачити
наступні розділи (або секції), які дозволяють визначити які дані будуть виводитися,
в якому порядку і в якому форматі:

Відображення::
  Кожен вид може мати одне або більше відображень, кожне з відображень використовує один з типів
  виведення. За замовчуванням модуль Views надає наступні типи відображень:
  Сторінка;;
    Створює виведення сторінки за певним URL, вивід контенту сайту в регіоні Головний контент буде братися з цього відображення для обраного URL.
  Блок;;
    Створює вивід в блоці, який може бути розміщений на сторінках.
  Потік даних;;
    Створює RSS або інші типи стрічок.
  Прикріплення;;
    Створює вивід який ви можете прикріпити до іншого відображення.
Формат::
  Залежить від типу відображення, який ви можете вибрати для виведення ваших даних в
  таблиці, сіткою, HTML списком або іншим форматом. Деякі формати також дають вам
  другий вибір, в якому дозволяються виводити або оброблені сутності або поля; інші
  формати не дають вам такого вибору (наприклад, якщо ви використовуєте формат таблиці,
  ви повинні завжди використовувати поля).
Поля::
  Залежать від формату який ви вибрали, щоб були доступні поля контенту
  для виведення. Наприклад, якщо ви зробили вид рецептів, в
  відображенні блоку ви можете показати тільки імена рецептів, в іншому місці на повній сторінці
  ви можете відобразити поля зображення, тому що там ви маєте більше місця.
Критерії фльтрування::
  Фільтри дають змогу обмежити виведення даних, залежно від критеріїв, таких як чи є
  контент опублікованими чи ні, тип матеріалу або значення поля.
  Наприклад, створивши вид рецептів, ви повинні будете відфільтрувати
  контент за типом матеріалу і виводити тільки опубліковані рецепти. Фільтри можуть також бути
   _розкритими_, це означає, що користувачі матимуть форму, де вони зможуть вибрати
  свої власні значення для фільтрів. Ви можете використовувати розкриті фільтри на сторінці рецептів, щоб дозволити користувачам
  фільтрувати рецепти по відповідним інгредієнтам.
Критерії впорядкування::
  Визначають порядок представлений у висновку, який грунтується на будь-яких полях
  контенту.
Контекстні фільтри::
  Контекстні фільтри подібні звичайним фільтрам, за винятком того, що значення приходять з
  _контексту_ відображення виду, наприклад з URL сторінки, де вид
  відображається, поточної дати або часу або деякі інші значення, які можуть бути
  визначені через обчислення у виді.
Зв'язки::
  Зв'язки дозволяють вам розширити відображення вашого виду, через зв'язки
  з базовим контентом що відображається у виді з іншими сутностями контенту. Зв'язки
  створюються використовуючи поля в базовому контенті, які пов'язують їх з іншим контентом;
  Одним з прикладів є те, що весь контент на сайті має поле автора, яке
  посилається на аккаунт користувача, який створив цей контент. У той момент, коли ви
  створили зв'язок, ви можете відображати поля з пов'язаної
  сутності у виді.

==== Пов'язані теми

<<views-create>>

// ==== Additional resources


*Автори*

Написано і змінено https://www.drupal.org/u/surendramohan[Surendra Mohan]
і https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].