[[views-concept]]
=== Основи: Використання Видів

[role="summary"]
Огляд видів і даних, які можуть бути відображені або виведені ними.

(((Вид, огляд)))
(((Views модуль, огляд)))

==== Необхідні знання

* <<planning-modular>>
* <<planning-data-types>>

==== Що таке вид?

_Вид_ це список контенту на сайті. Модуль ядра Views обробляє
відображення виду, і модуль ядра Views UI дозволяє створювати і редагувати
їх в адміністративному інтерфейсі. Коли ви налаштовуєте вид, ви зацікавлені
взяти дані з вашого сайту і відобразити їх користувачеві.

==== Які типи даних можуть бути відображені за допомогою виду?

Ви можете створювати види для виведення практично будь-якого вмісту, яке зберігається в
системі. Наприклад, ви можете створити такі списки для
сайту фермерського ярмарку:

* Списки продавців
* Списки рецептів
* Списки самого останнього контенту на сайті
* Списки користувачів на сайті

==== Як можна виводити дані з використанням видів?

Список, створений видом, може бути в будь-якій з наступних форм:

* Таблиця з сортованими полями
* Сітка
* Тизери або картинки, які посилаються на статті
* Блоки
* Вивід JSON
* RSS-канали
* Календарі
* Слайд-шоу на екрані

==== схожі теми

* <<views-parts>>
* <<views-create>>

// ==== Additional resources


*Автори*

Написано і змінено
https://www.drupal.org/u/michaellenahan[Michael Lenahan] в
https://erdfisch.de [erdfisch], і
https://www.drupal.org/u/jojyja[Jojy Alphonso] в
http://redcrackle.com [Red Crackle].

Переклав https://www.drupal.org/user/2914091[Олексій Бондаренко] із https://drupal.org/mazaltov[Mazaltov].