[[attributions]]
=== Общие сведения об авторах

[role="summary"]
Список участников, вовлечённых в управление проектом и в общие
задачи по написанию/редактированию.

(((Авторство этого руководства)))
(((Авторы этого руководства)))
(((Авторское право этого руководства)))

Это руководство написано участниками сообщества Drupal
и распространяется под
лицензией https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0]. См.
<<copyright>> для получения дополнительной информации. Подробности об участниках
общих задач приведены ниже. Для отдельных тем атрибуция написания,
редактирования и/или перевода находится в конце каждой темы.


==== Координация проекта исходного текста (English, Drupal 8)

Написание первоначальной версии этого руководства было
скоординировано следующими людьми:

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] - координация волонтёров
и управление проектом

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] - редактура контента

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] - редактура контента

* https://www.drupal.org/u/ifrik[Antje Lorch] - редактура контента


==== Написание, редактирование и тестирование оригинального текста

Следующие люди внесли вклад в написание руководства:

* Глоссарий был написан и адаптирован
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
частично на основе https://www.drupal.org/docs/7/understanding-drupal/glossary["Glossary"],
https://www.drupal.org/node/2120523["Overview of Configuration (vs. other
types of information)"] и
https://www.drupal.org/docs/8/theming-drupal-8/working-with-breakpoints-in-drupal-8["Working with
breakpoints in Drupal 8"],
авторские права каждой части принадлежат отдельным участникам
https://www.drupal.org/documentation[Drupal Community Documentation] (2000–2017).

* Оглавление было улучшено и курировалось
https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst].

* Обзоры тем были написаны
https://www.drupal.org/u/jojyja[Jojy Alphonso] at
http://redcrackle.com[Red Crackle].


Редактирование руководства было выполнено следующими людьми:

* https://www.drupal.org/u/amber-himes-matz[Amber Matz] at
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/avanraaphorst[Anna van Raaphorst]

* https://www.drupal.org/u/ifrik[Antje Lorch]

* https://www.drupal.org/u/balu-ertl[Balu Ertl]

* https://www.drupal.org/u/batigolix[Boris Doesborg]

* https://www.drupal.org/u/cleverington[Charles Leverington]

* https://www.drupal.org/u/chishah92[chirag shah]

* https://www.drupal.org/u/gdunham[Grant Dunham]

* https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

* https://www.drupal.org/u/eojthebrave[Joe Shindelar] at
https://drupalize.me[Drupalize.Me]

* https://www.drupal.org/u/jojyja[Jojy Alphonso] at
http://redcrackle.com[Red Crackle] -- который вычитал большую часть
User Guide

* https://www.drupal.org/u/kamalkantpansari[Kamal Kant Pansari] at
http://www.intelliswift.com/[Intelliswift]

* https://www.drupal.org/u/michaellenahan[Michael Lenahan]
at https://erdfisch.de[erdfisch]

* https://www.drupal.org/u/swarad07[Swarad Mokal] at
http://www.blisstering.com[Blisstering Solutions]


Контент был протестирован:

* https://www.drupal.org/u/zachcarter[Zach Carter]

* Воркшоп, организованный https://groups.drupal.org/spokane-wa["Spokane
Drupal User Group" on groups.drupal.org], со студентами программы Web Development
Certificate в http://scc.spokane.edu[Spokane Community College]


==== Изображения

Большинство изображений в руководстве — это скриншоты интерфейса Drupal,
созданные с помощью программ, написанных
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Слово Drupal, логотип Druplicon (который появляется на нескольких изображениях
руководства), и логотип-словосочетание Drupal (который является частью обложки
издания), являются
https://www.drupal.org/about/media-kit/logos[зарегистрированными товарными
знаками Dries Buytaert].

Обложка распространяется под лицензией CC BY-SA 2.0; иллюстрация создана
https://www.drupal.org/u/mndonx[Amanda Luker] at
https://www.advomatic.com/[Advomatic].

Логотип Городской ярмарки города N, который появляется на нескольких изображениях
руководства, распространяется под лицензией CC BY-SA 2.0; иллюстрация создана
Justin Harrell at https://drupalize.me/[Drupalize.Me].

Изображение пчелы, которое появляется в ряде иллюстраций руководства, является
общественным достоянием; автор —
https://en.wikipedia.org/wiki/User:Severnjc[John Severns] at the
https://en.wikipedia.org/wiki/Main_Page[English Wikipedia project] via
https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg[Wikimedia Commons].

Изображение фермы, которое появляется в ряде иллюстраций руководства, является
общественным достоянием; автор Xianmin Chang via
https://commons.wikimedia.org/wiki/File:Bere%26ModernBarley.jpg[Wikimedia Commons].

Изображение салата, которое появляется в ряде иллюстраций руководства, является
общественным достоянием; автор
https://www.goodfreephotos.com/[Yinan Chen] via
https://commons.wikimedia.org/wiki/File:Gfp-salad.jpg[Wikimedia Commons].

Изображение моркови, которое появляется в ряде иллюстраций руководства, является
общественным достоянием; изображение
https://www.ars.usda.gov/oc/images/photos/nov04/k11611-1/[K11611-1] by
Stephen Ausmus at the
https://en.wikipedia.org/wiki/Agricultural_Research_Service[Agricultural Research Service of the United States Department of Agriculture] via
https://commons.wikimedia.org/wiki/File:Carrots_of_many_colors.jpg[Wikimedia Commons]
