[[block-concept]]

=== Основы: Блоки

[role="summary"]
Обзор блоков.

(((Блок,обзор)))

//==== Prerequisite knowledge

==== Что такое блок?

_Блоки_ — это отдельные элементы макета веб-страницы вашего сайта. Они размещаются
внутри регионов (см. <<block-regions>>) вашей темы и могут быть созданы,
удалены и перемещены на странице _Схема блоков_ (_admin/structure/block_)
администрирования.  Примеры блоков включают список _Кто на сайте_,
главное меню навигации и цепочку «хлебных крошек». Основное содержимое страницы тоже
является блоком.

Некоторые модули добавляют новые блоки, доступные для размещения на сайте. Например,
когда установлен и настроен основной модуль Search, он предоставляет блок,
содержащий форму поиска. Вы также можете создавать и размещать свои собственные
блоки.

Каждый блок имеет собственные параметры, позволяющие выбирать,
на каких страницах сайта отображать блок. Можно разместить даже несколько
копий одного и того же блока, каждая — со своей конфигурацией и
правилами видимости.

==== Похожие темы

* <<block-regions>>
* <<block-create-custom>>
* <<block-place>>

//==== Additional resources


*Авторы*

Адаптировано https://www.drupal.org/u/les-lim[Les Lim] от
https://www.drupal.org/docs/core-modules-and-themes/core-modules/block-module/managing-blocks["Managing blocks"]
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
