[[block-concept]]

=== Основы: Блоки

[role="summary"]
Обзор блоков.

(((Блок,обзор)))

//==== Prerequisite knowledge

==== Что такое блок?

_Блоки_ являются отдельными частями макета веб-страницы вашего сайта. Они размещены
внутри регионов (смотрите <<block-regions>>) вашей темы, и может быть созданы,
удалены, и перемещены в _Схеме блоков_ (_admin/structure/block_)
административной страницы.  Примеры блоков включают в себя список _Кто на сайте_,
меню основной навигации, и хлебные крошки. Содержание главной страницы также
является блоком.

Некоторые модули делают новые блоки доступными для размещения на вашем сайте. Например,
когда модуль ядра Search установлен и настроен, он обеспечивает блок,
который содержит форму поиска. Вы также можете создать и разместить свои собственные
блоки.

Каждый блок имеет свои настройки, которые позволяют выбрать
на каких страницах вашего сайта будет отображаться блок. Также можно разместить
несколько копий блока, каждая со своей конфигурацией и
правилами видимости.

==== Похожие темы

* <<block-regions>>
* <<block-create-custom>>
* <<block-place>>

//==== Additional resources


*Авторы*

Адаптировано https://www.drupal.org/u/les-lim[Les Lim] от
https://www.drupal.org/docs/core-modules-and-themes/core-modules/block-module/managing-blocks["Managing blocks"]
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
