[[copyright]]
=== Авторские права

[role="summary"]
Информация об авторских правах этого руководства пользователя Drupal.

(((Авторские права для этого руководства)))

Это руководство было написано участниками проекта Drupal с открытым исходным
кодом. Авторские права 2015-copyright_upper_year принадлежат отдельным участникам, и
материалы могут использоваться в соответствии с
https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons License,
Attribution-ShareAlike 2.0] (CC BY-SA 2.0). Каждая страница этого документа
(включая эту) содержит раздел «Авторы» внизу, перечисляющий
людей, которые внесли вклад в написание и редактирование этой страницы. См. также
<<attributions>>, чтобы узнать об общих редактировании, переводах и управлении
проектом.

Лицензия CC BY-SA (очень похожая на GPL) позволяет любому копировать, изменять
и распространять модификации всей работы или её части при соблюдении
следующих условий:

* Вы указываете соответствующее авторство (подробности см. в лицензии).
* Вы предоставляете ссылку на лицензию.
* Вы отмечаете, были ли внесены изменения.
* Вы распространяете свою работу под той же лицензией, что и оригинал.

*Авторы*

Эта страница была адаптирована и отредактирована
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle], на основе
https://www.drupal.org/terms["Documentation copyright and licensing"],
авторские права 2000-copyright_upper_year принадлежат отдельным участникам
https://www.drupal.org/documentation[Drupal Community Documentation].

// Следующее уведомление об авторских правах отображается внизу
// каждой страницы HTML-версии этого руководства.

[role="copyright"]
Уведомление об авторских правах: 2015-copyright_upper_year, отдельные участники; см.
<<copyright>> для подробностей. Лицензия
https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0].
