[[extend-config-versions]]

=== Синхронизация версий конфигурации

[role="summary"]
Как синхронизировать конфигурацию между сайтом разработки и рабочим сайтом,
используя модуль ядра Configuration Manager.

(((Конфигурация,синхронизация между сайтом разработки и рабочим сайтом)))
(((Сайт разработки,синхронизация с рабочим сайтом)))
(((Рабочий сайт,синхронизация с сайтом разработки)))
(((Модуль Configuration Manager,использование для синхронизации конфигурации между сайтом разработки и рабочим сайтом)))
(((Модуль,Configuration Manager)))

==== Цель

Синхронизировать конфигурацию между сайтом разработки и рабочим сайтом.

==== Необходимые знания

* <<understanding-data>>
* <<install-prepare>>
* <<install-dev-sites>>
* <<install-dev-making>>

==== Требования к сайту

* У вас должна быть копия разработки вашего рабочего сайта. Смотрите
<<install-dev-making>>.

* Модуль ядра Configuration Manager должен быть установлен как на сайте
разработки, так и на рабочем сайте. Смотрите <<config-install>> для
инструкций по установке модулей ядра.

* Вы изменили конфигурацию либо на рабочем, либо на тестовом
сайте (_исходный сайт_) и хотите синхронизировать изменения с другим
сайтом (_целевой сайт_). Например, можно создать новый тип
контента, поля и представления на сайте разработки и,
убедившись в их правильной работе, развернуть изменения на рабочем сайте.

* Вся конфигурация, которую не нужно синхронизировать между исходным и
целевым сайтами, должна храниться в переопределениях конфигурации в файле
_settings.php_, а не в базе данных. Смотрите <<install-dev-making>>.

==== Шаги

. На исходном сайте в административном меню _Управление_ перейдите в
  _Конфигурация_ > _Разработка_ > _Синхронизация конфигурации_ > _Экспорт_
  (_admin/config/development/configuration/full/export_).

. Нажмите _Экспорт_. Сайт сформирует архив полной конфигурации.
  Сохраните файл на локальном компьютере.

. На целевом сайте в меню _Управление_ перейдите в
  _Конфигурация_ > _Разработка_ > _Синхронизация конфигурации_ > _Импорт_
  (_admin/config/development/configuration/full/import_).

. Найдите скачанный архив конфигурации и нажмите _Загрузить_. Файл будет
  загружен, после чего вы перейдёте на страницу _Синхронизировать_
  (_admin/config/development/configuration_), где появится сообщение
  об успешной загрузке файлов.

. Убедитесь, что показанные отличия соответствуют ожиданиям. Будут
  отображены элементы конфигурации, которые добавлены, удалены или изменены;
  для изменённых элементов можно нажать _Просмотреть отличия_, чтобы увидеть
  конкретные изменения.

. Когда всё проверено, нажмите _Импортировать всё_, чтобы применить изменения
  конфигурации.

==== Расширьте понимание

* Если изменения затрагивают только один элемент конфигурации (например,
  одно представление), можно воспользоваться одиночным экспортом/импортом
  конфигурации. См. <<extend-deploy>>.

* После экспорта полной конфигурации из исходного сайта вы можете распаковать
  архив и зафиксировать его в системе контроля версий, например Git, чтобы
  отслеживать историю настроек. См. <<extend-git>>.

==== Видео

// Видео от Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/dLUGQk8GKa0[title="Synchronizing Configuration Versions"]

// ==== Дополнительные материалы


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/MishaIsmajlov[Исмайлов Михаил].
