[[glossary]]
== Словарь терминов

(((Глоссарий)))
(((Терминология (Глоссарий))))

(((Ajax,определение)))
[glossary]
[[glossary-ajax]] Ajax::
   Веб технология использующая обмен данными с сервером для динамического
   обновления частей веб страницы (например, формы) без необходимости обновления всей
   страницы.
(((Синоним URL,определение)))
[[glossary-alias]] Синоним URL::
   Читаемое имя заменяющее внутренний <<glossary-path,path>>,
   которое Drupal связывает с URL на сайте. Например, вы можете связать
   синоним _/about_ к странице О Нас на сайте, для замены внутреннего
   пути _/node/5_. Это даст возможность отображают страницу по адресу _http://example.com/about_
   вместо _http://example.com/node/5_. Смотрите <<content-paths>> для большей
   информации.
(((Анонимный пользователь,определение)))
[[glossary-anonymous]] Анонимный пользователь::
   Пользователь (<<glossary-user,user>>) взаимодействующий с сайтом как не зарегистрированный
   пользователь. Смотрите <<user-concept>> для большей информации.
(((Блок,определение)))
[[glossary-block]] Блок::
   Кусочек <<glossary-content,content>> (текст, изображения, ссылки и так далее), который
   может быть отображен на странице сайта. Блоки отображаются в
   <<glossary-region,regions>>. Смотрите <<block-concept>> для большей информации.
(((Точка перехода,определение)))
[[glossary-breakpoint]] Точка перехода::
   Точки перехода используются для пошагового разделения типов устройств в зависимости от высоты или ширины браузера,
   принтеров и других типов медиа.
   <<glossary-responsive,responsive>> сайт настраивает его представления с помощью этих
   точек перехода. Смотрите <<structure-image-responsive>> для большей информации.
(((Подтип сущности,определение)))
[[glossary-bundle]] Подтип сущности::
   Синоним для <<glossary-entity-subtype,Entity subtype>>.
(((Кэш,определение)))
[[glossary-cache]] Кэш::
   Внутренний кэша хранит вывод долгих вычислений,
   таких как создание вывода для запроса HTML страницы и
   отправляет кэш вместо вычислений в следующий раз, когда эти результаты необходимы.
   Внешняя система кэширования может быть также использована на веб сервере для ускорения
   ответа сайта. Смотрите <<prevent-cache>> для большей информации о
   внутреннем кэше.
(((CMS (система управления сайтом),определение)))
(((Система управления сайтом (CMS),определение)))
[[glossary-cms]] CMS::
   Сокращение для
   <<glossary-content-management-system,Content Management System>>.
(((Конфигурация,определение)))
[[glossary-configuration]] Конфигурация::
   Информация о вашем сайте, которая не является <<glossary-content,content>>
   и также не является <<glossary-state,state>>,
   это настройки вашего сайта такие как имя вашего сайта, <<glossary-content-type,content types>>
   и <<glossary-view,views>> определенные вами и так далее. Смотрите <<understanding-data>>
   для больше информации.
(((Контент,определение)))
[[glossary-content]] Контент::
   Информация выводимая на вашем сайте, такая как текст, изображения,
   файлы для загрузки и так далее. Смотрите также <<glossary-configuration,Configuration>> и
   <<glossary-state,State>>. Смотрите <<understanding-data>> для большей информации.
(((Элемент контента,определение)))
[[glossary-content-item]] Элемент контента::
   Элемент <<glossary-content,content>>, который обычно нужен для
   отображения основного контента страницы вашего сайта. Это может быть
   <<glossary-entity-type,entity type>>.
   Смотрите <<planning-data-types>> для большей информации.
(((Система управления контентом (CMS),определение)))
[[glossary-content-management-system]] Система управления контентом (CMS)::
   Набор инструментов разработанных для создания, изменения,
   организации, поиска, восстановления и удаления информации на сайте.
   Смотрите <<understanding-drupal>> для большей информации.
(((Тип материала,определение)))
[[glossary-content-type]] Тип материала::
   <<glossary-entity-subtype,подтип сущности>> для
   <<glossary-content-item,элемента контента>> <<glossary-entity-type,типа материала>>.
   Каждый тип материла используются для определенных целей на сайте и каждый тип
   имеет свои собственные поля. Например, сайт городской ярмарки может иметь
   типы материалов для простых страниц и другие типы для отображения списка производителей.
   Смотрите <<planning-data-types>> для большей информации.
(((Контекстуальная ссылка,определение)))
[[glossary-contextual-link]] Контекстуальная ссылка::
   Ссылка на страницу администрирования для редактирования или настройки функционала
   сайта, показывается в месте, где отображается тот или иной функционал. Например:
   ссылка на настройку <<glossary-menu,меню>>, которая показывается, когда вы наводите курсор на
   меню. Смотрите <<config-overview>> для большой информации.
(((Дополнительный,определение)))
(((Дополнительный модуль,определение)))
(((Дополнительная тема,определение)))
[[glossary-contributed]] Дополнительный::
   Загрузка <<glossary-module,Модулей>>, <<glossary-theme,тем>> и
   <<glossary-distribution,дистрибутивов>>, которые не являются частью
   <<glossary-drupal-core,ядра Drupal>> и которые могут быть загружены
   отдельно с сайта https://www.drupal.org[_Drupal.org_].
(((Задача крона,определение)))
(((Расписание команд Cron,определение)))
[[glossary-cron]] Крон::
   На некоторых операционных системах, _крон_ - это планировщик задач, который
   выполняет команды или скрипты периодически.
   Ваш сайт задает периодические задачи, которые обычно называют задачами крона, задачи будут
   запускаться или операционной системой через расписание крона, или через Drupal. Смотрите
   <<security-cron-concept>> для большей информации.
(((Дистрибутив,определение)))
[[glossary-distribution]] Дистрибутив::
   Цельная сборка, которая предоставляет быстрый способ настойки определенных типов
   сайтов, таких как сайт для сообщества или интернет магазина.
   Дистрибутив содержит <<glossary-drupal-core,ядро Drupal>>, вместе с
   <<glossary-contributed,дополнительными модулями>> <<glossary-module,самописными модулями>> и
   <<glossary-theme,темами оформления>>; многие дистрибутивы также пред настраивают сайт
   или даже создают демо контент в процессе установки. Смотрите
   <<understanding-distributions>> для большей информации.
(((Ядро Drupal,определение)))
[[glossary-drupal-core]] Ядро Drupal::
   Файлы, темы оформления, инсталяционные профайлы и модули включённые вместе со стандартным
   проектом Drupal при установке. Смотрите <<understanding-drupal>> для больше информации.
(((Сущность,определение)))
[[glossary-entity]] Сущность::
   Элемент данных <<glossary-content,контента>> или
   <<glossary-configuration,конфигурации>>, несмотря на общее использование,
   термин чаще относится к сущностями контентам. Например включает в себя
   <<glossary-content-item,элементы контента>>, пользовательские <<glossary-block,блоки>>,
   <<glossary-taxonomy-term,термины таксономии>> и описания
   <<glossary-content-type,типов материалов>>; первые три являются сущностями
   контента, и последний конфигурационной сущностью. Смотрите также
   <<glossary-entity-type,Тип сущности>>,
   <<glossary-entity-subtype,Подтип сущности>> и
   <<glossary-field,Поле>>. смотрите <<planning-data-types>> для
   большей информации.
(((Подтип сущности,определение)))
[[glossary-entity-subtype]] Подтип сущности::
   <<glossary-content,Контент>> в <<glossary-entity-type,типе сущности>>,
   группируется по сущностям, которые имеют одинаковые <<glossary-field,поля>>.
   Например, <<glossary-content-item,элемент контента>> типа сущности,
   сайта городской ярмарки может быть подтипом (известным как
   <<glossary-content-type,тип материала>>) для статичных страниц и страниц производителя,
   каждый из них имеет свой набор полей. Вы также можете встретить термин _bundle_, _бандл_ используемый
   (особенно в документации для программистов) как синоним для подтипа сущности.
   Смотрите <<planning-data-types>> для большей информации.
(((Тип сущности,определение)))
[[glossary-entity-type]] Тип сущности::
   В целом тип <<glossary-entity,сущности>> обычно
   применяется только к сущностям <<glossary-content,контента>>. Примерами являются
   <<glossary-content-type,типы материалов>>,
   <<glossary-taxonomy-term,термины таксономии>> и пользовательские
   <<glossary-block,блоки>>. Смотрите <<planning-data-types>> для большей информации.
(((Поле,определение)))
[[glossary-field]] Поле::
   Данные определенного типа, которые привязаны к
   <<glossary-entity,сущности>> <<glossary-content,контента>>. Например, на
   сайте городской ярмарки тип материала производитель может иметь поля для
   изображения, описания производителя и
   <<glossary-taxonomy-term,термины таксономии>>. Смотрите
   <<planning-data-types>> для большей информации.
(((Набор полей,определение)))
[[glossary-field-bundle]] Набор полей::
   Синоним для <<glossary-entity-subtype,Подтипа сущности>>.
(((Форматер,определение)))
(((Форматер поля,определение)))
[[glossary-field-formatter]] Форматер поля::
   <<glossary-configuration,Конфигурация>> которая определяет как данные
   <<glossary-field,поля>> будут отображаться. Например, текстовое поле может
   быть отображено с префиксом и суффиксом и может также быть очищенным от HTML тегов
   или ограничить набор тегов. Смотрите также <<glossary-view-mode,Режим просмотра>> и
   <<glossary-field-widget,Виджет поля>>. Смотрите <<structure-view-modes>> для большей
   информации.
(((Виджет,определение)))
(((Виджет поля,определение)))
[[glossary-field-widget]] Виджет поля::
   <<glossary-configuration,Конфигурация>> которая определяет как можно 
   вводить или редактировать данные для <<glossary-field,поля>> в форме. 
   Например, текстовое поле может использовать однострочное или много строчное поле ввода и
   в виджете можно также указать настройки для размера этого поля ввода. Смотрите также
   <<glossary-field-formatter,Форматер поля>>. Смотрите <<structure-widgets>> для
   большей информации.
[[glossary-formatter]] Форматер::
   Смотрите <<glossary-field-formatter,Форматер поля>>.
(((FOSS (Бесплатное и открытое программное обеспечение),определение)))
(((Бесплатное и открытое программное обеспечение (FOSS),определение)))
[[glossary-foss]] FOSS::
   Сокращение для _Free and Open Source Software_, _Бесплатное и открытое программное обеспечение_,  
   обозначающее программное обеспечение, которое 
   разработано сообществом людей и выпущено под не коммерческой 
   лицензией. Смотрите также <<glossary-gpl,GPL>>. Смотрите <<understanding-project>> для
   большей информации.
(((GPL (General Public License or GNU General Public License),определение)))
(((GNU General Public License,определение)))
[[glossary-gpl]] GPL::
   Сокращение для _GNU General Public License_, некоммерческой лицензии для
   программного обеспечения. Все программное обеспечение загружается с сайта
   https://www.drupal.org[_Drupal.org_] лицензировано под
   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html["GNU General Public
   License, version 2"]. Смотрите также <<glossary-foss,FOSS>>. Смотрите
   <<understanding-gpl>> для большей информации.
(((Стиль изображения,определение)))
[[glossary-image-style]] Стиль изображения::
   Набор шагов обработки, которые трансформируют исходное изображение в новое изображение;
   наиболее частый пример обработки включает масштабирование и обрезку. Смотрите
   <<structure-image-styles>> для большей информации.
(((LAMP (Linux Apache MySQL PHP),определение)))
(((Linux Apache MySQL PHP (LAMP),определение)))
[[glossary-lamp]] LAMP::
   Сокращение _Linux, Apache, MySQL и PHP_: программное обеспечение на веб сервере,
   которое позволяет запускать скрипты Drupal (хотя могут быть использованы и для другие операционные
   системы, веб серверы и базы данных). Смотрите <<install-requirements>> для большей
   информации.
(((Логи,определение)))
[[glossary-log]] Логи::
   Список записанных событий на сайте, таких как использование данных, данные о производительности,
   ошибки, предупреждения и информация об операциях с контентом. Смотрите
   <<prevent-log>> для большей информации.
(((Меню,определение)))
[[glossary-menu]] Меню::
   Набор ссылок использованных в навигации на сайте, которые могут быть упорядочены в
   иерархию. Смотрите <<menu-concept>> для большей информации.
(((Модуль,определение)))
[[glossary-module]] Модуль::
   Программное обеспечение (обычно на PHP, JavaScript и CSS), которое расширяет возможности сайта
   и добавляет функционал. Проект Drupal различает модули
   _<<glossary-drupal-core,ядра>>_ и _<<glossary-contributed,дополнительные>>_
   модули. Смотрите <<understanding-modules>> для большей информации.
(((Путь,определение)))
[[glossary-path]] Путь::
   Уникальный, последняя часть внутреннего внутреннего URL, которые Drupal связывает со страницей
   на сайте, которые могут быть стилизованными страницами для пользователей или административными
   страницами. Например, внутренний URL для страницы О Нас на вашем сайте может быть
   _http://example.com/node/5_ и в этом случае, путь будет _node/5_. Смотрите также
   <<glossary-alias,Alias>>. Смотрите <<content-paths>> для большей информации.
(((Права доступа,определение)))
[[glossary-permission]] Права доступа::
   Возможность выполнять некоторые действия на сайте, такие как редактировать
   отдельные типы <<glossary-content,контента>> или просматривать профайлы пользователей.
   Смотрите также <<glossary-role,Role>>. Смотрите <<user-concept>> для большей информации.
(((Поле ссылки на сущность,определение)))
[[glossary-reference-field]] Поле ссылки на сущность::
   <<glossary-field,Поле>>, которое представляет связь между одной
   <<glossary-entity,сущностью>> и одной или несколькими другими сущностями, которые могут быть
   такого же <<glossary-entity-type,типа сущности>> или другого типа сущности. Например,
   на сайте городской ярмарки рецепт может иметь поле ссылки на сущность
   с производителем (который также является контентом), который публикует
   рецепт. Поля <<glossary-taxonomy-term,терминов таксономии>> также являются полями ссылки на
   сущность. Смотрите <<structure-reference-fields>> для большей информации.
(((Регион,определение)))
[[glossary-region]] Регион::
   Определенная область на странице где <<glossary-content,контент>> может быть выведен,
   например шапка, подвал, главный контент, левая колонка и так далее. Регионы
   определены в <<glossary-theme,темах оформления>> и контент отображается в каждом
   регионе выбранном на странице <<glossary-block,блоков>>. Смотрите <<block-regions>> для
   большой информации.
(((Адаптивность,определение)))
[[glossary-responsive]] Адаптивность::
   Сайт или <<glossary-theme,тема оформления>> называются адаптивными если они подстраивают
   вывод контент в соответствии с размером окна браузера, принтера или
   других типов медиа. Смотрите также <<glossary-breakpoint,Точки перехода>>. Смотрите
   <<structure-image-responsive>> для большей информации.
(((Редакция,определение)))
[[glossary-revision]] Редакция::
   Запись о прошедшем или текущем состоянии <<glossary-entity,сущности>>
   <<glossary-content,контента>>, который был отредактирован в прошлом it is edited over time. Смотрите
   <<planning-workflow>> для большей информации.
(((Роль,определение)))
[[glossary-role]] Роль::
   Наименованный набор <<glossary-permission,прав доступа>>, который применяется к
   <<glossary-user,аккаунту пользователя>>. Смотрите <<user-concept>> для большей информации.
(((Обновление безопасности,определение)))
[[glossary-security-update]] Обновление безопасности::
   <<glossary-update,Обновление>> - это правки относящихся к безопасности ошибок, таких как
   уязвимость для взлома. Смотрите <<security-concept>> для большей информации.
(((Состояние,определение)))
[[glossary-state]] Состояние::
   Информация временного характера о текущем состоянии вашего
   сайта, например время, когда <<glossary-cron,крон>> был запущен последний раз.
   Смотрите также <<glossary-content,Контент>> и
   <<glossary-configuration,Конфигурация>>. Смотрите <<understanding-data>> для
   большей информации.
(((Таксономия,определение)))
[[glossary-taxonomy]] Таксономия::
   Процесс классификации <<glossary-content,контента>>. Смотрите
   <<structure-taxonomy>> для большей информации.
(((Термин таксономии,определение)))
[[glossary-taxonomy-term]] Термин таксономии:
   Термины используются для классификации <<glossary-content,контента>>, например теги или
   категории. Смотрите также <<glossary-vocabulary,Словарь таксономии>>. Смотрите
   <<structure-taxonomy>> для большей информации.
(((Текстовые форматы,определение)))
[[glossary-text-format]] Текстовые форматы::
   <<glossary-configuration,Конфигурация>>, которая определяет обработку текста
   введенного пользователем, перед тем как показать его в браузере. Это может быть
   фильтр или ограничение HTML тегов, превращение путей URL в ссылки. Смотрите
   <<structure-text-formats>> для большей информации.
(((Тема оформления,определение)))
[[glossary-theme]] Тема оформления::
   Программное обеспечение и дополнительные файлы (изображения, CSS, PHP код и шаблоны), которое
   определяет стиль и макет вашего сайта. В Drupal существуют
   темы  _<<glossary-drupal-core,ядра>>_ и
   _<<glossary-contributed,дополнительные>>_ темы оформления. Смотрите <<understanding-themes>>
   для большей информации.
(((UI (Пользовательский интерфейс),определение)))
[[glossary-ui]] UI::
   Сокращение от <<glossary-user-interface,_User Interface_>>.
(((Обновление,определение)))
[[glossary-update]] Обновление::
   Новая версия программного обеспечения для вашего сайта, это может быть
   <<glossary-drupal-core,ядро Drupal>>, <<glossary-module,модуль>> или
   <<glossary-theme,тема оформления>>. Смотрите также
   <<glossary-security-update,Обновления безопасности>>. Смотрите <<security-concept>> для
   большой информации.
(((Пользователь,определение)))
[[glossary-user]] Пользователь::
   Посетитель взаимодействующий с сайтом, он может авторизоваться или быть
   <<glossary-anonymous,анонимным>>. Смотрите <<user-concept>> для большей информации.
(((Пользовательский интерфейс (UI),определение)))
[[glossary-user-interface]] Пользовательский интерфейс::
   Текст, стили и изображения, которые видны на сайте, разделенные логически
   в пользовательский интерфейс посетителя сайта и административный интерфейс
   пользователя.
(((Супер пользователь,определение)))
[[glossary-user-one]] Супер пользователь (Пользователь 1)::
   Начальный <<glossary-user,пользовательский>> аккаунт, который создается при установке
   сайта (и имеет ID номер 1). Этот пользователь автоматически имеет все
   <<glossary-permission,права доступа>>, даже если не отмечен для этого
   административной <<glossary-role,ролью>>. Смотрите <<user-admin-account>> для большей
   информации.
(((Представление,определение)))
[[glossary-view]] Представление::
   Форматированный список данных; обычно данные приходят из
   <<glossary-entity,сущностей>> <<glossary-content,контента>>. Например, на
   сайте городской ярмарки, вы можете создать
   <<glossary-content-item,элемент контента>> для каждого производителя. Вы можете также
   создать представление, которое сгенерирует вывод страницы, на которой будут показаны миниатюры изображений и
   короткое описание каждого из производителей, с ссылкой на полную страницу контента
   производителя. Используя те же данные, вы можете также создать представление, которое сгенерирует новый
   блок с производителями, в котором будет отображаться информация о недавно добавленных
   производителях. Смотрите <<planning-modular>> для большей информации.
(((Режим просмотра,определение)))
[[glossary-view-mode]] Режим просмотра::
   Набор <<glossary-configuration,конфигураций>>
   <<glossary-field-formatter,форматеров полей>> для всех
   <<glossary-field,полей>> из <<glossary-entity,сущности>>
   <<glossary-content,контента>>, некоторые из которых могут быть скрыты. Каждый
   <<glossary-entity-subtype,подтип сущности>> может иметь один или несколько режимов просмотра;
   например, <<glossary-content-type,типы материалов>> обычно имеют режимы просмотра
   _Полная версия_ и _Анонс_, где _Анонс_ режим просмотра отображающий уменьшенные
   или обрезанные поля. Смотрите <<structure-view-modes>> для большей информации.
(((Словарь таксономии,определение)))
[[glossary-vocabulary]] Словарь таксономии::
   Группа <<glossary-taxonomy-term,терминов таксономии>> выбранных для
   классификации <<glossary-content,контента>> по определенному признаку, например
   список категорий всех производителей на сайте
   городской ярмарке. Технически, словари являются
   <<glossary-entity-subtype,подтипом сущности>> для <<glossary-entity-type,типа сущности>>
   термина таксономии. Смотрите
   <<structure-taxonomy>> для большей информации.
(((Виджет,определение)))
[[glossary-widget]] Виджет::
   Смотрите <<glossary-field-widget,Field widget>>.
(((Мастер настройки,определение)))
[[glossary-wizard]] Мастер настройки::
   Веб форма, которая позволяет вам заполнить несколько значений и создает что-то
   с целесообразными настройками по умолчанию основываясь на выбранных вами значениях. Например, в случае
   модуля Views мастер настройки создает <<glossary-view,представления>> различных типов. Смотрите
   <<views-create>> для большей информации.
(((WYSIWYG (What You See Is What You Get),определение)))
(((What You See Is What You Get (WYSIWYG),определение)))
[[glossary-wysiwyg]] WYSIWYG::
   Сокращение от _What You See is What You Get_, означающее метод редактирования
   <<glossary-content,контента>>, где вы видите на странице редактирования
   приближенный вид конечного текста. Смотрите <<structure-text-format-config>> для
   большой.
