[[glossary]]
== Словарь терминов

(((Глоссарий)))
(((Терминология (Глоссарий))))

(((Ajax,определение)))
[glossary]
[[glossary-ajax]] Ajax::
   Веб-технология, позволяющая обмениваться данными с сервером для динамического
   обновления частей веб-страницы (например, форм) без необходимости полной
   перезагрузки страницы.
(((Синоним,определение)))
[[glossary-alias]] Синоним::
   Удобочитаемое имя, заменяющее внутренний <<glossary-path,путь>>,
   который система присваивает <<glossary-url,URL>> на сайте. Например, вы
   можете назначить синоним _/about_ для страницы "О нас", чтобы заменить
   внутренний путь _/node/5_. Это даст странице адрес _http://example.com/about_
   вместо _http://example.com/node/5_. Подробнее см. <<content-paths>>.
(((Анонимный,определение)))
[[glossary-anonymous]] Анонимный::
   Посетитель (<<glossary-user,пользователь>>), который взаимодействует с сайтом,
   не будучи авторизованным. Подробнее см. <<user-concept>>.
(((Аутентифицированный,определение)))
[[glossary-authenticated]] Аутентифицированный::
   Посетитель (<<glossary-user,пользователь>>), который авторизован на сайте.
   Подробнее см. <<user-concept>>.
(((Блок,определение)))
[[glossary-block]] Блок::
   Фрагмент <<glossary-content,контента>> (текст, изображения, ссылки и т.д.),
   который можно выводить на страницах сайта. Блоки размещаются в
   <<glossary-region,регионах>>. Подробнее см. <<block-concept>>.
(((Точка перехода,определение)))
[[glossary-breakpoint]] Точка перехода::
   Точки, используемые для разделения высоты или ширины экранов браузеров,
   принтеров и других медиа-выходов на шаги. <<glossary-responsive,Адаптивный>>
   сайт подстраивает отображение под эти точки. Подробнее см. <<structure-image-responsive>>.
(((Подтип сущности,определение)))
[[glossary-bundle]] Бандл::
   Синоним <<glossary-entity-subtype,подтипа сущности>>.
(((Кэш,определение)))
[[glossary-cache]] Кэш::
   Внутреннее хранилище сайта, в котором сохраняются результаты трудоемких
   вычислений, например, при обработке страницы. Это ускоряет повторные
   обращения к данным. Также могут использоваться внешние системы кэширования.
   Подробнее см. <<prevent-cache>>.
(((Стандарты кодирования, определение)))
[[glossary-coder]] Стандарты кодирования::
   Правила для программистов, определяющие лучшие практики, форматирование и другие
   соглашения, чтобы весь код был единообразным и ожидаемым. Подробнее см. <<install-tools>>.
(((Composer,определение)))
[[glossary-composer]] Composer::
   Менеджер зависимостей PHP, используемый Drupal, <<glossary-drush,Drush>>,
   Symfony и другими. Является предпочтительным способом установки проектов Drupal.
   Подробнее см. <<install-composer>>.
(((CMS (Система управления содержимым),определение)))
(((Система управления содержимым (CMS),определение)))
[[glossary-cms]] CMS::
   Аббревиатура от <<glossary-content-management-system,система управления содержимым>>.
(((Конфигурация,определение)))
[[glossary-configuration]] Конфигурация::
   Информация о сайте, которая не является <<glossary-content,контентом>>,
   и предназначена для постоянного хранения (например, название сайта,
   <<glossary-content-type,типы материалов>>, <<glossary-view,views>> и др.).
   Подробнее см. <<understanding-data>>.
(((Контент,определение)))
[[glossary-content]] Контент::
   Информация, отображаемая на сайте: текст, изображения, файлы и пр. См. также
   <<glossary-configuration,Конфигурация>> и <<glossary-state,Состояние>>.
   Подробнее см. <<understanding-data>>.
(((Элемент контента,определение)))
[[glossary-content-item]] Элемент контента::
   Единица <<glossary-content,контента>>, обычно предназначенная для вывода
   как основной материал страницы. Это вид <<glossary-entity-type,типа сущности>>.
   Подробнее см. <<planning-data-types>>.
(((Система управления содержимым (CMS),определение)))
[[glossary-content-management-system]] Система управления содержимым (CMS)::
   Набор инструментов для создания, изменения, организации, поиска и удаления информации на сайте.
   Подробнее см. <<understanding-drupal>>.
(((Тип материала,определение)))
[[glossary-content-type]] Тип материала::
   <<glossary-entity-subtype,Подтип сущности>> для
   <<glossary-content-item,элементов контента>> определенного <<glossary-entity-type,типа сущности>>.
   Каждый тип материала имеет свою задачу и собственные поля. Например, для ярмарки
   — отдельные типы для статических страниц и для карточки продавца. Подробнее см. <<planning-data-types>>.
(((Контекстный фильтр, определение)))
[[glossary-contextual-filter]] Контекстный фильтр (в Представлении)::
   Ограничивает выводимые данные в <<glossary-view,представлении>> на основе контекста (например, полного URL страницы).
   Подробнее см. <<views-parts>>.
(((Контекстная ссылка,определение)))
[[glossary-contextual-link]] Контекстная ссылка::
   Ссылка на административную страницу настройки элемента, отображается в месте
   вывода этого элемента. Например, ссылка на настройку <<glossary-menu,меню>>,
   появляющаяся при наведении мыши на меню. Подробнее см. <<config-overview>>.
(((Дополнительный,определение)))
(((Дополнительный модуль,определение)))
(((Дополнительная тема,определение)))
[[glossary-contributed]] Дополнительный::
   <<glossary-module,Модули>>, <<glossary-theme,темы>> и
   <<glossary-distribution,дистрибутивы>>, которые не входят в
   <<glossary-drupal-core,ядро Drupal>>, а загружаются отдельно с https://www.drupal.org[_Drupal.org_].
(((Крон,определение)))
[[glossary-cron]] Крон::
   Программа-расписание, которая периодически выполняет задания или скрипты.
   В Drupal задачи крона можно запускать как внешним расписанием, так и внутренним механизмом.
   Подробнее см. <<security-cron-concept>>.
(((Кросс-сайтовый скриптинг, определение)))
[[glossary-cross-site-scripting]] Кросс-сайтовый скриптинг::
   Уязвимость безопасности, когда злоумышленник может внедрить скрипты на страницы сайта,
   которые просматривают другие пользователи. Подробнее см. <<structure-text-formats>>.
(((Devel, определение)))
[[glossary-devel]] Devel::
   Модуль для разработки, помогает отладке, анализу запросов к базе, генерации фиктивного контента.
   Подробнее см. <<install-tools>>.
(((Сайт разработки,определение)))
[[glossary-development-site]] Сайт разработки::
   Копия основного сайта для разработки, обновления и тестирования.
   Подробнее см. <<install-dev-sites>>.
(((Дисплей, определение)))
[[glossary-display]] Дисплей (в Представлении)::
   Тип вывода <<glossary-view,представления>>, например страница, <<glossary-block,блок>> или лента.
   Подробнее см. <<views-parts>>.
(((Дистрибутив,определение)))
[[glossary-distribution]] Дистрибутив::
   Сборка, предоставляющая быстрый способ развернуть определённый тип сайта,
   включая ядро, дополнительные модули и темы, часто с демо-контентом.
   Подробнее см. <<understanding-distributions>>.
(((Drupal Association, определение)))
[[glossary-drupal-association]] Drupal Association::
   Некоммерческая организация, поддерживающая проект и сообщество Drupal.
   Подробнее см. <<understanding-project>>.
(((Ядро Drupal,определение)))
[[glossary-drupal-core]] Ядро Drupal::
   Файлы, темы, профили и модули, входящие в стандартный дистрибутив.
   Подробнее см. <<understanding-drupal>>.
(((Drush,определение)))
[[glossary-drush]] Drush::
   Командная оболочка и инструмент для скриптового управления Drupal. Подробнее см. <<install-tools>>.
(((Редакционный процесс, определение)))
[[glossary-editorial-workflow]] Редакционный процесс::
   Процесс создания, проверки, редактирования и публикации контента. В процессе
   могут участвовать разные роли (например, авторы и редакторы).
   Подробнее см. <<planning-workflow>>.
(((Сущность,определение)))
[[glossary-entity]] Сущность::
   Элемент данных <<glossary-content,контента>> или <<glossary-configuration,конфигурации>>;
   на практике обычно имеется в виду контент-сущность. Примеры:
   <<glossary-content-item,элемент контента>>, пользовательский <<glossary-block,блок>>,
   <<glossary-taxonomy-term,термин таксономии>>, описание <<glossary-content-type,типа материала>>.
   Первые три — сущности контента, последнее — конфигурационная сущность.
   См. также <<glossary-entity-type,Тип сущности>>,
   <<glossary-entity-subtype,Подтип сущности>> и <<glossary-field,Поле>>.
   Подробнее см. <<planning-data-types>>.
(((Подтип сущности,определение)))
[[glossary-entity-subtype]] Подтип сущности::
   В <<glossary-entity-type,типе сущности>> — группа сущностей с одинаковым набором
   <<glossary-field,полей>>. Например, у <<glossary-content-item,элемента контента>>
   могут быть подтипы (<<glossary-content-type,типы материала>>) — "Статическая страница",
   "Продавец", каждый со своими полями. Также может называться _bundle_ (бандл).
   Подробнее см. <<planning-data-types>>.
(((Тип сущности,определение)))
[[glossary-entity-type]] Тип сущности::
   Общая категория для <<glossary-entity,сущности>>; обычно применяется к сущностям контента.
   Примеры: <<glossary-content-type,типы материалов>>, <<glossary-taxonomy-term,термины таксономии>>,
   пользовательские <<glossary-block,блоки>>. Подробнее см. <<planning-data-types>>.
(((Поле,определение)))
[[glossary-field]] Поле::
   Данные определенного типа, связанные с <<glossary-entity,сущностью контента>>.
   Например, у материала продавца — поля для изображения, описания, <<glossary-taxonomy-term,термина таксономии>>.
   Подробнее см. <<planning-data-types>>.
(((Набор полей,определение)))
[[glossary-field-bundle]] Набор полей::
   Синоним <<glossary-entity-subtype,подтипа сущности>>.
(((Форматер поля,определение)))
[[glossary-field-formatter]] Форматер поля::
   <<glossary-configuration,Конфигурация>>, определяющая, как данные <<glossary-field,поля>> будут отображаться.
   Например, текстовое поле может выводиться с префиксом/суффиксом, очищаться от HTML-тегов и т.д.
   См. также <<glossary-view-mode,Режим просмотра>>, <<glossary-field-widget,Виджет поля>>.
   Подробнее см. <<structure-view-modes>>.
(((Виджет поля,определение)))
[[glossary-field-widget]] Виджет поля::
   <<glossary-configuration,Конфигурация>>, определяющая, как пользователь может вводить или
   редактировать данные для <<glossary-field,поля>> в форме. Например, поле может быть однострочным
   или многострочным, может задаваться размер поля. См. также <<glossary-field-formatter,Форматер поля>>.
   Подробнее см. <<structure-widgets>>.
(((Фильтр, определение)))
[[glossary-filter]] Фильтр (в Представлении)::
   Ограничивает данные для вывода в <<glossary-view,представлении>> на основе критериев,
   например, статус публикации, тип материала или значение поля.
   Подробнее см. <<views-parts>>.
[[glossary-formatter]] Форматер::
   См. <<glossary-field-formatter,Форматер поля>>.
(((FOSS (Свободное и открытое ПО),определение)))
[[glossary-foss]] FOSS::
   Аббревиатура от _Free and Open Source Software_, свободное и открытое ПО,
   разрабатываемое сообществом и распространяемое под некоммерческой лицензией.
   См. также <<glossary-gpl,GPL>>. Подробнее см. <<understanding-project>>.
(((Git, определение)))
[[glossary-git]] Git::
   <<glossary-vcs,Система управления версиями>>, используемая разработчиками Drupal
   для координации изменений. Git хранит историю изменений проекта в дереве файлов — <<glossary-repository,репозитории>>.
   Подробнее см. <<install-tools>>.
(((GPL (GNU General Public License),определение)))
[[glossary-gpl]] GPL::
   Аббревиатура от _GNU General Public License_, некоммерческая лицензия для ПО.
   Вся загрузка с https://www.drupal.org[_Drupal.org_] распространяется под
   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html["GNU General Public License, version 2"].
   См. также <<glossary-foss,FOSS>>. Подробнее см. <<understanding-gpl>>.
(((Стиль изображения,определение)))
[[glossary-image-style]] Стиль изображения::
   Набор шагов обработки, которые превращают исходное изображение в новое; обычно
   включают масштабирование и обрезку. Подробнее см. <<structure-image-styles>>.
(((Установка,определение)))
[[glossary-installing]] Установка::
   Подготовка ядра Drupal, темы или модуля для использования. Для ядра включает загрузку файлов,
   создание БД, запуск установочного скрипта. Подробнее см. <<install-decide>>.
(((LAMP, определение)))
[[glossary-lamp]] LAMP::
   Аббревиатура от _Linux, Apache, MySQL, PHP_: стандартный стек ПО для запуска сайтов Drupal,
   хотя возможны и другие ОС, серверы, СУБД. Подробнее см. <<install-requirements>>.
(((Лог,определение)))
[[glossary-log]] Лог::
   Список зафиксированных событий на сайте: использование, производительность, ошибки, предупреждения и др.
   Подробнее см. <<prevent-log>>.
(((Меню,определение)))
[[glossary-menu]] Меню::
   Набор ссылок для навигации по сайту, может быть иерархическим. Подробнее см. <<menu-concept>>.
(((Модуль, определение)))
[[glossary-module]] Модуль::
   ПО (обычно PHP, JS или CSS), расширяющее функционал сайта. В Drupal различают модули
   <<glossary-drupal-core,ядра>> и <<glossary-contributed,дополнительные>>.
   Подробнее см. <<understanding-modules>>.
(((Путь,определение)))
[[glossary-path]] Путь::
   Уникальная последняя часть <<glossary-url,URL>>, назначенная системой для страницы на сайте,
   будь то публичная или административная. Например, для страницы "О нас" это может быть _node/5_.
   См. также <<glossary-alias,Синоним>>. Подробнее см. <<content-paths>>.
(((Права доступа,определение)))
[[glossary-permission]] Права доступа::
   Возможность выполнять действие на сайте, например, редактировать конкретный тип
   <<glossary-content,контента>> или просматривать профили. См. также <<glossary-role,Роль>>.
   Подробнее см. <<user-concept>>.
(((Поле-ссылка,определение)))
[[glossary-reference-field]] Поле-ссылка::
   <<glossary-field,Поле>>, представляющее связь между одной <<glossary-entity,сущностью>>
   и другими сущностями, возможно других типов. Например, в материале-рецепте может быть ссылка на производителя.
   Поля <<glossary-taxonomy-term,терминов таксономии>> — тоже ссылки. Подробнее см. <<structure-reference-fields>>.
(((Регион,определение)))
[[glossary-region]] Регион::
   Область страницы, в которой можно размещать <<glossary-content,контент>>, например, шапка, подвал, сайдбар.
   Регионы определяются <<glossary-theme,темой>>, а содержимое выводится с помощью <<glossary-block,блоков>>.
   Подробнее см. <<block-regions>>.
(((Связь, определение)))
[[glossary-relationship]] Связь (в Представлении)::
   Позволяет расширять выводимые данные за счёт связи с другими сущностями. Подробнее см. <<views-parts>>.
(((Репозиторий, определение)))
[[glossary-repository]] Репозиторий::
   Место хранения файлов и истории изменений проекта в системе управления версиями. Подробнее см. <<install-tools>>.
(((Адаптивный,определение)))
[[glossary-responsive]] Адаптивный::
   Сайт или <<glossary-theme,тема>> называются адаптивными, если меняют отображение в зависимости от размера экрана.
   См. также <<glossary-breakpoint,Точка перехода>>. Подробнее см. <<structure-image-responsive>>.
(((Редакция,определение)))
[[glossary-revision]] Редакция::
   Запись о прошлых/текущих состояниях <<glossary-entity,сущности контента>>, изменявшейся со временем.
   Подробнее см. <<planning-workflow>>.
(((Роль,определение)))
[[glossary-role]] Роль::
   Набор <<glossary-permission,прав доступа>>, назначаемый <<glossary-user,аккаунту пользователя>>.
   Подробнее см. <<user-concept>>.
(((Обновление безопасности, определение)))
[[glossary-security-update]] Обновление безопасности::
   <<glossary-update,Обновление>>, исправляющее уязвимость. Подробнее см. <<security-concept>>.
(((Сессия, определение)))
[[glossary-session]] Сессия::
   Информация о взаимодействии пользователя с сайтом: залогинен ли, его куки и т.д.
   Подробнее см. <<understanding-data>>.
(((Сайт-стейджинг,определение)))
[[glossary-staging-site]] Сайт-стейджинг::
   Копия основного сайта для тестирования или показа клиенту перед публикацией. Подробнее см. <<install-dev-sites>>.
(((Состояние, определение)))
[[glossary-state]] Состояние::
   Временная информация о текущем состоянии сайта, например, время последнего запуска <<glossary-cron,крона>>.
   См. также <<glossary-content,Контент>> и <<glossary-configuration,Конфигурация>>. Подробнее см. <<understanding-data>>.
(((Таксономия,определение)))
[[glossary-taxonomy]] Таксономия::
   Процесс классификации <<glossary-content,контента>>. Подробнее см. <<structure-taxonomy>>.
(((Термин таксономии,определение)))
[[glossary-taxonomy-term]] Термин таксономии::
   Классификатор (метка, категория) для <<glossary-content,контента>>.
   См. также <<glossary-vocabulary,Словарь таксономии>>. Подробнее см. <<structure-taxonomy>>.
(((Текстовый формат,определение)))
[[glossary-text-format]] Текстовый формат::
   <<glossary-configuration,Конфигурация>>, определяющая обработку пользовательского текста перед отображением
   (например, очистка HTML, автоссылки для URL и пр.). Подробнее см. <<structure-text-formats>>.
(((Тема,определение)))
[[glossary-theme]] Тема::
   ПО и файлы (CSS, шаблоны, изображения и др.), определяющие внешний вид и
   верстку сайта. В Drupal темы бывают <<glossary-drupal-core,ядра>> и <<glossary-contributed,дополнительные>>.
   Подробнее см. <<understanding-themes>>.
(((UI (интерфейс), определение)))
[[glossary-ui]] UI::
   Сокращение от <<glossary-user-interface,пользовательский интерфейс>>.
(((Обновление,определение)))
[[glossary-update]] Обновление::
   Новая версия ПО сайта: <<glossary-drupal-core,ядро>>, <<glossary-module,модуль>> или <<glossary-theme,тема>>.
   См. также <<glossary-security-update,Обновление безопасности>>. Подробнее см. <<security-concept>>.
(((URL (Унифицированный указатель ресурса),определение)))
[[glossary-url]] URL::
   Уникальный адрес страницы в интернете, например, https://example.com/node/7.
   Подробнее см. <<content-paths>>.
(((Пользователь, определение)))
[[glossary-user]] Пользователь::
   Посетитель сайта (авторизованный или <<glossary-anonymous,анонимный>>).
   Подробнее см. <<user-concept>>.
(((Пользовательский интерфейс, определение)))
[[glossary-user-interface]] Пользовательский интерфейс::
   Текст, стили и изображения, составляющие внешний вид сайта: для посетителей и для администраторов.
(((Пользователь 1, определение)))
[[glossary-user-one]] Пользователь 1 (User one)::
   Первый <<glossary-user,пользователь>>, созданный при установке сайта (ID=1), имеющий все <<glossary-permission,права>>.
   Подробнее см. <<user-admin-account>>.
(((VCS (Система управления версиями), определение)))
[[glossary-vcs]] Система управления версиями::
   ПО для хранения файлов и истории изменений в <<glossary-repository,репозитории>>. Позволяет добавлять, удалять, обновлять файлы.
   Подробнее см. <<install-tools>>.
(((Представление, определение)))
[[glossary-view]] Представление::
   Отформатированный список данных (обычно из <<glossary-content,контента>>), например, список продавцов ярмарки.
   Можно создать представление в виде страницы или блока для отображения информации.
   Подробнее см. <<planning-modular>>.
(((Режим просмотра,определение)))
[[glossary-view-mode]] Режим просмотра::
   Набор <<glossary-field-formatter,форматеров полей>> для всех <<glossary-field,полей>> сущности,
   часть которых может быть скрыта. Обычно у типов материалов есть режимы _Полный_ и _Анонс_.
   Подробнее см. <<structure-view-modes>>.
(((Словарь, определение)))
[[glossary-vocabulary]] Словарь::
   Группа <<glossary-taxonomy-term,терминов таксономии>> для классификации контента,
   например, категории продавцов. Словарь — это <<glossary-entity-subtype,подтип сущности>> для терминов таксономии.
   Подробнее см. <<structure-taxonomy>>.
(((Виджет, определение)))
[[glossary-widget]] Виджет::
   См. <<glossary-field-widget,Виджет поля>>.
(((Мастер, определение)))
[[glossary-wizard]] Мастер::
   Веб-форма для создания объектов с набором значений и настройками по умолчанию,
   например, мастера создания <<glossary-view,представлений>>. Подробнее см. <<views-create>>.
(((WYSIWYG (What You See Is What You Get), определение)))
[[glossary-wysiwyg]] WYSIWYG::
   Аббревиатура от _What You See is What You Get_, то есть редактор, где итоговый результат похож на
   то, что вы видите при редактировании. Подробнее см. <<structure-text-format-config>>.
(((Workflow, определение)))
[[glossary-workflow]] Workflow::
   См. <<glossary-editorial-workflow,Редакционный процесс>>.
(((XSS (Кросс-сайтовый скриптинг), определение)))
[[glossary-xss]] XSS::
   Аббревиатура от <<glossary-cross-site-scripting,Кросс-сайтовый скриптинг>>.
