[[install-composer]]
=== Использование Composer для загрузки и обновления файлов

[role="summary"]
Как использовать инструмент Composer для управления файлами ядра Drupal, а также для загрузки и обновления модулей и тем оформления.

(((Инструмент Composer,использование для загрузки ядра)))
(((Инструмент Composer,использование для загрузки модулей)))
(((Инструмент Composer,использование для загрузки тем)))
(((Ядро,загрузка)))
(((Ядро,обновление)))
(((Загрузка,ядро)))
(((Загрузка,тема)))
(((Загрузка,модуль)))
(((Зависимости,управление)))
(((Модуль,загрузка)))
(((Модуль,обновление)))
(((Тема,загрузка)))
(((Тема,обновление)))
(((Дополнительная тема,загрузка)))
(((Дополнительная тема,обновление)))
(((Дополнительный модуль,загрузка)))
(((Дополнительный модуль,обновление)))
(((Обновление безопасности,применение)))

==== Цель

Используйте Composer для загрузки или обновления файлов и зависимостей ядра, а также дополнительных модулей и тем оформления.

==== Необходимые знания

<<install-tools>>

==== Требования к сайту

Если вы хотите использовать Composer, он должен быть установлен либо на локальном сервере разработки, либо на вашем рабочем сайте. Смотрите <<install-tools>>.

==== Шаги

Если вы не можете установить Composer на рабочем сервере, выполните действия из любого из разделов ниже на локальном сервере, затем перенесите все обновлённые или добавленные файлы на ваш рабочий сайт. Рекомендуется создать архив или zip-файл новых и изменённых директорий, передать архив на рабочий сервер, удалить изменённые директории и распаковать архив. Обязательно проверьте, были ли обновлены или добавлены следующие файлы в корне вашей установки:

* _vendor_ directory
* _autoload.php_
* _composer.json_
* _composer.lock_

===== Использование Composer для загрузки ядра

Выполните эти шаги, если вы ещё не загрузили или не устанавливали ядро и хотите использовать Composer для загрузки ядра и его внешних зависимостей:

. В командной строке перейдите на уровень выше директории, где вы хотите разместить сайт.

. Введите следующую команду, где _mydir_ — это директория, которую вы хотите создать:
+
----
composer create-project drupal/recommended-project mydir
----

. Последняя версия ядра будет загружена в поддиректорию _mydir/web_.

===== Использование Composer для загрузки модуля или темы

Выполните эти шаги, если вы уже используете Composer для управления ядром и хотите добавить дополнительный модуль или тему вместе с их зависимостями.

. Каждый раз, когда вы хотите добавить модуль или тему, определите короткое имя проекта. Это последняя часть URL страницы проекта; например, модуль Geofield на
https://www.drupal.org/project/geofield имеет короткое имя +geofield+.

. Для загрузки дополнительного модуля или темы, вместе с внешними зависимостями, введите следующую команду в корне сайта (замените короткое имя на нужное):
+
----
composer require drupal/geofield
----

===== Использование Composer для обновления ранее загруженных файлов

Выполните эти шаги для обновления файлов ядра, модуля или темы, после того как вы начали управлять зависимостями через Composer:

. Определите короткое имя проекта, который хотите обновить. Для ядра это _core_. Для дополнительных модулей и тем это последняя часть URL страницы проекта; например, модуль Geofield на https://www.drupal.org/project/geofield имеет короткое имя +geofield+.

. Чтобы обновить до последней стабильной версии, используйте следующую команду, подставляя короткое имя проекта:
+
----
composer update drupal/geofield --with-dependencies
----

. Если нужна определённая версия, узнайте как правильно указать номер версии. Например, для версии 8.x-1.16 модуля — просто 1.16, а для ядра 9.0.7 — 9.0.7. Затем введите команду (заменяя короткое имя проекта и версию):
+
----
composer require drupal/geofield:1.16
----

==== Расширьте своё понимание

Подробнее о командах Composer можно узнать через встроенную справочную систему Composer. Например, чтобы узнать больше о команде `create-project`, введите в командной строке `composer help create-project`.

// ==== Related concepts

==== Видео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/v-WeFthdmD4[title="Using Composer and Git to Download Files"]

==== Дополнительные материалы

* https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies[_Drupal.org_ документация "Использование Composer для управления зависимостями сайта"]
* https://www.drupal.org/docs/updating-drupal/update-drupal-core-via-composer[_Drupal.org_ документация "Обновление ядра Drupal через Composer"]
* https://www.drupal.org/docs/installing-drupal/add-composer-to-an-existing-site[_Drupal.org_ документация "Добавление Composer на существующий сайт"]

*Авторы*

Адаптировано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
https://www.drupal.org/u/hansfn[Hans Fredrik Nordhaug], и
https://www.drupal.org/u/eojthebrave[Joe Shindelar] в
https://drupalize.me[Drupalize.Me] из
https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies["Using Composer to manage Drupal site dependencies"],
copyright 2000-copyright_upper_year, отдельные участники
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
