[[install-ddev]]
=== Настройка окружения с помощью DDEV

[role="summary"]
Как настроить сайт для разработки с помощью DDEV — локального окружения для разработки PHP-приложений.

(((DDEV,обзор)))
(((DDEV,установка)))
(((DDEV,среда разработки)))
(((DDEV,сервер разработки)))
(((DDEV,локальный сервер)))

==== Цель

Настроить локальное окружение для разработки с помощью DDEV для запуска приложения и Composer для загрузки необходимых файлов.

==== Необходимые знания

<<install-requirements>>
<<install-composer>>

==== Почему использовать DDEV?

DDEV — это локальное окружение для разработки PHP-приложений, построенное на Docker. Оно включает все необходимые компоненты для работы основного программного обеспечения и используется многими разработчиками в сообществе Drupal.

==== Шаги

. Следуйте
https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/[официальной инструкции по установке DDEV]
для установки DDEV на ваш локальный компьютер. DDEV доступен для Windows, Mac и Linux. Процесс установки отличается для каждой операционной системы, поэтому обязательно следуйте инструкциям для вашей ОС.
. После установки DDEV следуйте
https://ddev.readthedocs.io/en/stable/users/quickstart/#drupal[инструкциям по быстрому старту для Drupal]
для загрузки основного программного обеспечения с помощью Composer и установки его в окружение DDEV.
. Выполните команду `ddev launch` из каталога, созданного на предыдущем шаге, чтобы открыть сайт в веб-браузере и убедиться, что окружение работает корректно.

==== Связанные темы

* <<install-requirements>>
* <<install-dev-sites>>
* <<install-tools>>

==== Дополнительные ресурсы

* https://ddev.readthedocs.io/en/stable/[Документация DDEV]
* https://www.drupal.org/docs/getting-started/installing-drupal/install-drupal-using-ddev-for-local-development[Установка Drupal с помощью DDEV для локальной разработки]

*Благодарности*

Автор и редактор: https://www.drupal.org/u/eojthebrave[Джо Шинделар] на
https://drupalize.me[Drupalize.Me].
