[[install-decide]]
=== Концепция: Способы загрузки и установки ядра Drupal

[role="summary"]
Обзор методов, которыми можно загрузить ядро Drupal.

(((Загрузка,ядро Drupal)))
(((Установка,ядро Drupal)))
(((Ядро Drupal,загрузка)))
(((Ядро Drupal,установка)))

==== Необходимые знания

* <<install-tools>>
* <<install-requirements>>
* <<understanding-distributions>>

==== Какие методы доступны для загрузки ядра Drupal?

Перед тем как начать создание сайта, нужно сначала скачать ядро Drupal.
В зависимости от ваших задач, есть несколько способов скачать ядро Drupal:

Использовать Composer::
  Если вы планируете создавать сайт и продолжать его развивать, рекомендуется
  использовать Composer для загрузки ядра, потому что Composer корректно управляет зависимостями.
  Если вы планируете использовать Drush (смотрите <<install-tools>>), Composer обязателен.
  Смотрите <<install-composer>> для инструкций.

Попробовать бесплатное онлайн-демо::
  Если вы оцениваете, стоит ли использовать Drupal для создания сайта,
  вы можете воспользоваться онлайн-провайдером для получения демо-установки ядра
  за 20 минут или меньше. См. страницу
  https://www.drupal.org/try-drupal[_Drupal.org_ "Try Drupal"].

Использовать установщик в один клик от хостинг-провайдера::
  Если вы устанавливаете ядро на хостинге, ваш провайдер может предлагать
  специальную документацию и/или установку в один клик. См.
  https://www.drupal.org/association/supporters/hosting[_Drupal.org_ список поддерживающих хостинг-провайдеров].

Использовать преднастроенное окружение::
  Используйте преднастроенное окружение или виртуальную машину, содержащие Drupal
  и все необходимые компоненты для локальной установки. См. раздел для вашей ОС в
  https://www.drupal.org/docs/develop/local-server-setup[_Drupal.org_ "Local server setup guide"].

==== Что происходит при установке ядра Drupal?

_Установка_ ядра Drupal означает настройку таблиц базы данных,
конфигурации и учетной записи администратора, чтобы вы могли создавать и использовать свой сайт.

==== Какие методы доступны для установки ядра Drupal?

Есть несколько способов установить ядро Drupal:

Автоматическая установка::
  Если вы используете онлайн-демо или установщик в один клик от хостинг-провайдера,
  ядро может быть установлено автоматически.

Интерактивная установка::
  В ядре есть интерактивная установка, которая предлагает несколько форм.
  После заполнения этих форм завершается установка. См. <<install-prepare>> и <<install-run>>.

Инструменты командной строки::
  Установку также можно выполнить с помощью командных инструментов (см. <<install-tools>>).

Установка демо-сайта::
  Быстро создайте временный демо-сайт, использующий встроенный веб-сервер и
  SQLite из PHP, выполнив команду ниже из корня вашего проекта.
  В этом случае не потребуется запускать интерактивный установщик.
  Подробнее — https://www.drupal.org/docs/official_docs/evaluator-guide[Evaluator Guide].

  ----
  php -d memory_limit=256M core/scripts/drupal quick-start demo_umami
  ----

// ==== Related topics

// ==== Additional resources

*Авторы*

Написано и отредактировано https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] из
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle]

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
