[[install-tools]]

=== Основы: Дополнительные инструменты

[role="summary"]
Обзор инструментов, которые позволяют быстрее и удобнее создавать и поддерживать сайты на Drupal.

(((Инструмент,Coder)))
(((Инструмент,Devel)))
(((Инструмент,Drush)))
(((Инструмент,Composer)))
(((Инструмент,Git)))
(((Coder,обзор)))
(((Devel,обзор)))
(((Drush,обзор)))
(((Composer,обзор)))
(((Git,обзор)))

==== Какие инструменты доступны создателям сайтов?

В разработке и поддержке сайта Drupal вам помогут следующие инструменты:

Drush::
  Подробнее о командных инструментах ниже.
Git::
  Подробнее о системе контроля версий ниже.
Composer::
  Подробнее о Composer — ниже.
Devel::
  https://www.drupal.org/project/devel[Devel] — модуль для разработчиков, который облегчает отладку, просмотр данных, генерацию тестового контента и многое другое.

==== Что такое инструменты командной строки?

Инструменты командной строки — альтернатива админ-интерфейсу для работы с сайтом. Они позволяют:

* Выполнять задачи быстрее и удобнее, чем через веб-интерфейс.
* Писать автоматические сценарии для регулярных операций.
* Получать доступ к возможностям, которых нет в интерфейсе сайта (например, выполнение SQL-запросов).

Наиболее популярный инструмент — https://www.drush.org/[Drush], который подходит для разработчиков, DevOps и администраторов. В этом руководстве приводятся примеры команд Drush. Для использования Drush необходим Composer и доступ к терминалу.

Установка Drush (в корне проекта):

----
composer require drush/drush
----

==== Что такое система управления версиями?

Система контроля версий (например, https://git-scm.com/[Git]) позволяет:

* Тестировать правки локально до выкладки на живой сайт.
* Сравнивать изменения и возвращаться к прежним версиям файлов.
* Объединять изменения от разных разработчиков.
* Поддерживать синхронизацию кода и конфигурации между локальными и рабочими сайтами.

Git — современная распределённая система, работает под Linux, Windows и macOS, а также поддерживается такими сервисами как https://github.com/[GitHub] и https://about.gitlab.com/[GitLab].

==== Для чего используется Composer?

https://getcomposer.org/[Composer] — инструмент для управления зависимостями PHP. С его помощью вы устанавливаете не только сам Drupal, но и модули, темы, а также сторонние библиотеки, которые требуются некоторым расширениям.

Drupal и многие модули требуют сторонних библиотек, поэтому Composer считается стандартом для современных Drupal-сайтов. Кроме того, Drush также устанавливается через Composer.

==== Какие ещё инструменты полезны для разработчиков?

В дополнение к вышеперечисленным:

Coder::
  https://www.drupal.org/project/coder[Coder] — инструмент для проверки кода модулей и тем на соответствие стандартам кодирования. Позволяет автоматизировать исправление ошибок форматирования.
Инструменты разработчика в браузере::
  В браузерах (например, Firefox, Chrome) доступны встроенные инструменты “Инспектор”, “DevTools” и др., которые позволяют анализировать и отлаживать HTML, CSS и JS прямо на сайте.

==== Связанные темы

<<install-composer>>

==== Дополнительные материалы

* https://www.drupal.org/docs/develop/development-tools/development-tools-overview[_Drupal.org_: Development tools overview]
* https://www.drupal.org/docs/develop/using-composer/using-composer-with-drupal[_Drupal.org_: Using Composer with Drupal]
* https://en.wikipedia.org/wiki/Distributed_version_control[Wikipedia: Distributed version control]

*Авторы*

Написано и отредактировано https://www.drupal.org/u/batigolix[Boris Doesborg], https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon], https://www.drupal.org/u/eojthebrave[Joe Shindelar] (Drupalize.Me). Часть текста адаптирована с https://www.drupal.org/node/991716["Introduction to Git"], авторские права — сообществу https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван], https://drupalbook.org/ru[DrupalBook].
