[[install-prepare]]
=== Подготовка к установке

[role="summary"]
Как загрузить основное программное обеспечение и удовлетворить требования к установке.

(((Загрузка,основное программное обеспечение)))
(((Ядро Drupal,подготовка установки)))

==== Цель

Загрузить основное программное обеспечение, и обработать все необходимые условия.

==== Необходимые знания

* <<install-requirements>>

* <<install-tools>>

* <<install-decide>>

* Как установить и настроить серверное программное обеспечение (при установке на Ваш личный
компьютер)

* Как настроить хостинг для стандартного веб-сайта

* Как создать базу данных

==== Требования сайта

Серверное программное обеспечение должно быть установлено на компьютер, где вы планируете развернуть свой
сайт. Смотрите <<install-requirements>>.

В зависимости от того, как Вы планируете загрузить основное программное обеспечение, возможно потребуется сперва установить
дополнительные инструменты к программному обеспечению. Смотрите <<install-decide>> и <<install-tools>>.

==== Этапы

. Выбрать методы загрузки и установки основного программного обеспечения, из
перечисленных в <<install-decide>>. Остальные инструкции относятся к
параметрам загрузки Composer и интерактивной программе установке; если Вы выбрали
другие опции, программное обеспечение должно быть установлено для Вас.

. Настройка URL и хостинга для Вашего сайта на сервере. Подтвердите, что хостинг
работает, помещая простой HTML-файл в веб-корневой каталог хостинга,
и посещая URL для Вашего сайта.

. Создайте базу данных, вместе с учётной записью пользователя базы данных с полным доступом.

. Загрузите файлы основного программного обеспечения в корневой каталог, используя метод,
который Вы выбрали. Смотрите <<install-decide>> для ссылок на инструкции.

==== Расширьте своё понимание

Смотрите <<install-run>>, чтобы запустить интерактивную программу установки.

Кроме того, Вы можете использовать следующую Drush-команду, из каталога,
в который Вы загрузили программное обеспечение, где _DB_NAME_, _DB_USER_ и
_DB_PASS_ являются учебными данными Вашей базы данных:

----
drush site:install standard --db-url='mysql://DB_USER:DB_PASS@localhost/DB_NAME' --site-name=example
----

// ==== Связанные концепции

==== Видео

// Видео с Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/7Aib3y9DM80[title="Preparing to Install"]

==== Дополнительные ресурсы

http://www.drush.org[Drush]


*Авторы*

Написано и отредактировано https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] на
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/jojyja[Jojy Alphonso] на
http://redcrackle.com[Red Crackle].

Переведено https://www.drupal.org/u/karina-masalova[Карина Масалова].
