[[install-dev-sites]]

=== Основы: Сайты для разработки

[role="summary"]
Обзор сайтов для разработки с примером рабочего процесса (deployment workflow) для создания и публикации сайта.

(((Сайт для разработки,обзор)))
(((Рабочий процесс развертывания,обзор)))
(((Тестовый сайт,обзор)))
(((Установка,сайт для разработки)))
(((Установка,тестовый сайт)))

==== Что такое сайты для разработки?

Сайты для разработки — это разные копии одного и того же сайта, используемые для разработки, обновления и тестирования, чтобы не рисковать целостностью живого (production) сайта.

Пример рабочего процесса по созданию и развертыванию сайта обычно включает в себя такие сайты:

Локальное окружение (local environment)::
  Разработка начинается с того, что разработчики создают новые функции, исправляют ошибки, настраивают темы и конфигурацию на своих локальных машинах. Рекомендуемый инструмент для настройки локального окружения — DDEV. Смотрите <<install-ddev>>.

Сайт для разработки (development site)::
  После локальной работы разработчики выкладывают свои изменения на сайт для разработки. Если в команде работает несколько человек, обычно применяется система контроля версий. Git — это система контроля версий, которая отслеживает изменения файлов. Изменения фиксируются (commit) и отправляются в репозиторий. Использование Git позволяет нескольким разработчикам работать параллельно, не перезаписывая работу друг друга, а также даёт возможность легко откатить изменения.

Сайт для тестирования (staging site)::
  Сайт для тестирования используется для проверки работы новых функций и согласования изменений с заказчиком. На этом этапе часто проводятся QA (контроль качества) и UAT (пользовательское тестирование). Рекомендуется, чтобы контент на сайтах для разработки и тестирования совпадал с «живым» сайтом, чтобы можно было проверить, как новые функции работают с реальными данными.

Живой сайт (production site)::
  Это основной сайт, доступный в интернете для посетителей. На нём появляются только те новые функции и изменения, которые были протестированы и признаны безопасными.

В зависимости от размеров и задач проекта, а также требований и количества участников, из приведённой схемы можно убрать какие-либо этапы либо добавить дополнительные. Например, для сложных проектов можно добавить отдельный тестовый сайт между development и staging, чтобы разделить техническое тестирование и пользовательскую приёмку.

==== Связанные темы

* <<install-dev-making>>
* <<install-ddev>>
* <<planning-workflow>>
* <<extend-git>>

// ==== Additional resources

*Авторы*

Написано и отредактировано https://www.drupal.org/u/dianalakatos[Diána Lakatos],
и https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle], а также
https://www.drupal.org/u/eojthebrave[Joe Shindelar] из https://drupalize.me[Drupalize.Me].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
