[[install-prepare]]
=== Подготовка к установке

[role="summary"]
Как загрузить ядро Drupal и выполнить необходимые предварительные требования для установки.

(((Загрузка,ядро Drupal)))
(((Ядро Drupal,подготовка установки)))

==== Цель

Изложить этапы загрузки ядра Drupal и выполнения всех обязательных предварительных условий.

==== Необходимые знания

* Как установить и настроить серверное программное обеспечение (если вы устанавливаете на свой компьютер)
* Как настроить хостинг для стандартного веб-сайта
* Как создать базу данных

==== Требования сайта

Серверное программное обеспечение должно быть установлено на компьютере, где вы планируете разместить свой сайт. Смотрите <<install-requirements>> для перечня требований.

Для локального запуска Drupal рекомендуется использовать DDEV — смотрите <<install-ddev>>.

В зависимости от того, как вы планируете загружать ядро, может потребоваться предварительно установить дополнительные инструменты. Смотрите <<install-decide>> и <<install-tools>>.

==== Этапы

. Выберите метод загрузки и установки ядра, исходя из списка в <<install-decide>>. Остальные инструкции относятся к вариантам с Composer и ручной загрузкой; если вы выбрали другие способы (например, установку в один клик у хостинг-провайдера), обратитесь к соответствующей документации для дополнительных шагов.

. Настройте URL и хостинг для вашего сайта на сервере. Проверьте, что хостинг работает, поместив простой HTML-файл в веб-корневую папку и открыв URL вашего сайта в браузере.

. Создайте базу данных и пользователя базы данных с полными правами.

. Загрузите файлы ядра Drupal в веб-корневой каталог, используя выбранный вами метод. Смотрите <<install-decide>> для ссылок на подробные инструкции.

==== Расширьте своё понимание

Смотрите <<install-run>> для запуска интерактивной установки.

==== Видео

// Видео с Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/7Aib3y9DM80[title="Подготовка к установке"]

==== Дополнительные ресурсы

http://www.drush.org[Drush]


*Авторы*

Написано и отредактировано https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] на
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/jojyja[Jojy Alphonso] на
http://redcrackle.com[Red Crackle].

Переведено https://www.drupal.org/u/karina-masalova[Карина Масалова].
