[[install-decide]]
=== Основы: Способы загрузки и установки Drupal

[role="summary"]
Обзор методов, которыми вы можете загрузить Drupal.

(((Загрузка,ядро Drupal)))
(((Установка,ядро Drupal)))
(((Ядро Drupal,загрузка)))
(((Ядро Drupal,установка)))

==== Необходимые знания

* <<install-tools>>
* <<install-requirements>>
* <<understanding-distributions>>

==== Какие методы доступны для загрузки Drupal?

Перед тем как вы сможете создавать свой сайт, вам необходимо сперва скачать Drupal.
В зависимости от ваших планов, есть несколько способов как вы можете скачать ядро
Drupal:

Попробовать бесплатное онлайн демо::
  Если вы определяетесь использовать или нет Drupal для создания сайта, вы
  можете использовать онлайн сервис для получения демо установки Drupal за
  20 минут или даже меньше. Смотрите статью
  https://www.drupal.org/try-drupal[_Drupal.org_ page "Try Drupal"].

Использовать установщик в один клик у вашего хостинг провайдера::
  Если вы выбираете CMS доступную на вашем хостинге, ваш
  хостинг может иметь документацию о том как установить в один клик
  CMS которая вам нужна. Смотрите
  https://www.drupal.org/association/supporters/hosting[_Drupal.org's_ list of hosting providers that support Drupal].

Использовать преднастроенное окружение::
  Использовать преднастроенное окружение или виртуальную машину, которая содержит Drupal и все необходимые библиотеки для установки Drupal локально. Смотрите раздел для вашей операционной системы https://www.drupal.org/docs/develop/local-server-setup[_Drupal.org_ страница документации сообщества "Local server setup guide"] с возможными вариантами.

Загрузить вручную с Drupal.org::
  Если вы планируете создавать сайт без дополнительных модулей,
  вы можете загрузить Drupal или дистрибутив,
  содержащий ядро Drupal и дополнительные модули и темы оформления, с сайта
  Drupal.org. Смотрите инструкции <<install-manual>>.

Использовать Composer::
  Если вы планируете использовать Drush (смотрите <<install-tools>>) или вы
  создаете сайт, используя дополнительные модули с библиотеками в зависимостях, то вам
  следует использовать Composer для загрузки Drupal, потому что Composer будет
  управлять зависимостями правильно. Если вы начнете делать ваш сайт, загрузив его
  вручную, то вы сможете конвертировать его с использованием Composer для управления зависимости
  позднее. Смотрите <<install-composer>> для детальных инструкции по загрузки и конвертации.

==== Что нужно сделать для установки Drupal?

_Установка_ Drupal требует настройки базы данных,
имя сайта и аккаунта администратора, после этого вы сможете создавать и использовать
ваш сайт.

==== Какие методы доступны для установки Drupal?

Есть несколько путей установки Drupal:

Установка в один клик::
  Если вы выбрали онлайн демо или установщик в один клик на вашем
  хостинге, Drupal будет установлен автоматически.

Интерактивная установка::
  Drupal имеет интерактивную установку, которая показывает несколько
  форм и после заполнения этих форм
  Drupal будет установлен. Смотрите <<install-prepare>> и <<install-run>>.

Установка демо сайта::
  Если вы загрузили Drupal на ваш локальный компьютер, вы можете быстро
  создать временный демо сайт использующий встроенный веб сервер и базу данных SQLite,
  которые являются частью PHP. Команда для настройки демо сайта описана в
  конце <<install-manual>>. В этом случае, вам не потребуется запускать интерактивную
  установку.

Установка через командную строку::
  Инструменты командной строки (смотрите <<install-tools>>) также могут быть использованы для выполнения
  установки Drupal.

// ==== Related topics

// ==== Additional resources

*Авторы*

Написано и отредактировано https://www.drupal.org/u/dgorton[Drew Gorton],
https://www.drupal.org/u/michaellenahan[Michael Lenahan] из
https://erdfisch.de[erdfisch],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle]

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
