[[install-dev-making]]
=== Создание сайта для разработки

[role="summary"]
Как создать копию живого сайта для разработки.

(((Сайт для разработки,создание)))
(((Тестовый сайт,создание)))

==== Цель

Создать копию сайта, которую можно использовать для разработки нового функционала и тестирования обновлений.

==== Необходимые знания

<<install-dev-sites>>

==== Требования к сайту

* У вас должен быть живой сайт, из которого вы хотите сделать копию для разработки.
* Если вы хотите использовать Drush для некоторых шагов, Drush должен быть установлен. Смотрите <<install-tools>>.
* Если вы хотите использовать DDEV для вашей локальной среды, выполните шаги из <<install-ddev>>, затем следуйте инструкциям в секции про DDEV ниже.

==== Общие шаги по созданию сайта для разработки

. Пройдите шаги из <<install-prepare>>, чтобы у вас был хостинг для сайта для разработки, знали где его веб-корень, и у вас была пустая база данных и пользователь для этой базы.
. Далее создайте дамп базы данных, содержащий содержимое вашей базы данных сайта. Файл может быть довольно большим, но есть два способа уменьшить размер:
+
 * Заархивируйте файл с помощью gzip или другой утилиты сжатия.
 * Исключите содержимое таблиц кеша, очистив эти таблицы (их данные временные, и вам нужна только структура таблиц).
+
Для создания дампа базы данных используйте один из следующих методов:
+
  * Если вы используете Drush, используйте эту команду (она сохранит только структуру таблиц кеша, не данные, и сожмет результат):
+
----
drush sql:dump --gzip --structure-tables-list="cache,cache_*" \
  --result-file='PATH/TO/BACKUPFILE.sql'
----
+
  * Если вы используете MySQL и командную строку, используйте эту команду после очистки таблиц кеша (замените имя базы, пользователя и пароль на свои):
+
----
mysqldump -u'USERNAME' -p'PASSWORD' DATABASENAME | \
  gzip > PATH/TO/BACKUPFILE.sql.gz
----

  * Если вы используете MySQL, и ваш сервер поддерживает phpMyAdmin, очистите таблицы кеша через интерфейс (операция _Очистить_), затем используйте вкладку _Экспорт_ и выберите _SQL_ с _gzip_.

  * Используйте https://www.drupal.org/project/backup_migrate[модуль Backup and Migrate] на живом сайте. Смотрите <<extend-module-install>> для установки модулей.
+
Теперь у вас есть дамп базы данных, хранящийся в файле _BACKUPFILE.sql.gz_. Из соображений безопасности не храните его на сервере в пределах корня сайта.

. Скопируйте все файлы из веб-корня живого сайта в веб-корень сайта для разработки. Можно использовать для этого Git, см. <<extend-git>>.
. Отредактируйте _sites/default/settings.php_ на сайте для разработки. Обновите строки с именем базы данных, пользователем и паролем на данные для тестовой базы. Строки выглядят примерно так:
+
----
$databases['default']['default'] = [
  'database' => 'live_site_database_name',
  'username' => 'live_site_database_username',
  'password' => 'live_site_database_password',
  …
----
. Проверьте, есть ли в _settings.php_ настройка:
+
----
$settings['trusted_host_patterns']
----
Если есть — отредактируйте, чтобы там был URL тестового сайта.
. Проверьте наличие строки:
+
----
$settings['hash_salt'] = 'строка_из_случайных_символов';
----
Если нет — добавьте ее. Для генерации случайной строки используйте:
+
----
drush php-eval 'echo \Drupal\Component\Utility\Crypt::randomBytesBase64(55) . "\n";'
----
или любой онлайн-генератор (примерно 74 символа).

. Импортируйте дамп базы данных в базу сайта для разработки одним из способов:
+
  * В phpMyAdmin вкладка _Импорт_ (при необходимости — повторяйте импорт если база большая).
  * Через командную строку:
+
----
gunzip < PATH/TO/BACKUPFILE.sql.gz | \
  mysql -u'USERNAME' -p'PASSWORD' DATABASENAME
----
+
  * Через Drush:
+
----
drush sql:query --file='PATH/TO/BACKUPFILE.sql.gz'
----
. Если сайт для разработки должен отличаться по настройкам, используйте переопределения в _settings.php_ через переменную _$config_. Например:
+
----
$config['system.site']['name'] = "Тестовая копия Ярмарки города N";
----

==== DDEV: шаги для создания сайта для разработки

. В папке с файлами сайта выполните команду для инициализации и запуска окружения:
+
----
ddev config --project-type=drupal11 --docroot=web
ddev start
----
+
(Если структура отличается, подправьте путь --docroot).
. Импортируйте дамп базы:
+
----
ddev import-db --src=PATH/TO/BACKUPFILE.sql.gz
----

==== Расширьте свое понимание

* Проверьте, что сайт для разработки работает.
* Зайдите на тестовый сайт под администратором и очистите кэш (<<prevent-cache-clear>>).
* <<extend-deploy>>
* <<extend-git>>

==== Видео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/FSBNm4oAkaA[title="Making a Development Site"]

==== Дополнительные материалы

* https://www.drupal.org/docs/official_docs/en/_local_development_guide.html[Installing a new Drupal application on your local machine]
* https://www.drupal.org/docs/official_docs/en/_evaluator_guide.html[Creating a Drupal demo application for evaluation purposes]

*Авторы*

Написано и отредактировано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
https://www.drupal.org/u/eojthebrave[Joe Shindelar] из
https://drupalize.me[Drupalize.Me] и
https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
