[[language-concept]]

=== Основы: Перевод интерфейса, конфигурации и контента

[role="summary"]
Обзор языков и перевода на сайте.

(((Пользовательский интерфейс,перевод)))
(((Конфигурация,перевод)))
(((Контент,перевод)))
(((Перевод,обзор)))
(((Языки,обзор)))
(((Модуль,Language)))
(((Модуль,Content Translation)))
(((Модуль,Configuration Translation)))
(((Модуль,Interface Translation)))
(((Content Translation,модуль,обзор)))
(((Configuration Translation,модуль,обзор)))
(((Interface Translation,модуль,обзор)))
(((Language,модуль,обзор)))

==== Необходимые знания

* <<understanding-data>>
* <<understanding-modules>>
* <<planning-data-types>>

==== Какие языки поддерживает Drupal?

Базовый язык ядра Drupal, модулей и тем оформления — английский. Однако, вы можете создать сайт, где язык по умолчанию будет не английский; в таком случае пользователи будут видеть только этот язык (если переводы полные). Также можно создать многоязычный сайт с переключателем языков, чтобы посетители могли выбирать предпочитаемый язык. Для этого на сайте должен быть включён модуль ядра Language.

==== Что можно переводить на сайте?

В Drupal есть три типа данных, доступных для перевода. Каждый из них имеет свой механизм:

Текст пользовательского интерфейса::
  Встроенные надписи и сообщения ядра, модулей и тем оформления. Эти строки можно переводить с базового английского языка на любые языки сайта. Обычно не требуется переводить их вручную — достаточно загрузить уже готовые переводы. Для этого включите модуль Interface Translation, а для автоматической загрузки переводов — Update Manager.

Текст конфигурации::
  Текст, определяемый структурой и настройками модулей и тем: подписи к полям, заголовки в представлениях (Views), название сайта, тексты системных писем и т. п. После добавления таких элементов на сайте вы можете перевести их на другие языки. Для этого необходим модуль Configuration Translation. Для стандартной конфигурации ядра и модулей переводы часто уже входят в загрузки переводов интерфейса.

Контент и файлы::
  Если сайт многоязычный, вы можете сделать поля контента переводимыми. После создания материала на одном языке вы сможете добавить его перевод. Поля могут содержать текст или файлы, и для каждого поля в каждом типе сущности вы определяете, переводимо оно или нет. Для перевода материалов включите модуль Content Translation.

==== Какая информация может остаться на английском?

Даже если язык по умолчанию на сайте не английский, на некоторых административных страницах вы можете видеть элементы интерфейса на английском. Это связано с тем, что редактирование конфигурации обычно происходит в базовом (исходном) языке, а переводы создаются отдельно. Например, на странице _Меню_ будут показаны английские названия, если они заданы так изначально. Чтобы изменить их перевод, нужен модуль Configuration Translation и кнопка _Перевести_ на нужной странице.

==== Связанные темы

* <<language-add>>
* <<language-content-config>>
* <<language-content-translate>>
* <<language-config-translate>>

//==== Additional resources

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
