[[language-concept]]

=== Основы: Интерфейс пользователя, Конфигурация и Перевод контента

[role="summary"]
Обзор языков и переводов на сайте.

(((Пользовательский интерфейс,перевод)))
(((Контигурация,перевод)))
(((Контент,перевод)))
(((Перевод,обзор)))
(((Языки,обзор)))
(((Модуль,Language)))
(((Модуль,Content Translation)))
(((Модуль,Configuration Translation)))
(((Модуль,Interface Translation)))
(((Content Translation модуль,обзор)))
(((Configuration Translation модуль,обзор)))
(((Interface Translation модуль,обзор)))
(((Language модуль,обзор)))

==== Необходимые знания

* <<understanding-data>>
* <<understanding-modules>>
* <<planning-data-types>>

==== Какие языки поддерживает Drupal?

Базовый язык для Drupal, который используется на вашем сайте (Ядро Drupal, модули и
темы оформления) это английский. Однако, используя Drupal вы можете создавать сайт, где
язык по умолчанию будет не английский, в этом случае любой кто простатривает сайт будет
видеть только этот язык (предполагается что сайт полностью переведен). Вы также можете
использовать Drupal для создания мультиязычного сайта, с переключателем языка,
который пользователи могут использовать для выборах их предподчтительного языка. Вы должны
установить модуль ядра Language для того чтобы исползовать язык отличный от
английского на вашем сайте.

==== Что может быть переведено на вашем сайте?

Есть три типа информации, которые вы можете перевести, каждый имеет свой собственный
метод для перевода:

Текст пользовательского интерфейса::
  Встроенный текст представленный в ядре Drupal, модулях и темах оформления. Этот текст может быть
  переведен с базового английского языка на любой другой язык(b)
  вашего сайта. Обычно, прежде чем переводить текст самому,
  вы можете скачать переводы. Вы должны включить модуль ядра Interface Translation,
  чтобы перевести этот текст text и модуль ядра Update Manager
  чтобы автоматически скачать переводы.
Текст конфигурации::
  Текст который относится к структуре и начальным значениям определенным ядром Drupal,
  модулями и темами оформления, однако только тот который вы можете изменить. Например это заголовки
  полей в ваших типах материала, текст в шапке представлений, имя вашего сайта и
  контент автоматических емейл сообщений, который сайт посылает. После создания
  конфигурационного текста на языке по умолчанию на вашем сайте, вы можете перевести его
  на другие языки. По умолчанию конфигурация предоставленная ядром Drupal,
  модулями и темами оформления, включает перевод вместе загруженными переводами для
  пользовательского интерфейса. ВЫ должны включить модуль ядра Configuration
  Translation для перевода этого текста.
Текст в контенте и файлы::
  Если ваш сайт мультиязычный, вы можете сделать поля контента на вашем
  сайте переводимыми. После создания контента на одном языке, вы можете
  перевести его на другие языки. Поля могут содержать текстовую информацию или
  загруженные файлы и для каждого поля в каждом типе материала, вы можете настроить будет ли
  оно переводимым или нет. Вы должны включить модуль ядра Content
  Translation для перевода этого текста.

==== Какая информация останется на английском на моем сайте?

Даже если язык по умолчанию на вашем сайте не английский, вы будете все равно видеть
английский текст для определенных страниц администратора при управление конфигурацией. Причина
по которой это так работает, вы должны редактировать конфигурацию, а также базовые,
непереводимые значения конфигурации; перевод конфигурации это отдельная
операция. Напримр, если вы зайдете на страницу _Меню_, вы
увидите английские названия меню (для меню, которые настроены при установки
вашего сайта) и если вы нажмете на ссылку _Редактировать меню_, вы сможете отредактировать
английское название и описание меню. Для редактирования имени меню на другой
язык, вы должны включить модуль ядра Configuration Translation
и использовать ссылку _Перевод_ для редактирования переведенном информации меню.

==== Связанные темы

* <<language-add>>
* <<language-content-config>>
* <<language-content-translate>>
* <<language-config-translate>>

//==== Additional resources


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из
https://www.technocrat.com.au/[Technocrat].
