[[menu-concept]]

=== Основы: Меню

[role="summary"]
Обзор концепции меню и меню, которые автоматически создаются при стандартной установке ядра.

(((Меню,обзор)))
(((Меню,основная навигация)))
(((Меню,администрирование)))
(((Меню,учётная запись)))
(((Меню,подвал)))
(((Меню,пользовательское)))
(((Административное меню,обзор)))
(((Меню учётной записи,обзор)))
(((Меню подвала,обзор)))
(((Пользовательское меню,обзор)))

// ==== Необходимые знания

==== Что такое меню?

Меню — это коллекция ссылок, используемых для навигации по сайту. Модуль ядра Menu UI предоставляет интерфейс для управления и настройки системы меню. Обычно меню отображаются в виде иерархического списка ссылок. По умолчанию новые ссылки меню добавляются во встроенное меню с названием _Основная навигация_, но администраторы могут создавать и собственные меню.

Стандартный профиль установки ядра содержит пять меню:

Основная навигация::
  Ссылки на разделы сайта, предназначенные для посетителей. Обычно их создают администраторы сайта.

Администрирование::
  Ссылки для выполнения административных задач. Это меню в основном содержит ссылки, добавленные модулями вашего сайта.

Меню учётной записи::
  Ссылки, связанные с действиями пользователя, например _Моя учётная запись_ и _Выход_.

Подвал::
  Ссылки на важные страницы сайта, которые отображаются в нижней части (подвале) сайта. Обычно их также создают администраторы.

Инструменты::
  Ссылки на задачи, которые могут понадобиться посетителям сайта. Некоторые модули размещают свои ссылки именно в этом меню.

Вы можете изменять меню, используя административные возможности Drupal, следующим образом:

* Создавать новые пользовательские меню.
* Добавлять новые ссылки в меню.
* Изменять порядок ссылок меню, задавая им "вес" или перетаскивая в нужное место.
* Переименовывать ссылки меню (названия ссылок).
* Изменять описание ссылок (всплывающие подсказки при наведении).
* Перемещать ссылку меню в другое меню, редактируя свойство _Родительская ссылка_.

Ссылка меню будет видна посетителю только в том случае, если у него есть права доступа к странице, на которую она ведёт. Например, ссылка на административное меню не показывается гостям (неавторизованным пользователям).

==== Связанные темы

* <<menu-link-from-content>>
* <<menu-reorder>>
* Чтобы отобразить меню, нужно разместить блок соответствующего меню в определённом регионе вашей темы оформления; см. <<block-concept>>, <<block-regions>> и <<block-place>>. Стандартный профиль установки размещает все созданные им меню, кроме меню _Администрирование_, в регионах базовой темы Bartik. Модуль ядра Toolbar, который устанавливается по умолчанию, отображает меню Администрирование; также его может показывать дополнительный модуль Admin Toolbar.

//==== Дополнительные материалы

*Авторы*

Написано и отредактировано https://www.drupal.org/u/ajayvi[Ajay Viswambharan], https://www.drupal.org/u/jojyja[Jojy Alphonso] из http://redcrackle.com[Red Crackle], https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] и https://www.drupal.org/u/bserem[Bill Seremetis].

Перевод: https://www.drupal.org/u/igorsh[Игорь Шабальников].
