[[menu-concept]]

=== Основы: Меню

[role="summary"]
Обзор концепции меню и меню, автоматически созданных с помощью стандартного
профиля установки ядра.


(((Меню,обзор)))
(((Меню,основная навигация)))
(((Меню,администрирование)))
(((Меню,учётная запись)))
(((Меню,подвал)))
(((Меню,пользовательское)))
(((Административное меню,обзор)))
(((Меню учетной записи,обзор)))
(((Меню подвала,обзор)))
(((Пользовательское меню,обзор)))

// ==== Prerequisite knowledge

==== Что такое меню?

Меню - это набор ссылок (ссылок меню), используемых для навигации по
веб-сайту. Основной модуль пользовательского интерфейса меню предоставляет
средства управления и настройки системы меню. Меню в основном отображаются в
виде иерархического списка ссылок. По умолчанию, новые ссылки меню помещаются
во встроенное меню под названием _Основная навигация_, но администраторы
также могут создавать собственные меню.

Стандартный профиль установки ядра содержит пять меню:

Основная навигация::
  Ссылки на разделы, предназначенные для посетителей сайта. Обычно они
  создаются администраторами сайта.

Администрирование::
  Ссылки на административные задачи. Это меню в основном содержит ссылки,
  предоставляемые модулями вашего сайте.

Меню учетной записи::
  Ссылки на задачи, связанные с учетной записью пользователя, такие как _Моя
  учётная запись_ и _Выход_.

Подвал::
  Ссылки на важные страницы сайта, предназначенные для подвала (нижнего
  колонтитула). Обычно они создаются администраторами сайта.

Инструменты::
  Ссылки на задачи, необходимые посетителям сайта. Некоторые модули имеют
  здесь свои ссылки.

Меню можно изменить следующим образом, используя следующий функционал
администрирования меню:

* Создание новых пользовательских меню.

* Добавление новых ссылок меню.

* Изменение порядка ссылок меню путем установки их "веса" или перемещения
на другое место.

* Переименование ссылок меню.

* Изменение заголовка ссылки (всплывающая подсказка, появляющаяся при
наведении курсора мыши на ссылку меню).

* Перемещение ссылки меню в другое меню путем редактирования свойства
_Родительская ссылка_.

Ссылка меню будет показан посетителю только в том случае, если у него есть
право на просмотр страницы, на которую он ссылается. Например, ссылка меню
администратора не отображается посетителям, не вошедшим в систему.

==== Связанные понятия

* <<menu-link-from-content>>

* <<menu-reorder>>

* Для отображения меню необходимо поместить блок, соответствующий меню, в
область темы, см. <<block-concept>>, <<block-regions>> и <<block-place>>.
Стандартный профиль установки содержит все определяемые меню, за исключением
меню Администрирование в регионах основной темы Bartik. Модуль Toolbar,
который устанавливается с помощью стандартного профиля установки, отображает
меню Администрирование; он также отображается с помощью дополнительного
модуля Admin Toolbar.

//==== Additional resources


*Авторы*

Написано и отредактировано https://www.drupal.org/u/ajayvi[Ajay Viswambharan],
https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle],
и https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено: https://www.drupal.org/u/igorsh[Игорь Шабальников].
