[[planning-workflow]]

=== Основы: Рабочий процесс редактирования

[role="summary"]
Обзор рабочего процесса редактирования для управления контентом на сайте.

(((Редакционный рабочий процесс, обзор)))
(((Статус опубликовано, обзор)))
(((Статус снято с публикации, обзор)))
(((Редакция, обзор)))

==== Необходимые знания

* <<understanding-drupal>>
* <<planning-data-types>>

==== Что такое рабочий процесс редактирования?

_Редакционный рабочий процесс_ — это последовательность шагов, которые проходят материалы на сайте: от создания и редактирования до проверки и публикации. В процесс могут быть вовлечены разные участники с разными ролями. Например, авторы собирают информацию и пишут тексты; редакторы проверяют и дорабатывают материалы, могут отправлять их на доработку, а затем публикуют для аудитории. Позднее, при необходимости изменений, редакции могут проходить простой или сложный цикл согласования в зависимости от масштаба изменений.

==== Какие инструменты есть для управления рабочим процессом?

Статус публикации::
  Материалы на сайте (например, страницы, записи) можно помечать как _Опубликованные_ или _Неопубликованные_. Права просмотра для опубликованного и неопубликованного контента различаются: опубликованный видят все, а неопубликованный — только авторы и редакторы.
Отслеживание редакций::
  Некоторые типы сущностей поддерживают хранение редакций (версий) — при изменениях все предыдущие варианты сохраняются и доступны для сравнения или отката.
Рабочие процессы::
  Ядро Drupal содержит модуль Workflows, позволяющий настраивать состояния и переходы (например, “На модерации”, “На утверждении”, “Опубликовано” и др.). Вместе с модулем Content Moderation можно назначать права и роли для различных переходов. Эти возможности применимы как для материалов, так и для пользовательских блоков.
Публикация блоков::
  Для пользовательских блоков вы можете сначала создать и подготовить блок, а опубликовать и сделать его видимым на сайте только после финального одобрения.

==== Связанные темы

* <<content-create>>
* <<content-edit>>
* <<block-create-custom>>
* <<block-place>>

// ==== Дополнительные материалы

*Авторы*

Написано и отредактировано https://www.drupal.org/u/dianalakatos[Diána Lakatos] из https://pronovix.com/[Pronovix],
https://www.drupal.org/u/gdunham[Grant Dunham],
и https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Перевод: https://www.drupal.org/u/levmyshkin[Абраменко Иван] для https://drupalbook.org/ru[DrupalBook].
