[[planning-data-types]]
=== Основы: Сущности контента и Поля

[role="summary"]
Обзор контент сущностей и полей.

(((Сущность,обзор)))
(((Термин таксономии,обзор)))
(((Словарь таксономии,обзор)))
(((Контент,тип сущности)))
(((Тип сущности,обзор)))
(((Подтип сущности,обзор)))
(((Блок,тип сущности)))
(((Тип сущности Комментарий,обзор)))
(((Тип сущности Контактная форма,обзор)))
(((Форма тип сущности,обзор)))
(((Контент тип материал,обзор)))
(((Пользовательский блок,тип сущности)))
(((Поле,обзор)))
(((Профиль пользователя тип материала,обзор)))
(((Модуль,Comment)))
(((Модуль,Contact)))
(((Модуль,Taxonomy)))
(((Модуль,User)))
(((Модуль,Node)))
(((Модуль,Custom Block)))
(((Модуль,File)))
(((Comment модуль,тип сущности)))
(((Contact модульь,тип сущности)))
(((Custom block модуль,тип сущности)))
(((Node модуль,тип сущности)))
(((Taxonomy модуль,тип сущности)))
(((User модуль,тип сущности)))
(((File модуль,тип сущности)))

==== Необходимые знания

* <<understanding-data>>
* <<understanding-modules>>

==== Что такое контент сущность?

_Контент сущность_ (или обычно просто, _сущность_) - это элементы данных контента,
который может состоять из текста, HMTL текста, изображений, прикрепленных файлов и других типов данных,
которые созданы для отображения посетителям сайта. Сущности контента могут быть
определены через ядро Drupal или модули.

Контет сущности сгруппированы в _типы сущностей_, которые созданы для одинаковых целей
и отображаются в одинаковом направление на сайте. Большинство типов
сущностей также разделены на _подтипы сущностей_, которые являются отделением
типа сущности и позволяет создавать различные вариации в которых сущности используются и
выводятся. Ниже таблица с некоторыми общими типами контента:

[width="100%",frame="topbot",options="header",grid="rows"]
|=============================================
|Тип Сущности |Подтип сущности |Определяющий модуль |Главное использование

|Элемент контента |Тип контента |Node модуль
  |Контент создан для вывода в главных регионах сайта на страницах сайта
  | 3+| *Пример:* На сайте примера городской ярмарки, вы можете увидеть контент
  типы для Основных страниц, страниц продавцов и страниц рецептов.

|Комментарий |Тип комментария |Comment модуль
  |Комментарий добавляются к контент сущностям (обычно к Материалам)
  | 3+| *Пример:* На сайте блоге, записи в блоге могут содержать комментарии. Они не нужны
  на сайте примере городской ярмарки.

|Профиль пользователа |(нет) |User модуль
  |Данные относящиеся к пользователю с аккаунтом (с возможностью авторизации) на сайте
  | 3+| *Пример:* Каждый сайт имеет по меньше мере базовый профиль пользователя с именем пользователя
  и емайлом; сайты социальных сетей могут имет более сложные пользовательские
  профили с гораздо большим количеством информации.

|Пользовательский блок |Тип Блока |Custom Block модуль
  |Текст и изображения маленькими кусочками, отображены в шапке сайта,
   подвале или колонках
  | 3+| *Пример:* На сайте городской ярмарки, вы можете положить часы работы
  и адрес в блок в колонке.

|Термин таксономии |Словарь таксономии |Taxonomy модуль
  |Используется для классификации остальных типов контента
  | 3+| *Пример:* На сайте примере городской ярмарки, вы можете классифицировать Рецепт
  материал с помощью словаря таксономии Ингредиенты, терминов таксономии, таких как
  Морковь и Помидоры. На сайте блоге, записи в блог могут быть классифицированны
  используя словарь Теги и возможно также словаря Категории.

|Файл |(нет) |File модуль
  |Изображение или прикрепленный файл, который отслеживается и управляется через сайт, часто
   прикладываются к другим типам контента
  | 3+| *Пример:* На сайте примера городской ярмарки, обе страницы Рецепт и Продавец
  могут иметь прикрепленные изображения, которые могли бы (через панель администрирования)
   управляться как сущности Файлов через сайт.

|Контактная форма |Тип формы |Contact модуль
  |Форма которая позволяет посетителям сайта связаться с владельцем сайта
  | 3+| *Пример:* Контактная форма нужна в сайте примера городской ярмарки.

|=============================================

==== Что такое поле?

В пределах сущности, данные хранятся как отдельные _поля_, каждое из которых
содержит один тип данных, такие как форматированный или обычный текст, изображения или другие файлы
или даты. Типы полей могут быть определены через ядро Drupal или модули.

Поля могут быть добавлены администратором для подтипа сущности, так что все
сущности этого подтипа имеют одинаковый набор доступных
полей. Например, Продавец тип материала на сайте городской ярмарки
может иметь поля для Имя продавца, логотипа, URL сайта и
описания, в то время как _Основная страница_ тип материала может иметь только поля для
заголовка и текста. Когда вы создаете или редактируете сущности, вы
определяете значения для полей в сущности.

==== Связанные темы

* <<planning-structure>>
* <<content-create>>
* <<structure-content-type>>
* <<structure-taxonomy>>
* <<user-concept>>
* <<block-concept>>

// ==== Additional resources


*Авторы*

Написано и отредактировано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]
и https://www.drupal.org/u/gdunham[Grant Dunham]

Переведено https://www.drupal.org/u/karina-masalova[Карина Масалова]
и https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
