[[planning-workflow]]

=== Основы: Рабочий процесс редактирования

[role="summary"]
Обзор рабочего процесса редактирования для управления контентом на сайте.

(((Рабочий процесс редактирования,обзор)))
(((Статус опубликовано,обзор)))
(((Статус снято с публикации,обзор)))
(((Редакция,обзор)))

==== Необходимые знания

* <<understanding-drupal>>
* <<planning-data-types>>

==== Что такое рабочий процесс редактирования?

_Рабочий процесс редактирования_ - это процесс организации создания, проверки,
редактирования и публикации контента. Много людей на различных должностях в
организации могут быть вовлечены в процесс. Например, создатель контента может
собирать информацию и писать статьи; редактор может проверять статьи, редактировать, запрашивать
изменения и публиковать контент, когда он будет готов для
аудитории. Позже, редакции контента могут быть изменены, используя простой процесс
для маленьких изменений или более сложный процесс с проверкой для больших изменений.

==== Какие инструменты доступны для рабочего процесса управления?

Опубликован/Снят с публикации статус контента::
  Сущность контента поддерживают пометку каждого элемента контента как
  Опубликованный или Снятый с публикации. Права на просмотр разделены для контента опубликованного и
  снятого с публикации; например, все посетители сайта могут видеть
  опубликованный контент, однако только создатели контента и редакторы могут просматривать
  контент снятый с публикации.
Отслеживание редакций::
  Некоторые типы контента поддерживают отслеживание редакций, это значит, что такой контент
  может быть исправлен и друпал хранит все старые правки, так что они могут быть
  сравнены и восстановлены.
Рабочие процессы::
  Модуль ядра Workflows позволяет определить состояния и переходы состояний контента в рабочем процессе,
  что больше чем просто публикация и снятие с публикации контента. Дополнительный модуль ядра
  Content Moderation позволяет связать права доступа и роли с
  переходами состояний контента в рабочем процессе. Оба модуля могут быть использованы для сущностей Содержимого и
  Пользоательских блоков.
Размещение блока::
  Сущность пользовательскго блока позволяет вам создавать пользовательский блок и редактировать его,
  и сделать его видимым, когда сайт будет готов к его показу.

==== Связанные материалы

* <<content-create>>
* <<content-edit>>
* <<block-create-custom>>
* <<block-place>>

// ==== Additional resources

*Авторы*

Написано и отредактировано https://www.drupal.org/u/dianalakatos[Diána Lakatos] из
https://pronovix.com//[Pronovix],
https://www.drupal.org/u/gdunham[Grant Dunham],
и https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из
https://www.technocrat.com.au/[Technocrat].
