[[preface-scenario]]
=== Основной сценарий

[role="summary"]
Понимание проектного сценария, используемого в этом руководстве для лучшего усвоения тем.

(((Сценарий для этого документа (городская ярмарка),обзор)))
(((Основной сценарий для этого документа (городская ярмарка))))
(((Сценарий использования для этого документа (городская ярмарка))))
(((Городская ярмарка, сценарий использования для этого документа)))

Когда читаете это руководство, полезно иметь в виду проект по созданию сайта.
Следующий проектный сценарий задаёт контекст и объединяет примеры в этом руководстве:

Вы создаёте сайт для городской ярмарки. Сайт должен отображать
информацию о месте проведения и часах работы ярмарки, а также страницу «О ярмарке» с
историей. Также нужен список производителей. Производители должны иметь
возможность редактировать свои карточки (включая логотип или фото) и публиковать рецепты. Посетители
сайта должны иметь возможность просматривать рецепты или искать рецепты по ингредиентам,
которые они приобрели на ярмарке. Некоторые посетители вашего сайта говорят на других
языках, поэтому основные страницы и страницы производителей должны быть переведены.

Когда вы проходите руководство и выполняете описанные задачи, вы можете
следовать сценарию в точности; а можете адаптировать задачи под свои цели. Если вы хотите следовать сценарию полностью, вам понадобятся
некоторые файлы изображений, которые находятся в папке _assets_ в архиве _.zip_
или _.tgz_, доступном для скачивания на странице
https://www.drupal.org/project/user_guide[User Guide project page].

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
