[[preface-audience]]

=== Аудитория и цель

[role="summary"]
Кому предназначено это руководство и чему вы научитесь.

Это руководство создано прежде всего для пользователей, которые только начинают знакомство с системой управления контентом Drupal. Темы помогут вам освоить установку, настройку, построение структуры сайта и управление контентом на Drupal-сайтах. Руководство также будет полезно тем, у кого уже есть опыт работы с Drupal (любой версии) и кто хочет расширить или актуализировать свои знания.

Предполагается, что вы уже приняли решение изучать и использовать Drupal. Если вы еще не определились, рекомендуем начать с главы <<understanding-drupal>>.

В зависимости от того, чему вы хотите научиться, вам могут понадобиться некоторые базовые навыки: общее понимание работы в интернете, умение пользоваться веб-хостингом и передавать файлы на сервер, а также базовые навыки работы с веб-формами.

После прочтения этого руководства вы сможете:

* Спланировать архитектуру Drupal-сайта
* Собрать сайт по своему плану
* Настраивать и администрировать сайт
* Разбираться в документации и блогах по темам, не охваченным этим руководством, чтобы расширять свои знания
* Присоединиться к мировому сообществу Drupal

*Авторы*

Оригинал: https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Перевод: https://www.drupal.org/u/levmyshkin[Абраменко Иван] для https://drupalbook.org/ru[DrupalBook].
