[[preface-organization]]
=== Структура

[role="summary"]
Понимание организационной структуры этого руководства для более удобной навигации по темам.

Это пользовательское руководство содержит серию тем, каждая из которых посвящена либо
_задаче_ (как что-то сделать), либо _основам_ (фоновым знаниям, терминологии
и т.д.). Темы по основам начинаются с _Основы:_, а темы по задачам содержат в названии глаголы, например: _Редактирование основных настроек сайта_.

Темы сгруппированы в главы в логическом порядке, при этом основы и задачи
чередуются, чтобы сначала давались основы, а затем связанные с ними задачи, и задачи строились друг на друге. Чтобы воспользоваться этим, рекомендуется читать всё руководство в представленном порядке, при необходимости пропуская темы, которые вам не интересны или уже знакомы. Не забывайте выполнять задания на своём сайте по мере чтения; большинство людей лучше учатся, делая, а не просто читая.

Если вы предпочитаете, вы также можете воспользоваться предметным указателем или оглавлением, чтобы сразу перейти к интересующей теме, а не читать всё руководство подряд. Для этого в каждой теме приведён список необходимых знаний для понимания темы (со ссылками на темы, в которых эти знания даются); темы с заданиями также содержат _требования к сайту_ (что должно быть настроено или создано на сайте для выполнения задачи). Также в конце большинства тем есть разделы, где можно найти дополнительную информацию и/или задания для расширения понимания и дальнейшего изучения.

Вы также можете обращаться к разделу <<glossary>> по мере чтения — он содержит
краткие определения большинства терминов, используемых в руководстве, со ссылками на темы, в которых даются более подробные объяснения.


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
