[[prevent-cache-clear]]

=== Очистка кэша

[role="summary"]
Как очистить кэш с помощью Drush или пользовательского интерфейса.

(((Кэш,очистка)))
(((Кэш,перестроение)))

==== Цель

Очистить или перестроить внутренние кэши вашего сайта, чтобы они были актуальны и содержали самые последние данные, используя пользовательский интерфейс или Drush.

==== Необходимые знания

* <<prevent-cache>>
* <<install-tools>>

==== Требования к сайту

Если вы хотите использовать Drush для очистки кэша, Drush должен быть установлен. Смотрите <<install-tools>>.

==== Шаги

Вы можете использовать административный интерфейс или Drush для очистки кэша. Вы также можете воспользоваться rebuild-скриптом или Drush для более полного перестроения кэша.

===== Использование административного интерфейса для очистки кэша

. В _Управление_ административного меню перейдите в _Конфигурация_ > _Разработка_ > _Производительность_ (_admin/config/development/performance_). Если у вас нет доступа к этой странице, используйте один из других способов очистки или перестроения кэша.

. Нажмите _Очистить все кэши_.

. В верхней части страницы появится сообщение о том, что кэш был очищен.

. Если это не решило проблему, из-за которой вы хотели очистить кэш, попробуйте вместо этого выполнить перестроение (rebuild).

===== Использование скрипта перестроения

. Откройте _settings.php_ (_/sites/default/settings.php_) в любом текстовом редакторе. Добавьте эту строку в конец файла и сохраните его:
+
----
$settings['rebuild_access'] = TRUE;
----

. Перейдите по адресу _http://www.example.com/core/rebuild.php_ в вашем браузере (где _www.example.com_ — это URL вашего сайта). После небольшой паузы вы должны быть перенаправлены на главную страницу вашего сайта, и кэш должен быть перестроен.

. Откройте _settings.php_ (_/sites/default/settings.php_) в текстовом редакторе. Найдите строку с _$settings['rebuild_access']_, удалите её и сохраните файл.

===== Использование Drush для перестроения или очистки кэша

Вы можете использовать одну из двух команд:

* Используйте команду `drush cache:rebuild`, чтобы очистить и перестроить все кэшированные данные сайта. После выполнения этой команды вы увидите сообщение "Cache rebuild complete."

* Используйте команду `drush cache:clear`, чтобы увидеть список отдельных кэшей и выбрать, какой именно кэш вы хотите очистить. При выполнении команды будет такой вывод:
+
----
> drush cache:clear
Enter a number to choose which cache to clear.
 [0]  :  Cancel
 [1]  :  drush
 [2]  :  theme-registry
 [3]  :  menu
 [4]  :  css-js
 [5]  :  block
 [6]  :  module-list
 [7]  :  theme-list
 [8]  :  render
 [9]  :  views
----
Выберите кэш для очистки, введя его номер. Нажмите "Enter" для продолжения.

Чтобы очистить конкретный тип кэша, укажите его в команде cache:clear.
Например, чтобы очистить render-кэш:
----
drush cache:clear render
----

//==== Expand your understanding


//==== Related concepts

==== Видео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/-evRieC6Y3U[title="Clearing the Cache"]

==== Дополнительные материалы

https://www.drupal.org/docs/7/administering-drupal-7-site/clearing-or-rebuilding-drupals-cache[_Drupal.org_ страница документации сообщества "Clearing or rebuilding Drupal's cache"]


*Авторы*

Адаптировано и отредактировано https://www.drupal.org/u/eojthebrave[Joe Shindelar]
и https://www.drupal.org/u/jerseycheese[Jack Haas] из
https://www.drupal.org/docs/7/administering-drupal-7-site/clearing-or-rebuilding-drupals-cache["Clearing or rebuilding Drupal's cache"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
