[[prevent-cache]]

=== Основы: Кэш

[role="summary"]
Обзор кэша и данных сайта, которые могут быть закэшированы.

(((Кэш,обзор)))
(((Кэш страницы,обзор)))
(((Модуль,Internal Page Cache)))
(((Модуль,Dynamic Page Cache)))
(((Internal Page Cache модуль,обзор)))
(((Dynamic Page Cache модуль,обзор)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое кэш страницы?

Программное обеспечение, на котором работает ваш сайт, при каждом запросе страницы должно выполнять вычисления и извлекать данные из базы данных, чтобы сформировать страницу, которая отправляется в веб-браузер или другое приложение, обращающееся к сайту. Эти вычисления занимают время, что может привести к тому, что загрузка страницы будет дольше, чем хотелось бы.

Существует несколько способов ускорить загрузку страницы, включая установку дополнительного ПО на сервер. Ядро включает модули Internal Page Cache и Dynamic Page Cache, которые не требуют дополнительного программного обеспечения на сервере; они используют механизм _кэша в базе данных_ для ускорения сайта. Принцип их работы в том, что во время вычислений промежуточные результаты и итоговый вывод страницы сохраняются в специальной области базы данных (называемой _кэш_). Затем при следующем совместимом запросе промежуточные или итоговые результаты, в зависимости от ситуации, могут быть извлечены и использованы вместо полного повторного вычисления. Кроме того, когда контент или данные, влияющие на вычисления, обновляются, соответствующие кэшированные данные удаляются из кэша, что заставляет пересчитать и сохранить их заново при следующем обращении.

Эти модули обычно работают достаточно хорошо и обеспечивают ускорение для большинства сайтов. Однако иногда кэш страницы может вызывать проблемы, например:

* Поврежденные данные в кэше, приводящие к искажённому или некорректному выводу страницы

* Слишком долгое хранение устаревших данных в кэше, приводящее к выводу устаревшей страницы

* Недостаточное кэширование, приводящее к медленной загрузке страниц

==== Какие еще данные кэшируются?

Независимо от того, включены ли у вас оба модуля кэширования страниц, программное обеспечение сайта всё равно кэширует результаты многих внутренних вычислений. Ядро кэширует, в частности:

* Система темизации кэширует информацию в базе данных о том, какие файлы шаблонов используются для вывода разных типов данных. Если вы разрабатываете новую тему и добавляете шаблон, потребуется очистить этот кэш, чтобы шаблон был распознан.

* Файлы CSS и JavaScript могут быть оптимизированы и сжаты (в зависимости от настроек сайта). В этом случае их сжатые версии сохраняются в файловой системе, чтобы не приходилось повторно их оптимизировать слишком часто. Если вы разрабатываете модуль или тему, может понадобиться отключить или очистить этот файловый кэш, чтобы изменения CSS или JS были применены.

* Система определяет расположение некоторых низкоуровневых функций и классов PHP, например, _реализации хуков_ и _классы плагинов_, из установленных модулей и сохраняет сведения о том, какой модуль предоставляет какой функционал. При разработке нового модуля или добавлении нового функционала в существующий модуль, возможно, потребуется очистить этот кэш, чтобы система «увидела» новые возможности.

==== Связанные темы

Если у вас возникли проблемы с сайтом, первым шагом почти всегда стоит попробовать очистить кэш. Смотрите <<prevent-cache-clear>> для подробностей.

==== Дополнительные материалы

Подробнее о кэшировании и оптимизации производительности читайте на странице
https://www.drupal.org/docs/7/managing-site-performance-and-scalability/caching-to-improve-performance/caching-overview[_Drupal.org_ страница документации сообщества "Caching overview"].


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
