[[prevent-backups]]

=== Основы: Резервная копия данных

[role="summary"]
Обзор резервных копий данных и что именно нужно сохранять на сайте.

(((Резервная копия,обзор)))
(((Контент,создание резервных копий)))
(((Файл,создание резервных копий)))
(((База данных,создание резервных копий)))

==== Необходимые знания

* <<understanding-drupal>>
* <<install-prepare>>

==== Что такое резервная копия сайта?

Если что-то случится с компьютером (или компьютерами), на которых работает ваш сайт и его база данных, или если вы потеряете доступ к этому компьютеру, вы можете потерять часть или все данные вашего сайта. Вы также можете потерять данные, если ваш сайт взломают или кто-то с административными правами по ошибке удалит или изменит данные через административный интерфейс. Чтобы предотвратить такие ситуации с постоянной или дорогостоящей потерей данных, важно регулярно делать резервные копии данных вашего сайта и хранить их отдельно от компьютера, где работает сайт.

Частота создания резервных копий и количество копий, которые стоит хранить, зависит от того, как часто изменяется ваш сайт. Если на сайте часто добавляется или обновляется большое количество данных, стоит делать резервные копии чаще, чем на сайте, который меняется редко. Также учитывайте, что может пройти какое-то время между возникновением проблемы с данными и тем моментом, когда вы её заметите, поэтому лучше хранить несколько последовательных копий (чтобы можно было вернуться к последней «рабочей» версии), а не просто перезаписывать одну и ту же копию каждый раз.

Ещё один важный момент: в каком бы формате вы ни хранили ваши резервные копии, желательно убедиться, что вы действительно сможете восстановить утраченные данные из этих копий. Можно протестировать различные сценарии потери данных и убедиться, что восстановление сайта проходит успешно во всех случаях.

Чтобы сделать полноценную резервную копию сайта, вам нужно сохранить следующие данные:

* Данные в каталоге _sites_, включая файл _sites/default/settings.php_.

* Данные базы данных вашего сайта. Некоторые таблицы можно не сохранять (например, временный кеш и сессии пользователей), но безопаснее делать копию всей базы данных.

* Загруженные файлы, такие как изображения и другие вложения. Путь к этим файлам можно настроить; по умолчанию это каталог _sites/default/files_ в корне сайта. В _Управлении_ административного меню перейдите в _Конфигурация_ > _Медиа_ > _Файловая система_ (_admin/config/media/file-system_), чтобы узнать, где хранятся файлы. Для изменения пути к файлам, нужно редактировать _settings.php_.

* Модули, темы и любые другие программные файлы, которые вы изменяли вручную. Пользовательские модули и темы находятся в каталогах _modules_ и _themes_ соответственно. Некоторые предпочитают сохранять резервные копии всех файлов (включая файлы ядра и сторонних модулей/тем, которые при необходимости можно заново скачать из исходников), а не выбирать отдельные файлы для резервного копирования.

Вы можете провести тест: разверните резервную копию на тестовом сайте (см. <<install-dev-making>>), чтобы убедиться, что всё сделано правильно.

==== Связанные темы

* <<security-update-core>>
* <<install-dev-making>>
* <<prevent-cache>>

==== Дополнительные материалы

* https://www.drupal.org/docs/7/backing-up-and-migrating-a-site/backing-up-a-site[_Drupal.org_ страница документации сообщества "Backing up a site"]

* https://www.drupal.org/project/backup_migrate[Contributed модуль Backup and Migrate], который можно использовать для автоматического резервного копирования базы данных и загруженных файлов.

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
