[[security-update-core]]

=== Обновление ядра Drupal

[role="summary"]
Как обновить ядро Drupal с помощью интерфейса администратора или Drush.

(((Ядро Drupal,обновление)))
(((Drush,использование для обновления ядра Drupal)))
(((Интерфейс администратора,использование для обновления ядра Drupal)))

==== Цель

Обновить ядро Drupal через интерфейс администратора или используя Drush.

//==== Prerequisite knowledge

==== Требования к сайту

* Если вы хотите использовать Drush, Drush должен быть установлен. Смотрите <<install-tools>>.

* Если ваш сайт находится в интернете, рекомендуется протестировать этот процесс в тестовой (разработческой) среде перед запуском обновления на рабочем сайте. Смотрите <<install-dev-making>>.

==== Шаги

. Сделайте полную резервную копию вашего сайта. См. <<prevent-backups>>.

. Откройте _settings.php_ (_/sites/default/settings.php_) в любом текстовом редакторе. Найдите строку с переменной _$settings['update_free_access']_. По умолчанию она установлена в "FALSE" из соображений безопасности. Измените значение на "TRUE":
+
----
$settings['update_free_access'] = TRUE;
----

. Отключите любые используемые вами системы кэширования (memcache, varnish и т.д.).

. Переведите ваш сайт в режим обслуживания. См. <<extend-maintenance>>.

. Если вы используете Composer для управления зависимостями, пропустите следующие шесть шагов и вместо этого используйте инструкции из <<install-composer>> для загрузки обновленных файлов. Продолжайте со шага _update.php_.

. Загрузите tar.gz или zip-архив с последней версией ядра Drupal вашей ветки (например, 8.x или 9.x) со страницы https://www.drupal.org/project/drupal[_Drupal.org_ Drupal Core Downloads]. См. <<install-prepare>> для деталей о том, как найти последнюю версию.

. Загрузите архив на сервер вашего хостинга.

. Распакуйте архив во временную папку на сервере (эта папка должна находиться вне директории сайта). В файловом менеджере панели управления хостингом обычно есть функция распаковки файлов. Если у вас есть терминальный доступ (Linux), используйте команду:
+
----
tar -xzf drupal-8.3.2.tar.gz
----

. В директории сайта удалите папки _core_ и _vendor_, а также все файлы, которые не лежат в поддиректориях, включая _.htaccess_, _composer.json_ и _autoload.php_. Не удаляйте кастомные и измененные вами файлы, иначе вы можете потерять вашу дополнительную функциональность.

. Скопируйте папки _core_ и _vendor_, а также некастомные файлы, которые вы удалили на предыдущем шаге, из временной папки в директорию сайта.

. Запустите скрипт _update.php_ одним из следующих способов:
+
  * Перейдите в браузере по адресу _http://www.example.com/update.php_ (где _www.example.com_ — это адрес вашего сайта). Нажмите _Продолжить_ на первом экране для запуска обновлений и успешного завершения скрипта.
  * Выполните команду Drush: `drush updatedb`

. Если вы получаете ошибку или предупреждение, повторно запустите _update.php_, пока все обновления не будут выполнены успешно.

. Откройте _settings.php_ (_/sites/default/settings.php_) в текстовом редакторе. Найдите строку с _$settings['update_free_access']_ и верните значение на "FALSE":
+
----
$settings['update_free_access'] = FALSE;
----

. Нажмите _Страницы администрирования_, чтобы вернуться в раздел администрирования вашего сайта.

. Выведите сайт из режима обслуживания. См. <<extend-maintenance>>.

. Очистите кэш. См. <<prevent-cache-clear>>.

. Вновь включите системы кэширования, которые были отключены на шаге 3.

. Теперь ваш сайт должен работать на обновленной версии. Проверить текущую версию можно на странице _Отчет о состоянии_ (см. <<prevent-status>>).

==== Улучшите свое понимание

* <<install-tools>>
* <<install-dev-making>>
* <<prevent-backups>>

==== Связанные концепции

<<prevent-status>>

==== Видео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/DqYqxp4xByk[title="Updating the Core Software"]

==== Дополнительные материалы

* https://www.drupal.org/project/drupal["Drupal Core Downloads" page on _Drupal.org_]
* https://www.drupal.org/project/registry_rebuild["Registry Rebuild" page on _Drupal.org_]
* Файл _/core/UPDATE.txt_ внутри вашей установки.


*Авторы*

Написано и отредактировано https://www.drupal.org/u/surendramohan[Surendra Mohan],
https://www.drupal.org/u/batigolix[Boris Doesborgh] и
https://www.drupal.org/u/jojyja[Jojy Alphonso] на
http://redcrackle.com[Red Crackle].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван].
