[[security-update-core]]

=== Обновление ядра Drupal

[role="summary"]
Как обновить ядро Drupal используя интерфейс администратора или Drush.

(((Ядро Drupal,обновление)))
(((Drush,использование для обновления ядра Drupal)))
(((Интерфейс пользователя,использование для обновления ядра Drupal)))

==== Цель

Обновить ядро Drupal через интерфейс администратора или
используя Drush.

//==== Prerequisite knowledge

==== Требования к сайту

* Если вы хотите использовать Drush, Drush должен быть установлен. Смотрите <<install-tools>>.

* Если сайт выложен в Интернет, вам следует протестировать процесс на копии сайта
локально перед тем как запускать обновление на живом сайте. Смотрите
<<install-dev-making>>.

==== Шаги

. Сделайте полную копию вашего сайта. Подробно как это сделать здесь <<prevent-backups>>.

. Откройте _settings.php_ (_/sites/default/settings.php_) в любом текстовом
редакторе. Найдите строчку с _$settings['update_free_access']_ переменной. По
умолчанию, переменная установлена как "FALSE" по соображениям безопасности. Измените значение на
"TRUE":
+
----
$settings['update_free_access'] = TRUE;
----

. Отключите любой кэш (memcache, varnish и так далее), который используется на вашем
сайте.

. Включите режим обслуживания на вашем сайте. Смотрите <<extend-maintenance>>.

. Если вы используете Composer для управления зависимостями, пропустите следующие шесть шагов и
вместо этого используйте инструкции с <<install-composer>> для загрузки обновленных
файлов. Продолжите с шага _update.php_.

. Загрузите tar.gz или zip архив с последней версией Drupal
той ветки которую вы сейчас используете (8.x или 9.x) со страницы
https://www.drupal.org/project/drupal[_Drupal.org_ Drupal Core Downloads].
Смотрите <<install-prepare>> для большей информации о том, как найти последнюю
версию.

. Загрузите файл архива на сервер вашего хостинга.

. Разархивируйте файл во временную папку на вашем сервере (должен быть
снаружи папки, где расположен сайт). Ваша панель управление на хостинге
дола иметь файловый менеджер способный разархивировать файлы. Если вы имеете
доступ к командной строке на вашем сервере (например использующем Linux), вы можете использовать команду:
+
----
tar -xzf drupal-8.3.2.tar.gz
----

. В папке сайта, удалите папки _core_ и _vendor_
и все файлы, которые находятся в корне сайта, включая _.htaccess_,
_composer.json_ и _autoload.php_. Не удаляйте дополнительные и измененные файлы,
потому что вы можете потерям часть дополнительного функционала, который основывается на этих файлах.

. Скопируйте папки _core_ и _vendor_ и остальные не дополнительные и не пользовательские
файлы, которые вы удалили в предыдущем шаге из временной папки на
вашем сайте.

. Запустите скрипт _update.php_ используя следующие инструкции:
+
  * Откройте в браузере _http://www.example.com/update.php_ (где
  _www.example.com_ это адрес URL вашего сайта). Нажмите _Продолжить_ на первом экране
  для запуска обновление и успешного завершения выполнения скрипта.
  * Запустите следующую Drush команду: `drush updatedb`

. Если вы получили какие-то ошибки или предупреждения, запускайте _update.php_ скрипт
снова до тех пока все обновления не будут выполнены успешно.

. Откройте _settings.php_ (_/sites/default/settings.php_) в текстовом редакторе. Найдите
строку с _$settings['update_free_access']_ переменной и обновите ее на
"FALSE":
+
----
$settings['update_free_access'] = FALSE;
----

. Нажмите _Страницы администрирования_, чтобы вернуться в раздел администрирования вашего
сайта.

. Отключите режим обслуживания на вашем сайте. Смотрите <<extend-maintenance>>.

. Очистите кэш. Смотрите <<prevent-cache-clear>>.

. Включите все дополнительные кэши обратно, которые вы выключали на Шаге 3.

. После этого вы должны иметь обновленную работающую версию Drupal. Вы можете проверить текущую
версию Drupal на странице _Status report_ (Смотрите
<<prevent-status>>).

==== Улучшите свое понимание

* <<install-tools>>
* <<install-dev-making>>
* <<prevent-backups>>

==== Связанные концепции

<<prevent-status>>

==== Видео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/eLzAD83a9BY[title="Updating the Core Software"]

==== Дополнительные материалы

* https://www.drupal.org/project/drupal["Drupal Core Downloads" page on _Drupal.org_]
* https://www.drupal.org/project/registry_rebuild["Registry Rebuild" page on _Drupal.org_]
* The file _/core/UPDATE.txt_ within your installation.


*Авторы*

Написано и отредактировано https://www.drupal.org/u/surendramohan[Surendra Mohan],
https://www.drupal.org/u/batigolix[Boris Doesborgh] и
https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван].
