[[security-cron-concept]]

=== Основы: Крон

[role="summary"]
Обзор крон и его отличий от Unix cron.

(((Задачи cron,обзор)))
(((Модуль Automated Cron,обзор)))

//==== Prerequisite knowledge

==== Что такое задачи cron?

Для того чтобы ваш сайт и его модули продолжали корректно работать, необходимо регулярно выполнять ряд административных операций. Эти операции называются задачами _cron_. Примеры таких задач: проверка обновлений модулей и тем, индексация контента для поиска или очистка временных файлов.

==== Какова связь между cron задачами сайта и Unix cron?

Операционные системы на базе Linux/Unix содержат планировщик cron, который можно использовать для запуска периодических задач. Вы можете настроить запуск задач cron сайта с помощью системного планировщика cron сервера. В качестве альтернативы можно использовать модуль ядра Automated Cron для запуска этих задач. Статус выполнения задач cron сайта можно посмотреть в отчете о состоянии.

==== Похожие темы

* <<security-cron>>
* <<prevent-status>>

==== Дополнительные ресурсы

https://www.drupal.org/docs/7/setting-up-cron/overview[_Drupal.org_ страница документации сообщества "Setting up cron"]


*Авторы*

Написано и отредактировано
https://www.drupal.org/u/dianalakatos[Diána Lakatos] на
https://pronovix.com/[Pronovix],
https://www.drupal.org/u/dalin[Dave Hansen-Lange] на
https://www.advomatic.com/[Advomatic],
и https://www.drupal.org/u/batigolix[Boris Doesborg].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
