[[security-announce]]

=== Отслеживание обновлений

[role="summary"]
Как обезопасить сайт, оставаясь в курсе последних обновлений безопасности.

(((Обновление,отслеживание)))
(((Обновление безопасности,отслеживание)))
(((Update Manager модуль,обзор)))
(((Уведомления о безопасности,подписаться на электронную почту)))
(((Уведомления о безопасности,подписаться на Twitter)))

==== Цель

Обеспечьте безопасность и актуальность своего сайта, следя за последними версиями обновления
безопасности.

==== Необходимые знания

<<security-concept>>

//==== Site prerequisites

==== Шаги

Существует несколько способов получения уведомлений о выпусках обновления безопасности:

* В _Управлении_ административного меню, перейдите в _Отчеты_ > _Доступные
обновления_ > _Настройки_. Введите адрес электронной почты, чтобы получать уведомления, когда они будут
доступны. Вы также можете указать, хотите ли вы получать уведомления ежедневно или еженедельно. Нажмите
_Сохранить конфигурацию_.

* Подписаться на рассылку по электронной почте. Чтобы подписаться, войдите в аккаунт
_Drupal.org_, перейдите на страницу своего профиля пользователя и подпишитесь
на рассылку об обновлении безопасности на вкладке _Edit_ > _My newsletters_.

* Следите за @drupalsecurity в Twitter.

* Подпишитесь на RSS-каналы для
https://www.drupal.org/security/rss.xml[core security updates],
https://www.drupal.org/security/contrib/rss.xml[contributed project updates] и
https://www.drupal.org/security/psa/rss.xml[public service announcements].

//==== Expand your understanding

==== Схожие понятия

* <<security-concept>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>

==== Видео

// Video from Drupalize.Me.
video::https://www.youtube-nocookie.com/embed/GcamYLNeGAs[title="Keeping Track of Updates"]

==== Дополнительные ресурсы

* https://www.drupal.org/security["Security advisories" on _Drupal.org_]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team]
* https://twitter.com/drupalsecurity[@drupalsecurity on Twitter]


*Авторы*

Написано https://www.drupal.org/u/hey_germano[Sarah German] в
https://www.advomatic.com[Advomatic].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
