[[security-cron-concept]]

=== Основы: Крон

[role="summary"]
Обзор cron и чем он отличается от Unix cron.

(((Задачи Cron,обзор)))
(((Автоматизированный модуль Cron,обзор)))

//==== Prerequisite knowledge

==== Что такое cron задачи?

Чтобы ваш сайт и его модули продолжали нормально функционировать, группа
административных операций должна выполняться периодически. Эти операции
называются задачами _cron_. Примеры cron задач: проверка обновлений для модуля или
темы, индексация контента для поиска или очистка временных файлов.

==== Какова связь между cron задачами и Unix cron?

Операционные системы на основе Linux / Unix имеют планировщик cron, который можно использовать для запуска
периодических задач. Вы можете использовать планировщик cron сервера для планирования запуска
cron задач сайта. Кроме того, вы можете использовать модуль ядра Automated Cron для
запуска задач. Вы можете проверить статус cron задач сайта в отчете о состоянии.

==== Похожие темы

* <<security-cron>>
* <<prevent-status>>

==== Дополнительные ресурсы

https://www.drupal.org/docs/7/setting-up-cron/overview[_Drupal.org_ страница документации сообщества "Setting up cron"]


*Авторы*

Написано и отредактировано
https://www.drupal.org/u/dianalakatos[Diána Lakatos] в
https://pronovix.com/[Pronovix],
https://www.drupal.org/u/dalin[Dave Hansen-Lange] в
https://www.advomatic.com/[Advomatic],
и https://www.drupal.org/u/batigolix[Boris Doesborg].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
