[[security-concept]]

=== Основы: Безопасность и регулярные обновления

[role="summary"]
Обзор обновлений безопасности, способы обработки ошибок и обновлений, не связанных с безопасностью.

(((Безопасность,обзор)))
(((Обновление,обзор)))
(((Ошибки,составление отчетов)))
(((Ошибка безопасности,составление отчетов)))
(((Команда безопасности,обзор)))

==== Необходимые знания

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>
* <<understanding-project>>

==== Что такое обновления безопасности?

Любое программное обеспечение иногда имеет ошибки, и иногда эти ошибки могут быть связаны с безопасностью.
Когда ошибки безопасности исправляются в ядре, модулях или темах, используемых на вашем сайте, выпускается _обновление безопасности_.
Когда критические обновления безопасности анонсируются, они будут отображаться на страницах администрирования вашего сайта.
Вам нужно применять обновления безопасности, чтобы ваш сайт оставался защищённым.
Смотрите <<security-announce>>, чтобы узнать, как получать уведомления об обновлениях безопасности по электронной почте,
а также <<security-update-core>>, <<security-update-module>> и <<security-update-theme>>, чтобы узнать, как выполнять обновления.

==== Что такое команда безопасности?

Проект с открытым исходным кодом Drupal имеет команду добровольцев, которые отслеживают ошибки, связанные с безопасностью,
и выпускают обновления безопасности. Они также помогают другим разработчикам исправлять ошибки и поддерживают информацию для пользователей о том, как защищать свои сайты.
Подробнее о команде безопасности и их процессах вы можете узнать на странице
https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team].

==== Как сообщать об ошибках безопасности?

Важно, чтобы проблемы безопасности оставались конфиденциальными до их исправления, чтобы снизить риск компрометации сайтов до их защиты.
Если вы обнаружили потенциальную проблему безопасности в любом программном обеспечении, скачанном с _Drupal.org_,
следуйте инструкциям на странице
https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team], чтобы отправить отчёт.

==== Что такое регулярные (не связанные с безопасностью) обновления?

Ядро Drupal, модули и темы также периодически получают обычные обновления,
добавляющие новые функции и исправляющие ошибки. Эти обновления менее критичны, чем обновления безопасности.
В целом, рекомендуется применять такие обновления, если они не вызывают проблем на вашем сайте.
Перед установкой обновлений на рабочем сайте всегда полезно тестировать их на копии сайта,
так как некоторые обновления могут быть несовместимы с существующими модулями или темами,
или могут нарушить определённую функциональность.

==== Похожие темы

* <<security-announce>>
* <<security-update-core>>
* <<security-update-module>>
* <<security-update-theme>>
* <<install-dev-making>>

==== Дополнительные ресурсы

* https://www.drupal.org/security/secure-configuration[_Drupal.org_ страница документации сообщества "Securing your site"]
* https://www.drupal.org/security["Советы по безопасности" на Drupal.org]
* https://www.drupal.org/drupal-security-team/general-information[_Drupal.org_ Security Team]

*Авторы*

Написано и отредактировано https://www.drupal.org/u/batigolix[Boris Doesborg]
и https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
