[[structure-text-formats]]

=== Концепция: Форматы текста и редакторы

[role="summary"]
Обзор форматов текста, фильтров, редакторов и межсайтового скриптинга.

(((Формат текста,обзор)))
(((Пользовательский контент,фильтрация)))
(((Безопасность,формат текста)))
(((Безопасность,межсайтовый скриптинг)))
(((Межсайтовый скриптинг (XSS),предотвращение)))
(((XSS (Межсайтовый скриптинг),предотвращение)))

// ==== Prerequisite knowledge

==== Что такое форматы текста и фильтры?

_Форматы текста_ изменяют то, как теги HTML и другой текст обрабатываются и отображаются
на вашем сайте. Форматы текста состоят из ряда _фильтров_, каждый из которых
трансформирует текст. Когда пользователи создают контент, с содержимым связывается
текстовый формат, и полный, исходный текст сохраняется в базе данных. Затем содержимое
пропускается через фильтры текстового формата перед выводом на
сайте.

Модуль ядра Filter обеспечивает функциональность форматов текста, а стандартный
установочный профиль создает форматы текста _Basic HTML_, _Restricted HTML_ и _Full HTML_.
Для каждого текстового формата есть соответствующее разрешение, чтобы вы могли
разрешить только доверенным пользователям использовать более свободные форматы текста. Это ограничивает
недоверенных пользователей такими форматами как _Basic HTML_, который фильтрует опасные
HTML-теги.

==== Какие редакторы связаны с форматами текста?

Каждый формат текста может быть связан с редактором, например, визуальным WYSIWYG
(What You See Is What You Get — «Что вижу, то и получаю») HTML-редактором. Модуль ядра Text Editor
позволяет ассоциировать редакторы с форматами текста и настраивать их
(например, добавлять или убирать кнопки на панели инструментов). Модуль ядра CKEditor
предоставляет стандартный редактор CKEditor, чтобы он мог
использоваться для редактирования HTML-контента на вашем сайте.

==== Что такое межсайтовый скриптинг?

Межсайтовый скриптинг (XSS) — это уязвимость безопасности, обычно встречающаяся на
веб-сайтах. На сайте без хорошей защиты злоумышленники могут вставить скрипт
на страницы, которые просматривают другие пользователи (например, в комментарии или
в основной текст страницы). Уязвимость межсайтового скриптинга может быть использована
злоумышленниками для входа как другой пользователь. Важно правильно настроить форматы
текста на вашем сайте, чтобы не допустить такой атаки.

==== Похожие темы

<<security-concept>>

==== Дополнительные ресурсы

* https://www.drupal.org/docs/core-modules-and-themes/core-modules/filter-module/filter-module-overview[_Drupal.org_ страница документации сообщества "Filter module overview"]

* https://en.wikipedia.org/wiki/Cross-site_scripting[Страница Википедии "Cross-site scripting"]


*Авторы*

Написано и отредактировано https://www.drupal.org/u/batigolix[Boris Doesborg] и
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
