[[structure-widgets]]

=== Концепция: Формы и виджеты

[role="summary"]
Обзор форм и виджетов.

(((Форма редактирования материала,обзор)))
(((Виджет,обзор)))
(((Поле,обзор)))
(((Форма,обзор)))

==== Необходимые знания

<<planning-data-types>>

==== Что такое формы и виджеты?

Программное обеспечение системы управления контентом, на которой работает ваш сайт,
позволяет администраторам редактировать контент и настраивать параметры онлайн,
используя различные веб-_формы_. В частности, _формы редактирования материала_ используются
для редактирования сущностей контента вашего сайта, и они настраиваются администраторами;
формы настройки параметров, предоставляемые модулями, не могут быть сконфигурированы отдельно.

Данные в сущностях контента вашего сайта хранятся в одном или нескольких полях,
которые привязаны к типу сущности и/или подтипу. Когда вы настраиваете форму редактирования
контента для каждого подтипа сущности, вы можете:

* Выбрать _виджет_ для каждого поля. Виджет определяет способ ввода данных для поля.
Например, термин таксономии можно выбрать через поле автозаполнения, выпадающий список
или виджет в стиле тегов, позволяющий редакторам автоматически добавлять новые теги.

* Настроить параметры виджета. Например, можно выбрать размер текстового поля.

* Скрыть одно или несколько полей из формы редактирования.

* Изменить порядок следования полей.

Теоретически, вы также можете создать несколько форм редактирования контента для
каждого подтипа сущности. Эта функция используется редко; распространенное исключение —
для пользовательских профилей: вы можете использовать разные формы для регистрации пользователя
и для его дальнейшего редактирования. Например, при регистрации может отображаться ограниченный
набор полей, а при редактировании профиля — большее количество полей.

==== Связанные темы

* <<structure-form-editing>>
* <<structure-view-modes>>

//==== Additional resources


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
