[[structure-image-styles]]

=== Основы: Стили изображений

[role="summary"]
Обзор стилей изображений и способов их использования для отображения одного изображения в разных вариантах.

(((Стиль изображения,обзор)))
(((Стиль,изображение)))
(((Эффект изображения,обзор)))
(((Эффект,изображение)))

==== Необходимые знания

<<structure-fields>>

==== Что такое стили изображений?

Стили изображений позволяют загрузить одно изображение и отображать его разными способами: каждый вариант отображения, или _стиль изображения_, формируется за счёт применения одного или нескольких _эффектов_ к исходному изображению.

Например, вы можете загрузить изображение с высоким разрешением (например, с соотношением сторон 4:3) и затем показывать его на сайте уменьшенным, обрезанным до квадрата, преобразованным в чёрно-белый вариант или с любым другим сочетанием эффектов. Ядро Drupal позволяет реализовать это эффективно:

. Настройте стиль изображения с нужными эффектами на странице _Стили изображения_ (_admin/config/media/image-styles_).
. При первом запросе изображения в определённом стиле к нему применяются эффекты.
. Полученное (обработанное) изображение сохраняется.
. При последующих запросах в этом же стиле возвращается уже готовое изображение, без повторного применения эффектов.

В ядре Drupal есть несколько стандартных эффектов, которые можно использовать для создания стилей. Дополнительные эффекты могут предоставляться сторонними модулями.

Посмотреть доступные стили изображений можно через административное меню _Управление_, выбрав _Конфигурация_ > _Медиа_ > _Стили изображения_ (_admin/config/media/image-styles_).

==== Похожие темы

* <<structure-image-style-create>>
* <<structure-image-responsive>>
* <<structure-fields>>

==== Дополнительные ресурсы

https://www.drupal.org/docs/core-modules-and-themes/core-modules/image-module/working-with-images[_Drupal.org_ страница документации сообщества "Working with images"]

*Авторы*

Адаптировано и отредактировано https://www.drupal.org/u/batigolix[Boris Doesborg] и
https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle], по материалам
https://www.drupal.org/docs/core-modules-and-themes/core-modules/image-module/working-with-images["Working with images"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
