[[structure-view-modes]]

=== Концепция: Режимы просмотра и форматеры

[role="summary"]
Обзор режимов просмотра и форматеров полей.

(((Режим просмотра, обзор)))
(((Режим просмотра сущности, обзор)))
(((Форматер, обзор)))
(((Форматер поля, обзор)))

==== Необходимые знания

<<structure-content-type>>

==== Что такое режим просмотра?

Как отображается сущность (например, содержимое, пользователь или комментарий), зависит от
контекста, в котором она показана. Этот контекст называется _режимом просмотра_.
Примеры режимов просмотра:

* полная страница содержимого со всеми значениями полей
* тизер содержимого с миниатюрой и ссылкой «Читать дальше»
* полный профиль пользователя с масштабируемой портретной фотографией
* аватар пользователя с именем пользователя и ссылкой на профиль

Каждый режим просмотра может быть настроен через административные страницы. Чтобы увидеть
варианты конфигурации режимов просмотра для типа материала Рецепт, перейдите
в _Управление_ административного меню -> _Структура_ > _Типы материалов_
(_admin/structure/types_) и нажмите _Управление отображением_ в выпадающем меню.
В каждом режиме просмотра можно скрыть или отобразить любое поле, и если поле
отображается, можно выбрать и настроить форматер поля.

==== Что такое форматер поля?

Форматер поля — это настройка отображения значения поля. Например,
длинные текстовые поля можно отображать обрезанными или полностью, а поля-ссылки на термины
таксономии — как простой текст или как ссылку на страницу термина.
Посмотрите страницу _Управление отображением_, чтобы увидеть форматеры для
полей типа материала Рецепт.

==== Похожие темы

* <<structure-content-type>>
* <<structure-content-display>>

==== Дополнительные ресурсы

https://www.drupal.org/node/1577752[_Drupal.org_ страница документации сообщества "View modes"]

*Авторы*

Адаптировано https://www.drupal.org/u/batigolix[Boris Doesborg] от
https://www.drupal.org/node/1577752["View modes"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
