[[structure-view-modes]]

=== Основы: Режимы просмотра и Форматеры

[role="summary"]
Обзор режимов просмотра и форматеров полей.

(((Режимы просмотра, обзор)))
(((Режимы просмотра сущности, обзор)))
(((Форматер, обзор)))
(((Форматер поля, обзор)))

==== Необходимые знания

<<structure-content-type>>

==== Что такое режимы просмотра?

Как отображается объект (например, содержимое, пользователь или комментарий), зависит от
контекста, в котором он отображается. Этот контекст известен как _режим просмотра_.
Примерами режима просмотра могут быть:

* полная страница содержимого со всеми значениями полей
* тизер содержимого с миниатюрой и ссылкой «Читать дальше»
* полный профиль пользователя с масштабируемой портретной фотографией
* аватар пользователя с именем пользователя и ссылкой на профиль

Каждый режим просмотра может быть настроен на страницах администрирования. Чтобы увидеть
параметры конфигурации для режима просмотра типа материала Рецепт, перейдите
в _Управлении_ административного меню _Структура_ > _Типы материалов_
(_admin/structure/types_) и нажмите _Управление отображением_ из выпадающего меню
кнопки. В каждом режиме просмотра все поля могут быть скрыты или отображены, и если они
отображаются, вы можете выбрать и настроить форматирование поля.

==== Что такое форматер поля?

Форматер поля - это настройка для отображения значений поля. Например,
длинные текстовые поля могут отображаться как обрезанные или полноразмерные, так и в термине таксономии
ссылочные поля могут быть отображены в виде простого текста или являться ссылкой на страницу термина
таксономии. Обратитесь к странице _Управление отображением_, чтобы увидеть форматеры поля для
полей типа материала Рецепт.

==== Похожие темы

* <<structure-content-type>>
* <<structure-content-display>>

==== Дополнительные ресурсы

https://www.drupal.org/node/1577752[_Drupal.org_страница документации сообщества "View modes"]


*Авторы*

Адаптировано https://www.drupal.org/u/batigolix[Boris Doesborg] от
https://www.drupal.org/node/1577752["View modes"],
авторские права 2000-copyright_upper_year отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
