[[structure-reference-fields]]

=== Концепция: Поле ссылка на сущность

[role="summary"]
Обзор полей ссылки на сущность и их обычно используемые типы.

(((Поле ссылка на сущность,обзор)))
(((Поле ссылка на сущность,материал)))
(((Поле ссылка на сущность,термин таксономии)))
(((Поле ссылка на сущность,пользователь)))
(((Поле,связь)))
(((Поле,ссылка на страницу материла)))
(((Поле,ссылка на термин таксономии)))
(((Поле,ссылка на пользователя)))
(((Поле ссылка на термин таксономии,обзор)))
(((Поле ссылка на пользователя,обзор)))
(((Поле ссылка на материал,обзор)))

==== Необходимые знания

<<planning-data-types>>

==== Что такое ссылочное поле

_Поле ссылка на сущность_ - это поле, которое представляет собой связь между
сущностью и одной или несколькими другими сущностями, которые могут
принадлежать к одному и тому же или разным типам сущностей. Наиболее часто
используются три вида полей ссылок на сущность:

Ссылка на страницу материал::
  Ссылка на страницу материла. Например, вам может понадобиться связать
  рецепты с производителями, которые их прислали. Вы можете указать производителя
  в поле "Добавлен"
  типа материала Рецепт.

Ссылка на термин таксономии::
  Например, вы можете связать рецепты к их ингредиентам. Вы можете создать поле
  ссылки на таксономический термин под названием Ингредиенты в типе материала
  Рецепт. В этом ссылочном поле будет указан словарь Ингредиенты.

Ссылка на пользователя::
  Ссылка на учетную запись пользователя. Например, можете связать рецепты блюд с
  их шеф-поварами. Вы можете создать ссылку на пользователя
  "Шеф-повар" в разделе "Тип содержимого рецепта".

==== Сопутствующие темы

<<structure-taxonomy>>

//==== Additional resources


*Авторы*

Написано и отредактировано https://www.drupal.org/u/surendramohan[Surendra
Mohan] и https://www.drupal.org/u/jojyja[Jojy Alphonso] из
http://redcrackle.com[Red Crackle].

Переведено: https://www.drupal.org/u/igorsh[Игорь Шабальников].
