[[structure-reference-fields]]

=== Концепция: Поле ссылка на сущность

[role="summary"]
Обзор полей-ссылок на сущности и их наиболее часто используемых типов.

(((Поле ссылка на сущность,обзор)))
(((Поле ссылка на материал,обзор)))
(((Поле ссылка на термин таксономии,обзор)))
(((Поле ссылка на пользователя,обзор)))
(((Поле,ссылка)))
(((Поле,ссылка на материал)))
(((Поле,ссылка на термин таксономии)))
(((Поле,ссылка на пользователя)))

==== Необходимые знания

<<planning-data-types>>

==== Что такое поле-ссылка на сущность?

_Поле-ссылка на сущность_ — это поле, с помощью которого можно установить связь между одной сущностью и одной или несколькими другими сущностями, которые могут принадлежать к тому же или разным типам сущностей. Наиболее часто используются следующие типы полей-ссылок:

Ссылка на материал::
  Ссылка на другой элемент содержимого (материал). Например, чтобы связать рецепт с производителем, который его разместил, добавьте в тип материала «Рецепт» поле-ссылку на материал с названием «Добавлено» и настройте связь с типом материала «Производитель».

Ссылка на термин таксономии::
  Ссылка на термин из словаря таксономии. Например, чтобы связать рецепт с его ингредиентами, добавьте в тип материала «Рецепт» поле-ссылку на термин таксономии с названием «Ингредиенты», выбрав нужный словарь.

Ссылка на пользователя::
  Ссылка на учётную запись пользователя сайта. Например, чтобы связать рецепт с поваром, создайте в типе материала «Рецепт» поле-ссылку на пользователя с названием «Шеф-повар».

==== Сопутствующие темы

<<structure-taxonomy>>

//==== Additional resources

*Авторы*

Написано и отредактировано https://www.drupal.org/u/surendramohan[Surendra Mohan] и https://www.drupal.org/u/jojyja[Jojy Alphonso] из http://redcrackle.com[Red Crackle].

Переведено: https://www.drupal.org/u/igorsh[Игорь Шабальников].
