[[structure-widgets]]

=== Основы: Формы и Виджеты

[role="summary"]
Обзор форм и виджетов.

(((Форма редактирования материала,обзор)))
(((Виджет,обзор)))
(((Поле,обзор)))
(((Форма,обзор)))

==== Необходимые знания

<<planning-data-types>>

==== Что такое формы и виджеты?

Система управления сайтом позволяет вашим администраторам
сайта редактировать контент и менять настройки онлайн, используя различные веб
_формы_. В частности, _форма редактирования материала_ используется для редактирования вашего
контента и эти формы настраиваются администраторами настройки конфигурации
форм предоставленных модулями, не могут быть настроены отдельно от модуля.

Данные в контенте вашего сайта храняться в одно или несколько полях, которые
привязаны к типу сущности и/или подтипу. Когда вы настраиваете форму редактирования
контента для каждого подтипа контента, вы можете:

* Выбрать _виджет_ для каждого поля. Виджет определяет метод используемый для ввода
данных в поле. Например, термин таксономии может использовать
поле с авто дополнением, выбор из списка или поле с выбором тегов, которые позволяют редакторам
добавлять новые теги автоматически.

* Настроить виджет поля. Например, вы можете выбрать размер
текстового поля ввода.

* Спрятать одно или несколько полей из формы редактирования.

* Менять поля местами.

Главным образом, вы можете также иметь различные формы редактирования доступные для
каждого подтипа сущности. Этот функционал редко используется, однако, в виде исключения
в общем случае для полей профиля пользователя: вы можете использовать различные формы для
регистрации и редактирования пользователя. Например, вам может быть необходимо ограничить набор
полей, которые показываются, когда пользователь регистрируется на сайте и показывать больше полей позже,
когда пользователь редактирует свой профиль.

==== Связанные темы

* <<structure-form-editing>>
* <<structure-view-modes>>

//==== Additional resources


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из
https://www.technocrat.com.au/[Technocrat].
