[[structure-image-responsive]]

=== Основы: Адаптивные стили изображений

[role="summary"]
Обзор адаптивных стилей изображений, которые позволяют использовать разные изображения для разных размеров экрана.

(((Адаптивный стиль изображения,обзор)))
(((Стиль изображения,адаптивный)))
(((Точка перехода,обзор)))
(((HTML5 picture тег, и адаптивные изображения)))

==== Необходимые знания

* <<understanding-themes>>
* <<structure-content-display>>
* <<structure-image-styles>>

==== Что такое адаптивные стили изображений?

Модуль ядра Drupal Responsive Image предоставляет возможность использовать адаптивные стили изображений. Это позволяет вашему сайту подставлять изображения оптимального размера для разных устройств и размеров экранов. Такой подход помогает ускорить загрузку сайта на мобильных устройствах, поскольку изображения подгружаются с меньшим разрешением для маленьких экранов.

Адаптивный стиль изображения — это сопоставление между стилями изображений и точками перехода (breakpoints). Точки перехода — это значения ширины экрана, при достижении которых дизайн сайта или параметры изображений должны меняться для адаптации под новое устройство. Адаптивные стили изображений могут работать с точками перехода, определёнными в вашей теме, или с точками перехода, заданными в настройках самого стиля.

Когда адаптивный стиль изображения создан, его можно выбрать в настройках отображения для полей изображений. Благодаря этому сайт будет выводить адаптивные изображения с помощью HTML5 тега _picture_ или с помощью атрибутов _srcset_ и _sizes_ в теге _img_, в зависимости от вашей конфигурации.

==== Похожие темы

<<structure-fields>>

==== Дополнительные ресурсы

* https://www.drupal.org/docs/mobile-guide/responsive-web-design[_Drupal.org_ страница "Responsive web design"]
* https://www.drupal.org/docs/mobile-guide/responsive-images[_Drupal.org_ страница "Responsive images"]
* https://www.drupal.org/docs/theming-drupal/working-with-breakpoints-in-drupal[_Drupal.org_ страница "Working with breakpoints in Drupal"]
* https://chromatichq.com/blog/responsive-images-drupal-8-using-srcset[Пост в блоге "Responsive Images in Drupal 8 using 'srcset'"]

*Авторы*

Адаптировано https://www.drupal.org/u/batigolix[Boris Doesborg] из
https://www.drupal.org/docs/mobile-guide/responsive-images[Responsive images],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
