[[thoughts-support]]
=== Техническая поддержка

[role="summary"]
Где найти поддержку для проблем, возникших при разработке сайта.

(((Поддержка,обнаружение)))
(((Форум,поддержка пользователей)))
(((IRC (Интернет-чат),использование онлайн чата)))
(((Интернет-чат (IRC),использование онлайн чата)))
(((Онлайн переписка)))

==== Необходимые знания

* <<understanding-project>>
* <<thoughts-connecting>>

==== Где вы можете найти поддержку?

Drupal имеет открытый исходный код, так что если у вас есть вопросы или проблемы
с программным обеспечением ваши варианты поиска ответов и исправлений будут несколько
отличаться от того, какими они будут для коммерческого программного обеспечения.

Существует несколько вариантов бесплатной поддержки, предоставляемой сообществом.
Во-первых, некоторые IRC-каналы, местные группы и языковые сообщества, поощряющие вопросы поддержки,
через онлайн-чат, личные встречи, или
сайты (узнать больше об этом в <<thoughts-connecting>>).

Во-вторых, в некоторых (но не всех) модулях, дистрибутивах и темах
можно публиковать вопросы по поддержке в проблемах(issues). Как правило, проекты, которые имеют
очень большое количество пользователей не разрешают публиковать запросы о поддержке в своих проблемах
(Ядро Drupal в этой категории), в то время как проекты с меньшим количеством пользователей
приветствуют вопросы по поддержке. С уважением относитесь ко времени разработчиков и
прочтите документацию по проекту, прежде чем отправлять вопрос. Но
с другой стороны, во всех проектах рекомендуется задать вопросы по
багам; смотрите <<thoughts-connecting>>, чтобы узнать больше об этом.

В дополнение к этим ресурсам, следующие сайты предоставляют бесплатные форумы, где
волонтеры отвечают на вопросы поддержки о Drupal:

* https://www.drupal.org/forum[_Drupal.org_ Форумы]
* https://drupal.stackexchange.com/["Drupal Вопросы" на StackExchange]

Если вы предпочитаете платить за поддержку (предположительно в обмен на более обширный набор
услуг или лучшую доступность), вы можете найти поставщиков услуг на
https://www.drupal.org/drupal-services["Drupal Marketplace" на _Drupal.org_].

==== Похожие темы

* <<thoughts-learn-more>>
* <<thoughts-connecting>>

==== Дополнительные ресурсы

* https://drupal.ru/forum/support[Русскоязычное сообщество Drupal.ru]
* http://dru.io/question[Русскоязычное сообщество Drupal]
* https://t.me/drupal_beginner[Telegram канал Друпал для начинающих]
* https://t.me/drupal_rus[Telegram канал Drupal.ru]
* https://medium.com/@ADCIRussia/tehobsluzhivanie-drupal-saita-f62191277881[Техобслуживание Drupal-сайта: что и как часто нужно проверять, чтобы сайт работал правильно]
* https://www.drupal.org/support[страница "Поддержки" на _Drupal.org_]
* https://www.drupal.org/drupal-services["Drupal Marketplace" на _Drupal.org_]
* The https://www.drupal.org/forum[_Drupal.org_ Форумы]
* https://drupal.stackexchange.com/["Drupal Вопросы" на StackExchange]


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
