[[thoughts-connecting]]
=== Связь с Сообществом Drupal

[role="summary"]
Как присоединиться и принять участие в сообществе Drupal.

(((Сообщество,связь)))
(((Drupal проект,связь)))
(((Событие,Drupal)))
(((Группа по интересам,поиск)))
(((Пользовательская группа,поиск)))
(((Группа,поиск)))
(((Пользовательская группа Drupal,поиск)))
(((IRC (Интернет-чат),использование онлайн чата)))
(((Интернет-чат (IRC),использование онлайн чата)))
(((Онлайн переписка)))
(((Вклад в проект)))
(((Ошибка,составление отчета)))

==== Необходимые знания

<<understanding-project>>

==== Как вы можете связаться с сообществом?

Проект Drupal имеет всемирное сообщество разработчиков и пользователей. Один из
лучших способов улучшить свои знания о платформе - это связаться с
другими людьми, которые используют её, и принять участие в сообществе Drupal. Есть
много способов, как вы можете начать:

Посетить мероприятие::
  Вокруг Drupal проводятся как региональные, так и международные мероприятия
  по миру. Смотрите https://events.drupal.org["DrupalCon" страница на _Drupal.org_],
  чтобы найти международные события, и 
  https://groups.drupal.org/events["Календарь событий" на _groups.drupal.org_]
  или https://www.drupical.com/[_drupical.com_], чтобы найти региональные события.
Присоединиться к местной группе::
  По всему миру есть группы пользователей Drupal. Многие из них имеют регулярные
  встречи, которые вы можете посетить, чтобы узнать больше о Drupal и присоединиться к другим
  пользователям Drupal. Найти локальные группы пользователей на
  https://groups.drupal.org/[_groups.drupal.org_].
Участвуйте в тематической или языковой группе::
  Существуют также группы интересов по широкому кругу тем, которые имеют онлайн
  дискуссионные форумы. Найти тематические группы на
  https://groups.drupal.org/[_groups.drupal.org_]. Многие языки также имеют
  собственные сайты; вы можете найти их на
  https://www.drupal.org/language-specific-communities["Языковые
  сообщества" страница на _Drupal.org_].
Онлайн чат::
  Проект Drupal использует IRC для онлайн-чата. Есть региональные, тематические,
  и общие чат группы. Узнайте больше на
  https://www.drupal.org/ircchat["IRC" страница на _Drupal.org_].
Сообщить о проблеме::
  Смотрите ниже.
Сотрудничество::
  Вы можете поделиться своим временем и опытом с сообществом различными способами, такими
  как:
  * Разработка модулей или тем. Смотрите на
    https://www.drupal.org/contribute/development["Способствование развитию"
    страница на _Drupal.org_], или улучшая их (использование очереди ошибок для существующих
    проектов).
  * Перевод пользовательского интерфейса. Смотрите
    https://localize.drupal.org[_localize.drupal.org_].
  * Написание документации. Смотрите
    https://www.drupal.org/contribute/documentation["Способствовать
    Документации" на _Drupal.org_].
  * Ответы на вопросы по поддержке. Смотрите <<thoughts-support>>.

==== Как вы можете сообщить о проблеме или предложить дополнительные возможности?

Каждый проект в сообществе (например ядро Drupal для базы
программного обеспечения и проекты для каждой темы и модуля) используют _проблемы(issues)_ в
отслеживании ошибок программного обеспечения и планирования новых дополнительных возможностей. Вы можете участвовать
в создании отчета об ошибке при обнаружении проблемы, создавать запрос на дополнительную возможность, или
комментировать существующие проблемы. Перед созданием проблемы,
убедитесь, что о проблеме или дополнительной возможности не было сообщено.
Смотрите
https://www.drupal.org/issue-queue[_Drupal.org_ страница "Использование очереди ошибок"] и
https://www.drupal.org/node/314185[_Drupal.org_ страница "Сообщение о проблеме"] для
дополнительной информации.

Если вы обнаружили проблему, которая, по вашему мнению, связана с безопасностью, такую как
уязвимость к межсайтовому скриптингу, не сообщайте об этом в стандартной очереди
ошибок. Вместо этого сообщите об этом в команду безопасности. Смотрите
https://www.drupal.org/node/101494[_Drupal.org_ страница "Как сообщить о проблеме безопасности"] для подробностей.

==== Похожие темы

<<thoughts-support>>

==== Дополнительные ресурсы

* https://www.drupal.org/dcoc["Нормы поведения" на _Drupal.org_]

* https://groups.drupal.org/events["Календарь событий" на _groups.drupal.org_] или
https://www.drupical.com/[_drupical.com_]

* https://www.drupal.org/community["Community" страница на _Drupal.org_]

* https://groups.drupal.org/[_groups.drupal.org_]

* https://www.drupal.org/ircchat["IRC" страница на _Drupal.org_]

* https://www.drupal.org/contribute["Способы принять участие" страница на _Drupal.org_]

* https://www.drupal.org/node/2486391[_Drupal.org_ страница "Зачем вмешиваться?"]

* https://www.drupal.org/contributor-tasks[_Drupal.org_ страница "Задачи участника"]

* https://www.drupal.org/issue-queue[_Drupal.org_ страница "Использование очереди ошибок"]

* https://www.drupal.org/node/314185[_Drupal.org_ страница "Сообщить о проблеме"]

* https://www.drupal.org/node/101494[_Drupal.org_ страница "Как сообщить о проблеме безопасности"]


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/eojthebrave[Joe Shindelar] в
https://drupalize.me[Drupalize.Me].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
