[[thoughts-learn-more]]
=== Продолжение обучения

[role="summary"]
Как найти дополнительный материал, чтобы получить продвинутые навыки по созданию сайтов.

(((Учебный ресурс,ссылка на)))
(((Обучение,ресурс)))
(((Drupal обучение,ресурсы для)))
(((Документация,о Drupal)))
(((Ресурс,документация и обучение)))
(((Документация,доступна на drupal.org)))
(((Документация,предоставлена сообществом Drupal)))
(((Документация,о Drupal API)))
(((Документация,для программистов)))
(((Документация,посты в блоге Drupal Planet)))
(((Обучение,Training Marketplace)))
(((Обучение,Global Training Days)))

==== Необходимые знания

* <<understanding-project>>
* <<thoughts-connecting>>

==== Где можно узнать больше?

Следующие ресурсы могут быть полезны вам по мере развития
ваших навыков:

https://www.drupal.org/documentation[Документация сообщества Drupal]::
  Wiki-подобная документация, предоставленная сообществом Drupal, от
  базового до продвинутого, по всем аспектам Drupal (создание сайтов,
  администрирование, темизация, разработка и модули).
https://api.drupal.org[_api.drupal.org_]::
  Справочная документация для программистов по Drupal API.
https://www.drupal.org/planet["Страница Drupal Planet" на _Drupal.org_]::
  Агрегатор блогов о Drupal со всего интернета — от участников сообщества,
  которые подали заявку на включение. Темы варьируются от программирования до сайтостроения и новостей о Drupal.
Группы, мероприятия и встречи::
  См. <<thoughts-connecting>> для подробностей о тематических, региональных и языковых группах,
  а также о местных, региональных и международных мероприятиях.
https://www.drupal.org/training["Страница Training Marketplace" на _Drupal.org_]::
  Marketplace перечисляет платных поставщиков обучения. Для бесплатного обучения смотрите, включают ли
  мероприятия учебные сессии; также существуют бесплатные или очень дешевые
  обучающие мероприятия, перечисленные на
  https://groups.drupal.org/global-training-days["странице Global Training Days" на
  _Drupal.org_].
Сайты поддержки::
  См. <<thoughts-support>> для поиска форумов поддержки; их поиск может быть полезен
  для изучения конкретных тем.

// ==== Related topics

// ==== Additional resources

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/eojthebrave[Joe Shindelar] на
https://drupalize.me[Drupalize.Me].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
