[[thoughts-connecting]]
=== Связь с сообществом

[role="summary"]
Как подключиться и принять участие в сообществе с открытым исходным кодом.

(((Сообщество,связь с)))
(((Drupal проект,связь с)))
(((Событие,Drupal)))
(((Группа по интересам,поиск)))
(((Пользовательская группа,поиск)))
(((Группа,поиск)))
(((Пользовательская группа Drupal,поиск)))
(((Slack,использование для онлайн-чата)))
(((DrupalChat,использование для онлайн-чата)))
(((Онлайн-чат)))
(((Вклад в проект)))
(((Ошибка,сообщение об ошибке)))

==== Необходимые знания

<<understanding-project>>

==== Как вы можете подключиться к сообществу?

В проекте Drupal есть мировое сообщество разработчиков и пользователей. Один из
лучших способов улучшить свои знания о платформе — это связаться с
другими пользователями и принять участие в сообществе с открытым исходным кодом. Существует
множество способов начать:

Посетить мероприятие::
  Проводятся как региональные, так и международные мероприятия Drupal по всему миру. Смотрите страницу
  https://events.drupal.org["DrupalCon" на _Drupal.org_], чтобы найти международные события, а также
  https://groups.drupal.org/events["Календарь событий" на _groups.drupal.org_]
  или https://www.drupical.com/[_drupical.com_], чтобы найти региональные события.
Присоединиться к местной группе::
  Существуют группы пользователей Drupal по всему миру. Многие из них регулярно проводят
  встречи, которые вы можете посещать, чтобы узнать больше о Drupal и познакомиться с другими
  пользователями. Найдите локальные группы пользователей на
  https://groups.drupal.org/[_groups.drupal.org_].
Принять участие в тематической или языковой группе::
  Существуют также группы по интересам для самых разных тем с онлайн-форумами для обсуждения.
  Найдите тематические группы на https://groups.drupal.org/[_groups.drupal.org_]. Многие языки имеют
  собственные сайты; их можно найти на странице
  https://www.drupal.org/language-specific-communities["Языковые сообщества" на _Drupal.org_].
Общаться онлайн::
  Проект Drupal использует Slack и DrupalChat для онлайн-чатов. Доступны региональные, тематические
  и общие чаты. Подробнее читайте на страницах
  https://www.drupal.org/slack["Slack" на _Drupal.org_] и
  https://www.drupal.org/drupalchat["DrupalChat" на _Drupal.org_].
Сообщить о проблеме::
  Смотрите ниже.
Внести вклад::
  Вы можете внести свой вклад в сообщество разными способами, например:
  * Разработка модулей или тем. Смотрите
    https://www.drupal.org/contribute/development["Внести вклад в разработку"
    на _Drupal.org_], или улучшайте их (используйте очереди задач для существующих проектов).
  * Перевод пользовательского интерфейса. Смотрите
    https://localize.drupal.org[_localize.drupal.org_].
  * Написание документации. Смотрите
    https://www.drupal.org/contribute/documentation["Внести вклад в документацию"
    на _Drupal.org_].
  * Отвечайте на вопросы поддержки. Смотрите <<thoughts-support>>.

==== Как можно сообщить о проблеме или предложить новую функцию?

Каждый проект в сообществе (например, проект ядра Drupal и проекты для каждой темы и модуля)
использует _issues_ (проблемы) для отслеживания багов и планирования новых функций. Вы можете участвовать,
создавая отчёт об ошибке, когда находите проблему, создавая запрос на новую функцию или
комментируя существующие проблемы. Перед созданием задачи,
убедитесь, что проблема или функция ещё не были зарегистрированы. Смотрите
https://www.drupal.org/issue-queue[Страница _Drupal.org_ "Использование очереди задач"] и
https://www.drupal.org/node/314185[Страница _Drupal.org_ "Сообщение о проблеме"] для получения
подробной информации.

Если вы нашли проблему, связанную с безопасностью, например, уязвимость к межсайтовому скриптингу,
не размещайте её в обычной очереди задач. Вместо этого обратитесь к команде безопасности.
Смотрите https://www.drupal.org/node/101494[Страница _Drupal.org_ "Как сообщить о проблеме безопасности"] для подробностей.

==== Похожие темы

<<thoughts-support>>

==== Дополнительные ресурсы

* https://www.drupal.org/dcoc["Кодекс поведения" на _Drupal.org_]
* https://groups.drupal.org/events["Календарь событий" на _groups.drupal.org_] или
  https://www.drupical.com/[_drupical.com_]
* https://www.drupal.org/community["Страница сообщества" на _Drupal.org_]
* https://groups.drupal.org/[_groups.drupal.org_]
* https://www.drupal.org/slack["Страница Slack на _Drupal.org_]
* https://www.drupal.org/drupalchat["Страница DrupalChat на _Drupal.org_]
* https://www.drupal.org/contribute["Способы принять участие" на _Drupal.org_]
* https://www.drupal.org/node/2486391[Страница _Drupal.org_ "Зачем участвовать?"]
* https://www.drupal.org/contributor-tasks[Страница _Drupal.org_ "Задачи участников"]
* https://www.drupal.org/issue-queue[Страница _Drupal.org_ "Использование очереди задач"]
* https://www.drupal.org/node/314185[Страница _Drupal.org_ "Сообщение о проблеме"]
* https://www.drupal.org/node/101494[Страница _Drupal.org_ "Как сообщить о проблеме безопасности"]

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/eojthebrave[Joe Shindelar] на
https://drupalize.me[Drupalize.Me].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
