[[thoughts-support]]
=== Получение поддержки

[role="summary"]
Как найти поддержку при возникновении проблем во время разработки сайта.

(((Поддержка,поиск)))
(((Форум,поддержка пользователей)))
(((Slack,использование для онлайн-чата)))
(((DrupalChat,использование для онлайн-чата)))
(((Онлайн-чат)))

==== Необходимые знания

* <<understanding-project>>
* <<thoughts-connecting>>

==== Где можно найти поддержку?

Проект Drupal — с открытым исходным кодом, поэтому если у вас есть вопросы или проблемы
с программным обеспечением, ваши варианты поиска ответов и решений будут несколько
отличаться от коммерческого ПО.

Есть несколько вариантов бесплатной поддержки, предоставляемой волонтёрами сообщества.
Во-первых, некоторые каналы Slack, каналы DrupalChat, локальные группы и
языковые сообщества поощряют вопросы поддержки — через онлайн-чат,
очные встречи или собственные сайты (подробнее — см. <<thoughts-connecting>>).

Во-вторых, некоторые (но не все) проекты модулей, дистрибутивов и тем
разрешают публиковать запросы поддержки в issues. Как правило, проекты с
очень большим количеством пользователей не принимают вопросы поддержки в issues
(ядро Drupal относится к этой категории), а в проектах с меньшим количеством пользователей
иногда приветствуют такие вопросы. Уважайте время разработчиков и обязательно
ознакомьтесь с документацией по проекту перед публикацией вопроса в issue.
С другой стороны, все проекты поощряют использование issues для сообщений о проблемах
и багах; см. <<thoughts-connecting>>, чтобы узнать об этом подробнее.

Кроме того, существуют сайты с бесплатными форумами, где волонтёры отвечают на вопросы
по Drupal:

* https://www.drupal.org/forum[_Drupal.org_ Forums]
* https://drupal.stackexchange.com/["Drupal Answers" на StackExchange]

Если вы предпочитаете платную поддержку (например, ради более широкого сервиса или
большей доступности), вы можете найти поставщиков услуг в
https://www.drupal.org/drupal-services["Drupal Marketplace" на _Drupal.org_].

==== Похожие темы

* <<thoughts-learn-more>>
* <<thoughts-connecting>>

==== Дополнительные ресурсы

* https://www.drupal.org/support["Support" страница на _Drupal.org_]
* https://www.drupal.org/drupal-services["Drupal Marketplace" на _Drupal.org_]
* https://www.drupal.org/forum[_Drupal.org_ Forums]
* https://drupal.stackexchange.com/["Drupal Answers" на StackExchange]

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
