[[understanding-gpl]]

=== Концепция: Лицензирование Drupal

[role="summary"]
Обзор лицензирования Drupal и методических рекомендаций, которым должны следовать пользователи и
вкладчики.

(((Лицензирование,обзор)))
(((Лицензирование Drupal,обзор)))
(((GPL (Универсальная общественная лицензия или GNU General Public License),обзор)))
(((GNU General Public License,обзор)))
(((Правовой,обзор)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое лицензирование Drupal?

Drupal и все размещённые на _Drupal.org_ вложения лицензируются по условиям GNU General Public License (GPL),
версии 2 или более поздней. Это значит, что вы можете свободно
загружать, использовать повторно, изменять и распространять любые файлы, являющиеся частью проекта на
_Drupal.org_ на условиях GPL версии 2 или 3. Вы также можете запускать ядро
в сочетании с любым кодом с лицензией, совместимой с версией 2 или 3.

Участники Drupal должны следовать следующим рекомендациям:

* Все файлы (PHP, JavaScript, изображения, Flash и т.д.), которые являются частью проекта
на _Drupal.org_, должны распространяться под GPL версии 2 или более поздней.

* Все вкладчики Drupal сохраняют авторские права на свой код, но соглашаются выпускать
его под той же лицензией, что и Drupal.

* Модули и темы для Drupal являются производным произведением Drupal. Если вы распространяете
их, вы должны делать это на условиях GPL версии 2 или более поздней.

* Весь контент на самом _Drupal.org_ принадлежит его исходным
авторам и лицензируется по лицензии Creative Commons Attribution-ShareAlike
версии 2.0.

* Примеры кода на _Drupal.org_ также доступны под GPL версии 2 или более поздней.

==== Связанные темы

<<thoughts-connecting>>

==== Дополнительные ресурсы

* https://www.drupal.org/about/licensing[_Drupal.org_ страница "Licensing"]

* https://api.drupal.org/api/drupal/core!LICENSE.txt/9.0.x["Drupal LICENSE.txt" страница на _api.drupal.org_]

* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU General Public License, версия 2]

* http://www.gnu.org/licenses/gpl-3.0.en.html[GNU General Public License, версия 3]

* https://creativecommons.org/licenses/by-sa/2.0/[Лицензия Creative Commons Attribution-ShareAlike 2.0.]

* https://groups.drupal.org/legal["Legal Group" на _groups.drupal.org_]


*Авторы*

Адаптировано https://www.drupal.org/u/dianalakatos[Diána Lakatos] на
https://pronovix.com/[Pronovix] из
https://www.drupal.org/about/licensing["Licensing"]
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].
