[[understanding-data]]
=== Основы: Типы данных

[role="summary"]
Обзор часто употребляемых типов данных, используемых на сайтах.

(((Тип данных,обзор)))
(((Тип данных,конфигурация)))
(((Тип данных,контент)))
(((Тип данных,состояние)))
(((Тип данных,сессия)))
(((Конфигурация как тип данных)))
(((Контент как тип данных)))
(((Состояние как тип данных)))
(((Сеанс работы как тип данных)))


//==== Prerequisite knowledge

==== Какие существуют типы данных?

Данные и информация на вашей странице делятся на четыре типа, которые
редактируются, переводятся и хранятся по-разному. Эти четыре типа:

Контент::
 Информация(текст, изображения и т.д.)предназначена для посетителей сайта. Этот
 тип информации, как правило, не изменяется, но он может
 редактироваться.

Конфигурация::
 Информация о вашей странице – не основное содержимое, но она не изменяется
 и может использоваться для определения того, как ваш сайт ведет себя или отображается. Она
 иногда отображает на сайте посетителей, но заботится о небольших частях
 текста(такие, как метки поля, название вашего сайта и т.д.) быстрее, чем о
 больших  частях, о которых вы обычно думаете, как о содержимом.

Состояние (state)::
 Информация временного характера о текущем состоянии вашего
 сайта, такая как время, когда задачи крона были запущены в последний раз.

Сессия::
 Информация о взаимодействии отдельных посетителей сайта на странице, такая
 как: вошли ли они в систему и о их куки. Технически, это
 подтип информации о положении, так как это также временно.

=== Связанные темы

* <<planning-data-types>>
* <<security-cron-concept>>
* <<user-concept>>
* <<language-concept>>

//==== Дополнительные ресурсы


*Авторы*

Написано/отредактировано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] from
https://www.drupal.org/node/2120523["Overview of Configuration (vs. other types of information)"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Переведено https://www.drupal.org/user/3615464[Аземша Дарья].
