[[understanding-project]]
=== Концепция: Проект Drupal

[role="summary"]
Обзор бесплатного и открытого программного обеспечения (FOSS), проекта Drupal и Ассоциации Drupal.

(((Проект Drupal,обзор)))
(((Ассоциация Drupal,обзор)))
(((FOSS (Бесплатное и открытое программное обеспечение),обзор)))
(((Бесплатное и открытое программное обеспечение (FOSS),обзор)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое бесплатное и открытое программное обеспечение?

Бесплатное и открытое программное обеспечение (FOSS) — это программное обеспечение, которое разрабатывается
сообществом, распространяется по некоммерческой лицензии, а его _исходный
код_ (программные файлы, составляющие это ПО) находится в свободном доступе. Подробнее о некоммерческой лицензии, используемой в Drupal, см. <<understanding-gpl>>.

==== Что такое проект Drupal?

Проект Drupal — это FOSS-проект, целью которого является разработка основного
программного обеспечения системы управления содержимым, а также дополнительных модулей,
тем оформления, переводов, документации и специализированных дистрибутивов.
Люди, которые вкладывают своё время и средства в проект Drupal, приходят со
всего мира и образуют разнообразное сообщество, объединённое общей целью.

Сообщество включает множество меньших групп, выполняющих самые разные задачи,
например, разработку определённых программных решений для Drupal, написание
документации, обеспечение безопасности программного обеспечения Drupal, перевод программного
обеспечения Drupal на различные языки, использование Drupal для определённых целей,
и проведение встреч в определённых регионах.

Подробнее о том, как можно присоединиться и взаимодействовать с мировым сообществом,
смотрите <<thoughts-connecting>> и <<thoughts-support>>.

==== Что такое Ассоциация Drupal?

https://www.drupal.org/association[Ассоциация Drupal] — это некоммерческая организация,
посвящённая поддержке проекта и сообщества Drupal. Её основные функции:

* Организация крупных мероприятий по всему миру
* Поддержка сайтов _Drupal.org_ и серверов, на которых они работают
* Продвижение Drupal как веб-платформы
* Поддержка образования и обучения по Drupal
* Выделение грантов сообществу Drupal для поддержки его миссии
* Сбор средств на эти цели

==== Связанные темы

* <<understanding-gpl>>
* <<security-concept>>
* <<thoughts-connecting>>
* <<thoughts-support>>

==== Дополнительные ресурсы

* https://www.drupal.org/governance[Управление проектом Drupal]
* https://www.drupal.org/dcoc[Кодекс поведения Drupal]

*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Переведено https://www.drupal.org/u/karina-masalova[Карина Масалова].
