[[understanding-distributions]]

=== Концепция: Дистрибутивы

[role="summary"]
Обзор дистрибутивов, которые могут быть использованы для создания сайтов для определённых
задач.

(((Дистрибутив,обзор)))
(((Дистрибутив,полнофункциональный)))
(((Дистрибутив,быстрый старт)))
(((Полнофункциональный дистрибутив,обзор)))
(((Дистрибутив для быстрого старта,обзор)))

==== Необходимые знания

* <<understanding-drupal>>
* <<understanding-modules>>
* <<understanding-themes>>

==== Что такое дистрибутивы?

_Дистрибутивы_ предоставляют функционал и возможности для сайта определённого типа
в виде одного архива, включающего ядро Drupal, дополнительные модули, темы
и заранее определённую конфигурацию. Дистрибутив позволяет настроить
сложный сайт для конкретной цели за меньшее число шагов, чем установка и
настройка каждого элемента по отдельности.

Существует два основных типа дистрибутивов:

Полнофункциональные дистрибутивы::
  Полнофункциональный дистрибутив — это проект, предоставляющий готовое решение
  для создания сайта под специализированную задачу: образование, бизнес,
  государство, некоммерческие организации, публикации, социальные сети и др. Например, вы можете
  использовать существующий дистрибутив для городского рынков, чтобы построить свой сайт, или
  можете поделиться своей сборкой сайта городского рынка как дистрибутивом для
  других пользователей.

Другие дистрибутивы::
  Дистрибутивы могут быть также инструментами быстрого старта, которые разработчики и
  сборщики сайтов используют как отправную точку.

==== Связанные темы

<<thoughts-connecting>>

==== Дополнительные материалы

https://www.drupal.org/project/project_distribution[_Drupal.org_ Drupal Distribution Downloads]


*Авторы*

Адаптировано и отредактировано https://www.drupal.org/u/dianalakatos[Diána Lakatos]
и https://www.drupal.org/u/ifrik[Antje Lorch],
из https://www.drupal.org/docs/7/distributions["Distributions"]
и https://www.drupal.org/project/project_distribution["Download & Extend -- Distributions"]
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].
