[[understanding-drupal]]

=== Концепция: Drupal как Система Управления Сайтом

[role="summary"]
Обзор Drupal и причин выбрать его как надёжную Систему Управления
Содержимым (CMS).

(((CMS (Content Management System),обзор)))
(((Система управления содержимым (CMS),обзор)))
(((Drupal система управления содержимым,обзор)))
(((Drupal система управления содержимым,требования к серверу)))
(((Drupal ядро,обзор)))
(((Drupal.org,загрузка модулей и тем оформления)))

//==== Prerequisite knowledge

==== Что такое Система Управления Содержимым?

Система управления содержимым (CMS) — это программный инструмент, который позволяет пользователям добавлять,
публиковать, редактировать или удалять контент с сайта через браузер на
смартфоне, планшете или компьютере. Обычно программное обеспечение CMS написано
на скриптовом языке, и его скрипты выполняются на компьютере с установленными базой данных и
веб-сервером. Контент и настройки сайта обычно
хранятся в базе данных, и для каждого запроса страницы, поступающего на веб-сервер,
скрипты собирают информацию из базы данных и _ресурсов_ (файлы JavaScript,
CSS, изображения и т.д., которые являются частью CMS или были
загружены), чтобы формировать страницы сайта.

Совокупность операционной системы, на которой работает CMS, скриптового
языка, на котором она написана, базы данных для хранения информации и
веб-сервера, который выполняет скрипты для получения данных и отдачи их в
браузер посетителя сайта, называется _стеком_, на котором работает CMS; часто
используемая комбинация Linux, Apache, MySQL и PHP называется _LAMP-стеком_.

==== Что такое Drupal?

Drupal — это гибкая CMS, построенная на LAMP-стеке, с модульной архитектурой, позволяющей
добавлять и удалять функции путём установки или удаления _модулей_, и
менять внешний вид сайта с помощью установки или удаления _тем_. Базовый
дистрибутив Drupal, называемый ядром, содержит PHP-скрипты, необходимые для базовой работы CMS,
несколько дополнительных модулей и тем, а также множество файлов JavaScript, CSS и изображений. Многие дополнительные
модули и темы можно скачать с сайта https://www.drupal.org[_Drupal.org_].

Drupal может также работать на других технологиях:

* Операционной системой может быть Windows или Mac OS вместо Linux.

* Веб-сервером может быть Nginx или IIS вместо Apache.

* В качестве базы данных можно использовать PostgreSQL или SQLite вместо MySQL, или
MySQL-совместимые решения, такие как MariaDB или Percona.

Можно также использовать другие ОС, веб-серверы и базы данных;
однако скрипты, которые использует программное обеспечение, написаны на PHP, это изменить нельзя.

==== Почему стоит использовать Drupal?

При создании сайта вы можете выбрать одну из многочисленных
существующих CMS или хостинг-сервисов, разработать собственную CMS или сделать сайт
без использования CMS. Вот причины выбрать именно Drupal:

* Создание небольшого простого сайта на статичном HTML несложно, и сайт
можно получить очень быстро. Однако создание сайта на CMS обычно
занимает больше времени на старте, но даёт онлайн-редактирование
(что проще для редакторов), единообразие (которое сложно поддерживать на больших
статичных сайтах), и возможность добавлять сложный функционал с базой данных.

* Некоторые CMS предназначены для узких задач: например, существуют решения для блога
или для сайтов-клубов. В отличие от этого, Drupal — универсальная CMS.
Если ваш сайт чуть выходит за рамки типовых задач, будет проще взять универсальную CMS, чем
адаптировать специализированную.

* Создание своей CMS может казаться интересным, но использовать универсальную CMS
(например, Drupal) — почти всегда лучший вариант, ведь базовый функционал
(например, учетные записи и управление контентом) разрабатывался тысячами человеко-часов, тестировался годами,
исправлялся и улучшался с точки зрения безопасности.

* Некоторые CMS стоят дорого. Некоторые бесплатны, но с ограничительными лицензиями,
которые запрещают модификации и расширения. Вы можете предпочесть систему
(как Drupal), с менее ограничительной лицензией и поддерживаемую всемирным
сообществом. Подробнее см. <<understanding-project>>.

==== Связанные темы

* <<understanding-modules>>
* <<understanding-themes>>
* <<understanding-distributions>>
* <<understanding-project>>

==== Дополнительные материалы

* https://www.drupal.org/docs/understanding-drupal/overview[_Drupal.org_ страница документации сообщества "Understanding Drupal: Overview"]

* https://www.drupal.org/about/faq[_Drupal.org_ страница "FAQ" (Часто задаваемые вопросы)]

* https://www.drupal.org/case-studies[_Drupal.org_ страница "Case Studies"]

* https://en.wikipedia.org/wiki/Content_management_system[Статья Википедии "Content management systems"]

* https://en.wikipedia.org/wiki/Modular_design[Статья Википедии "Modular design"]


*Авторы*

Написано и отредактировано https://www.drupal.org/u/kvantomme[Kristof van Tomme]
на https://pronovix.com/[Pronovix],
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon],
и https://www.drupal.org/u/michaellenahan[Michael Lenahan]
в https://erdfisch.de[erdfisch].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
