[[understanding-themes]]
=== Концепция: Темы оформления

[role="summary"]
Обзор тем оформления и где их можно получить.

(((Тема оформления,обзор)))
(((Тема оформления,ядро)))
(((Тема оформления ядра,обзор)))
(((Тема оформления,сторонняя)))
(((Сторонняя тема оформления,обзор)))
(((Тема оформления,пользовательская)))
(((Пользовательская тема оформления,обзор)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое тема оформления?

Тема оформления — это набор файлов, которые определяют внешний вид и ощущение от вашего сайта.
Ядро и модули, которые работают на вашем сайте, определяют,
какой _контент_ (включая HTML-текст и другие данные, хранящиеся в базе данных, загруженные
изображения и любые другие файлы-ресурсы) отображается на страницах сайта.
Тема определяет HTML-разметку и CSS-стили, которые обрамляют этот контент.

Ядро предоставляет несколько базовых тем в стандартной поставке.
Эти темы в основном были разработаны и созданы сообществом за последние
несколько лет и будут хорошим выбором для создания вашего первого сайта и
ознакомления с работой ядра Drupal.

Drupal — зрелая CMS, поэтому рынок сторонних тем — как бесплатных,
так и платных — очень развит.

Если ни одна из сторонних тем вам не подходит, потребуется создать пользовательскую
тему. Пользовательская тема может быть простой: достаточно одного CSS-файла, добавляющего стили
к разметке, предоставленной ядром. Руководство по созданию пользовательских тем оформления
Drupal можно найти на
https://www.drupal.org/docs/theming-drupal[_Drupal.org_ страница документации сообщества
"Theming Drupal"].

==== Связанные темы

* <<extend-theme-find>>
* <<extend-theme-install>>
* <<understanding-modules>>

==== Дополнительные ресурсы

https://www.drupal.org/docs/theming-drupal[_Drupal.org_ страница документации сообщества "Theming Drupal"]

*Авторы*

Написано и отредактировано https://www.drupal.org/u/jgrubb[John Grubb] и
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
