[[understanding-project]]

=== Основы: Проект Drupal

[role="summary"]
Обзор бесплатного программного обеспечения с открытым исходным кодом, проект Drupal, Ассоциация Drupal.

(((Проект Drupal,обзор)))
(((Ассоциация Drupal,обзор)))
(((Бесплатное программное обеспечение с открытым исходным кодом,обзор)))
(((Бесплатное программное обеспечение с открытым исходным кодом,обзор)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое бесплатное программное обеспечение с открытым исходным кодом?

Бесплатное программное обеспечение с открытым исходным кодом это программное обеспечение, которое разрабатывает
сообщество людей и выпускает под некоммерческой лицензией, и чей _исходный
код_ (программные файлы, составляющие программное обеспечение) в открытом доступе. За
дополнительной информацией о некоммерческой лицензии, используемой Drupal, смотрите
<<understanding-gpl>>.

==== Что такое проект Drupal?

Проект Drupal это проект Open Source, который нацелен на разработку программного обеспечения
системы управления содержимым ядра так же, как и на дополнительные модули, вспомогательные
темы, переводы, документацию, и дистрибутивы специального назначения. Люди,
которые вкладывают время и деньги в проект Drupal приезжают
со всего мира, и являются разносторонним сообществом, которое объединяется для
общей цели.

Сообщество охватывает более мелкие группы, которые выполняют различные задания,
такие, как разработка определенного программного обеспечения, связанного с Drupal, написание
документации, обеспечение безопасности программного обеспечения Drupal, переводы программного
обеспечения Drupal на определённый язык, использование Drupal для конкретной цели,
и собираются вместе, чтобы встретиться лично на определенной территории.

Подробнее о том, как Вы можете установить связь и общаться с мировым сообществом,
смотрите <<thoughts-connecting>> и <<thoughts-support>>.

==== Что такое Ассоциация Drupal?

https://www.drupal.org/association[Ассоциация Drupal] это некоммерческая организация
посвящённая поддержке проекта и сообщества Drupal. Главными функциями являются:

* Проведение крупных съездов по всему миру
* Поддержка _Drupal.org_ веб-сайтов и серверов, над которыми идёт работа
* Продвижение Drupal в качестве веб-платформы
* Поддержка Drupal-обучения и подготовки
* Предоставление пособия сообществу Drupal для поддержки цели
* Повышение фондов для этих целей

==== Связанные темы

* <<understanding-gpl>>
* <<security-concept>>
* <<thoughts-connecting>>
* <<thoughts-support>>

==== Дополнительные ресурсы

* https://www.drupal.org/governance[Drupal project governance]
* https://www.drupal.org/dcoc[Drupal Code of Conduct]


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Переведено https://www.drupal.org/u/karina-masalova[Карина Масалова].
