[[understanding-gpl]]

=== Концепция: Лицензирование Drupal

[role="summary"]
Обзор лицензирования Drupal и методические рекомендации, которым должны следовать пользователи и участники.

(((Лицензирование,обзор)))
(((Лицензирование Drupal,обзор)))
(((GPL (Универсальная общедоступная лицензия или  Открытое лицензионное соглашение),обзор)))
(((GNU Универсальная общедоступная лицензия,обзор)))
(((Правовой,обзор)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое Лицензирование Drupal?

Drupal и все вложенные файлы, расположенные на _Drupal.org_ , лицензированы Универсальной
Общедоступной Лицензией, версии 2 или более поздней. Это значит, что Вы можете бесплатно
загрузить, повторно использовать, изменить, и распространить файлы, которые являются частью проекта на
_Drupal.org_ в соответствии с условиями GPL версии 2 или 3. Вы также можете запустить основное
программное обеспечение в сочетании с любым кодом с лицензией, которая совместима с
версиями 2 и 3.

Участники Drupal должны следовать данным методическим рекомендациям:

* Все файлы (PHP, JavaScript, изображения, Flash, и т.д.), которые являются частью проекта
на _Drupal.org_ должны быть лицензированы версией 2 или более поздней.

* Все участники Drupal сохраняют авторские права на свой код, но соглашаются выпустить
его на ту же лицензию, что и Drupal.

* Модули и темы Drupal являются производной работой Drupal. Если Вы распространяете
их, Вы должны делать это в соответствии с условиями GPL версии 2 или более поздней.

* Все материалы на _Drupal.org_ принадлежат его первоначальным
вкладчикам, и лицензированы the Creative Commons Attribution-ShareAlike
license версии 2.0.

* Пример кода на _Drupal.org_ также доступен под лицензией GPL версии 2 или более поздней.

==== Связанные темы

<<thoughts-connecting>>

==== Дополнительные ресурсы

* https://www.drupal.org/about/licensing[_Drupal.org_ page on "Licensing"]

* https://api.drupal.org/api/drupal/core!LICENSE.txt/9.0.x["Drupal LICENSE.txt" page on _api.drupal.org_]

* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU General Public License, version 2]

* http://www.gnu.org/licenses/gpl-3.0.en.html[GNU General Public License, version 3]

* https://creativecommons.org/licenses/by-sa/2.0/[Creative Commons Attribution-ShareAlike license 2.0.]

* https://groups.drupal.org/legal["Legal Group" on _groups.drupal.org_]


*Авторы*

Написано https://www.drupal.org/u/dianalakatos[Diana Lakatos] на
https://pronovix.com/[Pronovix] из
https://www.drupal.org/about/licensing["Licensing"]
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Переведено https://www.drupal.org/u/karina-masalova[Карина Масалова].
