[[understanding-data]]
=== Концепция: Типы данных

[role="summary"]
Обзор распространённых типов данных, используемых на сайте.

(((Тип данных,обзор)))
(((Тип данных,конфигурация)))
(((Тип данных,контент)))
(((Тип данных,состояние)))
(((Тип данных,сессия)))
(((Конфигурация,как тип данных)))
(((Контент,как тип данных)))
(((Состояние,как тип данных)))
(((Сессия,как тип данных)))


//==== Prerequisite knowledge

==== Какие бывают типы данных?

Данные и информация на вашем сайте делятся на четыре типа, которые
редактируются, переводятся и хранятся по-разному. Эти четыре типа:

Контент::
  Информация (текст, изображения и др.), предназначенная для отображения
  посетителям сайта. Обычно это достаточно постоянная информация,
  однако она, как правило, может быть отредактирована.
Конфигурация::
  Информация о вашем сайте, которая не является контентом, но также достаточно
  постоянна и используется для определения поведения или внешнего вида сайта.
  Иногда она тоже отображается посетителям, но обычно это небольшие фрагменты
  текста (например, метки полей, название сайта и т. п.), а не крупные блоки,
  которые обычно воспринимаются как Контент.
Состояние (state)::
  Временная информация о текущем состоянии сайта, например,
  время последнего запуска заданий cron.
Сессия::
  Информация о взаимодействии отдельных посетителей сайта,
  например, вошли ли они в систему и их cookies. Технически, это
  подтип информации о состоянии, поскольку она также является временной.

==== Связанные темы

* <<planning-data-types>>
* <<security-cron-concept>>
* <<user-concept>>
* <<language-concept>>

//==== Additional resources


*Авторы*

Адаптировано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] из
https://www.drupal.org/docs/drupal-apis/configuration-api/overview-of-configuration-vs-other-types-of-information["Overview of Configuration (vs. other types of information)"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation]

Переведено https://www.drupal.org/user/3615464[Аземша Дарья].
