[[understanding-modules]]
=== Концепция: Модули

[role="summary"]
Обзор модулей и функциональности, для которой они могут быть использованы.

(((Модуль,обзор)))
(((Дополнительный модуль,обзор)))
(((Модуль ядра,обзор)))
(((Модуль Field,обзор)))
(((Модуль Field UI,обзор)))
(((Модуль Menu UI,обзор)))
(((Модуль Node,обзор)))
(((Модуль User,обзор)))
(((Модуль Views,обзор)))
(((Модуль Views UI,обзор)))
(((Модуль,ядро)))
(((Модуль,дополнительный)))
(((Модуль,Field)))
(((Модуль,Field UI)))
(((Модуль,Menu UI)))
(((Модуль,Node)))
(((Модуль,User)))
(((Модуль,Views)))
(((Модуль,Views UI)))

==== Необходимые знания

<<understanding-drupal>>

==== Что такое модуль?

Модуль — это набор PHP, JavaScript и/или CSS файлов, который расширяет возможности сайта
и добавляет функциональность.

Вы можете включить возможности и функциональность с помощью _установки_ модуля, и
вы можете отключить их с помощью _удаления_ модуля; перед удалением, возможно,
придётся удалить данные и конфигурации, связанные с возможностями или функциональностью.

Каждый установленный модуль увеличивает время, необходимое для генерации страниц на вашем
сайте, поэтому рекомендуется удалять ненужные модули.

Ядро Drupal предоставляет модули для следующей функциональности:

* Управление учетными записями пользователей (модуль ядра User)

* Управление основным содержимым (модуль ядра Node) и полями (модули ядра Field и
Field UI; существуют также модули ядра, обеспечивающие типы полей)

* Управление навигационными меню (модуль ядра Menu UI)

* Создание списков, таблиц и блоков на основе существующего содержимого (модули ядра Views и
Views UI)

Вы можете загрузить дополнительные _дополнительные модули_ с
https://www.drupal.org/project/project_module[_Drupal.org_ Module Downloads], либо
создать собственные _пользовательские модули_.

==== Похожие темы

* <<understanding-themes>>
* <<understanding-distributions>>
* <<config-uninstall>>
* <<extend-module-find>>
* <<extend-module-install>>
* <<security-concept>>
* <<security-update-module>>

==== Дополнительные ресурсы

https://www.drupal.org/developing/modules[_Drupal.org_ страница документации сообщества "Module developer's guide"]


*Авторы*

Написано https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon]

Переведено https://www.drupal.org/u/MishaIsmajlov[Исмайлов Михаил].
