[[user-concept]]
=== Концепция: Пользователи, Роли и Права доступа

[role="summary"]
Обзор учетных записей пользователей, прав доступа и ролей.

(((Пользователь,обзор)))
(((Роль,обзор)))
(((Роль пользователя,обзор)))
(((Права доступа,обзор)))
(((Анонимный пользователь,обзор)))
(((Авторизованный пользователь,обзор)))
(((Аккаунт администратора,обзор)))

// ==== Prerequisite knowledge

==== Кто такие пользователи?

Любой, кто посещает ваш сайт, является _пользователем_, включая вас. Есть три
группы пользователей:

* Пользователи, которые не вошли в систему, или _анонимные пользователи_

* Пользователи, которые вошли в систему, или _авторизованные пользователи_

* Административная учетная запись, которая была автоматически создана при
установке вашего сайта, или пользователь 1. См. <<user-admin-account>>.

==== Что такое права доступа?

Возможность выполнять действия на вашем сайте (включая просмотр контента, редактирование
контента и изменение конфигурации) регулируется _правами доступа_. Каждое
право доступа имеет имя (например, _Просмотр опубликованного контента_) и охватывает одно действие
или небольшое подмножество действий. Пользователь должен получить право доступа, чтобы выполнить
соответствующее действие на сайте; права определяются модулями,
которые предоставляют эти действия.

==== Что такое роли?

Вместо того чтобы назначать права доступа напрямую каждому пользователю, права
группируются в _роли_. Вы можете определить одну или несколько ролей на своем сайте, и
затем назначить права каждой роли. Права, предоставленные авторизованным
и анонимным пользователям, содержатся в ролях _Авторизованный пользователь_ и _Анонимный
пользователь_, а в зависимости от установочного профиля, который вы использовали при
установке сайта, также может быть роль _Администратор_, которой
автоматически назначаются все права на вашем сайте.

Каждая учетная запись на сайте автоматически получает роль _Авторизованный пользователь_,
и при необходимости ей могут быть назначены дополнительные роли. Когда вы
назначаете роль учетной записи пользователя, пользователь получает все права этой
роли при входе в систему.

Хорошей практикой является создание нескольких ролей на сайте. В примере сайта
городской ярмарки могут понадобиться такие роли:

* Роль производителя, которая позволяет производителям редактировать свои собственные страницы

* Роль редактора для редактирования общих страниц ярмарки

* Роль менеджера пользователей для управления аккаунтами производителей

* Роль _Администратор_, установленная вместе с сайтом, для опытных пользователей,
которые управляют конфигурацией сайта

==== Похожие темы

* <<user-new-role>>
* <<user-permissions>>
* <<user-roles>>
* <<user-new-user>>
* <<user-admin-account>>
* <<user-content>>

==== Дополнительные ресурсы

* https://www.drupal.org/node/120614[_Drupal.org_ страница документации сообщества "Users, roles and permissions"]
* https://www.drupal.org/docs/7/managing-users[_Drupal.org_ страница документации сообщества "Managing Users"]
* https://www.drupal.org/docs/7/managing-users/user-roles[_Drupal.org_ страница документации сообщества "User Roles"]

*Авторы*

Адаптировано https://www.drupal.org/u/mark-lacroix[Mark LaCroix],
https://www.drupal.org/u/batigolix[Boris Doesborg], и
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] с
https://www.drupal.org/docs/7/managing-users/user-roles["User Roles"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
