[[user-admin-account]]
=== Концепция: Аккаунт пользователя 1

[role="summary"]
Обзор аккаунта пользователя 1, также известного как root или административный аккаунт.

(((Пользователь,root)))
(((Пользователь,пользователь один)))
(((Пользователь,административный)))
(((Безопасность,аккаунт пользователя один)))

==== Необходимые знания

<<user-concept>>

==== Что такое аккаунт пользователя 1?

Во время установки вашего сайта вы создали первый аккаунт пользователя. Каждый
аккаунт пользователя внутри системы имеет числовой идентификатор пользователя, и поскольку ID
этого пользователя равен единице, обычно его называют аккаунтом _пользователь 1_. Этот аккаунт
особенный, потому что независимо от назначенных ролей, пользователь, вошедший как
пользователь 1, имеет разрешения на выполнение всех действий на сайте, включая просмотр и
редактирование всего контента, редактирование любого аккаунта пользователя, изменение конфигурации сайта,
установку и удаление модулей, а также запуск скрипта обновления.

Из-за такого уровня разрешений, некоторые называют этот аккаунт
_пользователь root_, аналогично аккаунту "root", обладающему полными административными
правами в Linux и других операционных системах.

Обычно лучше создавать отдельные аккаунты для каждого администратора,
назначая им роль _Администратор_, а не использовать для всех административных
пользователей один аккаунт пользователя 1. Вот несколько причин:

* Некоторые действия и обновления на сайте протоколируются, и если все используют один
аккаунт, сложно понять, кто их выполнил, если возникнут вопросы.

* Права роли _Администратор_ можно настроить безопаснее,
чем полный доступ пользователя 1, чтобы никто случайно не изменил важные
настройки сайта.

* Ответственность пользователей на сайте может меняться со временем. Для обычных пользователей
это отражается в правах через назначение или снятие ролей. Если все используют аккаунт 1,
управлять этим сложнее.

* На некоторых сайтах отображается или отслеживается автор материалов или комментариев, и если
все создают материалы с одного аккаунта, невозможно понять,
кто был автором.

Удалить аккаунт пользователя 1 через административный интерфейс невозможно. Это
можно сделать только запросом к базе данных, но это может вызвать
проблемы на сайте и не рекомендуется.

//==== Related topics

==== Дополнительные ресурсы

https://www.drupal.org/node/22284[_Drupal.org_ страница документации сообщества "Accounts and roles"]

*Авторы*

Написано и отредактировано https://www.drupal.org/u/mark-lacroix[Mark LaCroix]
и https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
