[[user-concept]]

=== Основы: Пользователи, Роли и Права доступа

[role="summary"]
Обзор учетных записей пользователей, прав доступа и ролей.

(((Пользователь,обзор)))
(((Роль,обзор)))
(((Роль пользователя,обзор)))
(((Права доступа,обзор)))
(((Анонимный пользователь,обзор)))
(((Авторизованный пользователь,обзор)))
(((Аккаунт администратора,обзор)))

// ==== Prerequisite knowledge

==== Что такое Пользователь?

Любой, кто посещает ваш сайт, является _user_, включая вас. Есть три
группы пользователей:

* Пользователи, которые не вошли в систему, или _анонимный пользователь_

* Пользователи, которые вошли в систему, или _авторизованный пользователь_

* Учетная запись администратора, которая была автоматически создана при
установке вашего сайта, или Пользователь 1. Смотрите <<user-admin-account>>.

==== Что такое Права доступа?

Возможность совершать действия на вашем сайте (включая просмотр контента, добавление
контента, и изменение конфигурации) регулируется _Правами доступа_. Каждое
право доступа имеет имя (такое, как _Просмотр опубликованного контента_) и охватывает одно действие
или небольшое подмножество действий. Пользователь должен получить разрешение для того, чтобы сделать
соответствующее действие на сайте; права доступа определяются модулями,
которые обеспечивают действия.

==== Что такое Роль?

Вместо того, чтобы назначать индивидуальные разрешения непосредственно каждому пользователю, права доступа
сгруппированы в _роли_.Вы можете определить одну или несколько ролей на вашем сайте, и
затем предоставить права доступа каждой роли. Права доступа, предоставленные авторизованным
и анонимным пользователям содержатся в ролях _Авторизованный пользователь_ и _Анонимный
пользователь_, и в зависимости от установочного профиля, который вы использовали, когда
устанавливали ваш сайт, также может быть роль _Администратор_, которой
автоматически назначаются все разрешения на вашем сайте.

Каждая учетная запись пользователя на вашем сайте автоматически получает роль_Авторизованный
пользователь_, и при желании может быть назначена одна или несколько дополнительных ролей. Когда вы
назначите роль учетной записи пользователя, пользователь будет иметь все права доступа
при входе в систему.

Хорошей практикой является создание нескольких ролей на вашем сайте. На примере сайта
городская ярмарка, вам могут понадобиться следующие роли:

* Роль производителя, которая позволяет производителям редактировать собственную страницу списка производителей.

* Роль редактора для редактирования страниц городской ярмарки

* Роль менеджера для управления счетами производителя

* Роль _Администратор_, установленная на вашем сайте, для пользователей, которые будут
управлять конфигурацией сайта

==== Похожие темы

* <<user-new-role>>
* <<user-permissions>>
* <<user-roles>>
* <<user-new-user>>
* <<user-admin-account>>
* <<user-content>>

==== Дополнительные ресурсы

* https://www.drupal.org/node/120614[_Drupal.org_ страница документации сообщества "Users, roles and permissions"]
* https://www.drupal.org/docs/7/managing-users[_Drupal.org_ страница документации сообщества "Managing Users"]
* https://www.drupal.org/docs/7/managing-users/user-roles[_Drupal.org_ страница документации сообщества "User Roles"]


*Авторы*

Адаптировано https://www.drupal.org/u/mark-lacroix[Mark LaCroix],
https://www.drupal.org/u/batigolix[Boris Doesborg], и
https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon] от
https://www.drupal.org/docs/7/managing-users/user-roles["User Roles"],
авторские права 2000-copyright_upper_year за отдельными участниками
https://www.drupal.org/documentation[Drupal Community Documentation].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
