[[views-concept]]
=== Основы: Использование представлений

[role="summary"]
Обзор представлений и данных, которые могут быть отображены или выведены с их помощью.

(((Представление,обзор)))
(((Views модуль,обзор)))

==== Необходимые знания

* <<planning-modular>>
* <<planning-data-types>>

==== Что такое представление?

_Представление_ — это список содержимого на сайте. Модуль ядра Views отвечает за
отображение представлений, а модуль Views UI позволяет создавать и редактировать
их в административном интерфейсе. Когда вы определяете представления, вы хотите
взять данные с сайта и показать их пользователю.

==== Какие типы данных могут быть отображены с помощью представлений?

Вы можете создавать представления для вывода практически любой сущности содержимого,
которая хранится в системе. Например, для сайта городского рынка можно создать такие списки:

* Списки производителей
* Списки рецептов
* Списки самого последнего содержимого на сайте
* Списки пользователей на сайте

==== Какими способами можно выводить данные с помощью представлений?

Списки, созданные представлением, могут иметь различные формы:

* Таблица с сортируемыми полями
* Сетка
* Тизеры или изображения, ведущие на статьи
* Блоки
* Вывод JSON
* RSS-ленты
* Календари
* Слайд-шоу на экране

==== Похожие темы

* <<views-parts>>
* <<views-create>>

// ==== Additional resources


*Авторы*

Написано и отредактировано
https://www.drupal.org/u/michaellenahan[Michael Lenahan] в
https://erdfisch.de[erdfisch], и
https://www.drupal.org/u/jojyja[Jojy Alphonso] в
http://redcrackle.com[Red Crackle].

Переведено https://www.drupal.org/u/MishaIsmajlov[Михаил Исмайлов].
