[[views-parts]]

=== Основы: Разделы представления

[role="summary"]
Обзор административных частей представления.

(((Представление,разделы)))
(((Отображение,раздел представления,обзор)))
(((Формат,раздел представления,обзор)))
(((Поля,раздел представления,обзор)))
(((Критерии фильтрации,раздел представления,обзор)))
(((Критерии сортировки,раздел представления,обзор)))
(((Контекстные фильтры,раздел представления,обзор)))
(((Связи,раздел представления,обзор)))
(((Представление,отображение)))
(((Представление,формат)))
(((Представление,поля)))
(((Представление,критерии фильтрации)))
(((Представление,критерии сортировки)))
(((Представление,контекстные фильтры)))
(((Представление,связи)))

==== Необходимые знания

* <<planning-data-types>>
* <<planning-modular>>
* <<views-concept>>
* <<content-paths>>
* <<block-concept>>

==== Какие есть разделы у представления?

При редактировании представления в административном интерфейсе вы увидите следующие разделы (или секции), которые позволяют определить, какие данные выводить, в каком порядке и в каком формате:

Отображение (Display)::
  Каждое представление может иметь одно или несколько отображений, каждое из которых формирует свой тип вывода. Возможные варианты:
  Страница;;
    Вывод на определённом URL — основной контент страницы.
  Блок;;
    Вывод в блоке, который можно разместить в регионах сайта.
  Лента (Feed);;
    Создание RSS или других типов лент.
  Вложение (Attachment);;
    Формирует вывод, который может быть добавлен к другому отображению.

Формат (Format)::
  В зависимости от выбранного типа отображения можно выбрать, как именно выводить данные: в виде таблицы, сетки, HTML-списка и т.д. Некоторые форматы позволяют дополнительно выбрать — выводить ли отдельные поля или целые сущности; другие форматы, например таблица, всегда используют поля.

Поля (Fields)::
  В зависимости от выбранного формата, вы можете выбирать, какие поля контента выводить. Например, если вы делаете представление рецептов, то в блоке можно показать только названия, а на отдельной странице — ещё и изображение, так как там больше места.

Критерии фильтрации (Filter criteria)::
  Фильтры ограничивают выводимые данные на основе различных условий: опубликован контент или нет, тип материала, значение определённого поля и т.д. Например, чтобы вывести только рецепты, нужно добавить фильтр по типу материала (Рецепт) и фильтр по статусу публикации. Фильтры могут быть _раскрытыми_ — это значит, что пользователи увидят форму и смогут выбирать значения фильтров сами, например фильтровать рецепты по определённым ингредиентам.

Критерии сортировки (Sort criteria)::
  Определяют порядок вывода данных, который может основываться на любом поле контента.

Контекстные фильтры (Contextual filters)::
  Похожи на обычные фильтры, но значения для них берутся из _контекста_ — например, из URL страницы, текущей даты/времени или другого значения, автоматически определяемого для данного представления.

Связи (Relationships)::
  Позволяют расширить вывод представления, добавив в выборку данные из связанных сущностей. Связи строятся на основе полей, которые связывают основной контент с другими сущностями. Например, каждое содержимое имеет автора — пользователя, и создав связь, вы можете выводить поля из связанных пользователей (авторов) прямо в представлении.

==== Связанные темы

<<views-create>>

//==== Additional resources

*Авторы*

Написано и отредактировано https://www.drupal.org/u/surendramohan[Surendra Mohan] и https://www.drupal.org/u/jhodgdon[Jennifer Hodgdon].

Переведено https://www.drupal.org/u/levmyshkin[Абраменко Иван] из https://drupalbook.org/ru[DrupalBook].
